### ISSUE TITLE
Feature Request: Disable chat on the HORUS theme

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1001]
<strong>Submitted At: </strong>7/21/2020 15:13:52
<strong>Is your feature request related to a problem? Please describe. </strong>
The scrolling chat is a lot of bright, fast motion. It's not a big deal on other themes, I can just close my eyes til they're done their "loading", but the chat on the HORUS theme never stops.
<strong>Describe the solution you'd like: </strong>
Ideally, a toggle in the options menu or something to disable rolling text entirely; if the text is important, just have it appear all at once. If it's not, leave it out.
<strong>Additional context: </strong>

<strong>Contact: </strong>

**Comment by DawnPaladin** [comment]
The CSS media query ["prefers-reduced-motion"](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) might help with this.
