### ISSUE TITLE
[BUG] Installing a .lcp file does not work on iPad

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1010]
<strong>Submitted At: </strong>7/31/2020 2:08:44
<strong>Platform: </strong>
PWA - iOS
<strong>Describe the bug: </strong>
Nothing happens after selecting the file from the iPadOS file browser.
<strong>To Reproduce: </strong>
1) Open COMP/CON on iPad
2) Select Content Manager and then the Install Content tab
3) Tap “Select an .LCP file” button
4) Choose “Browse” and find and select the lcp file
<strong>Expected behavior: </strong>
The page should show the info on the selected content pack and the Install button should become active.
<strong>Additional context: </strong>
The file I used is the official “Lancer CORE NPCs-1.0.4.lcp” file. The same file worked on Mac’s Safari.
<strong>Contact Info: </strong>
Lazarus#1095
<strong>Stack Trace: </strong>
No errors.

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
