### ISSUE TITLE
[Bug] System Selection Preview cannot handle negative numbers

### ISSUE THREAD

**Issue by Jjeter** [massif-press/compcon#1016]
In the mech hanger, I go to add a system that costs negative SP. However, the preview cannot handle it as that would create an array of negative size, I am assuming for the lightning bolts. There should be a handler to check that the array is of valid size before creating it.

**Comment by Jjeter** [comment]
The relevant line appears to be in  compcon/src/ui/components/cards/_MechSystemCard.vue:Line 3
v-if="item.SP"

To avoid throwing errors if the SP value is negative, my understanding is that the conditional should verify that SP is both extant and non-negative (Or positive depending on how you are rendering 0).

**Comment by jarena3** [comment]
Currently, negative SP equipment is unsupported
