### ISSUE TITLE
[BUG] NPC Class Sorting

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1017]
<strong>Submitted At: </strong>8/7/2020 5:10:34
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
It appears that attempting to sort NPCs by their stats outside of alphabetical name and role doesn't work. Armor, heatcap, HP, so on and so forth. 
<strong>To Reproduce: </strong>
Compendium -> NPC Classes -> click the stats like armor to sort ascending or descending. 
<strong>Expected behavior: </strong>
For NPCs to be sorted. 
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
collected in #840
