### ISSUE TITLE
[BUG] Can't destroy last weapon from repaired structure damage

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1018]
<strong>Submitted At: </strong>8/7/2020 12:44:16
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
I repaired my mech mid-mission twice, fixing two structure. Later, I took a structure, and had to destroy my last remaining weapon. However, selecting it in the menu as it arrived left it unbroken. Repeating the structure repeats the inability to destroy it
<strong>To Reproduce: </strong>
I had a manticore with a Flex (Swarm/hive nanite) and a heavy( Nanobot whip). The flex was already destroyed, I repaired to full structure, without fixing the weapon. Later, took a stress, rolled that would destroy the heavy, and it was not listed as destroyed. Restoring the structure, and trying to re-apply the damage continues to have the heavy selectable, and undestroyable
<strong>Expected behavior: </strong>
The heavy weapon is destroyed as expected
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Auraknight#5417
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
