### ISSUE TITLE
[BUG] NPC issue

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1020]
<strong>Submitted At: </strong>8/8/2020 8:28:08
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
No NPC data in compendium and can't build new NPCs in Encounter Builder
<strong>To Reproduce: </strong>
Go to Encounter toolkit -> NPC Roster -> Add new NPC -> no options available in Select NPC Class.

Go to Compendium -> select any of the three NPC options, and they are all empty 
<strong>Expected behavior: </strong>
The ability to view what is available for NPCs abd ti build new ones for encounters
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Kwisatz Haderach#0685
<strong>Stack Trace: </strong>

**Comment by Eranziel** [comment]
Working as intended - NPC LPC must be downloaded from itch and installed to add NPC content.
