### ISSUE TITLE
[BUG] Players missing on loading mission in progress

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1021]
<strong>Submitted At: </strong>8/8/2020 18:05:16
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Upon loading in-progress mission, players are not on tracker
<strong>To Reproduce: </strong>
Load in mission in progress (possibly after opening component encounter)
<strong>Expected behavior: </strong>
Players should be present
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
@Ninjaxenomorph#5067
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
