### ISSUE TITLE
[BUG] ERROR IMPORTING PILOT: t.loadouts is undefined when cloud or file importing

### ISSUE THREAD

**Issue by lowercasename** [massif-press/compcon#1022]
**Describe the bug**
When I try to import my pilot either via its cloud code or as a file, I receive the following message:

```
ERROR IMPORTING PILOT: t.loadouts is undefined
```

**To Reproduce**
1. Download the file I've attached below or use this cloud code: 98fcdce9cfa6e3eed9758ee3f3d89411
2. Attempt to import it into the pilot roster.

**Expected behavior**
My pilot to be imported into COMP/CON.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 79.0

[MIMIR.zip](https://github.com/massif-press/compcon/files/5046937/MIMIR.zip)

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
