### ISSUE TITLE
[BUG] Instances of Knowledge Downtime Reserves are actually duplicates of the same instance

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1028]
<strong>Submitted At: </strong>8/17/2020 1:59:48
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When creating new Knowledge Resource Downtime Reserve objects, if two or more are created at once, anything typed into or changed about one will be changed about the other. This does NOT occur if you reload COMP/CON between creations. Reloading also breaks the effect for existing objects that may have exhibited this behavior.
<strong>To Reproduce: </strong>
1. Create or open any character sheet.
2. Add a new Knowledge Downtime Reserve.
3. Type "Test" into the 'notes' section.
4. Add another new Knowledge Downtime Reserve. Inspect it.
5. Observe that "Test" is duplicated in its notes.
6. Change "Test" to "Test 2" while still in the second Knowledge Downtime Reserve.
7. Return to the 1st object.
8. Observe that its text has changed from "Test" to "Test 2."
9. Reload COMP/CON.
10. Reopen the character sheet.
11. Create a third new Knowledge Downtime Reserve.
12. Open it and observe that its notes have no text.
13. Write any text in its notes field.
14. Open the other two, and observe that their text is unchanged.
15. Change either of the other two's notes fields.
16. Open the other, and observe that its text is unchanged, unlike before reload.
<strong>Expected behavior: </strong>
Creating multiple objects of the same type shouldn't duplicate their notes.
<strong>Additional context: </strong>
I was pretty confident this would be something to do with failing to generate multiple entries, but the fact that reload causes it to work right makes me think that instead you're missing on an attempted reference in JQuery or whatever it is you guys use. Obviously, though, it's some kind of data linkage issue.
<strong>Contact Info: </strong>
Maersk Aerospace#6777
<strong>Stack Trace: </strong>

**Comment by sirbayer** [comment]
I didn't see this before I finished this bug report, but I'd wager money that this bug is related: https://github.com/massif-press/compcon/issues/677 It behaves in essentially the exact same way - as though the things displayed on the screen are actually copies of each other, instead of unique entities.
