### ISSUE TITLE
[BUG] NPC Archer Suppress is Mislabeled as reaction instead of Quick Action

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1034]
<strong>Submitted At: </strong>8/22/2020 9:39:40
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Suppress is considered a reaction instead of a quick action in the NPC UI. (using Lancer Core NPCs 1.0.4)
<strong>To Reproduce: </strong>
Make a new Archer NPC and look at its abilities.
<strong>Expected behavior: </strong>
Suppress should be considered a quick action instead of a reaction.
<strong>Additional context: </strong>
I'm not sure if there are any other non-reaction abilities with the reaction tag, but they also may have been mislabeled. Might be worth looking through. It also looks like the optional abilities Covering Fire/Got Your Back got merged into one kinda messy reaction block instead of being separate ones. This one seems harder to fix.
<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by SudoSanauu** [comment]
It looks like this is specifically in line 403-420 of npc_features.json:

```json
  {
    "id": "npcf_suppress_archer",
    ...
    "type": "Reaction",
    ...
  },
```
to:
```json
  {
    "id": "npcf_suppress_archer",
    ...
    "type": "Quick Action",
    ...
  },
```

Change gets more messy for Covering Fire/Got Your Yack, but that's on line 486.

**Comment by SudoSanauu** [comment]
The same problem appears to be present in the Mirage's Glitch Scanner's Quick Action, the Sentinel's Bodyguard Protocol. and the Sniper's Defensive Grapple Quick Action.
