### ISSUE TITLE
[BUG] Flex/Aux

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1035]
<strong>Submitted At: </strong>8/24/2020 12:48:35
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Using Mount Retrofitting on a Flex Mount lets you mount 3 Aux weapons.
<strong>To Reproduce: </strong>
If you use the Mount Retrofitting GMS Core Bonus on a Flex Mount and then put an Auxiliary Weapon in the Main slot of the newly created Main/Aux, it still thinks it's part of a Flex Mount and gives you a 3rd Aux slot on the Main/Aux.
<strong>Expected behavior: </strong>
I should have only been able to put 2 Aux Weapons in a Main/Aux.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Declansion#8984 (A Dreaming Bass in Pilot NET)
<strong>Stack Trace: </strong>

**Comment by Harlekin13** [comment]
still an issue
![grafik](https://user-images.githubusercontent.com/34014817/97382705-3bc39300-18cc-11eb-9ea7-5478a3259f8a.png)
