### ISSUE TITLE
[BUG] Mimic gun damage type is shown as variable, but should be kinetic

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1036]
<strong>Submitted At: </strong>8/27/2020 23:07:40
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
Looking in lancer-data it appears that the "type" property was simply left out. Though the damage values change, the type is always kinetic.
<strong>To Reproduce: </strong>
In Mech Weapons compendium screen, observe the mimic gun's damage column entry
<strong>Expected behavior: </strong>
Should show kinetic.
<strong>Additional context: </strong>
I only really care because that field not existing was making Foundryvtt have some issues, and figured it would be better to cut it off at the source
<strong>Contact Info: </strong>
WHITESPINE
<strong>Stack Trace: </strong>

**Comment by Harlekin13** [comment]
seems to me only the symbol is wrong
![grafik](https://user-images.githubusercontent.com/34014817/97383004-e045d500-18cc-11eb-9994-e7a7529e7e20.png)
