### ISSUE TITLE
[BUG] Hunter I Text Update

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1038]
<strong>Submitted At: </strong>8/31/2020 23:54:45
<strong>Platform: </strong>
Data Entry
<strong>Describe the bug: </strong>
Hunter I, Lunge, was changed to say "directly toward a targeted character before the attack" rather than "directly toward a character before the attack" and comp/con's text hasn't been updated to match.
<strong>To Reproduce: </strong>
This is a text issue
<strong>Expected behavior: </strong>
Comp/con should match the pdf text
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
