### ISSUE TITLE
[BUG] Png render issue in mech hanger

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1039]
<strong>Submitted At: </strong>9/2/2020 3:21:39
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Custom mech images (.png) Without background are displayed with a white background
<strong>To Reproduce: </strong>
Upload a png with a transparent background as a mech image
<strong>Expected behavior: </strong>
Image should be displayed without white background 
<strong>Additional context: </strong>
http://prntscr.com/ua3uxo  <- Uploading displays image properly http://prntscr.com/ua3v5f <- Build page does not
<strong>Contact Info: </strong>
Cthegoalie#4005
<strong>Stack Trace: </strong>

**Comment by smangham** [comment]
Still happening for this image:
![iskander3_upscaled](https://user-images.githubusercontent.com/8093436/174666231-07458ec5-3e16-416b-8517-3a4716d02111.png)

![compcon_image_upload](https://user-images.githubusercontent.com/8093436/174666187-2df77286-3db9-4603-b34b-421c532a09c5.png)
![compcon_image_error](https://user-images.githubusercontent.com/8093436/174666181-b9dc0574-05b2-4020-a2af-33f1bc8f2088.png)

Didn't happen when I downloaded one of the core images and tried re-uploading, so it's presumably some property of the image?
