### ISSUE TITLE
[BUG] Mimic Gun Core Bonus

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1040]
<strong>Submitted At: </strong>9/2/2020 12:59:13
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
In mech creation I can apply Overpower Caliber to the Mimic Gun
<strong>To Reproduce: </strong>
Create a pilot at least LL3. Take 2 licence levels in Pegasus. Take the Overpower Caliber Core Bonus. Create a mech with a heavy mount. Equip the Mimic Gun, then you can equip Overpower Caliber on the Mimic Gun
<strong>Expected behavior: </strong>
The Mimic Gun should not be allowed to benefit from Overpowered Caliber
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by Harlekin13** [comment]
it's not possible when using the pegasus frame, using the everest neither.
