### ISSUE TITLE
Feature Request: Show lower rank talent effects

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1044]
<strong>Submitted At: </strong>9/4/2020 15:21:17
<strong>Is your feature request related to a problem? Please describe. </strong>
Active mode only displays the effect of the highest rank in a talent
<strong>Describe the solution you'd like: </strong>
I'd like to see what the effects of the lower ranks are as well
<strong>Additional context: </strong>

<strong>Contact: </strong>
Reverend _Roscoe#5035

**Comment by jarena3** [comment]
collected in #1217
