### ISSUE TITLE
[BUG] caliban's Super massive mod

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1045]
<strong>Submitted At: </strong>9/6/2020 0:17:30
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
the caliban's super massive mod isnt showing up as an available mod for an cannon, cqb, or melee weapon
<strong>To Reproduce: </strong>
with the super massive mod unlocked, selecting to mod a cannon cqb or melee and viewing the listed options
<strong>Expected behavior: </strong>
for the mod to be a listed option
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
BigHatDreglin #0870
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
