### ISSUE TITLE
[BUG] MSMC poor print visibility

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1047]
<strong>Submitted At: </strong>9/7/2020 10:59:43
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When printing a character sheet with the Mirrorsmoke theme chosen, some of the text is still using the light-on-dark color scheme from the theme and is thus difficult to read against white paper.
<strong>To Reproduce: </strong>
Select the MSMC theme, create a character, go to Print.
<strong>Expected behavior: </strong>
Good print contrast regardless of visual theme selected.
<strong>Additional context: </strong>
Screenshot: https://i.imgur.com/dbqgOBR.png
<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
