### ISSUE TITLE
[BUG] Small Theme + Glyph visibility problem.

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1048]
<strong>Submitted At: </strong>9/8/2020 21:31:42
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
The Tier 3 NPC glyph is black - just like the HORUS Theme background. Unless highlighted, the glyph is not visible in the NPC Roster.
<strong>To Reproduce: </strong>
Select the HORUS theme. Create a Tier 3 NPC and enter the NPC Roster screen.
https://cdn.discordapp.com/attachments/392709194039689226/753078316688343046/unknown.png
<strong>Expected behavior: </strong>
A visible glyph is expected.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in 2.2.2
