### ISSUE TITLE
[BUG] Hide typo

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1049]
<strong>Submitted At: </strong>9/12/2020 15:34:30
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
The text for Hide in the compendium writes "disap‐ pears" rather than "disappears"
<strong>To Reproduce: </strong>
Go to the compendium -> action economy -> hide
<strong>Expected behavior: </strong>
For it to not be a typo
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Corrected in 2.2
