### ISSUE TITLE
[BUG] Berserker tactics misplaced

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1050]
<strong>Submitted At: </strong>9/13/2020 3:50:58
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
The "Tactics" description for the Berserker NPC shows up inside the "Flavour" section of it's entry in the NPC roster screen.
<strong>To Reproduce: </strong>
Make a Berserker NPC and check it's tactics and flavour boxes
<strong>Expected behavior: </strong>
The things to be in the right places
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Norgad#8398
<strong>Stack Trace: </strong>

**Comment by msprijatelj** [comment]
This fix has been applied to the Lancer NPC Data and will ship with the newest version of the LCP.
