### ISSUE TITLE
Feature Request: Make labeled NPC sections collapsible

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1051]
<strong>Submitted At: </strong>9/14/2020 14:20:32
<strong>Is your feature request related to a problem? Please describe. </strong>
NPCs lists can get long, and helps save on scrolling. 
<strong>Describe the solution you'd like: </strong>
Being able to click on the arrow next to the NPC label to collapse it. 
<strong>Additional context: </strong>

<strong>Contact: </strong>
R0bobot#2547

**Comment by jarena3** [comment]
collected in #982
