### ISSUE TITLE
[BUG] Quick Sync at pilot view is non-functional

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1053]
<strong>Submitted At: </strong>9/21/2020 0:24:02
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When at a pilot's profile screen, the Quick Sync option found within the cog menu does not sync, or even give an indication that it synced.
<strong>To Reproduce: </strong>
Enter a pilot's profile view. Open the Pilot Options menu from the bottom bar. Click "Quick Sync"
<strong>Expected behavior: </strong>
It should, (and used to) sync the pilot's cloud file, and activate the Pilot Data Saved notification.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
@OhCubed#7157
<strong>Stack Trace: </strong>
No information is present in the Error Log.

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
