### ISSUE TITLE
Feature Request: Pilot grouping issue with cloud synced sheets

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1054]
<strong>Submitted At: </strong>9/21/2020 15:52:06
<strong>Is your feature request related to a problem? Please describe. </strong>
As a GM i have a lot of player character sheets i like to have organized by campaign. However currently Characters retain their grouping from their creator through cloudsync, which gets refreshed everytime they get synced, which causes them to disrupt my grouping structure.
<strong>Describe the solution you'd like: </strong>
Removing Group information from the cloud sync data should fix this issue and allow local grouping without any issues.
<strong>Additional context: </strong>

<strong>Contact: </strong>

**Comment by jarena3** [comment]
Added in 2.2.6
