### ISSUE TITLE
[BUG] Descriptions for mech weapons seem to be broken

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1057]
<strong>Submitted At: </strong>9/22/2020 23:20:13
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
Full disclosure, first time using the application. 
It seems like the mech weapon descriptions aren't being loaded in correctly, as its just the same paragraph being shown for all weapons. I assume there would normally be the unique weapon description there. 
<strong>To Reproduce: </strong>
In the mech hangar, select a mech to view (or when creating a mech). Occurs when viewing all types of weapons.
<strong>Expected behavior: </strong>
I'm *assuming* it is supposed to show specific item descriptions. But I could be wrong! I'm submitting this because I'd rather have y'all know and the be wrong, than not know and let it keep being a problem.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
st.jude#2205
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
