### ISSUE TITLE
[BUG] Engineer Prototype Weapon Incorrect Text

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1059]
<strong>Submitted At: </strong>9/24/2020 20:40:32
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
The rules text for the Prototype Weapon Integrated Mount on the mech of a pilot displays an incorrect value for the 3rd tier of the talent. It describes the amount of limited uses as 1d6+2 still instead of as 2d6 which it should be. 
<strong>To Reproduce: </strong>
Take the Engineer talent to Tier 3 on any character and observe the integrated mount in either the Mech Hangar or Active Mode. The weapon effect text will have a line stating "Additionally, each time you perform a Full Repair, reroll 1d6+2 to determine this weapon’s Limited uses and choose two:"
<strong>Expected behavior: </strong>
The Integrated Mount's weapon effect text in the Tier 3 version of the talent should instead read as "Additionally, each time you perform a Full Repair, reroll 2d6 to determine this weapon’s Limited uses and choose two:"
<strong>Additional context: </strong>
There's also no method to add the rolled number of limited uses to the toggleable pips on the weapon, which may lead to some confusion.
<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Corrected in 2.2
