### ISSUE TITLE
Feature Request: Engineer Integrated Mount Display Limited Uses

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1060]
<strong>Submitted At: </strong>9/24/2020 20:45:46
<strong>Is your feature request related to a problem? Please describe. </strong>
The Prototype Weapon doesn't properly display the amount of limited uses an Engineer weapon has, as there's currently no way to input the result of the die roll to determine how many it gets. Instead, the only pips shown are those resultant from Engineering and Core Bonus.
<strong>Describe the solution you'd like: </strong>
A simple input method where the player can enter the number they rolled and have the limited use pips show up properly as that number, plus whatever bonus limited uses they have from other sources.
<strong>Additional context: </strong>

<strong>Contact: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
