### ISSUE TITLE
[BUG] Flatmap is not a function.

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1062]
<strong>Submitted At: </strong>9/27/2020 7:00:14
<strong>Platform: </strong>
Browser - Chrome within Tabletop Simulator
<strong>Describe the bug: </strong>
When creating, importing (file), and importing (cloud) it give me Error Importing Pilot: this.Contentacks.filter(...).flatMap is not a function.
<strong>To Reproduce: </strong>
Create, Import (file), or import (cloud) within TTS tablet browser.
<strong>Expected behavior: </strong>
Successful pilot creation or import.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Discord thirteenstrings#0566
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
