### ISSUE TITLE
[BUG] Scrollbar Bug when Editing Pilot Notes

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1065]
<strong>Submitted At: </strong>9/28/2020 17:38:26
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
On the pilot dossier, once the page is of sufficient length, typing anything into the "Player Notes" section causes the scrollbar to jump up so that the bottom navigation bar obscures whatever you're typing.
<strong>To Reproduce: </strong>
Create a pilot. On the dossier tab, fill out the pilot biography or pilot appearance with a paragraph or so. Then, go down to "player notes." Press enter a few times and type something. You'll quickly see the scroll bar start going crazy every time you input something. 
<strong>Expected behavior: </strong>
I don't understand what this question is asking.
<strong>Additional context: </strong>
I tried this a few times with a dummy pilot and placeholder text and the results were consistent.
<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Unable to reproduce
