### ISSUE TITLE
Feature Request: Homebrew Trigger LCPs

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1068]
<strong>Submitted At: </strong>9/29/2020 17:51:00
<strong>Is your feature request related to a problem? Please describe. </strong>
The official pilot triggers can vary from really broad (hack or fix) to really specific (blow something up). Our campaign likes to modify them a little for our own needs, sometimes by coming up with new ones. Currently, you can add custom triggers by giving players a reserve for it, and you can add new gear and mechs via uploading your own homebrew LCPs, but you can't just straight-up homebrew a new trigger to add to the list.
<strong>Describe the solution you'd like: </strong>
Add triggers to the accepted homebrew LCPs along with mechs, weapons, pilot gear, etc.
<strong>Additional context: </strong>

<strong>Contact: </strong>

**Comment by jarena3** [comment]
Added in 2.2
