### ISSUE TITLE
[BUG] Compendium NPC classes list not sortable

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1069]
<strong>Submitted At: </strong>10/7/2020 11:02:52
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
By clicking column titles, only the Class and Role columns change the order in the list
<strong>To Reproduce: </strong>
Go to the compendium > npc classes and try sorting the list by clicking the column titles
<strong>Expected behavior: </strong>
Be able to sort in descending or ascending order the npc list according to the column selected, to quickly see which npc has the most armor, highest heat cap or lowest sensor range
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Gorabora#6645
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
collected in #840
