### ISSUE TITLE
[BUG] Osiris NHP not classified as AI

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1072]
<strong>Submitted At: </strong>10/8/2020 2:39:09
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Osiris is not considered an AI for the purposes of searching the Compendium, it is instead filed under Tech.
<strong>To Reproduce: </strong>
go to mech systems, filter HORUS and AI "system type", see that Osiris is not there
<strong>Expected behavior: </strong>
see Osiris alongside other NHPs when searched for.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Corrected in 2.2
