### ISSUE TITLE
[BUG] number entry with horus theme text colour

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1074]
<strong>Submitted At: </strong>10/11/2020 17:57:23
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
With the horus terminal visual theme the number entry box on the action page (ie for HP, overshield, heat) that appears when you click the small keyboard icon still appears as black text on a black background so you can't see the number you are entering.
<strong>To Reproduce: </strong>
Switch to Horus Terminal then click the keyboard icon on the action page next to overshield 
<strong>Expected behavior: </strong>
The text will be black text on a black background ie invisible 
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
