### ISSUE TITLE
[BUG] Typo in FAQ

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1077]
<strong>Submitted At: </strong>10/12/2020 8:49:30
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
One of the "the"s is "ththe" in the FAQ.
<strong>To Reproduce: </strong>
Head to the FAQ next to the report button.
<strong>Expected behavior: </strong>
Should just be "the"
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in 2.2.2
