### ISSUE TITLE
[BUG] Tier 3 NPC Symbol Not Visible

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1078]
<strong>Submitted At: </strong>10/13/2020 13:50:00
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
In the NPC Roster, in the list of NPCs, the symbol denoting that an NPC is tier 3 is a different colour than the other tier symbols. This is most problematic in the Horus Terminal colour scheme where the black symbol becomes invisible against the black background.
<strong>To Reproduce: </strong>
Create an NPC, make it tier 3 and observe the symbol in the list on the left hand side. Most notable in the Horus Terminal colour scheme.
<strong>Expected behavior: </strong>
The symbol should be the same colour as the other tier symbols, or at the very least should be a different colour from each of the colour schemes' backgrounds so that it is clearly visible.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in 2.2.2
