### ISSUE TITLE
[BUG] Typos

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1079]
<strong>Submitted At: </strong>10/14/2020 14:28:43
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
A typo in Thermal Pistol and Thermal Rifle decriptions. There's one additional period at the end.

"The Type-II (T-2) line displays GMS’s proprietary “charged” melee weapons and energy weapons. ."

Meanwhile, Charged Blade lacks a period at the very end.
<strong>To Reproduce: </strong>
Read the descriptions, I guess.
<strong>Expected behavior: </strong>
Proper text.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in 2.2.2
