### ISSUE TITLE
[BUG] Typo in Flash Clone Quirk

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1081]
<strong>Submitted At: </strong>10/18/2020 23:36:49
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When scrolling over the 'X' to remove flash clone quirk, the descriptive text says "this will remove the pilot's quirt and clear their cloned status"
<strong>To Reproduce: </strong>
Scroll over the 'X' to remove quirk on a flash-cloned character
<strong>Expected behavior: </strong>
I did not expect to see a typo.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
corrected in 2.2
