### ISSUE TITLE
[BUG] Player mechs show as destroyed in mission runner after repairs

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1083]
<strong>Submitted At: </strong>10/23/2020 16:18:17
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
Player mechs that have been destroyed due to structure damage show as destroyed in the mission runner and do not get a turn, even if structure has been restored. 
<strong>To Reproduce: </strong>
1. On any fresh character, enter active play mode and enter combat.
2. Reduce structure by two and roll snake eyes.
3. End combat and spend the required repairs to restore the mech. Do not use full repair.
4. Add the character to any combat encounter in the mission runner. It will show as destroyed, despite having positive structure, stress, and HP.
<strong>Expected behavior: </strong>
Restoring structure by spending repairs after a combat should allow the mech to take turns in the mission runner.
<strong>Additional context: </strong>
Using the Full Repair button in active play mode allows the mech to be used in the mission runner again, but no other method appears to clear the "destroyed flag".
<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in 2.2
