### ISSUE TITLE
[BUG] Skill Trigger bonus with Reserves unusable

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1084]
<strong>Submitted At: </strong>10/25/2020 9:32:39
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When adding a Skill Point with the Reserves and Bonuses menu, the Skill Triggers count does update but, it doesn't allow the user to spend the new point
<strong>To Reproduce: </strong>
Go into Narrative Profile of a pilot, add a Skill Point Reserve and go try to edit the Skill Triggers
<strong>Expected behavior: </strong>
The newly acquired Skill Point should allow the pilot to upgrade one of his Skill Triggers
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Gorabora#6645
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
