### ISSUE TITLE
[FEATURE] option to unrestrict selection for licenses

### ISSUE THREAD

**Issue by Harlekin13** [massif-press/compcon#1085]
**Is your feature request related to a problem? Please describe.**

we got rewarded some random horus licenses for some major upload of data into the omninet. the ones we got were rank2 or rank3, but without the other ranks that come before that. for example i got the rank2 goblin license but not the rank1 license for that pattern group. It was possible to add a license point in reserves&bonuses and as i wanted the goblin anyway, i just took the rank1 license with the levelup, otherwise i wouldn't have been able to select the rank2 license. But if i had gotten a license i would have never picked myself (for example a minotaur rank3 license for my character) it would bother me more that i'd have to relocate other licenses to be able to select it even though i am not interested in neither rank2 nor rank3 of that pattern group.

**Describe the solution you'd like**

the license ranks look like there wouldn't be a problem if there was an option like with systems to unrestrict the selection, therefore adding that option would be nice. as a bonus it would address some issues from "[FEATURE] License Level parsing refactor #628" at least as a workaround, namely unlocking a frame with license rank1 or rank3 instead of rank2, the ranks wouldn't be in the correct order but it would be possible to select them.

**Describe alternatives you've considered**

it looks possible, to make the licensing in a way that you always could select any rank instead, but i think if it is intended that players go through the ranks in a certain order, adding only the option to unrestrict it would make it clear that the player is only intended to do it in agreement with the gm.

**Additional context**

**Comment by Harlekin13** [comment]
quote from beeftime:
when I get to manna rules there will be a reserve option added that unlocks a specific piece of gear until the reserve is removed. There won't, though, be any way to eg. get the third rank of a license independent from the first two


That would fix the problem (as the licenses shouldn't count towards corebonuses) even better than the fix i could come up with.

**Comment by jarena3** [comment]
colleted in #630
