### ISSUE TITLE
[BUG] Comp/Con Active Mode does not correctly handle Overheating Check on 1 Stress remaining

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1087]
<strong>Submitted At: </strong>11/3/2020 4:40:50
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When I remove my 3rd point of stress and pick a result that includes a single {{1}} on the die roll, it treats it as I have 2 points of stress remaining and has me make a check to avoid overheating.
<strong>To Reproduce: </strong>
When you are on 2 Stress left, remove 1 Stress, choose 1 and 2 other non-1 numbers and see what happens.
<strong>Expected behavior: </strong>
According to the Core Rulebook, it should meltdown instead.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
