### ISSUE TITLE
[BUG] Missing tags for mech systems that give reactions

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1089]
<strong>Submitted At: </strong>11/8/2020 12:22:55
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
There are a number of systems that give additional reactions, but that aren't tagged as reactions, so they don't show up if you filter for reactions
<strong>To Reproduce: </strong>
In the compendium, under mech systems, setting an item filter for the reaction tag
<strong>Expected behavior: </strong>
The untagged systems, afaik, are:
GMS Turret Drones
HA Noah NHP
HORUS Assassin Drone
HORUS Mimic Mesh
HORUS Monitor Module
HORUS Scylla NHP
IPSN Aegis Shiled Generator
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
