### ISSUE TITLE
Feature Request: Campaign manager

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1090]
<strong>Submitted At: </strong>11/8/2020 12:43:52
<strong>Is your feature request related to a problem? Please describe. </strong>
The campaign manager and encounter sheets have been visible in Comp/Con for ages but always marked as "in development", with no indication of what stage that development's at. Can we still expect these to be added, or will they just be removed at some future patch?
<strong>Describe the solution you'd like: </strong>
Some developmental transparency at least. Preferably the functionality in question being added.
<strong>Additional context: </strong>

<strong>Contact: </strong>

**Comment by jarena3** [comment]
Collected in #380
