### ISSUE TITLE
[BUG] Misaligned element on limited use items

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1091]
<strong>Submitted At: </strong>11/10/2020 22:00:29
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When you click to modify the amount of uses left on a mech system or pilot item such as Flash Charges or Stims, a circular effect pops up behind the hexes that serve as counters. This circle is too far to the right.
<strong>To Reproduce: </strong>
Click a counter hex to modify the remaining uses in a limited use system/item.
<strong>Expected behavior: </strong>
For the circle to be properly aligned.
<strong>Additional context: </strong>
Replicated with GMS and MSMC themes. Didn't check with HORUS theme. Image of what I'm talking about here, because I can suck at descriptions: https://i.imgur.com/hWVzO3n.png
<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
