### ISSUE TITLE
[BUG] 2 Repair Reactor

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1092]
<strong>Submitted At: </strong>11/11/2020 2:28:54
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
After spending 4 repair to rebuild a destroyed mech, spending 2 Repair on reactor fixes up to 4 reactor instead of 2.
<strong>To Reproduce: </strong>
Destroy mech via structure.
Rebuild mech using ally repair cap.
Click spend 2 repair cap for reactor.
Error: 4 reactor instead of 2.
<strong>Expected behavior: </strong>
Mech is repaired to 2 reactor.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
