### ISSUE TITLE
[BUG] Compendium: Missing Deployable Tags

### ISSUE THREAD

**Issue by Luciferos** [massif-press/compcon#1093]
**Describe the bug**
All Deployable tag systems from Core are missing in the Compendium Gear List, excepting those from add-on White Witch and Kidd systems. Sorting by Deployable tag in Mech Systems only shows Kidd and White Witch Deployables. (SEE BELOW)

Searching by System Type Deployable works fine so this is a minor issue, but System Type: Deployable also includes grenade systems which are not actually Deployables and do not have the Deployable tag; having a way to sort out specifically for systems that actually produce Deployables would be desirable. 

**To Reproduce**
1. Go to Compendium
2. Go to Mech Systems list
3. Add Tag Deployable

**Expected behavior**
The following list of additional systems would show up if Deployable Tag is selected:

-Pattern-A Jericho Deployable Shield
-Aegis Shield Generator
-Portable Bunker
-Webjaw Snare
-Perimeter Command Plate

**Screenshots**
![image](https://user-images.githubusercontent.com/20429868/98849181-d2da3000-2420-11eb-9475-1e671548f53c.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser/Version: Tested in Opera v.72.0.3815.186, Firefox v.82.0.2 x64, Chrome 86.0.4240.183

**Additional context**

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
