### ISSUE TITLE
Feature Request: Folders in the NPC Roster and Encounter Builder

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1094]
<strong>Submitted At: </strong>11/13/2020 2:40:00
<strong>Is your feature request related to a problem? Please describe. </strong>
I'm frustrated by my own clutter, but don't wish to delete or download just to reupload old units.
<strong>Describe the solution you'd like: </strong>
Folders just like the Pilot roster, drag and drops that are collapsable.
<strong>Additional context: </strong>
No extra context, but thanks for making Lancer so much easier to play and run!
<strong>Contact: </strong>

**Comment by jarena3** [comment]
collected in #982
