### ISSUE TITLE
[BUG] Freeze on uploading pilot image

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1096]
<strong>Submitted At: </strong>11/13/2020 21:44:33
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When uploading files with large dimensions the file upload image throws an "error 500" and stops working.
<strong>To Reproduce: </strong>
Attempted to upload this file: http://www.cgfeedback.com/cgfeedback/attachment.php?attachmentid=16497&d=1355502157
<strong>Expected behavior: </strong>
It's a fairly small file in size so I expected it to upload quickly.
<strong>Additional context: </strong>
The rest of comp/con is working fine, but the upload page is stuck and unresponsive to anything but closing it
<strong>Contact Info: </strong>
CYAN
<strong>Stack Trace: </strong>
```
Vue error at [cc-btn]
t.exports@https://compcon.app/app.bundle.js:85:23677
t.exports@https://compcon.app/app.bundle.js:85:1519154
t.exports/</m.onreadystatechange@https://compcon.app/app.bundle.js:85:22525
```

**Comment by jarena3** [comment]
Overly large file sizes run up against imgur's limits
