### ISSUE TITLE
[BUG] Monarch License 2 not appearing

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1097]
<strong>Submitted At: </strong>11/16/2020 4:28:10
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Selecting License Rank 2 of the Monarch doesn't actually give me the Gandiva Missiles or Stabilizer Mods that are supposed to be on it.
<strong>To Reproduce: </strong>
Tried removing the license and returning it - still no Gandivas or Stabilizer Mods. Tried it on another character, too, and the license just didn't appear.
<strong>Expected behavior: </strong>
...I expected to get my gun and my mod?
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Unable to reproduce
