### ISSUE TITLE
[BUG] Pilots vanish from encounter runner when continued

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1098]
<strong>Submitted At: </strong>11/16/2020 11:45:12
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
After clicking to continue an encounter in the mission runner, the pilots that had been part of the encounter are no longer there. Other than the pilots missing, everything else was fine, all stats were correctly recorded.
<strong>To Reproduce: </strong>
Unsure, when attempting to simply replicate it by making a new encounter with PCs, stopping and restarting it, the bug did not reoccur.
<strong>Expected behavior: </strong>
I expected to return to the encounter and have everything as it was when I left it (2 dead NPCs, 5 alive NPCs, 2 allied NPCs, 3 Pilots). 
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
