### ISSUE TITLE
[BUG] Import Long Rim problem

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1104]
<strong>Submitted At: </strong>11/21/2020 19:50:46
<strong>Platform: </strong>
PWA - Android
<strong>Describe the bug: </strong>
Inability to import The Long Rim. Gets an error.
<strong>To Reproduce: </strong>
Going to Options>Import All COMP/CON Data and selecting the Lancer Long Rim Data-1.0.2.lcp
<strong>Expected behavior: </strong>
To import the long rim expansion 
<strong>Additional context: </strong>
Using most updated google chrome browser. Also attempted firefox, resulting in the same/similar problem.
<strong>Contact Info: </strong>
@Kbutzkorner
<strong>Stack Trace: </strong>
```
Vue error at [v-file-input]
SyntaxError: Unexpected token P in JSON at position 0
    at JSON.parse (<anonymous>)
    at https://compcon.app/app.bundle.js?__WB_REVISION__=c502c4647bdce82a7209:72:127238
    at https://compcon.app/app.bundle.js?__WB_REVISION__=c502c4647bdce82a7209:16:2086
    at Object.next (https://compcon.app/app.bundle.js?__WB_REVISION__=c502c4647bdce82a7209:16:2191)
    at r (https://compcon.app/app.bundle.js?__WB_REVISION__=c502c4647bdce82a7209:16:930)```

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
