### ISSUE TITLE
[BUG] Create New Vault Record Not Working

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1108]
<strong>Submitted At: </strong>11/24/2020 13:40:14
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Whenever I click "Create New Vault Record" it'll load for a second, but then nothing happens. The text in the window still reads "PILOT STATUS:  No Vault data found PILOT SHARE CODE:  No Vault data found LAST UPDATE:  Never"
<strong>To Reproduce: </strong>
I've created a pilot ages ago and play every week using the browser version of Comp/Con on Chrome, but every now and again, I'll open Comp/Con up to find my pilot missing completely. To counteract this, I export the .JSON file for my pilot after every session and keep it as a backup for whenever he disappears off Comp/Con. I would like to make it easier by using the "Omninet Vault" feature but it never seems to want to generate a code for my pilot.
<strong>Expected behavior: </strong>
I would expect to be able to click "Create New Vault Record" and then see a code for my pilot to generate that I can then update at the end of every session and type in whenever my Comp/Con resets and wipes my pilot.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
My Discord is spoopy#4155
<strong>Stack Trace: </strong>

**Comment by Radai** [comment]
I also encountered this issue when recently (Nov 25, 2020) I tried syncing my pilot data to the Cloud but my GM couldn't see my pilot data in our Mission Runner. My pilot info was not updating via the previous share link, so I created a new Vault Record and experienced the same issue described above. I created a new Vault Record but it doesn't give me a shareable link nor can I do anything else.

Further, when I click the Save to Cloud button next to me Omninet Uplink ID on my Pilot page, I get "Unable to sync: Error: Request failed with status code 401" in the bottom right popup.

Also using Chrome.
