### ISSUE TITLE
[BUG] 401

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1109]
<strong>Submitted At: </strong>11/25/2020 1:00:21
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
I keep getting 401. I can't sync my old and new characters.
<strong>To Reproduce: </strong>
Create a new character and try to create a vault record, you'll get no sync. If you try to import an old character, it gives a 401 error.
<strong>Expected behavior: </strong>
Proper cloud sync.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
ecthelionv2#4904
<strong>Stack Trace: </strong>

**Comment by VexxMyst** [comment]
Can corroborate this issue, was trying to grab cloud link to import into Foundry and Save/Load is greyed out; Create New Vault Record activates for a second and ceases.
