### ISSUE TITLE
[BUG] For equipped Systems, "Change Item"/"Remove Item" under gear dropdown do nothing

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1112]
<strong>Submitted At: </strong>11/27/2020 19:04:09
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
On the "Mech Configuration" tab and in "Active Mode", the weapons and other systems currently equipped on the mech can be viewed and changed/removed.

For every currently equipped system (i.e. listed under the "Systems" section), there is a cog/gear icon to the left of the system's name. Clicking that icon causes a small menu to appear by it, with the following buttons/entries: "Change Item", "Mark as Destroyed", "Set Custom Name" and "Set Custom Description", and "Remove Item". (Each of these buttons includes both an icon and text.)

For some reason, clicking the "Change Item" or "Remove Item" buttons in this dropdown menu causes nothing to happen at all.

In contrast, to the right of the system's name (at the far end of the line), there are two icons: a "trash can" icon (which also appears in the gear menu next to "Remove Item") and a "curved vertical arrows" icon (which also appears in the gear menu next to "Change Item"); clicking either of these icons seems to behave as expected, changing/removing the system.
<strong>To Reproduce: </strong>
Build a mech, and add any desired systems to the mech. Then click the cog icon next to the system name, and click either "Change Item" or "Remove Item". (Nothing happens.)
<strong>Expected behavior: </strong>
When "Change Item" is selected from the gear menu, it should allow the currently equipped system to be swapped for a different one, as the corresponding icon to the right of the equipped system's name allows.

Likewise, when "Remove Item" is selected from the gear menu, it should remove the currently equipped system, as the corresponding icon to the right of the equipped system's name does.
<strong>Additional context: </strong>
For mounted weapons (i.e. listed under the "Weapons" section), clicking *either* the relevant icon outside the gear menu *or* the corresponding entry in the gear menu behaves as expected (removing the weapon or allowing it to be changed respectively).

But for some reason, *only* the icons outside the gear menu work for the "Systems" section - the entries in the gear menu seem to be totally nonfunctional.
<strong>Contact Info: </strong>
@V2Blast#8533
<strong>Stack Trace: </strong>
[N/A; error log is empty]

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
