### ISSUE TITLE
[BUG] Acions next round and Combatlog

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1113]
<strong>Submitted At: </strong>11/28/2020 11:32:45
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
If I skirmish with a weapon and complete the turn, on the next turn the weapon I skirmished with will be locked.Undoing action removes it from the Combat Log. 
<strong>To Reproduce: </strong>
>Start active mode
>Skirmish with a weapon
>Complete turn
>Check Combat Log
>Skirmish with the same weapon
-The weapon should be locked on the previous turn action-
>Undo action
>Check Combat Log
<strong>Expected behavior: </strong>
If I skirmish with a weapon and complete the turn, on the next turn the weapon I skirmished with will be locked, showing the action I took with the undo button available(as if I were still on th eprevious turn). If I undo the action to reroll a skirmish we the same weapon used before, it unlocks the weapon but the action taken on the precious turn is erased from the Combat Log.
<strong>Additional context: </strong>
This happened testing the new active mode.
<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
