### ISSUE TITLE
[BUG] Sitrep data is reference, not instance

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1114]
<strong>Submitted At: </strong>12/2/2020 14:26:29
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
I am noticing when setting up encounters that when I select a Sitrep for the encounter, and the navigate away from the window and come back to that specific Encounter that the Sitrep resets to Standard Battle. I however have noticed that the Sitrep is correct when plugging the Encounter into the Mission Builder and viewing it in the Mission Runner.
<strong>To Reproduce: </strong>
1) Create an Encounter, 2) Give the encounter a name and some other bit of data to prove that the whole Encounter isn't being reset. 3) Set the Sitrep to anything other than the default. 4) Return to the Home Screen and re-navigate to the Encounter Builder and select the aforementioned Encounter, where the other provided data should still be there but the SitRep has been returned to Standard Battle.
<strong>Expected behavior: </strong>
The Encounter Sitrep should persist between navigating pages in Comp/Con like other data does.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
cmdrmitch1136#5782
<strong>Stack Trace: </strong>
None Available that I could find

**Comment by msprijatelj** [comment]
This appears to have been handled by #1930. Closing.
