### ISSUE TITLE
[BUG] Hacking systems not flagged as Unique

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1116]
<strong>Submitted At: </strong>12/10/2020 23:46:14
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
In the Systems list for my Tortuga, I've already equipped Aggressive System Sync, yet when I go into the list of more systems, I still see it as an option, implying that I could take it multiple times on the same mech.
<strong>To Reproduce: </strong>
Three license levels into Tortuga, two into Minotaur and one into Goblin. Equip Aggressive System Sync, then reenter Systems list and reselect Aggressive System Sync.
<strong>Expected behavior: </strong>
I expected it to not do that, because having the same system twice feels redundant and the second one adds nothing on top of the first
<strong>Additional context: </strong>
It might be like that for other hacking modules too, dunno. Datapacks are installed, Long Rim 1.0.2 and Wallflower 0.9.14
<strong>Contact Info: </strong>
Nuke_The_Earth#9249
<strong>Stack Trace: </strong>
no log present

**Comment by jarena3** [comment]
Issue is in core data, wontfix until I get a Tom ruling
