### ISSUE TITLE
[BUG] Content pack mobile bug

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1117]
<strong>Submitted At: </strong>12/12/2020 13:41:28
<strong>Platform: </strong>
Android app
<strong>Describe the bug: </strong>
When I go to tap the content packs tab to try and download  long rim and wallflower content packs, it doesn't do anything. I dont get an error message or anything telling me the function is inoperable it just doesn't do anything.
<strong>To Reproduce: </strong>
Open the app. Tap content packs. 
<strong>Expected behavior: </strong>
The  content packs menu opens and should let me install wallflower and or long rim
<strong>Additional context: </strong>
No
<strong>Contact Info: </strong>
Zepher#0929
<strong>Stack Trace: </strong>
None

**Comment by jarena3** [comment]
Reimplemented in the 2.2.0 update
