### ISSUE TITLE
[BUG] Doubled stat row in Mech Configuration tab

### ISSUE THREAD

**Issue by Warp-Rider** [massif-press/compcon#1118]
In the mech config tab, the pilot stat row banner is still visible clipping out from underneath the mech stat row.  It is possible to hover the cursor over the state items and get pop-up text.

1. Go to the Mech Configuration tab, issue is immediately visible regardless of other variables (frame, LL, etc.)

I assume that the pilot stat bar should be replaced by, or completely obscured by the mech stat bar on this tab.

Screenshot attached.

 - OS: Windows 10 Pro and Windows 10 Home
 - Browser: Google Chrome and Microsoft Edge
 - Version: PREVIEW @ 280cbd6

![CompCon bug](https://user-images.githubusercontent.com/76007438/102123092-72ba1d80-3e14-11eb-8228-42d89c6b23f8.png)

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
