### ISSUE TITLE
[BUG] Active mode not taking NukeCav 2 into account

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1119]
<strong>Submitted At: </strong>12/24/2020 16:05:21
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
No matter what I do, the active mode does not add either the heat damage, or the extra d6 bonus damage from Nuclear Cavalier.
<strong>To Reproduce: </strong>
Do as above: add Nuclear Cavalier to a build, set heat to Danger Zone, and watch it not add the damage.
<strong>Expected behavior: </strong>
It adds the bonus damage, both heat and energy, as expected.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
TheLastShogun#7365
<strong>Stack Trace: </strong>
None available, not technically an error.

**Comment by jarena3** [comment]
this must be manually tracked, at least for now
