### ISSUE TITLE
[BUG] NPC Feature descriptions not in preview

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1120]
<strong>Submitted At: </strong>12/24/2020 16:27:27
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When selecting NPC optional features, the name of the feature appears but not the explanation text. Once an option is selected, both the name and text appear in the statblock correctly.
<strong>To Reproduce: </strong>
Click on the add feature button in an NPC statblock in the NPC roster. Clicking on the information button on the table view or click on the name of a feature in the list view. The description for the feature will not appear.
Alternatively, click on the add template button in an NPC statblock in the NPC roster. clicking on the names of the base or optional features will yield a text box containing only the name of the feature.

<strong>Expected behavior: </strong>
Clicking on the feature information gives both the name and description for a feature.
<strong>Additional context: </strong>
Fresh download of NPC lcp file, did a bulk import of all compcon data. Occurs with new NPCs and those created before the update. Bug still occurs on incognito windows. Bug also occurs on Chrome.
Works as expected on the old comp/con app.
<strong>Contact Info: </strong>
@Pretsal#2403
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
fixed in 2.2.0c
