### ISSUE TITLE
[BUG] Weapon filter not working

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1124]
<strong>Submitted At: </strong>12/25/2020 13:25:17
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
After the latest update filtering weapons stopped working. The same happens in Compendium>Mech weapons and when selecting weapons for specific mounts when configuring a mech.
The filter bar shows up normally and it's possible to select things from the dropdowns, but it does not affect the displayed list of weapons in any way.
<strong>To Reproduce: </strong>
Go to Compendium>Mech Weapons. Click the filter button on the top right. Select some items from the dropdowns (eg. Required Mount>Heavy and Weapon Type>Cannon)
<strong>Expected behavior: </strong>
Filtering works as before. Selecting something in the dropdowns restricts the list only to the weapons that match.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
ŁMM#7874
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in 2.2.2
