### ISSUE TITLE
Feature Request: Allow to organize the npc list

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1128]
<strong>Submitted At: </strong>12/25/2020 16:54:38
<strong>Is your feature request related to a problem? Please describe. </strong>

<strong>Describe the solution you'd like: </strong>
Allow me to drag in order the reorder the npcs I've constructed.
<strong>Additional context: </strong>

<strong>Contact: </strong>
Corvon#2560

**Comment by jarena3** [comment]
Collected in #453
