### ISSUE TITLE
[BUG] Can see mechs im not licensed for on mech creation

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1129]
<strong>Submitted At: </strong>12/25/2020 17:11:09
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Can see mechs im not licensed for on mech creation, specifically non-corebook mechs.
<strong>To Reproduce: </strong>
I made a pilot (latest wallflower and longrim .lcps), set level to 2, leveled up to 3 withe level up wizard thingie, moved on create the mech, then i could see mechs the pilot wasn't licensed for.
<strong>Expected behavior: </strong>
Not to see those options unless I did tick the unlock all the options thing.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Corvon#2560
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Unable to reproduce
