### ISSUE TITLE
Feature Request: X Button to consume all Movement

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1130]
<strong>Submitted At: </strong>12/26/2020 1:46:15
<strong>Is your feature request related to a problem? Please describe. </strong>
I find it a little fiddly to have to manually insert 0 to the Movement left in order to end the turn.
<strong>Describe the solution you'd like: </strong>
Ad an X Button that allows auto-sets movement left to 0, much like the Heat Reset X Button.
<strong>Additional context: </strong>
https://imgur.com/KzjhGHK
<strong>Contact: </strong>
Hit-Monkey#4540

**Comment by jarena3** [comment]
Added in 2.2.4
