### ISSUE TITLE
[BUG] Set Active Mech Button Missing

### ISSUE THREAD

**Issue by Warp-Rider** [massif-press/compcon#1132]
The Set Active Mech button is missing from the Mech Hangar screen.  There may be some poor scaling on the mouseover animation.

1. Go to mech hangar tab
2. Mouseover mechs

Upon mouseover, typically there is a button to set the currently highlighted mech as the active mech.

Screenshot below.  Note that the mech button on the bottom ribbon is also inactive meaning that no active mech is set.

![image](https://user-images.githubusercontent.com/76007438/103164974-e9c1bf80-47df-11eb-8c2d-f13af2eeffa4.png)

 - OS: Windows 10 Home
 - Browser: Chrome
 - Version 2.2.0c

**Comment by jarena3** [comment]
Active mech is now set when starting a mission in Active Mode (and, soon, when assigning pilots to a mission in GM mode)
