### ISSUE TITLE
[BUG] burn damage eng check & next round

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1151]
<strong>Submitted At: </strong>1/7/2021 0:15:41
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
ending the round with burn damage marked and then failing the engineering check doesn't move on to the next round
<strong>To Reproduce: </strong>
mark any amount of burn
click end round button
fail the engineering check
damage is applied automatically as expected
round doesn't end - actions aren't possible, movement isn't filled back up, etc
<strong>Expected behavior: </strong>
round should end after failing engineering check
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by MyrionPhoenixmoon** [comment]
Burn is currently applied on round end rather than on turn end, which is the wrong timing. It causes the burn check to come up just before a player starts their turn, not giving them a chance to Stabilize it away or similar.

So I don't know if this needs to be reopened or a new Issue made.
