### ISSUE TITLE
Feature Request: Showing the Tokugawa "Overclock" feature

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1157]
<strong>Submitted At: </strong>1/8/2021 19:17:22
<strong>Is your feature request related to a problem? Please describe. </strong>
Happened to notice that when looking at the Tokugawa, the Overclock protocol which I had seen in the rulebook pdf, wasn't there. If other people use the website instead of the rulebook, they might completely miss out on this important feature.
<strong>Describe the solution you'd like: </strong>
I just want it to be there when I look at the frame on the website.
<strong>Additional context: </strong>
The overclock protocol does show up when you enter combat mode, so everything is still perfectly usable.
<strong>Contact: </strong>
Snickering Tortoise#3319

**Comment by jarena3** [comment]
collected in #1207
