### ISSUE TITLE
[BUG] Certain Mechs Un-creatable

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1158]
<strong>Submitted At: </strong>1/8/2021 20:45:44
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When I attempt to make a mech, on the Add New Frame page, I select the Caliban, a random name, and when i hit register new mech, I get an error stating 'this._integrated map is not a function' in a little red pop-up in the bottom right corner
<strong>To Reproduce: </strong>
1. Go to Pilot Page
2. Hit 'Add New Mech'
3. Select the Caliban/Emperor/Enkidu Shock Berserker
4. Enter name or choose random
5. Register New Mech
<strong>Expected behavior: </strong>
I expected not to receive an error, as my character had the licenses to do a Caliban. 
<strong>Additional context: </strong>
I was able to select from mech frames the character does not have the licenses for, all from the wallflowers.lcp or thelongrim.lcp, and from the mechs I tested, i was able to replicate this bug with the Emperor, Enkidu Shock Berserker, 
<strong>Contact Info: </strong>
Bakure #7565
<strong>Stack Trace: </strong>
blank

**Comment by jarena3** [comment]
C/C does not yet model alternate frames
