### ISSUE TITLE
Feature Request: On-Hit Activated Effects Support

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1163]
<strong>Submitted At: </strong>1/10/2021 14:30:42
<strong>Is your feature request related to a problem? Please describe. </strong>
Right now, there is no support for weapons with activated on-hit effects, like the Manticore's Arc Projector.
<strong>Describe the solution you'd like: </strong>
A button of some kind on the attack screen in active mode that lets you trigger a weapons activeated on-hit effect. 
<strong>Additional context: </strong>
The ability to tie spending of Limited charges to this would also be helpful.
<strong>Contact: </strong>

**Comment by jarena3** [comment]
For the time being, this must be manually tracked
