### ISSUE TITLE
[BUG] Combat abilities don't render on Chrome

### ISSUE THREAD

**Issue by doorisajar** [massif-press/compcon#1165]
- Chrome Version 87.0.4280.141 (Official Build) (x86_64)
- MacOS 10.13.6 (this is on an old laptop)

Load any mech on a pilot, AFAICT, and all of the combat abilities don't render correctly. When I load the mech screen, I get the following red error pop-up:

![](https://user-images.githubusercontent.com/3525775/104141824-409dcc00-537e-11eb-8a8f-3635bdede842.png)

**Comment by jarena3** [comment]
Update to the latest version of the LCP
