### ISSUE TITLE
[BUG] Compendium license data unviewable

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1171]
<strong>Submitted At: </strong>1/11/2021 20:22:59
<strong>Platform: </strong>
PWA - Android
<strong>Describe the bug: </strong>
When opening the license section of the compendium, "Error: invalid array length" appears. The remaining space is blank.
<strong>To Reproduce: </strong>
In version 2.2.3, open compendium > licenses. See additional context.
<strong>Expected behavior: </strong>
The licenses appear as normal.
<strong>Additional context: </strong>
I have 3 content packs installed: Long Rim, Field Guide to Suldan, and Wallflower 0.10.0. Wallflower was very recently installed, and thus I suspect it of causing a problem.
<strong>Contact Info: </strong>
Parrotapocalypse#3122
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
This is due to alt frame data in the Wallflower pack that C/C doesn't currently support
