### ISSUE TITLE
[BUG] Terashima Blade Lord's Stance same as Default Stance

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1175]
<strong>Submitted At: </strong>1/12/2021 12:16:41
<strong>Platform: </strong>
Browser - Opera
<strong>Describe the bug: </strong>
Terashima Blade: Lord's Stance profile does not display any changes from default Stance. It is missing all of the Lord's Stance attributes
<strong>To Reproduce: </strong>
Looking at Lord's Stance profile in Terashima Blade when viewing from license in compendium
<strong>Expected behavior: </strong>
Should properly display properties of Lord's Stance
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Blind#8000
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
unable to reproduce
