### ISSUE TITLE
Feature Request: Multi-Type Weapons

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1178]
<strong>Submitted At: </strong>1/13/2021 15:37:42
<strong>Is your feature request related to a problem? Please describe. </strong>
This problem is homebrew-exclusive so it's not very serious. Right now, weapons in Comp/Con can only have a single type (launcher, melee, nexus, etc), and they cannot have types added, removed, or changed by mods or traits.
<strong>Describe the solution you'd like: </strong>
Allow weapons to support multiple types (largely for proper synergy locations and mod application by changing the "type" object from a string to a string[]
<strong>Additional context: </strong>

<strong>Contact: </strong>
hellaspooks#2744

**Comment by jarena3** [comment]
this request would represent too great a change for something that could be done on the synergy/mod side already
