### ISSUE TITLE
[BUG] Getting Errors and Unable to See Liscenses

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1180]
<strong>Submitted At: </strong>1/14/2021 21:04:45
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
I have leveled up my character from LL0 to LL1 and it will not display the licenses that I may choose. Even if I back out of the level up process without choosing one, I cannot choose one in my pilot's tactical profile. I have a homebrew LCP installed that adds new frames to the game, if that affects this.
<strong>To Reproduce: </strong>
Level up a character from LL0 to LL1 and then try to add a mech license. Maybe have a homebrew LCP installed.
<strong>Expected behavior: </strong>
I expected to be able to pick a license level
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Superst2653#1761
<strong>Stack Trace: </strong>

**Comment by Superst2653** [comment]
Original Poster here, would like to add that an Error code reading "Invalid Array Length" pops up every time I try to access a page displaying licenses.

**Comment by jarena3** [comment]
This is due to homebrew licenses not having at least one item. This is typically because of a workaround for alt-frames, whose support is coming shortly and is tracked in https://github.com/massif-press/compcon/issues/1202
