### ISSUE TITLE
[BUG] Lession of the Held Image Reaction Activation Not Appearing in active mode

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1183]
<strong>Submitted At: </strong>1/17/2021 4:16:02
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
"Lesson of the Held image" core bouns does appear but the reaction box that can be seen in Narrative Profile does not show when in active mode so that reaction cannot be triggered or tracked
<strong>To Reproduce: </strong>
create a mech with the core bouns "Lession of the Held Image"
<strong>Expected behavior: </strong>
A "Reaction Action" box should be seen under Lession of the Held Image Core bonus
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Unable to reproduce
