### ISSUE TITLE
[BUG] Players disappear from active mission after returning to it

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1188]
<strong>Submitted At: </strong>1/17/2021 15:20:56
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Players seem to disappear from encounters and missions after returning to them (probably after closing and reopening the google chrome page)
<strong>To Reproduce: </strong>
Put players in a mission and close chrome and reload it, they disappear from the tracking tab
<strong>Expected behavior: </strong>
They should stay on the tracking tab and in the mission
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Eld#7590
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Unable to reproduce
