### ISSUE TITLE
[BUG] Images not showing up 

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1191]
<strong>Submitted At: </strong>1/19/2021 0:38:14
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
I'm on a MacBook Pro and the images in the Frames section don't show up. 
<strong>To Reproduce: </strong>
Any time I got to look at Frame no art is there. 
<strong>Expected behavior: </strong>
To see art
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
@wdm1262
<strong>Stack Trace: </strong>
https://compcon.app/#/compendium/frames

**Comment by jarena3** [comment]
Unable to reproduce
