### ISSUE TITLE
[BUG] Several Actions Miscategorized

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1208]
<strong>Submitted At: </strong>1/19/2021 12:03:10
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
On the Action Economy page of the compendium, Move, Boost, Hide, Search, Prepare, Skill Check, and Overwatch are labelled as Pilot-Only Actions, when they are not.
<strong>To Reproduce: </strong>
1: Go to Compendium from main menu. 2: Go to Action Economy. 3: Scroll down to Pilot-Only Actions to see the miscategorized actions.
<strong>Expected behavior: </strong>
Move, Boost, Hide, Search, Prepare, Skill Check, and Overwatch should be categorized under Mech Actions and not Pilot-Only Actions
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Collected in https://github.com/massif-press/compcon/issues/1197
