### ISSUE TITLE
[BUG] Multi-Profile LCP weapons Not Properly Rendering Effect Boxes In the Compendium

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1219]
<strong>Submitted At: </strong>1/21/2021 23:02:59
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Specifically in the Licences section of the Compendium, the two multi profile Long Rim weapons, the D/D 288 and the Terashima Blade, do not render their effect text boxes properly. However, if you look at the Mech Weapons section, they will show their effect text properly then. Additionally, if you select one of the profiles that should have an equipment effect on the Licenses page, and refresh the page, the equipment effect will render properly upon returning to that weapon, and will default to the profile last picked.
<strong>To Reproduce: </strong>
After installing the Long Rim LCP, go to the Compendium, head to the Licenses section, select either the Atlas or the Zheng, and select the D/D 288 or the Terashima Blade.
<strong>Expected behavior: </strong>
The equipment effect should render upon loading.
<strong>Additional context: </strong>
The two default profiles on the D/D 288 and the Terashima Blade (as well as the Troll Stance) do not have Equipment Effect boxes as all (this appears to be intended as those do not have effects). This seems to, specifically in the Licenses section of the compendium, prevent the Equipment Effect box from being rendered at all, as if one sets a different Profile as "the one last loaded and thus the one to display first when clicking on the weapon" after either refreshing, or returning to the compendium from another page of comp/con, the Equipment effect will show up properly. 

The fact that you can select a different weapon profile in the Weapons section of the compendium, with a proper equipment effect, and then have the weapon render properly in the Licenses section suggests that the problem could possibly be fixed by having all multi-profile weapons have an Equipment Effect box, even on their more "vanilla" profiles, as that would ensure that there would be no "empty" equipment effect box causing it not to render. 

Additionally, this doesn't seem to be a problem with the Drake's Leviathan Cannon, another weapon with multiple profiles. That weapon does have an Equipment Effect box on the default profile, unlike the other two weapons discussed here.

Checking the Active Mode and the Mech Hanger, this does not seem to be a problem there.
<strong>Contact Info: </strong>
lcl#4495
<strong>Stack Trace: </strong>

**Comment by lenaleciel** [comment]
I forgot about the Cannibal on the Caliban, which also uses the same profile system and appears to have the same problem.

**Comment by lenaleciel** [comment]
#1238 and #1228 appear to be related to this.
