### ISSUE TITLE
[BUG] lcp doesn't auto update in batch add

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1222]
<strong>Submitted At: </strong>1/23/2021 15:20:33
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
I added the KTB lcp for the first time and updated my wallflower lcp at the same time. It added the KTB lcp but it didn't update the wallflower lcp - I had to add the wallflower lcp again separately.
<strong>To Reproduce: </strong>
Basically the bug description. Have an old wallflower lcp and no ktb lcp, then add the latest versions of both.
<strong>Expected behavior: </strong>
It should add the ktb lcp and update the wallflower lcp.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Winged#1414
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
There shouldn't be a way to add multiple files in that interface and in testing I found this to be true
