### ISSUE TITLE
[BUG] Overcharge Doesn't Work

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1227]
<strong>Submitted At: </strong>1/24/2021 20:56:15
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
I press Overcharge. It does not add Heat, let me roll for Heat, or give me the ability to select a QA.
<strong>To Reproduce: </strong>
Cleared the Overcharge counter and tried again, same result. Refreshed browser, same result
<strong>Expected behavior: </strong>
Heat used to be added automatically, and if a roll was required to determine Heat, there would be a pop-up to input the die roll
<strong>Additional context: </strong>
Everything else seems fine and is working well! I'm tracking manually at the moment.
<strong>Contact Info: </strong>
Discord: Fidchel#1753
<strong>Stack Trace: </strong>
No error log

**Comment by jarena3** [comment]
Unable to reproduce. I think this got taken care of somewhere along the way.
