### ISSUE TITLE
[BUG] Flex Mount Mount Retrofit

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1232]
<strong>Submitted At: </strong>1/27/2021 1:33:55
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When applying Mount Retrofitting Core Bonus to a Flex Mount and selecting an Auxiliary weapon for the Main Weapon slot of the new Main/Aux mount, an extra Auxiliary slot appears.
<strong>To Reproduce: </strong>
I made a second pilot with 3 Licences in Nelson, took the Mount Retrofitting CB, and stuck it on the Flex Mount, and put an Aux Weapon in the Main slot, and bam! Free Aux slot, for a total of Main (Aux), Aux, Aux.
<strong>Expected behavior: </strong>
To only be able to equip two Aux weapons, rather than three.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
collected in #1035
