### ISSUE TITLE
[BUG] Mines tagged as Deployable

### ISSUE THREAD

**Issue by SirAston** [massif-press/compcon#1236]
**Describe the bug**
What the title says. All mines, with the exception of Caliban's Spike Charges, are tagged as "Deployable" (which they are not according to the Core Book).

**To Reproduce**
1. Enter "Mech Systems" in the Compendium.
2. Open the filter via the Döner menu.
3. Insert "Mine" Tag and "Deployable" System Type.

**Expected behavior**
Mines not being from the "Deployable" System Type.

**Comment by jarena3** [comment]
Mines are **typed** as Deployable (they can be deployed) but **tagged** as Mines (referencing the book rules), the Spike Charges will be updated, and this ticket closed, on the next Long Rim data update
