### ISSUE TITLE
Pilot E-defense says 10 when armor says 8

### ISSUE THREAD

**Issue by Adrian1358** [massif-press/compcon#1239]
When you equip the stealth hardsuit on a pilot, it shows as having 10 E-defense and 8 Evasion at the top banner, when the armor shows 8 E-defense and 8 Evasion

(Th

1. Create a pilot
2. Equip the Stealth hardsuit
3. the top banner which has your pilots health and defenses shows 10 E-defense

 - OS: Windows
 - Browser: Google Chrome
 - Version 2.2.5

**Comment by jarena3** [comment]
Fixed in 2.2.9
