### ISSUE TITLE
Feature Request: Editable Armour

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1249]
<strong>Submitted At: </strong>2/6/2021 23:27:58
<strong>Is your feature request related to a problem? Please describe. </strong>
The White Witch's core system allows it to change its armour mid-combat, but there is no way to track that in comp/cons active move
<strong>Describe the solution you'd like: </strong>
a way to edit armour, similar to overshield
<strong>Additional context: </strong>

<strong>Contact: </strong>
Skelepope#3174

**Comment by jarena3** [comment]
This will be included with WW mechanics on its official release
