### ISSUE TITLE
[BUG] Terashima Blade - lord and wind stances

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1250]
<strong>Submitted At: </strong>2/7/2021 7:53:12
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
Lord and wind stance of the terashima are not complete.
<strong>To Reproduce: </strong>
Go in the compendium and look for the terashima blade
<strong>Expected behavior: </strong>
• Lord’s Stance: You cannot make ranged or
tech attacks, but any ranged attack against
you that misses deflects off your sword, dealing
2 damage (same type as the attack) to a
character of your choice in 􀀮3 and line of sight
from you. Any melee attack that misses you
forces the attacker to pass a HULL save or be
knocked PRONE.
• Wind Stance: (This weapon gains RELIABLE 2,
􀀸2, and KNOCKBACK 2. -- already good) After attacking with this
weapon, hit or miss, you may move 2 spaces in
any direction, ignoring engagement and
reactions.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Collected in #1228
