### ISSUE TITLE
[BUG] Core Power missing

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1259]
<strong>Submitted At: </strong>2/11/2021 7:45:58
<strong>Platform: </strong>
Browser - Safari
<strong>Describe the bug: </strong>
ERROR:   undefined is not an object (evaluating 't.coreSystem.Activation.toLowerCase') 
Core power for Atlas and Sunzi not displaying
<strong>To Reproduce: </strong>
Opening the Atlas or Sunzi frame description
<strong>Expected behavior: </strong>
To be able to see the core powers of all frames
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
User needs to update their long rim version
