### ISSUE TITLE
[BUG] Cannot access pilot roster

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1261]
<strong>Submitted At: </strong>2/11/2021 18:14:43
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
"ERROR:   Cannot read property 'filter' of undefined" on click. 
<strong>To Reproduce: </strong>
Click on Pilot Roster.
<strong>Expected behavior: </strong>
No categories or pilots show, and the error message flashes as usual on the lower left-hand side.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>
N/A

**Comment by Kansattica** [comment]
Seconding this. If I refresh the page, I can get the categories to show up, but trying to open them gives the same message. 
![image](https://user-images.githubusercontent.com/10965841/107716149-9e774980-6c85-11eb-82f5-84b6b9a539ad.png)
