### ISSUE TITLE
[BUG] Unable to delete characters or user data

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1278]
<strong>Submitted At: </strong>2/15/2021 17:13:58
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
I am unable to delete characters from the Pilot Roster and I am also unable to clear my user data.
<strong>To Reproduce: </strong>
From the Pilot Roster I select the pilot I wish to delete and select 'Delete PIlot', then confirm. The pilot is not deleted. I also attempted to clear my user data by selecting 'Options' from the main Comp/Con screen and then selecting 'Delete All User Data' and confirming. My data is not deleted. I even attempted to load a prior data backup with no success.
<strong>Expected behavior: </strong>
I should be able to delete individual pilots or clear my user data.
<strong>Additional context: </strong>
This has occured after the most recent update. I also attempted the same actions on my Android device's Chrome browser and was met with the same results.
<strong>Contact Info: </strong>
Discord user: ZombieMike#0864
<strong>Stack Trace: </strong>
No Error Log Present

**Comment by jarena3** [comment]
hotfixed in 2.2.9a
