### ISSUE TITLE
[BUG] Barrage Vlad Combat Drill error

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1294]
<strong>Submitted At: </strong>2/26/2021 5:28:02
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
No data after selecting superheavy Combat Drill to Barrage with
Error: Cannot read property 'init' of undefined
<strong>To Reproduce: </strong>
Barrage with Combat Drill as first action of second combat turn
<strong>Expected behavior: </strong>
Able to attack with superheavy combat drill
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Unable to reproduce
