### ISSUE TITLE
[BUG] Null or empty snowflake error while trying to reset password

### ISSUE THREAD

**Issue by quasarinfinity** [massif-press/compcon#1296]
**Describe the bug**
When I attempt to reset my password I get the following error:
ERROR:   Unable to change password: PostConfirmation failed with error Null or empty snowflake.

**To Reproduce**
1. Go to 'the compcon login'
2. Click on 'reset password'
3. type in the verification code sent to me, as well as a new password

**Expected behavior**
That my password would change

**Screenshots**

**Desktop (please complete the following information):**
I tried this on my desktop and on my tablet
 - OS: Windows 10
 - Browser Firefox
 - Version 86.00 64bit

**Smartphone (please complete the following information):**
 - Device: Kindle Fire
 - OS: Fire OS
 - Browser Silk
 - Version Unknown
 - 
**Additional context**

**Comment by jarena3** [comment]
@quasarinfinity are you able to log in normally, and, are you a subscriber to the comp/con patreon?

**Comment by quasarinfinity** [comment]
I am not able to log on normally because I have unfortunately forgotten my
password. I've created another account under a different email. Both are
linked to my patreon account. The username of my patreon account is
QuasarInfinity.

-Ian

**Comment by jarena3** [comment]
@quasarinfinity ok, it looks like I will need to manually edit your user data on my side. I'll close this ticket, but could you please message me on patreon with the e-mail you are using?

**Comment by quasarinfinity** [comment]
Sorry, I missed this email somehow.


How do I message you on Patreon? Just message the comp/con account?

Thanks,
Ian

**Comment by jarena3** [comment]
yes please, thank you!
