### ISSUE TITLE
[BUG] Profile crashes Pilot Roster

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1298]
<strong>Submitted At: </strong>3/4/2021 15:18:07
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Importing pilot profile aecf728968cee4302d2ea16fd342f25a from cloud will crash Pilot Roster page.
<strong>To Reproduce: </strong>
Import profile aecf728968cee4302d2ea16fd342f25a. Then open pilot page.
"ERROR:   t.profile.GetView is not a function" will appear and no profiles will be loaded, and the screen will remain blank.
<strong>Expected behavior: </strong>
Pilot profiles will load.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
zchen27#0804
<strong>Stack Trace: </strong>
None

**Comment by DanteTheGallent** [comment]
The same thing is happening with me. Idk what's happening
