### ISSUE TITLE
[BUG] Suldan

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1299]
<strong>Submitted At: </strong>3/4/2021 21:13:17
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
It says in the Lcp dictionary that it's out of date (1.0.4) but I have the 2.1.8
<strong>To Reproduce: </strong>
just check the dictionary I suppose.
<strong>Expected behavior: </strong>
I tried downloading the file again, but it still stuck on 1.0.4, I just want the warning sign to become a check
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
@Sad in pilot net
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
corrected remote manifest
