### ISSUE TITLE
[BUG] Pilot License Level Up Bug

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1306]
<strong>Submitted At: </strong>3/10/2021 21:52:24
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When levelling up to LL3 in IPS-N I am supposed to get a core bonus, but COMP/CON isn't letting me add one, saying that I'm ineligible, but all other LL3 players are able to get their core bonuses. 
<strong>To Reproduce: </strong>
I tried to level down to 2 and then back to 3 manually to try and fix the issue, but it's still not working.
<strong>Expected behavior: </strong>
I expected to have a core bonus for a company, after having three license levels in it.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
WonderWoman#4671
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Unable to reproduce
