### ISSUE TITLE
Feature Request: Autocomplete proof the login

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1307]
<strong>Submitted At: </strong>3/11/2021 5:41:03
<strong>Is your feature request related to a problem? Please describe. </strong>
When you sign in often the program that autofill your email/password lets a space after your email. When that's the case there is a big warning and nothing works so you have to manually remove it (it's also not clear what's the problem the first time you encounter it)
<strong>Describe the solution you'd like: </strong>
Make it so the email section ignores any space characters in it
<strong>Additional context: </strong>
https://i.imgur.com/tR5XZ6Y.png
<strong>Contact: </strong>

**Comment by jarena3** [comment]
added a string trimmer to this input
