### ISSUE TITLE
Feature Request: Ability To Edit Names And Callsign After Character Creation

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1308]
<strong>Submitted At: </strong>3/11/2021 15:06:29
<strong>Is your feature request related to a problem? Please describe. </strong>
I'm always annoyed when i try and duplicate a character and it doesn't let me edit the name, i'd like to keep the same stats and edit the name instead of having to remake the entire character
<strong>Describe the solution you'd like: </strong>
add an option to rename the characters name, biography, callsign etc. after creation, so people don't have to remake the entire character
<strong>Additional context: </strong>

<strong>Contact: </strong>

**Comment by jarena3** [comment]
this exists (click the pencil icon in the dossier)
