### ISSUE TITLE
[BUG] anti-armor signature weapon stats wonky

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1311]
<strong>Submitted At: </strong>3/12/2021 17:21:37
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
The comp/con version of the pilot weapon has threat 1 and 1 kinetic damage with limited 1 and reliable 1. The book says it has 15 range, deals 5 energy kinetic or explosive damage, is limited 2 and reliable 2.
<strong>To Reproduce: </strong>
Opening the pilot gear loadout and adding the anti-armor signature weapon.
<strong>Expected behavior: </strong>
Expecting the stats to line up.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
corrected in Wallflower LCP
