### ISSUE TITLE
Feature Request: Functionality of listed GitHub bonus IDs

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1314]
<strong>Submitted At: </strong>3/13/2021 21:36:37
<strong>Is your feature request related to a problem? Please describe. </strong>
I am frustrated when the list of available IDs in the GitHub and other terms aren't actually supported in Comp/Con, especially when coding LCPs
<strong>Describe the solution you'd like: </strong>
I would like the list of IDs for Bonuses to be put into Comp/Con properly so they can be used for homebrew coding and for consistency's sake. If there are any other pieces of inert code in the GitHub, I'd like those made real as well, but the Bonuses are a priority.
<strong>Additional context: </strong>

<strong>Contact: </strong>
ActualWizard#1010

**Comment by jarena3** [comment]
removed nonworking IDs
