### ISSUE TITLE
[BUG] UI Breaks upon opening "Set Pilot Licenses"

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1319]
<strong>Submitted At: </strong>3/15/2021 0:46:19
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When I load the "Field Guide to Suldan" LCP - the UI becomes incredibly buggy and broken when I open the "Set Pilot Licenses" menu. Multiple mech frames become completely unclickable as their UI is shunted underneath other mech frame buttons. 
<strong>To Reproduce: </strong>
Install the "Field Guide to Suldan" LCP by following the link provided in the LCP Directory. Make a Pilot. Navigate to "Set Pilot Licenses". The UI is broken.
<strong>Expected behavior: </strong>
The UI should not have certain frames overlapping/issues with accessibility for certain frames. It is not in a usable state.
<strong>Additional context: </strong>
I have tried multiple times reinstalling the LCP. I check for updates each time. I have cleared my User Data multiple times. I have tried opening comp/con and doing all these steps multiple times on 3 different browsers (Firefox, Chrome, Edge) - all giving very much the same results. I have cleared my caches and done a clean install of all 3 browsers - same result each time. This issue is apparently not recreated when I send other people my .compcon backup. I am completely out of ideas on what could be the issue on my end after trying on 3 different browsers and failing each and every time to have it load correctly.
<strong>Contact Info: </strong>
JuliaTheGiantRat#3985
<strong>Stack Trace: </strong>
No error log is shown.

**Comment by jarena3** [comment]
Unable to reproduce
