### ISSUE TITLE
[BUG] Jolly Roger missing text

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1320]
<strong>Submitted At: </strong>3/15/2021 10:59:58
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
In the text writeup of the IPS-N Kidd's core Jolly Roger system, it does not list the second effect. The effect is present in the Active Mode modules within the writeup, but not the text itself.
<strong>To Reproduce: </strong>
Opened the Kidd frame in the Compendium.
<strong>Expected behavior: </strong>
Full trait writeup without gaps.
<strong>Additional context: </strong>
I noticed this system also had some similar typos in the released PDF so it may stem from that.
<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Wallflower LCP updated
