### ISSUE TITLE
[BUG] t.tag.GetName is not a function

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1323]
<strong>Submitted At: </strong>3/16/2021 10:19:40
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
t.tag.GetName is not a function appears as an error when rapid print cannons is mounted onto any mount of any mech. The message pops up twice and requires dismissing twice. 
<strong>To Reproduce: </strong>
Requires Rank 1 of Magarac to attain rapid print cannons, then mount it onto any active mech and start active mode
<strong>Expected behavior: </strong>
t.tagGetName should not appear
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
this looks like a problem with a custom tag in a homebrew LCP
