### ISSUE TITLE
Wallflower Exotic weapons missing

### ISSUE THREAD

**Issue by Greychapel** [massif-press/compcon#1325]
**Describe the bug**
In the Wallflower lcp file, Exotic weapons are missing the required `"source": "EXOTIC"` field, preventing them from showing up in the compendium.

**To Reproduce**
Open "Mech Weapons" in compendium.

**Expected behavior**
Exotic weapons should (presumably) be listed similarly to how Exotic systems are when viewing "Mech Systems" in the compendium.

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox 86.0.1

**Comment by jarena3** [comment]
Corrected in 2.2.13
