### ISSUE TITLE
Mod tooltip is "undefined" in License Browser

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#133]
<strong>Submitted At: </strong>5/1/2019 18:07:53
<strong>Platform: </strong>Windows portable/standalone
<strong>Severity: </strong>High (problem that impairs software function, bad or missing game mechanic implementation)
<strong>Issue Description: </strong>UNCLE-Class NHP not visible under the systems tab.
<strong>Reproduction Steps: </strong>Create a pilot, acquire Rank III (Raleigh), make a mech, check systems, RALEIGH III system not visible. When hovering over the UNCLE-class NHP in the Raleigh's rank profile, there's a field registered as undefined.

Using v1.2.8.

**Comment by aritsune** [comment]
UNCLE is a mod in the latest version of the core rulebook and it's been updated in COMP/CON too reflect that. You can add it to a weapon by clicking on the wrench next to that weapon. You should be able to remove the old version from your systems normally.

**Comment by aritsune** [comment]
It's a mod now, as per the rulebook. You add it to a weapon with the wrench button. Mods showing up as undefined in the rank profile is definitely a bug though.
