### ISSUE TITLE
[BUG] Mount Retrofitting grants extra Aux mount

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1356]
<strong>Submitted At: </strong>3/27/2021 1:51:10
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Taking GMS Core Bonus "Mount Retrofitting" and using it on a flex mount grants a Main/Aux mount that can mount either one main and one auxiliary weapon, or three aux weapons.
<strong>To Reproduce: </strong>
Level a character up to LL3. Pick DMS core bonus "Mount Retrofitting". Select a mech with a Flex mount. Click the button in the top right of the mounting that says "Core Bonus Available" and select "Install Mount Retrofitting". Install an Auxiliary weapon in the main slot. You will see two additional slots for Auxiliary weapons. 
<strong>Expected behavior: </strong>
From page 32 of Lancer CRB: "Main/aux mounts can take one MAIN weapon and one AUXILIARY weapon, or two AUXILIARY weapons."
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
WarrenPeace (Shortspark)#4190
<strong>Stack Trace: </strong>
n/a

**Comment by jarena3** [comment]
collected in #1035
