### ISSUE TITLE
[BUG] Search Bar on NPC Features in Compendium locks up comp con

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1374]
<strong>Submitted At: </strong>4/7/2021 21:30:27
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When trying to use the search bar in the Compendium specifically for NPC features, putting in anything results in the entire app becoming unresponsive. Only way to resolve this is by reloading the page
<strong>To Reproduce: </strong>
Open CompCon. Click on Compendium. Click on NPC Features. Click on the Search Bar. Type "Turret".
<strong>Expected behavior: </strong>
Pressing any button on the screen will no longer navigate anything. hitting Forward or Backward in browser will not do anything so long as it's still navigating to somewhere in Comp Con
<strong>Additional context: </strong>
the search bar also won't narrow down any of the options
<strong>Contact Info: </strong>
enkufka#9874 on Discord
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
collected in #1375
