### ISSUE TITLE
[FEATURE] More basic Talent view option in Tactical Profile

### ISSUE THREAD

**Issue by DataNinjaZero** [massif-press/compcon#1388]
**Is your feature request related to a problem? Please describe.**
It's very hard for me to look over quickly at what talents my players have just by looking at their sheet in Tactical Mode. Instead of a few helpful boxes, I now have to either:
- have icons that I can't remember what they represent, followed by having to mouseover to view actual text
- switch to a format that has the icons, then having to hover each talent individually
- switch to a format where basically each individual talent takes up the entire screen, and talents they _have not_ taken are there but greyed out. There's also all the fluff in this format, which takes up more room
In all cases, it's virtually impossible to just see all of what they can do at once.

**Describe the solution you'd like**
The ability to once more see the talents displayed like they were prior - in a double column of boxes, where there's no need to hover over or click on things, nor have extraneous talent ranks displayed.

**Describe alternatives you've considered**
Any format that gives the clear ability to see the rules text of each selected Talent rank without having to individually select them or scroll through each of them would be much appreciated

**Additional context**
Many talents are simply impossible to view in the default mode:
![Screenshot (44)](https://user-images.githubusercontent.com/81269546/115156726-8e3f6a00-a03a-11eb-974d-0a7a5b2ef7bd.png)

**Comment by jarena3** [comment]
Added a toggleable option (on by default in the pilot talent block) to hide locked talents and terse/fluff text
