### ISSUE TITLE
[BUG] Problem 400 stops me from uploading pics

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1396]
<strong>Submitted At: </strong>4/20/2021 13:44:25
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
whenever uploading image for mechs, i get error message 400
<strong>To Reproduce: </strong>
change mech image
<strong>Expected behavior: </strong>
i expect my image to be changed
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by coop9828** [comment]
*same
