### ISSUE TITLE
[BUG] Critical Hits Handled Wrong / Overkill Messes With Crits

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1404]
<strong>Submitted At: </strong>4/26/2021 9:38:46
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
Critical hits seem to roll two dice and pick the higher for each dice in the attack, rather than rolling all dice and picking the higher (2d6 is 2d6kh1+2d6kh1 instead of 4d6kh2). In addition, looks like Overkill overrides selecting the higher dice in favor of rerolling.
<strong>To Reproduce: </strong>
Roll a critical hit with/without an Overkill weapon to reproduce.
<strong>Expected behavior: </strong>
Should roll twice the dice and keep the higher, and Overkill should just add rerolls to the pool rather than selecting them as a 'high' roll.
<strong>Additional context: </strong>
Sent you an image on Discord.
<strong>Contact Info: </strong>
Arcran#2718
<strong>Stack Trace: </strong>

**Comment by TranslucentSabre** [comment]
I would like to look at this one, if that is ok.

**Comment by TranslucentSabre** [comment]
I've looked at the dice rolling code. COMP/CON is actually being more generous than it should and is not giving overkill heat in all cases. Let me see what I can do.
