### ISSUE TITLE
[BUG] Missing tag

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1408]
<strong>Submitted At: </strong>4/28/2021 13:24:07
<strong>Platform: </strong>
opera browser
<strong>Describe the bug: </strong>
missing tag on the reaction "SYMPATHETIC PRECOGNITION" from Empath talent
<strong>To Reproduce: </strong>
open talents, look at 1st level
<strong>Expected behavior: </strong>
"1/scene" tag
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by lenaleciel** [comment]
Similar to this situation, other talents that grant reactions such as Exemplar 1 and Bonded 2 with pdf listed limitations such as 1/round don't have the limitation listed as a tag or otherwise when viewed in any page on comp/con.
