### ISSUE TITLE
Feature Request: Calculating damage output for groups of pilots

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1414]
<strong>Submitted At: </strong>4/30/2021 15:06:01
<strong>Is your feature request related to a problem? Please describe. </strong>
Nope
<strong>Describe the solution you'd like: </strong>
As a GM, I am trying to properly scale an encounter based on the average damage output they can give per round. 

In this scenario, there will be no opposing NPCs, so the PR for the mission won't apply. 

I am currently using the following tool to get these results, but being able to see this for my group as a whole would be very beneficial. 

https://dice.clockworkmod.com/

In addition to raw damage output, it would be nice to be able to calculate their damage output adjusted by range, or accuracy and difficulty as well. 
<strong>Additional context: </strong>
My specific scenario is as follows: 

The PCs are defending a spaceship as it flies through an asteroid field. They need to destroy asteroids before they collide with the ship. Each round, more asteroids are added, and the existing asteroids move towards the ship. The ship can take a certain amount of damage, so they won't fail if they don't get each asteroid, but too many will severely damage the ship and fail the mission.  

As a GM, I want to calculate how many HP worth of asteroids I can throw at my players. 
But I need to find the right balance between unfairly overwhelming them, and too easy and boring.

My existing process is to look at the low average of the player's damage output for weapons with a range of 6 or higher, and to only add as many asteroids as equals that total damage output. 
<strong>Contact: </strong>
Fishdinner#9551

**Comment by jarena3** [comment]
Out of scope
