### ISSUE TITLE
Feature Request: Core Power Tag Readjustment

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1422]
<strong>Submitted At: </strong>5/8/2021 19:26:35
<strong>Is your feature request related to a problem? Please describe. </strong>
The Core Active of each mech has a tag next to the action required to activate them such as "Encounter," "Mission," or "Next Turn," with the Encounter tag being for Core Actives that last for the rest of the Scene/Encounter, with the Next Turn tag being for Core Actives that last until your next turn, and the Mission tag being for Core Actives that happen just once and then stop. This isn't taken from the PDF, being a Comp/Con original label for ease of use, and the Mission tag in particular is somewhat misleading, as based on the other two tags, it implies that the effects of the Core Active would last the rest of the Mission, which isn't true. Additionally, all of the Long Rim mechs have Core Actives tagged with "Mission" even if their effects are more aptly described as "Encounter."
<strong>Describe the solution you'd like: </strong>
The "Mission" tag should be renamed to something to make it more clear that things like the Monarch's Divine Punishment or the Blackbeard's Omni-Harpoon only happen once when you spend the Core Power, to better be in line with the other two tags. Additionally, all of the Long Rim mechs except for the Kobold should have their tags changed from "Mission" to "Encounter" as they all have effects that last until the end of the scene. 
<strong>Additional context: </strong>

<strong>Contact: </strong>

**Comment by lenaleciel** [comment]
This issue was never resolved in the License view or the Mech Frame view in the compendium or when looking at mechs in the Mech Hanger, and persists to the current version, despite being closed. Should I repost this issue or is commenting sufficient to get new eyes on it?
