### ISSUE TITLE
[BUG] Autoloader Drone not reloading

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1425]
<strong>Submitted At: </strong>5/9/2021 22:34:25
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
After deploying autoloader drone, there is no quick action option to allow to reload.
<strong>To Reproduce: </strong>
Deploy Autoloader drone, open quick action menu
<strong>Expected behavior: </strong>
Autoloader drone reload quick action appears on quick action menu after deploying it
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
The target player gets to reload as a quick action, not the drone
