### ISSUE TITLE
[BUG] Snicker Snack

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1442]
<strong>Submitted At: </strong>5/28/2021 21:12:06
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When taking a vorpal gun, CompCon gives you the ability to use the SnickerSnack reaction twice in one round 
<strong>To Reproduce: </strong>
Take Vorpal Gun on any mech main, flex or main/aux mount
<strong>Expected behavior: </strong>
Only one instance of Snicker Snack would be given per round, I'd imagine
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by NordicNinja** [comment]
Verifying currently a Gorgon with 2 Vorpals has 4 Snicker Snacks.

![image](https://user-images.githubusercontent.com/85514107/121066355-a3a15c80-c77e-11eb-8e03-0a94a0ec3e3b.png)
