### ISSUE TITLE
[BUG] GMS Systems don't display desc in search results

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1469]
<strong>Submitted At: </strong> 6/7/2021 13:12:57<br><br><strong>Browser: </strong> Chrome & Firefox confirmed<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Search Compendium for a GMS system, they display but not their 3-line description<br><br><strong>Reproduction Steps:<br> </strong> Open Compendium, search for 'a', compare GMS systems to license systems<br><br><strong>Expected Result:<br> </strong> They would show the first three lines worth of the item description on the results page<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by NordicNinja** [comment]
![image](https://user-images.githubusercontent.com/85514107/121068620-5bd00480-c781-11eb-9328-35942e73f82b.png)
