### ISSUE TITLE
[BUG] Data not syncing to cloud

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1470]
<strong>Submitted At: </strong> 6/8/2021 4:44:25<br><br><strong>Browser: </strong> One PC using Edge, the other Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Content added to the encounter toolkit (NPCs, Encounters) created on one computer don't show up on another after syncing with cloud.<br><br><strong>Reproduction Steps:<br> </strong> I logged into comp/con on a different computer today (using Edge) and prepared some encounters for an upcoming session. All my existing content was there and everything worked fine. I did a manual syn before closing it down, which was reported as having been successful. When I got to my own laptop and logged into comp/con (using Chrome) it continued to show the previous state without the extra NPCs and encounters I added earlier.<br><br><strong>Expected Result:<br> </strong> The content added on another PC gets synced.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by humburg** [comment]
It seems to be working fine now. Looks like the latest update fixed it.
