### ISSUE TITLE
[BUG] Sagarmatha's frame traits typos

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1487]
<strong>Submitted At: </strong> 6/15/2021 11:37:33<br><br><strong>Source: </strong> The Long Rim<br><br><strong>Incorrect Text/Data: </strong><br> Sagarmatha's Traits all have "Sagarmartha" with an extra r.<br><br><strong>Correct Text/Data: </strong><br> Sagarmatha<br>

**Comment by NordicNinja** [comment]
![image](https://user-images.githubusercontent.com/85514107/122091197-69a70a80-cdbd-11eb-994c-72c880728e6d.png)
