### ISSUE TITLE
[BUG] Pilot Weapon/Gear has no equip option in list mode

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1495]
<strong>Submitted At: </strong>6/21/2021 12:54:05
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When in the Pilot's narrative profile tab, trying to add a Pilot Weapon or Gear can't be done 
 in list mode/view (middle option of 3). Instead, there is a detail column with an info symbol button in each row.
<strong>To Reproduce: </strong>
Create a new pilot, or edit an existing pilot. Enter Narrative Profile tab, and attempt to add or modify a Pilot Weapon or Gear, and choose the list view (middle option of 3)
<strong>Expected behavior: </strong>
There should be an "+ equip" button instead of an info symbol button, and it should equip the item and return to the Narrative Profile tab
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
geoffreypi#9524
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
this error occurs in the mobile view only
