### ISSUE TITLE
[FEATURE] Show source of items in CompCon

### ISSUE THREAD

**Issue by lambdaknight** [massif-press/compcon#1502]
**Is your feature request related to a problem? Please describe.**
When building characters in mechs in CompCon, I am unsure which LCP things come from.

**Describe the solution you'd like**
Some way to determine which LCP items in CompCon come from. Ideally, it would be universal, appearing in the compendium as well as the character builder.

**Comment by TranslucentSabre** [comment]
What is the scope of this?
I have a commit that adds this information for Player mech frames, weapons, and systems. Those CompendiumItems were already storing the LCP name for filtering. Right now it does not look like we are storing the LCP name for anything on the NPC side or talents.
