### ISSUE TITLE
[BUG] Can't set Custom Description for NPC systems

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1506]
<strong>Submitted At: </strong> 7/2/2021 0:53:16<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When setting a custom description for an NPC system, the custom description doesn't show up. Trying to edit the custom description of previously created NPCs causes no change either.<br><br><strong>Reproduction Steps:<br> </strong> Select an NPC from the NPC roster, click on the cog next to a system or weapon, and hit "Set Custom Description"<br><br><strong>Expected Result:<br> </strong> The text for the custom description should show up on the system.<br><br><strong>Additional Context:<br> </strong> If a custom description is set and "Set Custom Description" is clicked again, the description shows up in the text box as faded text, but still isn't visible/edited on the NPC system<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by jarena3** [comment]
Collapsing into #1505
