### ISSUE TITLE
[BUG] Shock Wreathe' is misspelled as 'Wreath'

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1507]
<strong>Submitted At: </strong> 7/2/2021 9:37:53<br><br><strong>Source: </strong> LANCER Core Book<br><br><strong>Incorrect Text/Data: </strong><br> SHOCK WREATH<br><br><strong>Correct Text/Data: </strong><br> SHOCK WREATHE<br>

**Comment by lenaleciel** [comment]
Shock Wreath (Without an E at the end) is spelled that way in the latest pdfs. Wreathe with an e is a verb, while wreath without an e is a noun.
Notably, it was intentionally changed to Wreath in editing as noted here: https://github.com/AshleyMoni/Lancer-Community-Edition/issues/711

This also means that the flavor text should probably be edited in both the pdf and the lcp, as it uses "wreathes" as opposed to "wreaths", and the Zheng has an issue with the Molten Wreath(e) as well, though the Zheng has an e in both the pdf and the current comp/con lcp. I'm aware though that this isn't exactly the place for requesting pdf errata, this is mostly just for context.
