### ISSUE TITLE
[BUG] a possible typo

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1517]
<strong>Submitted At: </strong> 7/6/2021 18:54:02<br><br><strong>Source: </strong> LANCER Core Book<br><br><strong>Incorrect Text/Data: </strong><br> "Probability results are then fed to the Swallowtail’s choir processors"
<br><br><strong>Correct Text/Data: </strong><br> "Probability results are then fed to the Swallowtail’s core processors"
<br>

**Comment by lenaleciel** [comment]
Probably not a typo: Other Swallowtail fluff refers to "a suite of predictive choral intelligences" and the concept of "choirs" or "choruses" shows up in other prediction related Lancer technobabble.

**Comment by jarena3** [comment]
@lenaleciel is correct
