### ISSUE TITLE
[FEATURE] Extra Core Bonus Ignore Licenses

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1523]
**Is your feature request related to a problem? Please describe.**
The Extra Core Bonus reserve still enforces required licenses for non-GMS core bonuses, which is somewhat non-intuitive.

**Describe the solution you'd like**
The bonus CB point should be spendable on any CB regardless of license count.

**Describe alternatives you've considered**
Leave things as they are. Requires workarounds to actually add a bonus CB that a pilot's licenses don't qualify them for, namely adding extra license reserves.

**Comment by Eranziel** [comment]
I made this one, should be a feature request. Oops!
