### ISSUE TITLE
[BUG] The large coloured Manufacturer logo does not load for homebrew content.

### ISSUE THREAD

**Issue by LordFluffyIII** [massif-press/compcon#1535]
**Describe the bug**
The large coloured Manufacturer logo does not load for homebrew content, instead tripping a Security Error.

**To Reproduce**
1. Install a content pack with a custom manufacturer (e.g. Suldan or Grimm and Sons)
2. Navigate to the Compendium\Manufacturers screen
3. Open the custom manufacturer 
4. The larger logo fails to load. 

**Expected behavior**
A large image of the manufacturer's logo should appear on the right of the screen.

**Screenshots**
![LogoBug](https://user-images.githubusercontent.com/87622766/126085158-634dfc76-7fbb-4250-8db4-4ba0fca29adc.JPG)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox
 - Version 90.0

**Additional context**
This was also replicated using chrome, giving the possibly more helpful error message:
"Unsafe attempt to load URL https://compcon-image-assets.s3.amazonaws.com/icons/gs.svg from frame with URL https://compcon.app/#/compendium/manufacturers. Domains, protocols and ports must match."

**Comment by msprijatelj** [comment]
Found a potential package to handle this external SVG issue: https://github.com/jonathantneal/svg4everybody

That said, the logo SVGs are clearly loading elsewhere, so I'm wondering what's different between the big logos and the small ones if they're referencing the same image URL.  Digging deeper.

**Comment by msprijatelj** [comment]
Mucked around a bit with `svg4everybody` and couldn't get it to work with Vue.  Exploring other options now.

**Comment by msprijatelj** [comment]
Trying to get a handle around [external-svg-loader](https://www.npmjs.com/package/external-svg-loader) for this but still not having much luck.  If anyone else is finding success to this, let me know!

**Comment by msprijatelj** [comment]
Last update for tonight: Finally got `external-svg-loader` to behave as expected... and ran straight into a CORS wall.  Using Chrome with Grimm & Sons installed:
```
Access to fetch at 'https://compcon-image-assets.s3.amazonaws.com/icons/gs.svg#Content' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
CORS is one of my weak points in web development, so any advice would be appreciated.

**Comment by msprijatelj** [comment]
After spending a very long time learning about `fetch` and `XHR` and `CORS`, I think I can safely say that this issue lies with the content creators and not with COMP/CON.  If the SVG image doesn't permit cross-origin access, compcon.app can't retrieve it.

**Comment by msprijatelj** [comment]
@jarena3 Hypothetically, if an SVG were to be included in an LCP file, would COMP/CON be able to cache that file upon LCP installation, and then refer to it later? Would we *want* content creators to include SVG files within their LCPs, or would that potentially slow COMP/CON down too much?

**Comment by jarena3** [comment]
@msprijatelj I'd like to avoid people adding more and denser data to LCPs, so I'm good with CORS concerns on the creators' side. I think a good future move on my part would be to add a formal method to submit LCP images to a C/C S3 bucket
