### ISSUE TITLE
[BUG] User Data does not reload on LCP Enable/Disable

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1540]
<strong>Submitted At: </strong>7/21/2021 8:44:16
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
User Data does not automatically update when an installed LCP is disabled or enabled, which can cause user data to still be visible after disabling and user data to be overwritten by recent changes when enabling.
<strong>To Reproduce: </strong>
Steps are dealing with NPC LCP, but similar behavior may occur for other LCPs (e.g. Pilots, Frames, etc.). Behavior is identical both while logged out (Local) and logged into Cloud Account:
0. Have Core NPC LCP enabled, NPCs in NPC Roster
1. Disable Core NPC LCP.  Immediately check NPC Roster; NPC Roster is still populated, but new NPC creation/import is disabled.
2. Refresh CompCon. Check NPC Roster: NPC Roster is empty, new NPC creation/import still disabled.
3. Enable Core NPC LCP. *Do NOT refresh CompCon*
4. Create new NPC on NPC Roster.
5. Refresh CompCon.  Check NPC Roster: Only the new NPC shows up; all previous NPCs are missing.
<strong>Expected behavior: </strong>
User data reloads immediately upon disabling or enabling an installed LCP to reflect the removal or addition of available LCP data (e.g. NPC roster is emptied immediately without user's manual refresh upon NPC LCP disable, and repopulated from cache immediately upon NPC LCP enable).
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Valkyrion#6196
<strong>Stack Trace: </strong>

**Comment by msprijatelj** [comment]
Additional information: This same behavior occurs when deleting/reuploading an LCP to COMP/CON, in addition to when the LCP is toggled ON or OFF.  Data reload may need implementation for both of these cases.

**Comment by msprijatelj** [comment]
In the case of disabling/re-enabling NPC LCPs, it may be prudent to "disable" or "grey out" any NPCs that have a class from a disabled LCP (assuming we don't shift paradigms with the GM Toolkit Overhaul).  It's only a thought; it may be better to just reload the NPCs on an LCP change data and let it be.

**Comment by msprijatelj** [comment]
@jarena3 This issue may be closed by the cloud save/content manager changes you're currently working on.

**Comment by jarena3** [comment]
Yep, the loading and startup procedure have been modified to ensure this happens, and it seems to be working. Closing this.
