### ISSUE TITLE
[BUG] Siege Cannon still has "loading" in direct fire.

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1565]
<strong>Submitted At: </strong> 7/29/2021 23:11:14<br><br><strong>Issue: </strong><br> The core rules describe the Siege Cannon as having the "loading" tag while in siege mode only. COMP/CON is displaying it as also having the "loading" tag in direct fire mode.<br><br><strong>Massif Reference: </strong> Lancer Core Rules, page 229.<br>

**Comment by msprijatelj** [comment]
This appears to be an issue in the [lancer-data weapons file](https://github.com/massif-press/lancer-data/blob/master/lib/weapons.json), and should probably be moved to that repo.  I'll make a PR there to address the issue.

**Comment by msprijatelj** [comment]
Created  [lancer-data PR #154](https://github.com/massif-press/lancer-data/pull/154) to fix this issue.
