### ISSUE TITLE
[FEATURE] Equipment and trigger options for Human NPCs

### ISSUE THREAD

**Issue by zamarren** [massif-press/compcon#1572]
**Is your feature request related to a problem? Please describe.**
Just like with Pilots, it would be nice if I could pick equipment and triggers for my Human NPCs. I can currently write this info in the notes, but it is time-consuming to do this for all of your Human baddies.

**Describe the solution you'd like**
Having the same item and trigger selection menus for NPCs as we do for pilots (or some version of it) would be a time saver.

**Comment by jarena3** [comment]
Human NPCs as NPCs and Human NPCs as characters are both getting updates in the GM overhaul, but they won't be getting Pilot Equipment or Triggers
