### ISSUE TITLE
[BUG] Orochi drones bug

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1577]
<strong>Submitted At: </strong> 7/31/2021 16:00:41<br><br><strong>Browser: </strong> Edge, Opera and Safari<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When deploying an orochi drone in active mode, they can't be used anymore in future encounters or missions, the button stays grayed out<br><br><strong>Reproduction Steps:<br> </strong> -Enter combat mode with a hydra
-Click any of the orochi drones
-End combat
-End encounter
-The next encounter, the selected drone will still be grayed out and unavailable<br><br><strong>Expected Result:<br> </strong> The orochi drone should be available to use again after a rest or a full repair<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by jarena3** [comment]
fixed in 2.2.28
