### ISSUE TITLE
Feature Request: Consistent Dialogue Boxes

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#158]
<strong>Submitted At: </strong>5/9/2019 18:12:56
<strong>Feature: </strong>Consistent Dialogue Boxes
<strong>Details: </strong>When you change your name/callsign/mech config name, you can click the shadowed areas outside of it, and it'll close automatically. However, when you do this for the frame summary and a new mech entry, clicking outside causes the box to pulsate instead of close itself.

This is totally not a high-priority thing, but having it be consistent at least between these similarly acting things would make things feel better I would think.
<strong>Contact: </strong>

**Comment by Isoptera** [comment]
This ticket is pretty closely related to #267.
