### ISSUE TITLE
[BUG] Repair Cap Doesn't Scale With Max

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1586]
<strong>Submitted At: </strong>8/3/2021 10:10:17
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When repair cap increases (e.g. Hull bonuses) current repairs available remain the same.
<strong>To Reproduce: </strong>
1. Create/Edit a pilot so that they have at least 2 points in Hull (or 2 more points than before)
2. Create a new frame/check an existing frame
3. See that Max Repair Cap has increased, but available repairs have remained the same

<strong>Expected behavior: </strong>
Increasing the Repair Cap by an amount should increase available repairs by the same amount.
<strong>Additional context: </strong>
See #1569 for how a similar issue was resolved for Current HP vs. Max HP.  Arguably, similar "missing [statistic]" approaches should be applied to other fields, like Structure and Stress. Though they may be edge cases (max structure/stress are rarely touched), they might crop up in the future, and this would nip any such issues in the bud.
<strong>Contact Info: </strong>
Valkyrion#6196
<strong>Stack Trace: </strong>

**Comment by msprijatelj** [comment]
Note: Consider performing the same mathematics for "current uses" items with Limited Uses (limited uses increase/decrease with Engineering and result in behavior similar to above)
