### ISSUE TITLE
Feature Request: Maintain Pilots on LCP Deletion

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1599]
<strong>Submitted At: </strong>8/6/2021 13:05:02
<strong>Is your feature request related to a problem? Please describe. </strong>
I am frustrated that when I ~~disable or~~ uninstall an LCP, any pilot using content from that LCP is "invisible" and unavailable.
<strong>Describe the solution you'd like: </strong>
When I delete an LCP, my pilots using content from that LCP remain visible and either:
a) The options from the deleted LCP are still available, instantiated in their pilot sheet
OR
b) The options from the deleted LCP are disabled, deleted, or otherwise made unavailable until the LCP is re-enabled.
OR
c) The pilot is simply disabled altogether (but still visible in the pilot roster) until the LCP is re-enabled.
<strong>Additional context: </strong>

<strong>Contact: </strong>
Valkyrion#6196

**Comment by jarena3** [comment]
Added in 2.3
