### ISSUE TITLE
[BUG] Mission Runner using Vault Synced Pilots is broken

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1605]
<strong>Submitted At: </strong> 8/9/2021 13:01:06<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When using pilots from my players synced through Vault import in a mission, loading the first encounter throws a number of errors. <br><br><strong>Reproduction Steps:<br> </strong> As a player user, create a pilot and mech. Share your vault record id with the GM User. As the GM user, import the player via Vault import. Navigate to Mission Runner, select a Mission you have created with at least one encounter. Add the pilot and begin the mission<br><br><strong>Expected Result:<br> </strong> You can see the details of all the mechs in the encounter, and do things like adjust stats and end turns.<br><br><strong>Additional Context:<br> </strong> For the GM user, the synced pilots appear to have no active mech, even though the players have set active mechs. The GM can choose a mech when adding them to the mission, but on a reload, the players are back to having no active mech and then the mission view is completely blank.<br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
TypeError: Cannot read property 'ID' of null
    at https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:343:209510
    at Array.find (<anonymous>)
    at a.selected (https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:343:209483)
    at un.get (https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:22:26610)
    at un.evaluate (https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:22:27760)
    at a.selected (https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:22:29669)
    at https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:343:150302
    at a.ge [as _l] (https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:22:15925)
    at a.dr (https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:343:150198)
    at a._render (https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:22:35296)```<br>

**Comment by TranslucentSabre** [comment]
This seems to be an issue when pilots are synced without an "Active Mech" set. The GM player cannot set the "Active Mech" and have it be retained.
This played havoc because the mission runner cannot operate with out an active mech for each lancer.

**Comment by TranslucentSabre** [comment]
A possible, though very limited work-around is to only enable manual sync for the GM player. This allows some functionality, but obviously has some major drawbacks.

**Comment by TranslucentSabre** [comment]
@jarena3 , the real question here. Is there a way to make the active mech field writable on a vault synced mech in such a way that it will stay written by the "GM" user?
