### ISSUE TITLE
[BUG] Pilot Vault codes are displayed with upper case characters in the UI, but the Vault code import only accepts lower case characters.

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1606]
<strong>Submitted At: </strong> 8/9/2021 13:14:24<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When you display your pilots Vault code, it displays in the UI with upper case letter characters. If you cope that code and paste it into the vault import UI, it fails with a JSON error.<br><br><strong>Reproduction Steps:<br> </strong> Have one user create a pilot. Click "Settings Gear Icon" > COMP/CON Vault Record. Highlight and copy the displayed code. As another user, go Pilot Records > Add New Pilot > Vault Import. Paste the copied code, not that all letter characters are in upper case. Click Link Pilot.<br><br><strong>Expected Result:<br> </strong> Either the Vault Import should accept uppercase character codes, or the UI for Vault Code should display the code in lower case.<br><br><strong>Additional Context:<br> </strong> If you click the "Copy" icon next to the Vault code, it copies the code in lower case and then can be successfully imported by the second user.<br><br><br><strong>Stack Trace: </strong> ERROR IMPORTING PILOT: Unexpected token < in JSON at position 0<br>

**Comment by TranslucentSabre** [comment]
Here is a bit more information:
Using Firefox, a manual copy and paste resulted in a lowercase string.
Using Chrome, a manual copy and paste resulted in the behavior described above.

**Comment by msprijatelj** [comment]
Are returned vault codes usually all-lowercase? Or do they have a mix of upper/lower? Because if it's the former, this may be a straightforward matter of applying `string.lower()` to the Vault Import
