### ISSUE TITLE
[BUG] HP Buttons On Active Mode Pilot Screen Don't Work Properly

### ISSUE THREAD

**Issue by lothgirard** [massif-press/compcon#1616]
**Describe the bug**
When in active mode on the pilot screen on Comp/con, pressing the - (MINUS) button for HP only let me go down to maxHP-1, and no further, no matter how often I pressed, and if I typed manually what my new HP was and then pressed the + button, it jumped back to maxHP automatically, as if I had been on maxHP-1

**To Reproduce**
1. Select a pilot
2. Go into Active Mode, and make sure you are either in downtime mode or ejected from your mech in combat.
3. Scroll up until you see your pilot stats
4. Press the minus button directly under your HP
5. Press it again; you should see that it doesn't go down any further.
6. Press the plus button - it will go back to maxHP, as it should.
7. Type in any value less than maxHP-1 manually
8. Press the plus button - it will go back to maxHP instead of currentHP+1

**Expected behavior**
Pressing the minus button multiple times should lead to HP decreasing each time, and pressing the plus button while HP is low should only increase it by one each time, not back to full.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 92.0.4515.131 (Official Build) (64-bit)

**Comment by msprijatelj** [comment]
Closed by [8adce20](https://github.com/massif-press/compcon/commit/8adce20e049d0d8c4670287e2209022531e4f4ef).
