### ISSUE TITLE
Bug Report: External batteries don't affect range

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#162]
<strong>Submitted At: </strong>5/12/2019 6:27:45
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>External batteries don't affect range
<strong>Reproduction Steps: </strong>Slap some external batteries onto a frame using energy weapons, and youll see that the energy weapons' range doesnt increase.
<strong>Contact Info: </strong>Kastrand#7274

**Comment by aritsune** [comment]
can't reproduce; if you're trying to do this on line/burst/etc weapons, page 97 of the corebook specifies that range extensions don't apply to these
(this is pretty old so might have been fixed and not closed)
