### ISSUE TITLE
Feature Request: LCP Source

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1632]
<strong>Submitted At: </strong>8/18/2021 12:08:20
<strong>Is your feature request related to a problem? Please describe. </strong>
This is hardly a pressing issue, but as it stands there is no way to know what features (Frames/NPC Classes/ect) come from which LCP. Being able to track this would not only be useful for if different GM's rule differently on what homebrew is allowed, but also for being able to tell where to ask about rules clarification if needed
<strong>Describe the solution you'd like: </strong>
List the name of the LCP somewhere on a given feature (mspaint mockup given in the linked screenshot)
<strong>Additional context: </strong>
https://media.discordapp.net/attachments/440153797973508108/877599549164773386/unknown.png?width=1200&height=181
<strong>Contact: </strong>
Skelepope#3174

**Comment by msprijatelj** [comment]
A lot of this information has been added thanks to @TranslucentSabre ; #1604 details what still remains pilot-side.  Don't know if NPC classes/content will be touched until during/after the GM Toolkit Overhaul

**Comment by msprijatelj** [comment]
#1661 covered all remaining issues.  Closing.
