### ISSUE TITLE
[BUG] t.profile.GetView is not a function

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1642]
<strong>Submitted At: </strong> 8/25/2021 8:18:51<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Very minor; an error pops up in the bottom-right corner: "t.profile.GetView is not a function"<br><br><strong>Reproduction Steps:<br> </strong> Click on the pilot view option very quickly after loading the page.<br><br><strong>Expected Result:<br> </strong> No error message.<br><br><strong>Additional Context:<br> </strong> The error appears to come from src/features/pilot_management/Roster/index.vue<br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
va@https://compcon.app/app.bundle.js:343:217897
t.prototype._render@https://compcon.app/app.bundle.js:22:35296
i@https://compcon.app/app.bundle.js:22:64441
un.prototype.get@https://compcon.app/app.bundle.js:22:26610
un@https://compcon.app/app.bundle.js:22:26528
kn.prototype.$mount/<@https://compcon.app/app.bundle.js:22:64455
kn.prototype.$mount@https://compcon.app/app.bundle.js:22:64602
init@https://compcon.app/app.bundle.js:22:19337
n@https://compcon.app/app.bundle.js:22:23167
d/<@https://compcon.app/app.bundle.js:22:52509
d@https://compcon.app/app.bundle.js:22:52786
lo</<@https://compcon.app/app.bundle.js:22:56922
t.prototype._update@https://compcon.app/app.bundle.js:22:34351
i@https://compcon.app/app.bundle.js:22:64431
un.prototype.get@https://compcon.app/app.bundle.js:22:26610
un@https://compcon.app/app.bundle.js:22:26528
kn.prototype.$mount/<@https://compcon.app/app.bundle.js:22:64455
kn.prototype.$mount@https://compcon.app/app.bundle.js:22:64602
init@https://compcon.app/app.bundle.js:22:19337
d/<@https://compcon.app/app.bundle.js:22:52509
d@https://compcon.app/app.bundle.js:22:52786
h@https://compcon.app/app.bundle.js:22:53378
d@https://compcon.app/app.bundle.js:22:52900
h@https://compcon.app/app.bundle.js:22:53378
d@https://compcon.app/app.bundle.js:22:52900
lo</<@https://compcon.app/app.bundle.js:22:56922
t.prototype._update@https://compcon.app/app.bundle.js:22:34351
i@https://compcon.app/app.bundle.js:22:64431
un.prototype.get@https://compcon.app/app.bundle.js:22:26610
un@https://compcon.app/app.bundle.js:22:26528
kn.prototype.$mount/<@https://compcon.app/app.bundle.js:22:64455
kn.prototype.$mount@https://compcon.app/app.bundle.js:22:64602
init@https://compcon.app/app.bundle.js:22:19337
n@https://compcon.app/app.bundle.js:22:23167
d/<@https://compcon.app/app.bundle.js:22:52509
d@https://compcon.app/app.bundle.js:22:52786
S/<@https://compcon.app/app.bundle.js:22:55650
S@https://compcon.app/app.bundle.js:22:55834
S/<@https://compcon.app/app.bundle.js:22:55359
S@https://compcon.app/app.bundle.js:22:55834
lo</<@https://compcon.app/app.bundle.js:22:56970
t.prototype._update@https://compcon.app/app.bundle.js:22:34334
i@https://compcon.app/app.bundle.js:22:64431
un.prototype.get@https://compcon.app/app.bundle.js:22:26610
un.prototype.run@https://compcon.app/app.bundle.js:22:27494
pn@https://compcon.app/app.bundle.js:22:25602
ee/<@https://compcon.app/app.bundle.js:22:12293
Jt@https://compcon.app/app.bundle.js:22:11737
```<br>

**Comment by msprijatelj** [comment]
I've seen this one myself; I believe it's due to a logged-in user's Pilot Roster syncing/loading on a refresh (since the UserProfile is still being fetched/defined from the sync pull).  The pilot roster loads shortly after the sync is complete, so the bug doesn't appear to be breaking anything.

**Comment by msprijatelj** [comment]
Linking #700 to this, since they fall under the same umbrella
