### ISSUE TITLE
[BUG] pilots from vault and cloud imports not being added to pilot roster

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1650]
<strong>Submitted At: </strong> 8/28/2021 15:30:54<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> when trying to import a pilot from a vault or cloud code if the pilot being imported is in a folder/group in the original players compcon then the imported pilot will not show up in the pilot roster until compcon is refreshed at which point it will appear under the same folder it was in for the player that created it<br><br><strong>Reproduction Steps:<br> </strong> 1) on account A create a folder/group and add a pilot to it
2) on account B import the pilot created in step 1
3) the pilot probably wont appear in account B's comp/con
4) refresh the comp/con on account B. the pilot should now appear under it's original folder<br><br><strong>Expected Result:<br> </strong> the expected behavior was for the imported pilot to appear in the pilot roster without the need for a refresh (either ungrouped or under a new folder)<br><br><strong>Additional Context:<br> </strong> *) the group/folder the pilot was imported from did not exist for the one importing it so this bug might not appear if the same folder/group appears in both accounts
*) the bug occurs both for vault and cloud imports
*) i have personally encountered this bug and have also seen it happen to someone else (both times the pilot did not appear in the roster until comp/con was refreshed)<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Crud, this may have been an oversight from the pilot ordering change I made. The fix should be as simple as making sure PilotGroups gets updated on the PilotManagementStore on pilot import/add
