### ISSUE TITLE
[BUG] Unclear pilot Vault Data code error msg when not cloud synced

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1664]
<strong>Submitted At: </strong> 9/5/2021 4:52:13<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When trying to get the vault code for a pilot character that is not cloud synced, it simply reads ERR where the code should be, with no additional context.<br><br><strong>Reproduction Steps:<br> </strong> Create a character without an account logged in and try to get a shareable Vault code for it in the Pilot roster. Then make a new account, log in and try it again (should still read ERR as the sync was not immediate).<br><br><strong>Expected Result:<br> </strong> A more descriptive error message such as "You must cloud sync this character to your online comp/con account before a vault code can be generated!"<br><br><strong>Additional Context:<br> </strong> This same issue tripped up two players on separate occasions when introducing them to the app. They had both finished making their characters then made accounts so it took a fair while to figure out it was because the character information had not synced yet. There was nothing obvious to tell them this was necessary to generate the code or even that their data was not synced yet at all. There was only a full instead of faded cloud icon in a place they never look to indicate a lack of sync - so nothing visibly out of the ordinary.<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Having a descriptive error message makes sense here, given that Vault Exports use a menu instead of a prompt with buttons like Vault Imports.  I wonder, though, if we could grey out the Vault Export menu option and have an alternative description of "Requires Comp/Con Account" when there isn't a user logged in, to save the user the frustration of clicking into an error?
