### ISSUE TITLE
[BUG] Warning for Most Recent LCP Version

### ISSUE THREAD

**Issue by msprijatelj** [massif-press/compcon#1666]
**Browser:** Firefox
**Platform:** Desktop

**Issue Description:**
When an installed, up-to-date LCP has a version number higher than the one recorded in Comp/Con's S3-hosted `communitypacks.json`, Comp/Con displays a "Pack Outdated" warning in the LCP Directory for that LCP.

**Reproduction Steps:**
1. Navigate to Content Manager -> LCP Directory
2. Download an LCP from the Community Content section, noting the version listed on Comp/Con.
3. Zip Extract the LCP, modify its `lcp_manifest.json` to have a higher version number, then re-zip the LCP files into a new LCP package.
4. Install the new LCP with the modified version.
5. Navigate to Content Manager -> Content Packs; note version of installed LCP matches the modified version.
6. Navigate to the LCP Directory tab.
7. Observe the "Pack Outdated" warning next to the LCP version of the newly-installed LCP.

**Expected Result:**
Ideally, when a community creator releases a new version of an LCP, the version in Comp/Con updates to match.  With that in mind, I see a few possible solutions:
1. Ensure Comp/Con's versioning of Community Content is up-to-date on a more consistent basis
2. Suppress the "Pack Outdated" warning when the installed LCP version is newer than the one stored by Comp/Con.
3. Change the "Pack Outdated" warning into a warning like "version does not match expected; proceed with caution" or the like.

**Additional Context:**
A PilotNET user reported this issue in the Discord.  I don't know the current process of submitting an LCP to Community Creations & subsequently updating its versioning, so I don't have any recommendations on that front.  I will note that for solution 2, mentioned above, a more robust version checker (probably a new node module) may be necessary to handle the variety of versioning that content creators may employ.

**Comment by jarena3** [comment]
I've got versioning in a dynamo now, and LCP creators have a tool to update it without my intervention, so we should be okay (I think)
