### ISSUE TITLE
[BUG] Caliban Mod not appearing

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1669]
<strong>Submitted At: </strong> 9/13/2021 17:45:46<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> all of them<br><br><strong>Issue Description: </strong><br> can not apply the Supermassive mod to weapons in new compcon<br><br><strong>Reproduction Steps:<br> </strong> attempt to place supermassive mod to a weapon<br><br><strong>Expected Result:<br> </strong> should be able to apply the super massive mod<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
I followed the (limited) steps to reproduce, and was able to apply the Caliban I: Supermassive Mod to a Melee, CQB, and Cannon weapon.  I could only equip one at a time, keeping in line with the Unique tag.  Given the mention of "new compcon" in the original issue, I can only guess that the user may need to update or reinstall their Long Rim LCP to the latest version.

I did notice, however, that the Supermassive Mod lacked "Added Tags" for Overkill and Knockback 1 (at minimum).  I don't know if mods can have profiles, but at the very least I feel the Overkill tag should be included in the mod.  I'll make a new Long Rim Data PR to address that.
