### ISSUE TITLE
[FEATURE] Additional entries for the mech name generator

### ISSUE THREAD

**Issue by ArcanErasmus** [massif-press/compcon#1672]
**Is your feature request related to a problem? Please describe.**
I have come up with more names and want to share them with lancers everywhere.

**Describe the solution you'd like**
Any of the provided names deemed suitable get added.

**Describe alternatives you've considered**
I am given feedback indicating why the names don't work and I remake some of them.

**Additional context**
The names:

```
A Final Donation
Accidental Caps Lock
Aftermarket Alimony
Ancient Breathing Apparatus
Assisted Living
Bittersweet Release
Brevity Without Wit
Brush With Doubt
Ceremonial Sympathy
Coal-Fired Friendship
Confused But Supportive
Craven But Kind
Customary Martyrdom
Date With Devilry
Death in Vain
Declined Promotion
Delays In Processing
Desperate Measurements
Dinner With Her Parents
Empty Threat
Far Too Trusting
Faustian Slip
Flammable Feelings
Hero (Derogatory)
Humanity, Tested
In Sickness And In Hell
Indirect Injection
Judgemental Connotation
Last In, Last Out
Meaningless Compromise
Melodious Oddity
Mortophobic
No Hidden Agenda
Not Fun By Myself
Not Worth Going Back For
Opiate Overtones
Outlived Mantra
Over-Seasoned And Under-Cooked
Passionate But Powerless
Power of Won't
Preventative Pity
Resigned Optimism
Sappy But Bittersweet
Secondhand Hope
Sincerity Couched Behind Humor
Soothing Refrain
Stash of Sunlight
This Machine Doesn't
Uncomfortably Vague
Unleaded Florescence
We Patched Things Up
Whole-Ass One Thing
Worrying Parallels
You'll Make It Through This
Zealous Indifference
```

**Comment by msprijatelj** [comment]
I think it could be cool if we could get more community submissions like this! I don't know if there's a great way right now to handle these submissions so we don't get overwhelmed if it picks up (and wind up with a massive name file), but I'd love it if we could evaluate some of these names and pull them in.  At the end of the day, I'm glad this submission has been made so we can discuss community contributions in this vein!

**Comment by msprijatelj** [comment]
The requested mech names have been added!
