### ISSUE TITLE
[BUG] "undefined is not an object"

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1674]
<strong>Submitted At: </strong> 9/16/2021 21:22:15<br><br><strong>Browser: </strong> Safari<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> I have a lich mech. When I go to the lich's tab in the Mech Hangar, it always brings up a red box with an error message saying "undefined is not an object (evaluating 't.coreSystem.Activation.toLowerCase)'. On a possibly related note, the mech's core power, Glitch Time, does not appear in the lich's tab.<br><br><strong>Reproduction Steps:<br> </strong> Have a lich and look at it in the mech hangar.<br><br><strong>Expected Result:<br> </strong> Not sure. Haven't used comp/con beforehand. As far as I expect, there shouldn't be any error messages, and Glitch Time should probably be showing up.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
wh@https://compcon.app/app.bundle.js:343:598034
https://compcon.app/app.bundle.js:22:35300
i@https://compcon.app/app.bundle.js:22:64448
https://compcon.app/app.bundle.js:22:26614
un@https://compcon.app/app.bundle.js:22:26531
https://compcon.app/app.bundle.js:22:64461
init@https://compcon.app/app.bundle.js:22:19343
https://compcon.app/app.bundle.js:22:52510
d@https://compcon.app/app.bundle.js:22:52786
h@https://compcon.app/app.bundle.js:22:53378
d@https://compcon.app/app.bundle.js:22:52901
https://compcon.app/app.bundle.js:22:56923
https://compcon.app/app.bundle.js:22:34360
i@https://compcon.app/app.bundle.js:22:64438
https://compcon.app/app.bundle.js:22:26614
un@https://compcon.app/app.bundle.js:22:26531
https://compcon.app/app.bundle.js:22:64461
init@https://compcon.app/app.bundle.js:22:19343
n@https://compcon.app/app.bundle.js:22:23167
https://compcon.app/app.bundle.js:22:52510
d@https://compcon.app/app.bundle.js:22:52786
https://compcon.app/app.bundle.js:22:55651
S@https://compcon.app/app.bundle.js:22:55834
https://compcon.app/app.bundle.js:22:56970
https://compcon.app/app.bundle.js:22:34343
i@https://compcon.app/app.bundle.js:22:64438
https://compcon.app/app.bundle.js:22:26614
https://compcon.app/app.bundle.js:22:27497
pn@https://compcon.app/app.bundle.js:22:25605
https://compcon.app/app.bundle.js:22:12297
Jt@https://compcon.app/app.bundle.js:22:11737
promiseReactionJob@[native code]```<br>

**Comment by msprijatelj** [comment]
If the issue author is reading this: My gut reaction to try to fix this would be to uninstall the Long Rim LCP and reinstall the latest version.  Definitely verify if you're using the latest version.
