### ISSUE TITLE
[BUG] Can’t Import Pilots on Mobile

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1686]
<strong>Submitted At: </strong> 9/27/2021 11:04:44<br><br><strong>Browser: </strong> Safari<br><strong>Platform: </strong> Phone<br><br><strong>Issue Description: </strong><br> When I try to import a .json pilot file on mobile, the Files screen opens, but all .json files in all folders are greyed out and unselectable, like an unsupported file type.<br><br><strong>Reproduction Steps:<br> </strong> Try to import a pilot on safari on iOS<br><br><strong>Expected Result:<br> </strong> Being able to import a pilot<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by jarena3** [comment]
this is, unfortunately, an issue with iOS
