### ISSUE TITLE
Feature Request: House Rules

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#169]
<strong>Submitted At: </strong>5/16/2019 12:29:47
<strong>Feature: </strong>House rules
<strong>Details: </strong>The ability for the GM to modify thing like :
Pilot progress (more or less skill points , talents or core bonuses)
More or less equipement/mount/weapon for the pilot or mech

Finer tweaking like
Mech editing for example :
Changing the stat of a mech 
Adding/removing frame trait or core system 
Same for weapons (range,damage,damage type, etc)

Systems editing
for example:
SP cost adjustement 
System modification 

 Thanks for reading this suggestion
<strong>Contact: </strong>Casty#6967

**Comment by aritsune** [comment]
@jarena3 didn't you say this was out of scope a couple weeks ago on discord, or is this something different?

**Comment by jarena3** [comment]
I think, provisionally, there'll be space to have house rules on a per-campaign level (by managing the stuff that's in rules.json now). I'm not sure about the extent of it yet -- probably not everything asked for in the FR -- but I think we can definitely do something with this
