### ISSUE TITLE
[BUG] Compendium Frame Art cropped on wide windows

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1690]
<strong>Submitted At: </strong> 9/29/2021 19:47:12<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When *increasing* the width of the page in the License Compendium, the art for the frames becomes increasingly cropped off the righthand side.<br><br><strong>Reproduction Steps:<br> </strong> 1. Open Compendium, navigate to Licenses
2. Resize window width to increase and decrease
3. Note that the frame's banner art is more heavily cropped off when the window is wider, but mostly intact when width is decreased<br><br><strong>Expected Result:<br> </strong> The frame art more tightly hugs the right-hand edge of the license banner so that most of the art remains visible, similar to the spacing in Pilot License management and Mech creation.<br><br><strong>Additional Context:<br> </strong> Biggest offender here is the Mourning Cloak, which has an unflattering crop at max width.<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
PilotNET member pointed out the Mourning Cloak had a very unflattering crop, so I decided to report this to see if there was a way to tweak the CSS in a way that preserves more of the Frames' art.  Example shown:
![This could stand to be improved.](https://cdn.discordapp.com/attachments/568459736119509023/892931201822756934/unknown.png)

**Comment by msprijatelj** [comment]
[Offending line](https://github.com/massif-press/compcon/blob/master/src/features/compendium/Views/Licenses.vue#L50) in Compendium Licenses here.

[Line behind the desired behavior](https://github.com/massif-press/compcon/blob/master/src/features/pilot_management/PilotSheet/sections/hangar/components/NewMechMenu.vue#L70).
