### ISSUE TITLE
[FEATURE] Cleanly update to new versions of content packs

### ISSUE THREAD

**Issue by msprijatelj** [massif-press/compcon#1697]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I cannot share my pilot through the vault because they are equipped with out-of-date components from a content pack I recently updated.

**Describe the solution you'd like**
I would like some form of dialog box or prompt to display when I replace a content pack, asking if I would like to update all of my pilots to use the contents of the new pack.  If "No", no update occurs. If "Yes", the following occurs:

1. A progress bar or loading icon/gif displays until the process is complete.
2. CompCon goes through all of my pilots and their gear, checking for content that matches the pack name but differs in version number.
3. All content with the same pack name but with a different version number is replaced with the content with a matching ID from the incoming version.
4. Any content that could not be replaced is left as-is, but reported to the user as a warning (e.g. "The following content on the following pilots and mechs could not be replaced: [content] These pilots will not sync until the obsolete content is replaced").

Including version numbers (and/or version mismatch warnings) alongside LCP name displays would assist in determining data out-of-date with the installed version.  In addition, an "up-to-date" status icon for pilots and/or mechs with up-to-date data would be a useful graphic.

**Describe alternatives you've considered**
At the very least, a reminder to change out old content would be useful for users updating their content.  If LCP version numbers and/or version mismatch warnings were included next to LCP content, I feel it would greatly improve the user experience of updating their content to the most recent version.

**Additional context**
PilotNet has seen a lot of version mismatch issues for people using the old Long Rim LCPs.  Implementing some form of update or notice would reduce pain for both the users and the people helping them.

**Comment by msprijatelj** [comment]
If some sort of "warning: pilot or mech out of date" system were implemented, it could probably be expanded to include instances where the LCP data can't be found, like mentioned in #1599.

**Comment by jarena3** [comment]
Added in 2.3
