### ISSUE TITLE
[FEATURE] Automatic Local Data Backups

### ISSUE THREAD

**Issue by CubularMonoxide** [massif-press/compcon#1701]
**Is your feature request related to a problem? Please describe.**
Sync issues are an infrequent but very present problem for my team's campaign. Every so often, someone will log in to C/C and find that seemingly random data has been lost from their accounts, including Pilots, Mechs, and sometimes installed LCPs. It's annoying, and the exact issues are random and infrequent, making troubleshooting a difficult task.

**Describe the solution you'd like**
I'd like to be able to set up automatic local data backups. Local data backups already exist, of course, but I'd like to be able to have them occur automatically, with a list of triggers that can be toggled, similar to [what already exists for Syncing](https://cdn.discordapp.com/attachments/568459736119509023/894073734380544080/chrome_P0rjbx4RDP.png).

**Describe alternatives you've considered**
The most obvious solution is simply to download backups yourself. I do do this, but given my (what I assume to be) ADHD, remembering to do this after I've made critical changes is not always a guarantee. Streamlining the process would lift huge worries off my shoulders.

**Additional context**
N/A

**Comment by CubularMonoxide** [comment]
> I think the original poster is asking for CompCon to automatically create “.compcon” backups when an appropriate event occurs - no reading from the local machine, just attempting a download periodically. It would probably be opt in, but I still think it would be weird for a user to see a bunch of .compcon backups in their download history. Maybe the requester feels differently, though?

This is what I was intending, yes. I don't feel that it would be very intrusive, mostly because it would be opt-in, but I can see how it would be annoying for someone that doesn't understand the feature.

**Comment by jarena3** [comment]
yeah I could see how something like "create COMP/CON autosaves" would be useful. I think, though, for security concerns the downloads can't be overwritten and either have to always throw up a save dialog or download only to the user downloads folder. The former kind of defeats the purpose of making this automatic, but maybe as an opt-in the latter wouldn't matter too much.

**Comment by msprijatelj** [comment]
After a conversation on PilotNET today, I believe that even if we don't do a sort of "auto save" or "end of session save", it would behoove us to include an easy-to-access "Save Local Data" button in the navbar.  Right now the best way to make a backup is on the Main Page or in the Options menu (where it could get overlooked).  Having a clear "download" button may help with an "in sight, in mind" pattern

**Comment by jarena3** [comment]
the plan right now is to have the content management tools accessible from the navbar, so creating a backup (or syncing to the cloud, etc) can be done in ~two clicks

**Comment by jarena3** [comment]
Addressed in 2.3
