### ISSUE TITLE
[BUG] Tooltip Mismatch in Mech Hanger

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1702]
<strong>Submitted At: </strong> 10/3/2021 13:14:59<br><br><strong>Source: </strong> No Room for a Wallflower<br><br><strong>Incorrect Text/Data: </strong><br> The Atlas gets +1 Difficulty on ENGINEERING checks and saves.<br><br><strong>Correct Text/Data: </strong><br> The Kobold gets +1 Difficulty on ENGINEERING checks and saves.<br>

**Comment by msprijatelj** [comment]
Duplicate of #1652
