### ISSUE TITLE
[BUG] Limited systems displaying additional uses (12/9)

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1708]
<strong>Submitted At: </strong> 10/8/2021 18:16:06<br><br><strong>Issue: </strong><br> In active combat mode, Limited systems are displayed with uses beyond the cap (12/9 uses remaining). Not entirely clear why.<br><br><strong>Massif Reference: </strong> <br>

**Comment by msprijatelj** [comment]
Additional context: This is reproducible by providing any kind of limited systems bonus (Engineering bonus, HA Integrated Ammo Feeds Core Bonus, etc.) and by starting a new mission in Active Mode.  It doesn't "stack" the uses (i.e. starting a mission several times in a row doesn't subsequently increase the cap) but it does apply the limited systems bonus twice when determining starting uses.  Max uses are calculated correctly.
