### ISSUE TITLE
[BUG] Pilot Groups hidden on login

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1709]
<strong>Submitted At: </strong> 10/9/2021 11:05:40<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Pilot Groups do not initialize upon logging into CompCon.<br><br><strong>Reproduction Steps:<br> </strong> 1. Be logged into CompCon, create a pilot, put them in a custom-named group, and sync the pilot
2. Open CompCon with no local storage (e.g. in Incognito mode)
3. Log into account from step 1
4. Navigate to Pilot Roster
5. Observe that the custom Pilot Group from step 1 is not present
6. Refresh page
7. Observe that the custom Pilot Group from step 1 is present<br><br><strong>Expected Result:<br> </strong> Upon log in, pilot groups are initialized in the app to prevent confusion and/or necessitating a page reload.<br><br><strong>Additional Context:<br> </strong> This group initialization was previously added for importing pilots, so similar code added to the "login startup" may solve this issue.
<br><br><br><strong>Stack Trace: </strong> 

**Discord Handle:**
Valkyrion#6196<br>

**Comment by jarena3** [comment]
This may be resolved by incoming changes to address #1642
