### ISSUE TITLE
[BUG] Unable to delete pilots from Pilot Roster

### ISSUE THREAD

**Issue by 112nugohS** [massif-press/compcon#1723]
**Describe the bug**
Unable to delete pilots without crashing, after crashing, restart COMP/CON and see the pilots are back

**To Reproduce**
1. Go to 'Pilot Roster'
2. Attempt to delete pilots from pilot roster
3. shortly thereafter run out of memory and crash
4. refresh program
5. see all deleted pilots returned

**Expected behavior**
The pilots remain deleted

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 2.2.32

**Additional context**
In general, COMP/CON is consuming a large amount of RAM, and is crashing frequently when allowed to run for more than a few minutes.

**Comment by jarena3** [comment]
this seems to have been resolved after the rollback and leak fix
