### ISSUE TITLE
[BUG] Refreshing COMP/CON duplicates cloud vault contents

### ISSUE THREAD

**Issue by sealtrowitz** [massif-press/compcon#1725]
**Describe the bug**
Refreshing the page while on COMP/CON's website duplicates all cloud vault contents. It doesn't seem to actually duplicate the contents on COMP/CON itself (IE none of my pilots are actually duplicated in the Pilot Roster). Manually syncing causes the numbers in the cloud vault to drop back down to normal.

**To Reproduce**
1. Open COMP/CON in a browser window
2. Click on the Connected button on the home page to check your vault contents
3. Refresh the browser page
4. Click on the Connected button again to see the duplicated contents

**Expected behavior**
Refreshing the page should not duplicate cloud vault contents.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/14993881/137412399-6bcdcdf3-4473-4dad-9dcf-54114fa748d1.png)

After:
![image](https://user-images.githubusercontent.com/14993881/137412445-8d388ff6-5746-4ea0-ab87-14d8c14ae38b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: COMP/CON version 2.2.32

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Additional context**
Tested both with my LCPs enabled and disabled, the problem persisted either way. Didn't try uninstalling them though.  The number it duplicates the cloud vault contents by appears to be consistent when I managed to reproduce the bug (IE my number of pilots in the vault jumped from 20 to 60 each time), though when I tried disabling all LCPs and refreshing again, that number changed, and re-enabling the LCPs caused the numbers to change again. Subsequent refreshes keep the numbers consistent though. I should also note that I have Manual Sync Only enabled.

**LCPs installed**
![image](https://user-images.githubusercontent.com/14993881/137412505-7ebda91b-dd36-4e2e-84b9-e4a4ce954ff4.png)

**Comment by msprijatelj** [comment]
Found that the issue could be reproduced by initializing a sync while a previous sync was still running, then refreshing the page while the "On App Load" Sync setting was disabled.

Quoting Beeftime from the Discord thread on this issue:

> aha! finally got it to appear. I can confidently say we're not double loading anything. Those vault content counts are referencing a key store of database record pointers, and they're not getting cleared out on reload -- I think because without the initial appload sync we don't have anything that reinitializes the userstore

So it may be prudent to add logic that reinitializes the userstore on Startup, regardless of whether sync is enabled (or maybe even regardless of if the user is signed in).

**Comment by msprijatelj** [comment]
@jarena3 I assume that the v2.3 overhaul makes this issue moot?

**Comment by jarena3** [comment]
good catch -- yeah this one can be safely closed, I think
