### ISSUE TITLE
[BUG] Saladin Enclave Support Shield Heat Tag Misrepresentation

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1732]
<strong>Submitted At: </strong> 10/18/2021 14:44:03<br><br><strong>Issue: </strong><br> The Saladin's ENCLAVE-Pattern Support Shield has both a Quick Action and a Reaction tied to it: There is a Heat cost attached to the reaction (Heat 2 (Self)) but due to how Equipment tags work, the Heat 2 (Self) tag is attached to the System as a whole, making it seem like the Quick Action costs 2 heat to use. The Blinkfield Intervention has a line of text in the reaction's Effect itself specifying that you take 2 Heat when you use it that isn't there in the original PDF to preserve functionality, so it may be fine to just strip the Heat 2 (Self) tag from the System itself, or alternatively specify in the Quick Action that you do not take this System's Heat cost when you use the Quick Action.<br><br><strong>Massif Reference: </strong> Lancer Corebook Pg. 244<br>

**Comment by lenaleciel** [comment]
As a note, the active mode actions for both the Quick Action and the Reaction appear to be properly tagged with the heat tags necessary for them to function in Active mode (0 heat for the quick action, 2 for the reaction) so I left those alone.

**Comment by msprijatelj** [comment]
Closed by [lancer-data #161](https://github.com/massif-press/lancer-data/pull/161#event-5569712604)
