### ISSUE TITLE
[BUG] Compendium Mech weapons Bug

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1738]
<strong>Submitted At: </strong> 10/22/2021 19:30:47<br><br><strong>Browser: </strong> Opera<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Going to Mech Weapons in the Compendium and trying to filter results through damage type gives up an error prompt, "Cannot read properties of undefined (reading 'map')". Then it does not filter the weapons based on damage type.<br><br><strong>Reproduction Steps:<br> </strong> Go to Comp/con
Go to Compendium
Go to Mech Weapons
Click on Set Item Filters
Click on Damage Type and select any damage type
See Error Prompt come up<br><br><strong>Expected Result:<br> </strong> I expected the filter to filter the weapons based on damage type<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
TypeError: Cannot read properties of undefined (reading 'map')
    at e.get (https://compcon.app/app.bundle.js:37:94271)
    at https://compcon.app/app.bundle.js:183:65623
    at Array.some (<anonymous>)
    at https://compcon.app/app.bundle.js:183:65597
    at Array.filter (<anonymous>)
    at https://compcon.app/app.bundle.js:183:65565
    at Array.forEach (<anonymous>)
    at Function.t.Filter (https://compcon.app/app.bundle.js:183:64987)
    at a.fItems (https://compcon.app/app.bundle.js:328:684087)
    at un.get (https://compcon.app/app.bundle.js:22:26610)```<br>

**Comment by jarena3** [comment]
this seems to be due to an LCP item
