### ISSUE TITLE
Feature Request: android port

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#174]
<strong>Submitted At: </strong>5/19/2019 14:04:53
<strong>Feature: </strong>Android port
<strong>Details: </strong>An android version, if feasible, would be greatly appreciated.
<strong>Contact: </strong>

**Comment by Ignus3** [comment]
Seconding this request,  especially as a comp/con unit seems to be effectively a smart phone in universe. Also, I saw someone who offered to take a stab at it, I also would be willing to try to contribute, though my experience with porting is nonexistent. I do know some javascript though, and general dev concepts

**Comment by aritsune** [comment]
Dupe of #300
