### ISSUE TITLE
[BUG] Ricochet Blades Typo

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1746]
<strong>Submitted At: </strong> 10/29/2021 10:38:01<br><br><strong>Source: </strong> The Long Rim<br><br><strong>Incorrect Text/Data: </strong><br> "As a quick action, you throw a ricochet blade along a Range 3 path, dealing 2 Kinetic Damage to all characters within the affected area. If the initial LINE reaches a piece of terrain or object of SIZE 1 or larger, draw another Range 3 path from that object in a new direction that doesn't overlap with the object it ricocheted off. Characters within the affected area must succeed on an AGILITY save or take 1d6+3 Kinetic Damage."
<br><br><strong>Correct Text/Data: </strong><br> "As a quick action, you throw a ricochet blade along a line 3 path, dealing 2 kinetic damage to all characters within the affected area. If the initial line reaches a piece of terrain or object of SIZE 1 or larger, draw another line 3 path from that object in a new direction that doesn't overlap with the object it ricocheted off. Characters within the affected area must succeed on an Agility save or take 1d6+3 kinetic damage."

reupload of issue #1516 : The unique tag was properly added, but the line is still listed as range, and there are still formatting inconsistencies with core book systems. (AGILITY being Agility in other core book systems, Kinetic Damage being kinetic damage, and so on.)<br>

**Comment by lenaleciel** [comment]
Addressed in https://github.com/massif-press/long-rim-data/pull/15 , alongside a suite of other formatting changes to match with the core book data.
