### ISSUE TITLE
[BUG] Wallflower LCP is missing the Scouring Whip weapon on the Lurker NPC 

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1750]
<strong>Submitted At: </strong> 11/1/2021 0:19:53<br><br><strong>Source: </strong> No Room for a Wallflower<br><br><strong>Incorrect Text/Data: </strong><br> Scouring Whip weapon is missing entirely<br><br><strong>Correct Text/Data: </strong><br> Scouring Whip
Heavy Melee, +0 vs evasion
[�1][8/10/12�]
This weapon gains �3 and +1�when used
within a SHROUD ZONE.
On hit: The target is pulled adjacent to the Lurker,
or as close as possible.
On critical hit: As above, and the target is
immediately GRAPPLED.<br>

**Comment by msprijatelj** [comment]
I believe this has to do with the change in the Scouring Whip ID from `souring` to `scouring`.  Workaround is to create a new Lurker NPC using the Wallflower NPC Data v1.0.5.
