### ISSUE TITLE
[BUG] Mission runner resets character sheets when using cloud sync'd characters

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1767]
<strong>Submitted At: </strong> 11/8/2021 20:37:19<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When you have cloud sync'd characters in a mission, close it, and come back sometime later, the character sheets are reset as if a full repair has happened (ive had two instances of this where i went back after a week and it was reset)<br><br><strong>Reproduction Steps:<br> </strong> Create a mission, add some pilots shared from another pilot's vault, start the mission, use some of their resources, fully close out of compcon, and then reopen after several days.<br><br><strong>Expected Result:<br> </strong> Character sheet data persists across loads in the mission runner<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by jarena3** [comment]
Fixed in 2.3
