### ISSUE TITLE
[BUG] Print Sheet Off-center HASE and Armor numbers

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1768]
<strong>Submitted At: </strong> 11/10/2021 13:51:42<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> HASE and Armor numbers appear off-center when printing a character sheet.<br><br><strong>Reproduction Steps:<br> </strong> Print a character sheet.<br><br><strong>Expected Result:<br> </strong> The numbers being centered in the hexagons and shield for HASE and Armor respectively.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Issue was discussed more on PilotNET. The issue apparently doesn’t occur on Chrome, nor on iOS Firefox (screenshot attached):
![3F358153-F902-40AE-92E1-83386FE30C40](https://user-images.githubusercontent.com/44978587/141184585-2c2bf253-3d6a-44c8-b174-b457b47542fa.jpeg)
