### ISSUE TITLE
[BUG] foundry comp/con???

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1771]
<strong>Submitted At: </strong> 11/14/2021 2:46:06<br><br><strong>Browser: </strong> Foundry <br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Im unable to log into the comp con system in foundry <br><br><strong>Reproduction Steps:<br> </strong> when i open up my lancer campaign i go to the information to login to comp/con. i don't know if its an oversite on my. But I'm unable to see were my comp/con username is for me to login to the comp/con in foundry.<br><br><strong>Expected Result:<br> </strong> i would think that foundry would except my comp/con features and apply them to the online tabletop.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
If you’re already logged into CompCon, your username is at the top of the Cloud Account window (click the Connected button in the bottom left corner on the main page). The username is case sensitive, even though it is an email address. Any other issues would be on the Foundry side of things.
