### ISSUE TITLE
[BUG] Talents unclear

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1772]
<strong>Submitted At: </strong> 11/29/2021 20:03:38<br><br><strong>Issue: </strong><br> Talents do not list in their language if they are once/round or otherwise (see Valient Aid). Please put it in writing in the wording for clarity as colour is not a strong indicator (nor colour blind easy)<br><br><strong>Massif Reference: </strong> idk the page for Valient Aid in talents, but it is there.<br>

**Comment by msprijatelj** [comment]
Exemplar 1's Valiant Aid reaction lists its frequency in the granted Reaction (1/round). If there are other talents that both lack a 1/round descriptor in their description **and** any actions they grant, please share them and so they can be promptly fixed.

**Comment by jarena3** [comment]
Seems like it's there to me too, closing this.
