### ISSUE TITLE
[BUG] Burn Prevents New Round Start

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1774]
<strong>Submitted At: </strong> 12/1/2021 19:24:14<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> The engineering check for burn should occur at the end of a player's turn. Instead it occurs whenever attempting to begin or end a round, and prevents the round from beginning/ending .<br><br><strong>Reproduction Steps:<br> </strong> In a mech combat encounter:
- Apply burn to the mech
- Attempt to start a new round<br><br><strong>Expected Result:<br> </strong> Round should begin<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
This error is occurring in active mode.  More detailed steps to reproduce:

1. Enter Active Mode - Combat Mode
2. Click End Turn and confirm
3. Before clicking "Start Round 2", apply burn to the mech
4. Click "Start Round 2"
5. Observe that the burn check prompt pops up
