### ISSUE TITLE
[BUG] Can't view pilot and lots of error messages

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1777]
<strong>Submitted At: </strong> 12/10/2021 17:22:30<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> t.pilot is undefined is spammed in my console for however many times I've tried to link a pilot with a vault import --- Seems to be an error in PilotListItem.vue<br><br><strong>Reproduction Steps:<br> </strong> Tried to import pilot: 12945e97-917c-4861-adb2-b1b83fb93150//7d2f340e-8305-4d82-ad4f-2d33241bb7ba

Hit confirm after seeing pilots name and callsign.

Pilot shows up in list but cannot be clicked, refreshing the page hides the pilot but keeps displaying error messages.<br><br><strong>Expected Result:<br> </strong> pilot should be imported<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
ka@https://compcon.app/app.bundle.js:343:228359
t.prototype._render@https://compcon.app/app.bundle.js:22:35296
i@https://compcon.app/app.bundle.js:22:64441
un.prototype.get@https://compcon.app/app.bundle.js:22:26610
un@https://compcon.app/app.bundle.js:22:26528
kn.prototype.$mount/<@https://compcon.app/app.bundle.js:22:64455
kn.prototype.$mount@https://compcon.app/app.bundle.js:22:64602
init@https://compcon.app/app.bundle.js:22:19337
d/<@https://compcon.app/app.bundle.js:22:52509
d@https://compcon.app/app.bundle.js:22:52786
h@https://compcon.app/app.bundle.js:22:53378
d@https://compcon.app/app.bundle.js:22:52900
lo</<@https://compcon.app/app.bundle.js:22:56922
t.prototype._update@https://compcon.app/app.bundle.js:22:34351
i@https://compcon.app/app.bundle.js:22:64431
un.prototype.get@https://compcon.app/app.bundle.js:22:26610
un@https://compcon.app/app.bundle.js:22:26528
kn.prototype.$mount/<@https://compcon.app/app.bundle.js:22:64455
kn.prototype.$mount@https://compcon.app/app.bundle.js:22:64602
init@https://compcon.app/app.bundle.js:22:19337
d/<@https://compcon.app/app.bundle.js:22:52509
d@https://compcon.app/app.bundle.js:22:52786
lo</<@https://compcon.app/app.bundle.js:22:56922
t.prototype._update@https://compcon.app/app.bundle.js:22:34351
i@https://compcon.app/app.bundle.js:22:64431
un.prototype.get@https://compcon.app/app.bundle.js:22:26610
un@https://compcon.app/app.bundle.js:22:26528
kn.prototype.$mount/<@https://compcon.app/app.bundle.js:22:64455
kn.prototype.$mount@https://compcon.app/app.bundle.js:22:64602
init@https://compcon.app/app.bundle.js:22:19337
d/<@https://compcon.app/app.bundle.js:22:52509
d@https://compcon.app/app.bundle.js:22:52786
h@https://compcon.app/app.bundle.js:22:53378
d@https://compcon.app/app.bundle.js:22:52900
h@https://compcon.app/app.bundle.js:22:53378
d@https://compcon.app/app.bundle.js:22:52900
h@https://compcon.app/app.bundle.js:22:53378
d@https://compcon.app/app.bundle.js:22:52900
lo</<@https://compcon.app/app.bundle.js:22:56922
t.prototype._update@https://compcon.app/app.bundle.js:22:34351
i@https://compcon.app/app.bundle.js:22:64431
un.prototype.get@https://compcon.app/app.bundle.js:22:26610
un@https://compcon.app/app.bundle.js:22:26528
kn.prototype.$mount/<@https://compcon.app/app.bundle.js:22:64455
kn.prototype.$mount@https://compcon.app/app.bundle.js:22:64602
init@https://compcon.app/app.bundle.js:22:19337
d/<@https://compcon.app/app.bundle.js:22:52509
d@https://compcon.app/app.bundle.js:22:52786
h@https://compcon.app/app.bundle.js:22:53378
d@https://compcon.app/app.bundle.js:22:52900
lo</<@https://compcon.app/app.bundle.js:22:56922
t.prototype._update@https://compcon.app/app.bundle.js:22:34351
i@https://compcon.app/app.bundle.js:22:64431
un.prototype.get@https://compcon.app/app.bundle.js:22:26610
un@https://compcon.app/app.bundle.js:22:26528
kn.prototype.$mount/<@https://compcon.app/app.bundle.js:22:64455
kn.prototype.$mount@https://compcon.app/app.bundle.js:22:64602
init@https://compcon.app/app.bundle.js:22:19337
d/<@https://compcon.app/app.bundle.js:22:52509
d@https://compcon.app/app.bundle.js:22:52786
h@https://compcon.app/app.bundle.js:22:53378
d@https://compcon.app/app.bundle.js:22:52900
lo</<@https://compcon.app/app.bundle.js:22:57233
t.prototype._update@https://compcon.app/app.bundle.js:22:34334
i@https://compcon.app/app.bundle.js:22:64431
un.prototype.get@https://compcon.app/app.bundle.js:22:26610
un.prototype.run@https://compcon.app/app.bundle.js:22:27494
pn@https://compcon.app/app.bundle.js:22:25602
ee/<@https://compcon.app/app.bundle.js:22:12293
Jt@https://compcon.app/app.bundle.js:22:11737
promise callback*Gt@https://compcon.app/app.bundle.js:22:11827
ee@https://compcon.app/app.bundle.js:22:12356
un.prototype.update/<@https://compcon.app/app.bundle.js:22:27422
un.prototype.update@https://compcon.app/app.bundle.js:22:27431
pt.prototype.notify@https://compcon.app/app.bundle.js:22:4811
set@https://compcon.app/app.bundle.js:22:7323
u</e.prototype.SET_USER_PROFILE@https://compcon.app/app.bundle.js:52:3542
m/i.mutations[e]@https://compcon.app/app.bundle.js:66:5528
f/</</<@https://compcon.app/app.bundle.js:233:478038
p.prototype.commit/</<@https://compcon.app/app.bundle.js:239:638
p.prototype.commit/<@https://compcon.app/app.bundle.js:239:616
p.prototype._withCommit@https://compcon.app/app.bundle.js:239:2446
p.prototype.commit@https://compcon.app/app.bundle.js:239:590
p/this.commit@https://compcon.app/app.bundle.js:233:475503
u</e.prototype.setUserProfile@https://compcon.app/app.bundle.js:52:3875
u/</<@https://compcon.app/app.bundle.js:66:4662
s/</<@https://compcon.app/app.bundle.js:66:1292
s/<@https://compcon.app/app.bundle.js:66:1397
s/<@https://compcon.app/app.bundle.js:66:334
s@https://compcon.app/app.bundle.js:66:108
u@https://compcon.app/app.bundle.js:66:4493
f/</</<@https://compcon.app/app.bundle.js:233:478222
p.prototype.dispatch@https://compcon.app/app.bundle.js:239:1047
p/this.dispatch@https://compcon.app/app.bundle.js:233:475453
value/</</n[i]/</<@https://compcon.app/app.bundle.js:66:4035
s/</<@https://compcon.app/app.bundle.js:66:1292
s/<@https://compcon.app/app.bundle.js:66:1397
s/<@https://compcon.app/app.bundle.js:66:334
s@https://compcon.app/app.bundle.js:66:108
value/</</n[i]@https://compcon.app/app.bundle.js:66:3939
u</e.prototype.setAws/</<@https://compcon.app/app.bundle.js:52:4508
s/</<@https://compcon.app/app.bundle.js:37:2228
s/<@https://compcon.app/app.bundle.js:37:2333
a@https://compcon.app/app.bundle.js:37:1072
promise callback*l@https://compcon.app/app.bundle.js:37:1237
s/<@https://compcon.app/app.bundle.js:37:1248
s@https://compcon.app/app.bundle.js:37:1015
u</e.prototype.setAws@https://compcon.app/app.bundle.js:52:4154
u/</<@https://compcon.app/app.bundle.js:66:4662
s/</<@https://compcon.app/app.bundle.js:66:1292
s/<@https://compcon.app/app.bundle.js:66:1397
s/<@https://compcon.app/app.bundle.js:66:334
s@https://compcon.app/app.bundle.js:66:108
u@https://compcon.app/app.bundle.js:66:4493
f/</</<@https://compcon.app/app.bundle.js:233:478222
p.prototype.dispatch@https://compcon.app/app.bundle.js:239:1047
p/this.dispatch@https://compcon.app/app.bundle.js:233:475453
value/</</n[i]/</<@https://compcon.app/app.bundle.js:66:4035
s/</<@https://compcon.app/app.bundle.js:66:1292
s/<@https://compcon.app/app.bundle.js:66:1397
s/<@https://compcon.app/app.bundle.js:66:334
s@https://compcon.app/app.bundle.js:66:108
value/</</n[i]@https://compcon.app/app.bundle.js:66:3939
e.a/</</<@https://compcon.app/app.bundle.js:233:57454
promise callback*e.a/</<@https://compcon.app/app.bundle.js:233:57434
s/</<@https://compcon.app/app.bundle.js:37:2228
s/<@https://compcon.app/app.bundle.js:37:2333
a@https://compcon.app/app.bundle.js:37:1072
```<br>

**Comment by msprijatelj** [comment]
Bug accidentally introduced with #1751.  Workaround to get pilots to display and stop the error is to delete `pilot_groups.json` from Local Storage and refresh the page.  This can be done through the browser devtools, or by doing the following:
1. Ensure your data is sync'd to the cloud (and that you have a local backup)
2. Log out from your CompCon account
3. Delete all local compcon data
4. Log back into your CompCon account and perform a Cloud Load
