### ISSUE TITLE
[BUG] Railgun not getting range upgrades applied

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1783]
<strong>Submitted At: </strong> 12/10/2021 22:17:27<br><br><strong>Issue: </strong><br> I acquired the Neurolink Targeting core power, which gives ranged weapons +3 range. It applies to the Vulcan DMR that I have equipped, giving it a range of 18, but the Railgun I have equipped stays at the range of 20 when it should be 23. <br><br><strong>Massif Reference: </strong> 158<br>

**Comment by msprijatelj** [comment]
From page 64 of the Lancer Core Rulebook:

> Some mech FRAMES and systems grant increased RANGE. This does not affect the size of the area affected by CONE, LINE , BURST and BLAST attacks, although it does increase the RANGE of such attacks that have a listed range.

The "listed range" is referring to the range indicator for placing a burst/blast/cone/line (currently just blasts, for placing the center of the blast).  Line attacks are not eligible for range extension under the core rules, so CompCon is behaving as intended.
