### ISSUE TITLE
Feature Request: Mobile (android/apple) support

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#179]
<strong>Submitted At: </strong>5/21/2019 21:35:38
<strong>Feature: </strong>Mobile (android/apple) support
<strong>Details: </strong>I would more than happily pay a few bucks for the option to have comp/con on my phone/tablet. Understandable if it's beyond the scope/plan of the project though
<strong>Contact: </strong>

**Comment by aritsune** [comment]
Dupe of #300
