### ISSUE TITLE
[BUG] Pilot roster will not open. Error "length" cannot be defined

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1790]
<strong>Submitted At: </strong> 12/11/2021 19:30:02<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Tablet<br><br><strong>Issue Description: </strong><br> Attempting to open pilot roster gives "Error length not defined" after recently updating. No pilots appear in roster.<br><br><strong>Reproduction Steps:<br> </strong> Click on Pilot roster from main menu. <br><br><strong>Expected Result:<br> </strong> Click on Pilot roster, and be able to access pilot<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Duplicate of #1785
