### ISSUE TITLE
[BUG] Cloud save data loss

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1805]
<strong>Submitted At: </strong> 12/29/2021 21:28:14<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> I've had multiple instances of the cloud not saving when all auto-save options are enabled.
Once, I had multiple tabs on, and pilots did not save their LL level-ups but did save their downtime activity reserves they obtained.
The second time, I was using an incognito tab to test on another account and and closed it - mech changes were not saved.
The third and most important part: I created and edited 2 NPCs. I left my browser on for a long while, then closed it when I returned. When I got back into compcon, only 1 of the NPCs was there (the first I made) and it had none of the changes - just a default "New CARRIER".<br><br><strong>Reproduction Steps:<br> </strong> I know the first two instances (multiple tabs and incognito mode) are known to cause issues, but I have absolutely no idea why my NPC edits were not saved.
My only guess is that maybe cloud saves don't necessarily save when you edit an NPC. But I know for a fact I created an NPC after I already edited the Carrier Class one (save on NPC creation enabled), so I have no idea why the Carrier NPC didn't save its changes.<br><br><strong>Expected Result:<br> </strong> Expect compcon to save to cloud on enabled cloud save options, and also periodically to prevent data loss.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by jarena3** [comment]
this will be collected in, and addressed by, #1816
