### ISSUE TITLE
[BUG] Covering Fire not in active pilot page

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1807]
<strong>Submitted At: </strong> 12/31/2021 6:54:44<br><br><strong>Issue: </strong><br> The reaction for Covering Fire does not show up in the active sheet. It's really tedious to have to open up the game's rules for something quick which should 100% be on an abilities summary.<br><br><strong>Massif Reference: </strong> <br>

**Comment by msprijatelj** [comment]
Duplicate of #1808
