### ISSUE TITLE
[BUG] Covering Fire reaction not showing in active sheet

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1808]
<strong>Submitted At: </strong> 12/31/2021 6:56:21<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> The Covering Fire reaction does not show up in the active sheet, neither do any such as Overwatch (they do for NPCs but not players).<br><br><strong>Reproduction Steps:<br> </strong> It's very clear on active mission mode.<br><br><strong>Expected Result:<br> </strong> To be able to see all actions, reactions and other such abilities available to the pilot/mech without having to open up the book.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
As a Workaround: The "Reaction" for Heavy Gunner I's "Covering Fire" is described under the Quick Action for "Covering Fire". It looks like this was overlooked since the reaction wasn't in a proper "statblock" in the Core Book.
