### ISSUE TITLE
[BUG] Constant, Extreme Data Loss

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1812]
<strong>Submitted At: </strong> 1/2/2022 9:48:54<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Keep losing huge amounts of data and many hours of prep work due to poor saving features<br><br><strong>Reproduction Steps:<br> </strong> I don't know where to start, because I've been losing data over any reason.
I saved a backup, closed my app and later turned it back on. Several of my NPCs, encounters, missions, etc were missing because the autosave didn't work for hours, and neither did manual save (clicking the cloud icon). Fortunately, I backup very frequently now.
My backup is not only missing just as much information, but it actually somehow has 0 encounters.<br><br><strong>Expected Result:<br> </strong> Encounters, NPCs, etc to be saved when the app changes are saved. It's easily the most time consuming out of all things one can do in the app, and it's extremely frustrating to see it being functionally useless.<br><br><strong>Additional Context:<br> </strong> I had a second tab opened momentarily at one point to check the compendium while I worked, since you can't do both at the same time (which should also be a feature). I dont know how a second tab would do anything, but if it did, it should not.<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by jarena3** [comment]
this will be collected in, and addressed by, #1816
