### ISSUE TITLE
[FEATURE] Cloud Sync should be manual by default

### ISSUE THREAD

**Issue by Eldraen** [massif-press/compcon#1820]
**Is your feature request related to a problem? Please describe.**
Auto Sync being the default has lead to frustrating data loss where Compcon reverts back to a previous state without asking, which also applies to settings making it sometimes really hard to get out of Auto Sync as it Auto Syncs back to being enabled, we never tend to have these issues when we all switched to manual sync.

**Describe the solution you'd like**
I'd like it if Manual Sync was the default, with an option to manually sync elsewhere in compcon to compensate, making you able to sync while checking a pilot for example, or in the middle of an encounter, this would prevent a lot of frustration that comes with automation.

**Describe alternatives you've considered**
Making a double of the data where not everything is dictated by the cloud, and essentially have an option to revert to "cached" state and switch between what's saved on the cloud and what's saved locally instead of the cloud overwriting local data.

**Discord contact info**
Eld#7590

**Comment by jarena3** [comment]
this will be collected in, and addressed by, #1816
