### ISSUE TITLE
[BUG] Mobile cloud data sync

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1823]
<strong>Submitted At: </strong> 1/12/2022 16:50:20<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Phone<br><br><strong>Issue Description: </strong><br> I have imported new pilots and updated others on my computer (firefox browser on windows 10). When trying to sync on my phone, a list of changes appears bit quickly disappears, but nothing has changed. I am still missing characters and others haven't leveled up. Strangely, the first time I did, one new character did get added, but the others didn't update.<br><br><strong>Reproduction Steps:<br> </strong> Have a cloud saved pilot
sync on pc and phone
Modify or import on pc
Sync on pc
sync on phone: nothing<br><br><strong>Expected Result:<br> </strong> I expected my old characters to level up as I did on my computer, and the new ones to appear.<br><br><strong>Additional Context:<br> </strong> the new characters are copies of already present charzcters (with different names): I had the "master" copy of the characters but wanted my players to have it instead<br><br><br><strong>Stack Trace: </strong> No errors<br>

**Comment by jarena3** [comment]
Fixed in 2.3
