### ISSUE TITLE
[FEATURE] End Mission without adding mission data to the Pilot Combat Telemetry Record

### ISSUE THREAD

**Issue by mrashovrer** [massif-press/compcon#1825]
I've been messing around with my character outside of sessions to test out my build, but realized there is no way to get rid of the mission data for moves, damage dealt, enemies destroyed, etc. when exiting active mode with the end mission button, and exiting it simply by going back to the home screen keeps this data when active mode is next entered.

I would like if there was an option to exit active mode that discards any mission data, rather than adding it to the Pilot Combat Telemetry Record.

Alternatively, being able to manually edit the Pilot Combat Telemetry Record would also work for this issue, which would also be useful if someone wants to manually make rolls for attack and damage, but still wants to keep track of the mission data on comp/con.

**Comment by jarena3** [comment]
Added in 2.3.3
