### ISSUE TITLE
[BUG] Negative LLs possible

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1826]
<strong>Submitted At: </strong> 1/19/2022 12:18:53<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When clicking "Edit License Level", when at LL0, it is possible to reduce LL to negative values.<br><br><strong>Reproduction Steps:<br> </strong> 1. Create a new pilot.
2. Navigate to the new pilot's pilot sheet.  They should be LL0.
3. Click on the "Edit License Level" button next to "License Level" on the pilot sheet.
4. In the resulting dialog box, reduce the LL by 1 and click "Set Pilot Level".
5. Observe that the pilot is now registered with LL -1.
6. Repeat steps 3 and 4. Observe that this can drive a Pilot's LL lower and lower.<br><br><strong>Expected Result:<br> </strong> LL can go no lower than 0; the tick box that can edit LL can only cover the rules-legal levels of 0 to 12.<br><br><strong>Additional Context:<br> </strong> Instead of reducing the LL by 1, try to reduce by 2 or more. Click "Set Pilot Level". Observe that the LL resets to 0, as normally expected.

Beyond this, I'd recommend using a dropdown menu instead of an editable input box with upticking or downticking.  This would prevent any malformed inputs and more strongly define the legal license levels.<br><br><br> **Contact Info:**<br/>Valkyrion#6196<br>

**Comment by msprijatelj** [comment]
Example, going all the way to LL -10:
![image](https://user-images.githubusercontent.com/44978587/150191135-9ffdeb96-5e32-43e8-b62e-8392a3fffdad.png)

**Comment by msprijatelj** [comment]
Additional context: While in negative LL, if the LL is increased and then decreased, the LL resets to 0 again.

Honestly, using a fixed dropdown menu would probably save some headaches. From an aesthetic standpoint, it would also give an excuse to change the "current LL" display to use something other than a disabled input field so it looks cleaner, too.
