### ISSUE TITLE
[FEATURE] Reorder Systems on a Mech

### ISSUE THREAD

**Issue by ksteeves** [massif-press/compcon#1828]
**Is your feature request related to a problem? Please describe.**
For a system-focused player the order of the systems on a mech can be important to taking one's turn's quickly. However, currently systems can not be reordered, they must be removed and added in the correct order.

**Describe the solution you'd like**
**Being able to reorder systems without removing them.** Click and holding to drag them up and down would be nice and clean, but other methods would be fine.

**Describe alternatives you've considered**
Removing and adding the systems in the correct order is the current solution, but it is frustrating, requires memory, and is not easily changeable.

**Additional context**
I understand this is a QOL improvement, so it is probably pretty low-priority, but an update addressing multiple QOL issues would go a long way in improving the UX for comp/con.

**Comment by msprijatelj** [comment]
This could probably be addressed with `vue-draggable` like we've done with the Pilot Roster, though it should be easier to accomplish since there's no "system groups" to complicate the matter.

**Comment by super-salad** [comment]
I have changes started for this. Simply being able to rearrange the system tiles is straightforward, but when working on persisting that order, I encountered Issue #1989.  I'm going to wait and see what changes come out of that before going much further, since it will probably change what I have so far.

**Comment by msprijatelj** [comment]
> I have changes started for this. Simply being able to rearrange the system tiles is straightforward, but when working on persisting that order, I encountered Issue #1989. I'm going to wait and see what changes come out of that before going much further, since it will probably change what I have so far.

@super-salad Feel free to open a Draft PR or otherwise save your code to GitHub. I have a feeling that your changes won’t be affected much, just that any “save” call you make will be using a different method in the future
