### ISSUE TITLE
[BUG] Text crawl error on home page

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1829]
<strong>Submitted At: </strong> 1/22/2022 19:45:55<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When navigating to the main menu with the HORUS Terminal theme enabled, the text crawl on the right side of the screen does not play and "ERROR:   n(...).split is not a function" is shown. This does not occur on the GMS or MSMC themes, only the HORUS one. Clearing the browser cache and reloading did not fix the issue.<br><br><strong>Reproduction Steps:<br> </strong> With the HORUS Terminal theme enabled, navigate to the main menu from a different page.<br><br><strong>Expected Result:<br> </strong> Expected the "chat room" text crawl to play as normal.<br><br><strong>Additional Context:<br> </strong> This occurred after the newest update (I believe v3.0.36 but the version number is empty, which I'm aware is a known issue)<br><br><br><strong>Stack Trace: </strong> ```
Vue error at [ee]
TypeError: n(...).split is not a function
    at ht (https://compcon.app/js/app.2315ade6.js:1:251115)
    at pt (https://compcon.app/js/app.2315ade6.js:1:252416)
    at a.mounted (https://compcon.app/js/app.2315ade6.js:1:254318)```<br>

**Comment by heckinahandbag** [comment]
Also experiencing this on Firefox and Edge
