### ISSUE TITLE
[BUG] Pilot Profile picture rendering incorrectly (v3.0.36)

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1830]
<strong>Submitted At: </strong> 1/22/2022 19:51:51<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> After the update, pilot profile images have been erroneously displaying the imgur URL they are hosted at above the picture itself, displacing the picture downward outside of the ui space dedicated to them.<br><br><strong>Reproduction Steps:<br> </strong> Upload a picture to the pilot profile using the Set Pilot Portrait feature.<br><br><strong>Expected Result:<br> </strong> The URL should not be visible and the picture should not break out of its frame.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by lenaleciel** [comment]
![image](https://user-images.githubusercontent.com/49732719/150661517-db180a8c-7af9-442f-9704-850dc2cdf08b.png)
Example shown here.

**Comment by lenaleciel** [comment]
Never mind, it just fixed itself somehow.

**Comment by lenaleciel** [comment]
I'm not, I'm on the compcon.app page.

The problem initially showed up when I went to options and hit the download updates and force reload, which caused it to update to the version with the missing version number. However, for whatever reason, when I close the tab and open Comp/Con again, it displays 2.2.35 as a version number, and the issue goes away.

If I go back and hit the download updates and force reload button again, it goes back to the missing number version, which does have the error and a similiar error involving talents that someone else posted here #1835, but closing the tab and opening the page again, or even just reloading the page reverts it to 2.2.35 again.

**Comment by jarena3** [comment]
ah, I think I found the issue, fix incoming shortly
