### ISSUE TITLE
[BUG] Berserker NPC text typo

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1834]
<strong>Submitted At: </strong> 1/23/2022 17:29:38<br><br><strong>Source: </strong> LANCER Core Book<br><br><strong>Incorrect Text/Data: </strong><br> Berserker mechs are built to take advantage of advanced heat-cycling systems that allow them to shunt heat - as it is generated - into pure offensive force, increasing their weapon output by orders of magnitude. The archetype, best-known for its use by Gen’Dal Merlos’s Knights of Imminent Destruction, is preferred by pure combat-focus organizations, PMCs, and deniable-asset corps in established states.Tactics
Berserkers are excellent melee duelists that are very scary up close. Their potential is greatest when they are as close to enemy forces as possible. Due to their terrible Heat Cap and E-Defense, Berserkers are vulnerable to tech attacks. Savvy opponents will use Aggression to their own advantage, turning Berserkers against their allies, so it’s best to keep them away from friendly forces.<br><br><strong>Correct Text/Data: </strong><br> I can't format the correct version of the text correctly here; essentially, the "Tactics" at the end of the first paragraph has been erroneously inserted into the flavor description instead of being the beginning of a separately-formatted "Tactics" section, as with other NPCs.<br>

**Comment by msprijatelj** [comment]
Duplicate of #1050 . Already fixed on the NPC Data repo; awaiting a new release on Itch.io.
