### ISSUE TITLE
[BUG] Changing Pilot Weapon damage or description doesn't update immediately

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1840]
<strong>Submitted At: </strong> 1/27/2022 21:10:39<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When trying to rename a pilot weapon (Medium A/C), clicking save after typing the name doesn't update the name<br><br><strong>Reproduction Steps:<br> </strong> click gear on a pilot weapon, rename and type in a name, hit save. bug might only happen if you have just renamed a weapon on a different slot <br><br><strong>Expected Result:<br> </strong> name should update to the name you typed, when you click save<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
I can reproduce this.  Seems to occur when a pilot weapon has just been equipped.  The name does not dynamically update until AFTER you navigate away from the page.  May be a similar fix as #1578 ?

**Comment by msprijatelj** [comment]
Okay, I can rename a piece of pilot equipment (armor, weapon, or gear) and have it immediately update and stick around after navigating away and back to the page.  However, weapon damage does not immediately update, nor does Pilot Gear description, though once some other update occurs on the page, they populate correctly.  Keeping this one open for now, with a modified title.
