### ISSUE TITLE
[BUG] Sentinel Drone Description Typo

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1855]
<strong>Submitted At: </strong> 2/14/2022 17:39:48<br><br><strong>Source: </strong> LANCER Core Book<br><br><strong>Incorrect Text/Data: </strong><br> The sentinel drone drone can be deployed to any free space within Sensors and line of sight,<br><br><strong>Correct Text/Data: </strong><br> The sentinel drone can be deployed to any free space within Sensors and line of sight,<br>

**Comment by msprijatelj** [comment]
Seems to be a typo within the Core Book itself; fixed it in the lancer-data repo and reported it in https://github.com/AshleyMoni/Lancer-Community-Edition/issues/953.
