### ISSUE TITLE
[BUG] Cloud Save

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1856]
<strong>Submitted At: </strong> 2/16/2022 12:45:58<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> NPC, Encounter, and Mission data is not syncing correctly with the Cloud. Often scrubs data, only saves one NPC, Encounter, and Mission at a time.<br><br><strong>Reproduction Steps:<br> </strong> Create NPC, Encounter, Mission or all three, click to sync with the cloud, then close the browser so that all cookies and personal data will clear out automatically. Then reopen the Comp/Con site, log in, and check your NPC, Encounter, Mission section.<br><br><strong>Expected Result:<br> </strong> All the information how I left it.<br><br><strong>Additional Context:<br> </strong> I'm getting a UI Split error, but I don't know if that's related or not.<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
The “split” error has been occurring with the Horus theme, so I’m inclined to think it’s unrelated to the rest of this report.

**Comment by jarena3** [comment]
Fixed in 2.3
