### ISSUE TITLE
[BUG] Backgrounds - Not Humnized - text is poping up

### ISSUE THREAD

**Issue by NHPSHAKA** [massif-press/compcon#1857]
So i'm not sure why but when i load up the .lcp into C/C it shows the following. It's not preventing me from uploading the .lcp i'm just curious why it pops up. may be a bug. 

![image](https://user-images.githubusercontent.com/99981551/154714817-87099125-e5e6-44f6-8aed-00a6c3a68698.png)

**Comment by msprijatelj** [comment]
@NHPSHAKA This does look like a bug; when I check the code, it looks like Backgrounds may have been omitted from the expected Pack Info.  Are the backgrounds still loading into CompCon?
