### ISSUE TITLE
Bug Report: SCYLLA NHP system lists incorrect Heat damage value upon printing.

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#186]
<strong>Submitted At: </strong>5/25/2019 16:12:33
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Minor/Cosmetic (styling errors, misspellings, etc)
<strong>Issue Description: </strong>SCYLLA NHP system lists incorrect Heat damage value upon printing.
<strong>Reproduction Steps: </strong>Create a mech with the Gorgon's SCYLLA system installed and print the char sheet as if to PDF.  In software, Heat (self) damage is listed as 2 while printed version lists as 3.
<strong>Contact Info: </strong>

**Comment by patglavin** [comment]
I'm not sure I'm able to reproduce this, both my printed and in-app character sheets list the Heat (self) damage as 2.
