### ISSUE TITLE
[BUG] MSMC Alternate Text Scroll Doesn't Work On Initial Load

### ISSUE THREAD

**Issue by KaiTave** [massif-press/compcon#1861]
**Describe the bug**
When a user's theme is set to something else aside from GMS Red, for example MSMC Solarized, the alternate text scroll that's been set up for that theme will not load at first. Upon moving to a different tab within Comp/Con such as Compendium and then returning to the home page, the alternate text will then load.

**To Reproduce**
1. Go to Options and set your theme to MSMC Solarized (presumably this would also work with the HORUS chat style text, but that's currently suffering a bug of its own and won't load regardless, so for this purpose I'm using MSMC).
2. Open a fresh Comp/Con tab or reload, observe the opening text is the same as the default GMS Red text.
3. Tab to Compendium or some other page, then return to the home screen.
4. The text should now be loading appropriately to the theme.

**Expected behavior**
Presumably, if a user has selected an alternate theme then all components of that theme should load upon an initial startup of Comp/Con.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 97.0

**Comment by jarena3** [comment]
Fixed in 2.3
