### ISSUE TITLE
[BUG] Make Verification Link Visible by default

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1864]
<strong>Submitted At: </strong> 2/19/2022 21:35:46<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Phone<br><br><strong>Issue Description: </strong><br> Saying i have a account butbi never finished making it and it wont let me use my email for making a account<br><br><strong>Reproduction Steps:<br> </strong> I wrote down all my info to make a login and i closed the app to get the code i needed and my email wont work anymore.<br><br><strong>Expected Result:<br> </strong> To make a account <br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
If you start typing into the email form, a “Have a verification code?” Clickable message will show up underneath it. Click that and you can enter your verification code to finish account creation.

**Comment by msprijatelj** [comment]
I’m modifying this issue to instead focus on making the “Have a validation code?” Link permanently visible, and maybe making the both it and the “forgot password” links a little more prominent.
