### ISSUE TITLE
[BUG] Incorrect iOS home screen icon & text

### ISSUE THREAD

**Issue by wilt00** [massif-press/compcon#1866]
**Issue Description:**
When saving COMP/CON as a PWA shortcut to the iOS home screen, the title of the page shows up as "compcon" rather than "COMP/CON", and the icon is a screenshot of the page, rather than the intended icon.

I will be posting a PR to fix this momentarily.

**To Reproduce**
1. Open compcon.app in iOS Safari
2. Tap the 'Share' icon at the bottom of the screen
3. Select 'Add to Home Screen'

**Expected behavior**
Text should be "COMP/CON", icon should be COMP/CON logo on white background (Note that unlike Android, transparency is not supported in home screen icons on iOS)

**Screenshots**
<img src="https://user-images.githubusercontent.com/7883508/155070189-6a85766f-1fc4-414f-9c72-5ab1166985dd.PNG" width=250 />

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 15.3.1
 - Browser: Safari

**Comment by msprijatelj** [comment]
Closed by #1867
