### ISSUE TITLE
[BUG] iOS home indicator overlaps footer buttons

### ISSUE THREAD

**Issue by wilt00** [massif-press/compcon#1868]
**Describe the bug**
When installed as a PWA on iOS, the iOS home indicator bar overlaps the footer buttons, decreasing the effective touch target size and increasing the likelihood of misclicks.

I have a PR to fix this that I'll be posting later today.

**To Reproduce**
1. Save app to iOS home screen
2. Open & observe

**Expected behavior**
Additional padding should be applied to the footer such that the footer buttons are not obscured by the home indicator

**Screenshots**

<img src="https://user-images.githubusercontent.com/7883508/155225756-4913d464-784a-4fe0-a49c-35b3bc5dff1b.PNG" width=250 />

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 15.3.1
 - Browser: Safari

**Additional context**

**Comment by msprijatelj** [comment]
Closed by #1869
