### ISSUE TITLE
[BUG] 5+3=53

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1871]
<strong>Submitted At: </strong> 3/1/2022 16:29:29<br><br><strong>Source: </strong> LANCER Core Book<br><br><strong>Incorrect Text/Data: </strong><br> The auto cannon has a range of 5 but when a license buff is applied which is supposed to give it +3range it gives it 53<br><br><strong>Correct Text/Data: </strong><br> 8<br>

**Comment by msprijatelj** [comment]
This looks like it may be an issue with how the Range is stored for the Auto Cannon; it should be a number, not a String. It may be good to control for that in the broader app too, though
