### ISSUE TITLE
[BUG] e.profile.GetView is not a function

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1872]
<strong>Submitted At: </strong> 3/4/2022 15:38:01<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Can't pull up NPC profiles<br><br><strong>Reproduction Steps:<br> </strong> unknown. Loaded a Backup and problem occurred. Unsure if present before backup<br><br><strong>Expected Result:<br> </strong> pulls up an NPC profile in the NPC Encounter Toolkit<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ```
Vue error at [ee]
get@https://compcon.app/js/app.34c35e74.js:1:1869186
2b0e/</rr.prototype.get@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30788
2b0e/</rr.prototype.evaluate@https://compcon.app/js/chunk-vendors.e01a280c.js:7:31777
2b0e/</fr/<@https://compcon.app/js/chunk-vendors.e01a280c.js:7:33470
o@https://compcon.app/js/app.34c35e74.js:1:1867479
2b0e/</wn/e.prototype._render@https://compcon.app/js/chunk-vendors.e01a280c.js:7:23862
r@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27903
2b0e/</rr.prototype.get@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30788
rr@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30706
Ln@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27917
2b0e/</Ar.prototype.$mount@https://compcon.app/js/chunk-vendors.e01a280c.js:7:66038
init@https://compcon.app/js/chunk-vendors.e01a280c.js:7:20676
p@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44578
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44207
b@https://compcon.app/js/chunk-vendors.e01a280c.js:7:45193
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44322
b@https://compcon.app/js/chunk-vendors.e01a280c.js:7:45193
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44322
2b0e/</Ri/<@https://compcon.app/js/chunk-vendors.e01a280c.js:7:48688
2b0e/</Pn/e.prototype._update@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27087
r@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27893
2b0e/</rr.prototype.get@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30788
rr@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30706
Ln@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27917
2b0e/</Ar.prototype.$mount@https://compcon.app/js/chunk-vendors.e01a280c.js:7:66038
init@https://compcon.app/js/chunk-vendors.e01a280c.js:7:20676
p@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44578
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44207
2b0e/</Ri/<@https://compcon.app/js/chunk-vendors.e01a280c.js:7:48688
2b0e/</Pn/e.prototype._update@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27087
r@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27893
2b0e/</rr.prototype.get@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30788
rr@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30706
Ln@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27917
2b0e/</Ar.prototype.$mount@https://compcon.app/js/chunk-vendors.e01a280c.js:7:66038
init@https://compcon.app/js/chunk-vendors.e01a280c.js:7:20676
p@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44578
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44207
b@https://compcon.app/js/chunk-vendors.e01a280c.js:7:45193
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44322
b@https://compcon.app/js/chunk-vendors.e01a280c.js:7:45193
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44322
2b0e/</Ri/<@https://compcon.app/js/chunk-vendors.e01a280c.js:7:48688
2b0e/</Pn/e.prototype._update@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27087
r@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27893
2b0e/</rr.prototype.get@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30788
rr@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30706
Ln@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27917
2b0e/</Ar.prototype.$mount@https://compcon.app/js/chunk-vendors.e01a280c.js:7:66038
init@https://compcon.app/js/chunk-vendors.e01a280c.js:7:20676
p@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44578
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44207
b@https://compcon.app/js/chunk-vendors.e01a280c.js:7:45193
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44322
2b0e/</Ri/<@https://compcon.app/js/chunk-vendors.e01a280c.js:7:48688
2b0e/</Pn/e.prototype._update@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27087
r@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27893
2b0e/</rr.prototype.get@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30788
rr@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30706
Ln@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27917
2b0e/</Ar.prototype.$mount@https://compcon.app/js/chunk-vendors.e01a280c.js:7:66038
init@https://compcon.app/js/chunk-vendors.e01a280c.js:7:20676
p@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44578
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44207
2b0e/</Ri/<@https://compcon.app/js/chunk-vendors.e01a280c.js:7:48688
2b0e/</Pn/e.prototype._update@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27087
r@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27893
2b0e/</rr.prototype.get@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30788
rr@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30706
Ln@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27917
2b0e/</Ar.prototype.$mount@https://compcon.app/js/chunk-vendors.e01a280c.js:7:66038
init@https://compcon.app/js/chunk-vendors.e01a280c.js:7:20676
p@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44578
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44207
b@https://compcon.app/js/chunk-vendors.e01a280c.js:7:45193
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44322
b@https://compcon.app/js/chunk-vendors.e01a280c.js:7:45193
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44322
2b0e/</Ri/<@https://compcon.app/js/chunk-vendors.e01a280c.js:7:48688
2b0e/</Pn/e.prototype._update@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27087
r@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27893
2b0e/</rr.prototype.get@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30788
rr@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30706
Ln@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27917
2b0e/</Ar.prototype.$mount@https://compcon.app/js/chunk-vendors.e01a280c.js:7:66038
init@https://compcon.app/js/chunk-vendors.e01a280c.js:7:20676
p@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44578
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44207
b@https://compcon.app/js/chunk-vendors.e01a280c.js:7:45193
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44322
2b0e/</Ri/<@https://compcon.app/js/chunk-vendors.e01a280c.js:7:48688
2b0e/</Pn/e.prototype._update@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27087
r@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27893
2b0e/</rr.prototype.get@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30788
rr@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30706
Ln@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27917
2b0e/</Ar.prototype.$mount@https://compcon.app/js/chunk-vendors.e01a280c.js:7:66038
init@https://compcon.app/js/chunk-vendors.e01a280c.js:7:20676
p@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44578
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44207
b@https://compcon.app/js/chunk-vendors.e01a280c.js:7:45193
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44322
2b0e/</Ri/<@https://compcon.app/js/chunk-vendors.e01a280c.js:7:48688
2b0e/</Pn/e.prototype._update@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27087
r@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27893
2b0e/</rr.prototype.get@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30788
rr@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30706
Ln@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27917
2b0e/</Ar.prototype.$mount@https://compcon.app/js/chunk-vendors.e01a280c.js:7:66038
init@https://compcon.app/js/chunk-vendors.e01a280c.js:7:20676
p@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44578
f@https://compcon.app/js/chunk-vendors.e01a280c.js:7:44207
x@https://compcon.app/js/chunk-vendors.e01a280c.js:7:46808
T@https://compcon.app/js/chunk-vendors.e01a280c.js:7:47595
2b0e/</Ri/<@https://compcon.app/js/chunk-vendors.e01a280c.js:7:48736
2b0e/</Pn/e.prototype._update@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27070
r@https://compcon.app/js/chunk-vendors.e01a280c.js:7:27893
2b0e/</rr.prototype.get@https://compcon.app/js/chunk-vendors.e01a280c.js:7:30788
2b0e/</rr.prototype.run@https://compcon.app/js/chunk-vendors.e01a280c.js:7:31521
Zn@https://compcon.app/js/chunk-vendors.e01a280c.js:7:29728
2b0e/</mt/<@https://compcon.app/js/chunk-vendors.e01a280c.js:7:12771
ut@https://compcon.app/js/chunk-vendors.e01a280c.js:7:12166
```<br>

**Comment by Aruin1** [comment]
I had a similar issue on Opera disabling the inbuilt adblocker seemed to fix the issue

**Comment by msprijatelj** [comment]
There was an issue with the load balancer on the backend; Beef has handled the issue and it should be working properly again.
