### ISSUE TITLE
[BUG] Heavy Melee Weapon display Duelist talent diamond

### ISSUE THREAD

**Issue by Wisedukk** [massif-press/compcon#1873]
**Describe the bug**
On a LL7 Balor frame, Heavy Melee Weapon displays the Duelist 1 diamond "indicator" underneath the weapon.

**To Reproduce**
1. Go to 'Talents' in Tactical Profile
2. Click on 'Talents'
3. Scroll down to 'Duelist'
4. Choose Duelist 3.
5.  Exit Talents.
6. access Balor Frame mech
7. Equip Heavy Melee, or Superheavy Melee.
   (Seen this with D/D 288, Nanobot Whip, Nanocarbon Sword, at least)
8. see the first/leftmost Talent diamond under the weapon show as Unstoppable.

**Expected behavior**
Unstoppable should not display for Heavy Weapons, or Superheavy Weapon.

**Screenshots**
<img width="1324" alt="Screen Shot 2022-03-05 at 8 35 38 AM" src="https://user-images.githubusercontent.com/101007565/156888502-6c9b28e5-2ef5-4fa6-bafe-3b4c591eb10f.png">

**Desktop (please complete the following information):**
 - OS: 10.14.16 Mac OS
 - Browser Chrome Version 98.0.4758.109

**Comment by msprijatelj** [comment]
This is is working as expected; Unstoppable is not limited to Main Melee weapons. Please see page 93 of the Lancer core book.
