### ISSUE TITLE
[BUG] Lich, errata changes.

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1874]
<strong>Submitted At: </strong> 3/6/2022 0:12:04<br><br><strong>Source: </strong> The Long Rim<br><br><strong>Incorrect Text/Data: </strong><br> 1. Wandering Nightmare lacks Unique Tag

2. Chronostutter:

    The character taking the action is pushed up to 3 spaces in a direction of your choice, even if they have IMMUNITY to involuntary movement<br><br><strong>Correct Text/Data: </strong><br> The target of the action action is pushed up to 3 spaces in a direction of your choice, even if they have IMMUNITY to involuntary movement<br>

**Comment by msprijatelj** [comment]
Lich Errata link: https://lancer-faq.netlify.app/#5782e0

@jarena3 What’s Comp/Con’s policy when it comes to errata? Follow the errata or stick to the published books?

**Comment by jarena3** [comment]
We're sticking with the book to the extent possible. Tom has talked about an update at which time we'd pull these in. Barring that, a future feature could include eg. errata tooltips. Closing this for now.
