### ISSUE TITLE
[BUG] Integrated Latch Drone disappears when equipping External Batteries

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1875]
<strong>Submitted At: </strong> 3/6/2022 14:27:32<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> In Mech Configuration view, when equipping the External Batteries system on a Lancaster, an error message saying "Cannot read properties of undefined (reading 'map')" shows, and the integrated Latch Drone mount vanishes, though the integrated mount container is still visible.
This does not break scripts otherwise, and the sheet still operates as normal, but refreshing or hard-refreshing always results in the same error message immediately, with the same missing Latch Drone issue.
Removing the system, then refreshing the page alleviates the issue.<br><br><strong>Reproduction Steps:<br> </strong> Create a new Lancaster mech, then, in the Mech Configuration view, equip the Tokugawa's External Batteries to that Lancaster.<br><br><strong>Expected Result:<br> </strong> Latch Drone doesn't seem to mechanically (at least as far as the book is concerned) interact with External Batteries, one would not expect the system being equipped to do anything to it, successfully or not.<br><br><strong>Additional Context:<br> </strong> I *do* have several sets of homebrew LCP, some on the community LCP and several of my own, but this error happens even when nothing but the External Batteries are equipped on a Lancaster.
I switched to Edge, cleared it's cache for paranoia's sake, then created a profile that had absolutely no character progression applied, and the error still happens when creating a Lancaster and equipping it as described above.<br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
TypeError: Cannot read properties of undefined (reading 'map')
    at e.get (https://compcon.app/app.bundle.js:66:64204)
    at https://compcon.app/app.bundle.js:66:24985
    at Array.some (<anonymous>)
    at https://compcon.app/app.bundle.js:66:24958
    at Array.forEach (<anonymous>)
    at https://compcon.app/app.bundle.js:66:24740
    at Array.forEach (<anonymous>)
    at Function.t.CalculateRange (https://compcon.app/app.bundle.js:66:24705)
    at a.getRange (https://compcon.app/app.bundle.js:233:337168)
    at un.get (https://compcon.app/app.bundle.js:22:26610)```<br>

**Comment by msprijatelj** [comment]
I’m betting that this is because Latch Drone completely lacks a “damage” field. https://github.com/massif-press/lancer-data/blob/master/lib/weapons.json#L2251

Gravity Gun, another no-damage weapon, has a damage field, but it’s an empty array. https://github.com/massif-press/lancer-data/blob/master/lib/weapons.json#L1863

I would recommend testing if this error also occurs on the Gravity Gun; if it doesn’t, I’d say the recommended fix is to add a similar empty array as Latch Drone’s damage.
