### ISSUE TITLE
[BUG] Cannibal perhaps not tagged correctly

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1877]
<strong>Submitted At: </strong> 3/13/2022 13:22:56<br><br><strong>Source: </strong> The Long Rim<br><br><strong>Incorrect Text/Data: </strong><br> On the Mech Weapons page, if you filter using the Loading tag, the Cannibal does not appear in the list of displayed weapons. Though the weapon entry itself does correctly state it's a Loading weapon. <br><br><strong>Correct Text/Data: </strong><br> <br>

**Comment by msprijatelj** [comment]
This is likely because the “loading” tag for the Cannibal is outside of a Weapon Profile. It may be worthwhile to change how compcon handles tags outside of weapon profiles so that those tags are treated as part of the profile for filtering/display purposes.

**Comment by msprijatelj** [comment]
The "quick fix" for this would be to move the "Loading" tag on the Cannibal into both of its profiles, though then an update would need released to itch.io.  I'm inclined to look into a more robust fix like the one I mentioned previously, so we can keep LCPs DRY.

**Comment by msprijatelj** [comment]
Closed by https://github.com/massif-press/compcon/commit/ca874d43fff2905a6e43f313c19b0162e3730144
