### ISSUE TITLE
[BUG] Compcon not updating to newest version

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1878]
<strong>Submitted At: </strong> 3/13/2022 13:57:47<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Will not update past the 2.2.35 version.<br><br><strong>Reproduction Steps:<br> </strong> Have reloaded the page, signed out and back in and tried multiple times to update with no effect.<br><br><strong>Expected Result:<br> </strong> Should have it update to the latest version 2.2.37 by hitting the update button.<br><br><strong>Additional Context:<br> </strong> user id is 44d70cfb-836d-47af-a453-6935b4f00da9<br><br><br><strong>Stack Trace: </strong> No error log available<br>

**Comment by msprijatelj** [comment]
Likely need to delete the old Service Manager in order to update to the newest version. This can be done through developer tools or by performing a hard reset of CompCon’s website data (combined with a backup beforehand, likely).

**Comment by jarena3** [comment]
Missed a commit that re-enables the update checker and an app-initiated reload, so this one should be good
