### ISSUE TITLE
[FEATURE] Dedicated Share Pilot Data Tab

### ISSUE THREAD

**Issue by Icosacube** [massif-press/compcon#1879]
**Is your feature request related to a problem? Please describe.**
Now that COMP/CON has Foundry integration, it is all the more necessary that players can intuit how to share their pilot and mech data. However, at present, these options are tucked away in small menus.

While this may not be an issue for experienced users, new users will often ask how to share a vault code or export a statblock. As this is a common inquiry among new users, this may be an issue worth investigating.

**Describe the solution you'd like**
A large, obvious Share Data tab on the pilot view screen, with the vault code in plain sight. The depreciated download codes may or may not be present. The tab may or may not also feature the mech statblock, to reduce the number of screens required to share one's build.

**Describe alternatives you've considered**
- A Share Data button on the Dossier tab of the pilot view screen that brings up a dialog box with the codes.

**Comment by jarena3** [comment]
This is a good idea -- as part of the cloud service overhaul I'm working on now I'm going to greatly simplify the share process, and having this as a front-and-center feature makes more sense than keeping it in a menu

**Comment by jarena3** [comment]
Added (a share code tool available in the pilot tab bar) in 2.3
