### ISSUE TITLE
[BUG] One weapon from some downloadable content cant be used in a mount

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1880]
<strong>Submitted At: </strong> 3/15/2022 13:48:57<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Phone<br><br><strong>Issue Description: </strong><br> the flair gun from the HandD customs cant be equiped into a mount<br><br><strong>Reproduction Steps:<br> </strong> unlock the level 1 license for it and it cant be used<br><br><strong>Expected Result:<br> </strong> it should be in the list of weapons<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
This sounds like an issue with Third-Party content and should probably be addressed by the original author.
