### ISSUE TITLE
[FEATURE]Generate Statblock Revision

### ISSUE THREAD

**Issue by Ferrin33** [massif-press/compcon#1887]
The primary use of the "Generate Statblock" feature is to copy-paste mech builds. Rarely is it used to also have the other pilot information. To newer players the "Compact build" checkmark isn't immediately obvious either.

After a little bit of back and forth on the Lancer discord this is what we came up with to make it a more user-friendly and require less clicks in general for the most common feature, as well as add clarity.

Generate Statblock feature change request:
- Change default to a compact view of the Active Mech in the mech hangar.
- Checkmark to include Pilot statblock, effectively the opposite of compact view.
- To only get the pilot statblock people could deselect the mech and check the pilot statblock checkmark.
- Change formatting slightly so that pilot and mech statblocks are no longer interwoven if both are included.

**Comment by karidyas** [comment]
taking a look at this :)

**Comment by msprijatelj** [comment]
Closed by #1983
