### ISSUE TITLE
Bug Report: Fuel Rod Gun is not affected by Neuro-linked Targeting when it should be

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#189]
<strong>Submitted At: </strong>5/29/2019 20:56:34
<strong>Platform: </strong>OSX
<strong>Severity: </strong>High (problem that impairs software function, bad or missing game mechanic implementation)
<strong>Issue Description: </strong>Fuel Rod Gun is not affected by Neuro-linked Targeting when it should be
<strong>Reproduction Steps: </strong>Having both Fuel Rod Gun and Neuro-Linked Targeting on at the same time
<strong>Contact Info: </strong>Radio Protector

**Comment by aritsune** [comment]
fixed in #245
