### ISSUE TITLE
[BUG] GM Mode Crash when searching for an optional while "unlocked" from class/templates

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1893]
<strong>Submitted At: </strong> 4/5/2022 10:13:12<br><br><strong>Browser: </strong> Vivaldi (Chromium based still as far as I'm aware)<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> As title says. Attempted to search for an optional in "unlocked mode" (specifically Archer's "Got Your Back" reaction as it wasn't on after I had given it "Covering Fire" and wasn't in the initial list).
Compcon then completely locks up, preventing me from closing the search, moving anything or otherwise going to the main menu.<br><br><strong>Reproduction Steps:<br> </strong> As above as far as I'm aware unless this is a CC data specific issue as I've reported a memory leak previously and it could be some very old code causing consistent performance issues with misc crashes.<br><br><strong>Expected Result:<br> </strong> 1. To initially find the reaction in the list of archer optionals
2. For compcon to not crash when I attempt to search the unfiltered list of optionals across all NPCs<br><br><strong>Additional Context:<br> </strong> The Reaction in question I was looking for has only gone missing after the LCP has been updated to 1.0.5, so I can only assume something went wrong in there unless this is reproducible with 1.0.4.<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Collecting this in #1375
