### ISSUE TITLE
[BUG] Empath Frequency Error (Encounter/Scene)

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1894]
<strong>Submitted At: </strong> 4/5/2022 15:03:38<br><br><strong>Source: </strong> No Room for a Wallflower<br><br><strong>Incorrect Text/Data: </strong><br> Ranks I and III of the Empath talent, in the specially formatted boxes for the granted Reaction and Quick Action are referred as being "1/Encounter" while the proper wording for this would be "1/Scene" as present in the talent text body itself.<br><br><strong>Correct Text/Data: </strong><br> <br>

**Comment by lenaleciel** [comment]
Sorry for having to put in an issue for this rather than fixing it myself, I don't have access to that particular repository.

**Comment by msprijatelj** [comment]
The Wallflower side of things is fine; this is an issue with how CompCon internally refers to "1/scene" vs "1/encounter" durations.  Change pushed.
