### ISSUE TITLE
[BUG] I have tried to create an account but it is not recognizing my verification code and wont let me get a new one sent.

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1898]
<strong>Submitted At: </strong> 4/7/2022 11:56:16<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Created an account but the verification code will not work, nothing happens when I click to resend (to get another sent out)<br><br><strong>Reproduction Steps:<br> </strong> I created an account with my email address on my phone, chose my password then moved to my email inbox in the next tab to get the code, when I came back to enter it the webpage reloaded, the code wouldn't be accepted and then when I tried to have another sent nothing happens.<br><br><strong>Expected Result:<br> </strong> Another code to be sent to my email address so I could verify my account and begin using Comp/Con.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by jarena3** [comment]
can't do much about this, hopefully this person gets at me on Discord or twitter or something
