### ISSUE TITLE
[BUG] HA plasma talons are listed in the same way as GMS systems when searching for mech weapons instead of being hidden during search like other integrated core weapons

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1901]
<strong>Submitted At: </strong> 4/12/2022 13:11:46<br><br><strong>Source: </strong> No Room for a Wallflower<br><br><strong>Incorrect Text/Data: </strong><br> HA plasma talons available at LL0<br><br><strong>Correct Text/Data: </strong><br> HA plasma talons are core integrated equipment<br>

**Comment by jarena3** [comment]
Seems to be an old version of the NRFAW data
