### ISSUE TITLE
[BUG] Unable to add Mech Loacout

### ISSUE THREAD

**Issue by msprijatelj** [massif-press/compcon#1903]
**Describe the bug**
An error is received when attempting to add a new Mech Loadout, whether via Adding it or Cloning it.

**To Reproduce**
1. Create a new pilot and give it a mech.
2. Click on the 3-line button to the left of the loadout's name and click "Add New Loadout"
3. See that the error "e.mech.AddLoadout is not a function" pops up.
4. Attempt to click the "Clone loadout" button on the right end of the loadout header
5. See that the error "e.mech.CloneLoadout is not a function" pops up.

**Expected behavior**
Selecting "Add New Loadout" and/or "Clone Loadout" will successfully create a new loadout for the mech to use.

**Desktop (please complete the following information):**
 - OS: Windows
 - Firefox
 - CompCon Version 2.3.0a

**Additional Context**
This may be an overlooked part of the "save controller" setup introduced in v2.3's cloud update.

**Comment by jarena3** [comment]
fixed in 2.3.0b
