### ISSUE TITLE
[BUG] Core Bonuses math adding to the wrong places

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1913]
<strong>Submitted At: </strong> 4/13/2022 14:19:24<br><br><strong>Issue: </strong><br> Some core bonuses such as Superior by Design, Subjectivity Sync, and Intergrated Ammo Feeds will add flat bonuses to resources, however when hovering over certain stats, they will add onto stats they are not supposed to. For examples, Superior by Design, Subjectivity Sync, and Integrated Ammo feeds will add their bonuses to health making it bigger than it should be<br><br><strong>Massif Reference: </strong> <br>

**Comment by msprijatelj** [comment]
This looks like bonuses may be applied in a blanket? I see on a mech with Heatfall Coolant System, when I hover the mech stats to get the calculation Tooltip, "HEATFALL COOLANT SYSTEM" appears as part of all tooltips.
