### ISSUE TITLE
[BUG] Pilot roster view modes broken

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1917]
<strong>Submitted At: </strong> 4/13/2022 21:03:35<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Clicking the different view-style buttons (list, grid, small grid) at the top of the pilot roster does nothing.<br><br><strong>Reproduction Steps:<br> </strong> Open the Pilot Roster with some pilots in it, click any of the view-style buttons.<br><br><strong>Expected Result:<br> </strong> The view to change appropriately.<br><br><strong>Additional Context:<br> </strong> The "Pilot Roster" title seems to be tucked up under the Back/Forward/Home bar at the top of CompCon.<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by jarena3** [comment]
fixed in 2.3.3
