### ISSUE TITLE
[BUG] bonded traits don't show up in compendium 

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1918]
<strong>Submitted At: </strong> 4/14/2022 1:17:19<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> I have Lancer KTB Data (really cool mechs btw) but when I updated the systems and went to the compendium, I couldn't find any of the bonded traits there.<br><br><strong>Reproduction Steps:<br> </strong> Not necessarily a reproducible bug. My best guess on how to reproduce it would be to get another account and download KTB Ashwell, see if they have the bonded traits in compendium or not.<br><br><strong>Expected Result:<br> </strong> I was expecting to see the bonded traits like some of my friends had for their comp/con.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
This usually occurs when the KTB LCP is installed before updating to version 2.3 of COMP/CON. It is resolved by updating to COMP/CON v2.3 and reinstalling the KTB LCP. Closing for now.
