### ISSUE TITLE
[BUG] Synergies missing from weapons

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1919]
<strong>Submitted At: </strong> 4/14/2022 7:53:31<br><br><strong>Browser: </strong> Edge<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> The weapons no longer show synergies<br><br><strong>Reproduction Steps:<br> </strong> Have a pilot talent with a weapon type (ex. Crack shot) with a relevant weapon (Ex Rifle)<br><br><strong>Expected Result:<br> </strong> A synergy should show up on the mount and when firing the weapon that describes the ability<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Verified on Firefox Mobile, may have to do with the new Controller structure.

**Comment by jarena3** [comment]
fixed in 2.3.3
