### ISSUE TITLE
[BUG] Boons count towards the limit of Bond Powers that can be selected

### ISSUE THREAD

**Issue by CubularMonoxide** [massif-press/compcon#1920]
**Describe the bug**
Boons don't count as distinct Bond Powers; they are a bonus the player receives for selecting a Veteran Power (a power from a different Bond). However, taking a Boon counts as taking a Bond Power, and counts against the Bond Power limit, when it shouldn't.

**To Reproduce**
1. Enter your pilot's Bond screen
2. Pick Bonds for your pilot, selecting a Boon in the process
3. Note that the Boon counts against the Bond Power limit, when it should not

**Expected behavior**
Boons should not count against the Bond Power limit.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome App
 - Version: 2.3.3b

**Comment by msprijatelj** [comment]
To pull from the PilotNET #comp-con channel, from Beeftime:

> Mini: How do you add boons if you managed to select the third bond power?

> Beeftime: you add it like a power

> Mini: you don't get the boon off rip after the third bond power?

> Beeftime: that's what I thought as well, but I asked Tom about it directly and he told me that you spend a power on it. Maybe he misunderstood my question, or we might get more clarification on it this weekend. In either case if he says otherwise I'll update C/C to reflect that

So basically we'll wait and see for clarification over the weekend.

**Comment by msprijatelj** [comment]
Closed by [099f035](https://github.com/massif-press/compcon/commit/099f035e82ce7e6deff710b3c56784a9c2af532f)
