### ISSUE TITLE
[BUG] Talent Display Config Not Saved

### ISSUE THREAD

**Issue by msprijatelj** [massif-press/compcon#1921]
**Describe the bug**
The Pilot Talent display mode does not persist between switching pages or refreshing.

**To Reproduce**
1. Go to Pilot Management
2. Change the Talent display to something other than the default
3. Navigate to a different page
4. Navigate back to the Pilot Talent page
5. Observe that the Talent display has reset to the default

**Expected behavior**
Talent display mode persists between navigating away from the page and after refreshes.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CompCon Version 2.3.3b (but has been present since version 2.2)

**Additional context**
I've checked the user settings, and while other display modes are saved for a user, Talent display mode is not.  It probably just needs added to the rest of the user display settings?

**Comment by jarena3** [comment]
I added the save to the actual pilot sheet, but kept the talent selector separate and not savable -- I think this provides a slightly better UX

**Comment by msprijatelj** [comment]
Hate to do this, but I'm reopening this because the Talent view config doesn't update immediately upon selection.  It does, however, update when navigating away and back to the page.

**Comment by jarena3** [comment]
ah, rats. 
this might be because of a user profile sync debounce that has a pretty long tailing time so the backend doesn't get overwhelmed with toggles &c. I'll take a look at this and see if there's a good workaround but it might be just one of those things. Maybe caching some of these things client-side?

**Comment by msprijatelj** [comment]
Nevermind, whatever it was it's fixed now; the Talent View mode updates responsively. Might've just been me? Closing again
