### ISSUE TITLE
[BUG] An error occurred during import attempt

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1925]
<strong>Submitted At: </strong> 4/15/2022 1:44:37<br><br><strong>Browser: </strong> Opera GX<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Attempted to use the new Share code to import a pilot.  Other player says the screen shows "An Error Occured during the Import Attempt.  Please check the Error Log.  The error log is empty<br><br><strong>Reproduction Steps:<br> </strong> Create a share code.  Copy it to the other player.  have them update Compcon.  Have them try and input the share code.  No dice.<br><br><strong>Expected Result:<br> </strong> I expected it to work.<br><br><strong>Additional Context:<br> </strong> I use Opera GX.  I do not know if this is an issue.<br><br><br><strong>Stack Trace: </strong> The Error Log is empty<br>

**Comment by jarena3** [comment]
unable to reproduce (I think this was someone in the chat whose sharing worked after they updated)
