### ISSUE TITLE
[BUG] Condensed talent view not functioning

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1934]
<strong>Submitted At: </strong> 4/15/2022 15:14:20<br><br><strong>Browser: </strong> Vivaldi, Chromium based so should be consistent across browsers.<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Exactly what it says on the tin, CC only displays talents using the first display option in the tactical profile - this is aggravating if I want to quickly check more than 3 talents at a time while swapping between bonds, mech hanger and the narrative profile/dossier.<br><br><strong>Reproduction Steps:<br> </strong> Make a pilot, add talents, attempt to swap the display in the Tactical Profile, the display then does not swap.<br><br><strong>Expected Result:<br> </strong> The display should swap (I'm unsure what option 2 is normally supposed to do, option 3 is what I was attempting to access which is tile view, just the talent icon and a rank)<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
I ran into a similar issue earlier when first trying to work with the views.  Now, they seem to be working properly; I assume it was an issue with instantiating the configuration in the first place.  I would recommend the reporter sync their changes, close and reopen the CompCon tab, and try again.

**Comment by jarena3** [comment]
I think this is the case. It might be sticky the first time if you're logged in and it's taking a beat to sync your userprofile, but afterwards you should be okay. Closing this one.
