### ISSUE TITLE
[BUG] Major Ideals for a bond show single instead of all

### ISSUE THREAD

**Issue by smangham** [massif-press/compcon#1937]
**Describe the bug**
On the Bonds tab, the Major Ideals field starts empty and has a random-select button that randomly picks one of the Major Ideals from your Bond. However, selecting a Bond gives you all of its Major Ideals - it looks like only Minor Ideals are randomly selected per session. You also cannot see all of your major ideals, as the box shrinks.

**To Reproduce**
1. Go to 'Bonds' and select a bond
2. Click on 'Random' below 'Major Ideal'
3. It selects a single Major Ideal
4. Copy-paste all Major Ideals into the box (it is now the right size)
5. Return to the Home page
6. Go to Pilots -> Your Pilot -> Bond
7. The Major Ideals box is no longer the right size

**Expected behavior**
The Major Ideal box should auto-populate with all the Major Ideals for the bond.

**Screenshots**
![builder](https://user-images.githubusercontent.com/8093436/163631595-d3a2fe70-a124-4b27-b058-e0672b905557.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 99.0.1 (64 bit)
 
**Additional context**
None

**Comment by msprijatelj** [comment]
Closed by [099f035](https://github.com/massif-press/compcon/commit/099f035e82ce7e6deff710b3c56784a9c2af532f)
