### ISSUE TITLE
[BUG] Mech Reserves are not adding to final Mech Stats

### ISSUE THREAD

**Issue by Wisedukk** [massif-press/compcon#1938]
**Describe the bug**
Mech Reserves from Reserves and Bonuses, are not 'adding to' a Mech's stats in the Mech Hanger.
**To Reproduce**
1. Start with an already-built Pilot, with at least one Mech in the Mech Hanger.
2. Go to 'Reserves and Bonuses', add Extra Repairs.
3. Scroll down to 'Mech Hanger', click on any Mech.
4. Hover mouse over the Repair Cap Stat - it will list the RepCap as only adding Frame + Hull Bonuses.

**Expected behavior**
RepCap should add in any amounts of Repairs from Extra Repair Mech Reserve.

**Screenshots**
<img width="1227" alt="Screen Shot 2022-04-15 at 10 24 36 PM" src="https://user-images.githubusercontent.com/101007565/163659699-3c476180-f558-49f0-9693-771b660da2ef.png">
This was taken from a Pilot using an Emperor, with 3 "Extra Repairs" tokens from Reserves and Bonuses.

**Desktop (please complete the following information):**
 - OS: [Mojave, 10.14.6
 - Browser [Chrome]
 - Version [100.0.4896.88 (Official Build) (x86_64)]

**Comment by msprijatelj** [comment]
Can confirm that a) the Extra Repairs reserve has a bonus to `repcap` built-in already, and b) that bonus is not reflecting on Compcon v2.3.4.  Looks like the mech needs to register the pilot's ReserveController under its FeatureControllers.
