### ISSUE TITLE
[BUG] Lost my pilots

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1941]
<strong>Submitted At: </strong> 4/16/2022 20:08:18<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When entering Pilots tab, Compcon shows an error  "Cannot read properties of undefined (reading 'Portrait')" and fails to show either of my two pilots<br><br><strong>Reproduction Steps:<br> </strong> enter pilot roster.<br><br><strong>Expected Result:<br> </strong> Find both my pilots.<br><br><strong>Additional Context:<br> </strong> When i attempt to copy the stack trace the site freezes up.<br><br><br><strong>Stack Trace: </strong>  Cannot read properties of undefined (reading 'Portrait')<br>

**Comment by msprijatelj** [comment]
Talked with the user who had this error. Seemed to be an issue with an incomplete update? Their pilots are now back and the issue is resolved.
