### ISSUE TITLE
[BUG] Sanitize username input

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1942]
<strong>Submitted At: </strong> 4/16/2022 21:12:35<br><br><strong>Browser: </strong> All<br><strong>Platform: </strong> All<br><br><strong>Issue Description: </strong><br> My party didn't realize that the app input on the phone (iPhone at least?) capitalizes the first letter of the email/username, which then prevented them from logging in elsewhere. The email goes to the right place so they can create the account but if they don't notice what happened/don't guess later they can't log in anywhere else.<br><br><strong>Reproduction Steps:<br> </strong> Try making an account with an email address on the app with initial capitalization and then try logging in with the first letter uncapitalized.<br><br><strong>Expected Result:<br> </strong> For the app to sanitize my input because capitalization generally doesn't matter for email addresses. So I shouldn't need to reproduce capitalization to log in (or at least get told that that might be the problem).<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> N/A<br>

**Comment by msprijatelj** [comment]
I believe this one was already fixed? Legacy accounts will still be affected, though. I’ll test it out before closing this issue.

**Comment by msprijatelj** [comment]
Verified that new accounts created are automatically sanitized to lowercase.  Pre-existing accounts will remain unaffected; it is recommended that users either use the same capitalization as initially used, or to create a new account with strictly lowercase letters and migrate their data to the lowercase-only account.
