### ISSUE TITLE
[BUG] NPC Portrait not Updating

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1945]
<strong>Submitted At: </strong> 4/18/2022 6:08:38<br><br><strong>Browser: </strong> Edge and Brave<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> clicking set image on NPCs does not change the displayed image on the NPC roster<br><br><strong>Reproduction Steps:<br> </strong> Attempt to upload image (displays correctly on that page), Click set image (button grayed as if working) return to NPC page and it still shows default [no image data] image.<br><br><strong>Expected Result:<br> </strong> Image should be replaced with new PNG.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Fixed by massif-press/compcon@40155d836630e212ed6af7a8cdd49dca03afdab6
