### ISSUE TITLE
[BUG] Drone Commander not working

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1953]
<strong>Submitted At: </strong> 4/19/2022 21:02:07<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When deploying drones in Active Mode, they use their base health without applying the +5 HP from Drone Commander 1<br><br><strong>Reproduction Steps:<br> </strong> Create a pilot with the first level of the drone commander talent
Equip one or more drones
Enter active mode
Upon deploying a drone, it will not have the additional 5 hp from drone commander
Hydra's System Link trait appears to work properly, as does the Grit bonus to the Orochi Drones' HP.<br><br><strong>Expected Result:<br> </strong> Drones deployed by a mech with this talent should have their HP increased by the appropriate amount in the deployed equipment section<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Deployables probably need to register their pilot’s TalentsController (and maybe others) for their FeatureController’s bonus collection
