### ISSUE TITLE
[BUG] Cloud Sync Doesn't Save Remote Pilots

### ISSUE THREAD

**Issue by msprijatelj** [massif-press/compcon#1958]
**Describe the bug**
My pilots imported as remote resources are not saved to my cloud account.

**To Reproduce**
1. Log into a COMP/CON account.
2. Using a share code, import a pilot as a remote resource.
3. Refresh the page. Verify that the remote pilot is still present (as expected; this indicates that the remote pilot is still stored in local memory)
4. Perform a Smart Sync to save the most recent local data to the cloud.
5. Open a new private/incognito window. In this window, log into the same COMP/CON account again.
6. Check the pilots retrieved from the cloud. Verify that no remote pilots are present (*NOT* expected)

**Expected behavior**
When I import a pilot as a remote resource, in addition to adding the pilot to my local data, the pilot (or their reference, at least) is also automatically added to my cloud account so that I can successfully retrieve them on a new log in.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - COMP/CON Version 2.3.5

**Additional Context**
This occurs even if you select the remote pilots in the Cloud Sync menu and select "Overwrite Cloud", suggesting that this is **NOT** a Smart Sync issue.

**Comment by TranslucentSabre** [comment]
@jarena3 explicitly mentioned this behavior when announcing 2.3.0

(Sorry I can't seem to be able to grab the discord link on mobile) 
> @COMP/CON Club 
Hello, everyone! For reasons that will become apparent fairly soon I wanted to get the C/C update out the door earlier than Wednesday. In a few minutes v2.3.0 should be live at https://compcon.app
This includes a bunch of stuff related to a Cloud Save overhaul. This should, for the most part, Just Work (you may have to hit auto-sync twice to get things to "take" if you have a slow connection), and any remotely synced pilots will need to be re-imported though the new share code system, found by clicking the little share icon on the bottom navigation bar on the pilot sheet. Sorry about this disruption, but this is way better in almost every respect!

> The old version (2.2.38) of the app is still up and running at https://compcon-old.netlify.app and will continue working until the GM update

> Also, a note on some changed cloud behavior: remote data (ie. pilots owned by other users whose updates you subscribe to) are not registered to your cloud account and must be imported per device. This will not be changed in the short term.

I suggest we resolve this via documentation in the faq for now.

**Comment by msprijatelj** [comment]
Okay excellent, I missed that part. I’ll add it to the FAQ and close this issue once I do so.
