### ISSUE TITLE
[BUG] ZF4 doesn't show Ordnance tag in active mode

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1959]
<strong>Submitted At: </strong> 4/21/2022 0:06:32<br><br><strong>Browser: </strong> Occurs on both Firefox and Opera GX<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> While in Active Mode, the ZF4's Ordnance tag is not visible unless you actively click into the weapon. Additionally, it doesn't show up in the hanger without clicking into it, although because the weapon profiles are hidden until you click in, this is slightly less of problem.<br><br><strong>Reproduction Steps:<br> </strong> Create a Sherman Frame and use it in Active Mode.<br><br><strong>Expected Result:<br> </strong> The Ordnance tag should always be visible in the weapon's information at a glance.<br><br><strong>Additional Context:<br> </strong> #1458 is also this issue, which is marked as resolved, but it's showing up again. Might be fixed by manually adding Ordnance to each of the profiles of the ZF4.<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by lenaleciel** [comment]
![image](https://user-images.githubusercontent.com/49732719/164376205-035d09d4-c142-41e3-84b1-baef3841ff04.png)
shows the Hangar View.

![image](https://user-images.githubusercontent.com/49732719/164376267-b9770125-b665-4c1b-af20-70963d905ac3.png)
shows the Active Mode View without clicking in.

It does show up properly if you click in though.
![image](https://user-images.githubusercontent.com/49732719/164376305-41a9381d-33eb-447a-9705-139b65676f8e.png)
