### ISSUE TITLE
[BUG] Remote Pilots getting flagged for deletion 

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#1961]
When syncing a pilot with the same id as one already in the roster, c/c may erroneously flag the wrong pilot for deletion

**Comment by msprijatelj** [comment]
Workaround while the issue is active, from LostDeviljho on Pilot NET:
> If you have a duplicate pilot with the same id flagged for deletion, it'll let you import the remote resource, but then it conflates the two and removes the remote one on reload cause it thinks it's flagged for delete.
> 
> You can solve this by just permanently deleting the duplicate from your sync management page or from console options, then re-importing the remote pilot.
