### ISSUE TITLE
[BUG] Weapons have "hello world" printed in them.

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1963]
<strong>Submitted At: </strong> 4/21/2022 18:55:12<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Every weapon in the comp/con data has "hello world" written above or below the mech weapon descriptions.<br><br><strong>Reproduction Steps:<br> </strong> Open any weapon description, it should be above the equipment tags area.<br><br><strong>Expected Result:<br> </strong> No "hello world" text should be present.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by jarena3** [comment]
removed with a 2.3.5 hotfix
