### ISSUE TITLE
[BUG] System Points cost not labeled

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#1964]
<strong>Submitted At: </strong> 4/22/2022 3:10:19<br><br><strong>Issue: </strong><br> This is a simple yet troubling one, but essentially, when i go to the compendium and select "mech weapons", it displays all the weapons, BUT it does not display all the stats of the weapons, particularly what im noticing is that it does not display the system point cost for weapons UNLESS i specifically set the item filters options to display specific sp weapons. <br><br><strong>Massif Reference: </strong> <br>

**Comment by msprijatelj** [comment]
This seems less like a bug and more like a feature request.

**Comment by jarena3** [comment]
that's 100% correct
