### ISSUE TITLE
[BUG] Gyges Frame Core Bonus shows twice in Mech Hanger frame Builds.

### ISSUE THREAD

**Issue by Wisedukk** [massif-press/compcon#1968]
**Describe the bug**
The Gyges Frame Core Bonus from ISP-N "Diamond" indicator shows twice in Hangar.

**To Reproduce**
1. Go to 'Core Bonuses', and select Gyges Frame from ISP-N.
2. Choose already-created Mech in Hangar.
3. Check Mech Attributes - and see the "diamond" indicator twice.

**Expected behavior**
Only One instance of the Gyges Frame Bonus Indicator.

**Screenshots**
<img width="1650" alt="Screen Shot 2022-04-22 at 11 23 42 PM" src="https://user-images.githubusercontent.com/101007565/164876590-7a45ec78-788b-4316-b235-e199e318386a.png">

**Desktop (please complete the following information):**
OS: [Mojave, 10.14.6]
Browser [Chrome]
Version [100.0.4896.88 (Official Build) (x86_64)]

**Additional context**
This bug affects any mech that has the Core Bonus applied.
This is visible in Active Mode as well.

**Comment by msprijatelj** [comment]
My first instinct is that this may be due to the FeatureController collecting the synergy twice? Like if it‘a present in two separate controllers registered to the FeatureController. Need to verify this issue first, though.

**Comment by TesserWract** [comment]
This bug isn't limited to just the Gyges Frame, it also appears on the Kai BioPlating, The Lesson of Disbelief, and Armory-Sculpted Chassis. There seems to be some sort of duplication bug related to core bonuses that grant synergies to mech skills.
