### ISSUE TITLE
Feature Request: Column title in the compendium scrolls down with user

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#197]
<strong>Submitted At: </strong>6/1/2019 22:19:59
<strong>Feature: </strong>Column title in the compendium scrolls down with user
<strong>Details: </strong>When scrolling down the compendium, the list of attributes at the top scrolls down so the user doesn't have to scroll back and forth to check what numbers are.
<strong>Contact: </strong>

**Comment by aritsune** [comment]
Duplicate of #249
