### ISSUE TITLE
[BUG] Adding new Mech Weapons/Systems Automatically gives them a Custom name of their own default name

### ISSUE THREAD

**Issue by MagicalAmber** [massif-press/compcon#1973]
**Describe the bug**
Any time a new Weapon or System is added to a mech (Or replaces an old one which had been in that slot before), it adds the weapon/system, but automatically comes renamed _as_ itself, with its originally name in smaller type beside it, as would happen for any system/weapon that you gave a custom name to.

For example, adding Heavy Machine Gun to a Heavy mount now shows, in its titlebar, "**HEAVY MACHINE GUN** //Heavy Machine Gun   Heavy Cannon"
(I can't show different font sizes or colors here, but that's what screenshots are for.)

It CAN be made to look normal again, thankfully. Click the gear icon, choose "Set Custom Name...", and then press the "Reset" button by the text field. But that means I have to do that for _every_ single new thing I add or replace.

**To Reproduce**
1. Go to any frame on any pilot, and scroll down to the loadout section
2. Click on any mount and add a new weapon or system.
3. Presto namechange-o!
4. To fix it, click the gear > Set Custom Name... > [Reset]

**Expected behavior**
Should just say "**HEAVY MACHINE GUN**   Heavy Cannon". 
(Of course, systems wouldn't have the weapon type and class in grey, so for them it'd be back to just a name.)

**Screenshots**
Freshly added
![double trouble](https://user-images.githubusercontent.com/68796051/164950357-e33ee9d7-4619-466b-9be4-b5d811fc877a.png)

After hitting Reset (and what it's supposed to look like to begin with.)
![unfucked](https://user-images.githubusercontent.com/68796051/164950665-7b850717-ddf0-4d4f-a0cb-178cf9da3ec7.png)

**Desktop:**
 - OS: Windows 7
 - Chrome v. 100.0.4896.127 

**Additional context**
This is one of many weird problems that have cropped up since 2.4.3, along with bizarre white-box flickers all over parts of the interface and cloud synching becoming not just unreliable but actively impeding progress by constantly reverting changes. I'm not sure why these are good.

**Comment by msprijatelj** [comment]
This looks to be a result of the fix for #1915, where integrated weapons wouldn't properly save custom names.
