### ISSUE TITLE
[BUG] Deleted items are being reloaded across multiple device logins

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#1976]
Permanently deleted items are being recognized as new items across multiple devices. Once the remote data goes, there's nothing to tell a different device that the data no longer exists/should be permanently removed.

The fix is probably to set a new status (perm-delete) that is ignored globally that has a long TTL or different S3 archive state

**Comment by msprijatelj** [comment]
Reopening this as users are still encountering the issue.

**Comment by jarena3** [comment]
collecting in https://github.com/massif-press/compcon/issues/2222
