### ISSUE TITLE
[FEATURE] There should be a way to navigate between the mech loadout screen and the pilot's tactical profile screen directly

### ISSUE THREAD

**Issue by BlckKnght** [massif-press/compcon#1984]
**Is your feature request related to a problem? Please describe.**

I play Lancer primarily in a community that does not require strict character progression, any build of the appropriate license level for the tier of game you're playing in is OK, even if its unrelated to what you played the previous time out. Because of that, I often remake my character with completely different talents and licenses, and need to make a variety of builds for different license levels, rather than following the steady progression you'd get playing a more conventional campaign.

When theorycrafting, or trying out a completely new build, it is very frustrating to move from the active mech page, where I'm adjusting my weapons and systems, to the pilot's "Tactical Profile" page, where I can change licenses, core bonuses and talents. I have to click to the pilot sheet, which starts on the "Narrative Profile" page (with skill triggers and pilot gear), and then I have to click another link to switch to the tactical profile.

Example of the problem:

1. I want to try out a system on a different license, so on the Tactical Profile page, I click on the edit button and change what licenses I have unlocked. This is fine.
2. I click on the mech icon on the bottom bar, which takes me to the Active Mech screen, where I can add the newly available system to my build. This is perfect, one navigation click got me where I want to be.
3. I decide I don't like the new system and want to replace its license with another option. I can't click to go directly back to the tactical page. Instead, I click on the pilot icon on the bottom right which goes to the wrong part of the pilot sheet, the Narrative Profile.
4. On the Narrative Profile page, I click on Tactical Profile. This step should be unnecessary.
5. Finally I'm back where I started and can change licenses or talents.

**Describe the solution you'd like**

I'd like the Tactical Profile page to have a direct link from the active mech page. There already exists a link going the other direction, but not from mech to pilot-tactical.

**Describe alternatives you've considered**

Making the tactical sheet the default pilot sheet page (either when switching from the mech sheet or always) would also be fine.

**Comment by msprijatelj** [comment]
This should be handled by #1979

**Comment by karidyas** [comment]
As long as the link is un-reverted to it's broken, now-fixed destination and it doesn't just add the route, yep :)
