### ISSUE TITLE
[BUG] "Request a Feature / Report a Bug" only handles bugs, not feature requests

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2001]
<strong>Submitted At: </strong> 5/10/2022 19:49:02<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> The feature request / bug report button in CompCon takes users to a form that is only appropriate for reporting bugs, not for requesting features.<br><br><strong>Reproduction Steps:<br> </strong> Click on "Help" in CompCon, and then click on the large "Request a Feature / Report a Bug" button.<br><br><strong>Expected Result:<br> </strong> Either a) the bug report form should be generalized to have options appropriate to feature requests, b) the button's text should be changed so that it just says "Report a Bug", or c) two different buttons should be used which link to different forms.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
So, https://github.com/massif-press/compcon/pull/2033 removes the mention of "Request a Feature", but I do believe that the feature request form should be re-introduced. 

Another helpful addition would be adding the "Contact information" field back to the forms, to make it easier to reach out to users. Often a bug with a known workaround will be reported, but we're unable to directly inform the reporter of that that workaround.

That's just my 0.0002 manna, anyway.
