### ISSUE TITLE
[BUG] Double Titanomachy Mesh synergy on Ram or Grapple

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2003]
<strong>Submitted At: </strong> 5/11/2022 12:53:42<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Titanomachy appears twice on the Ram and Grapple synergy list in active mode<br><br><strong>Reproduction Steps:<br> </strong> Create a character, give them the core bonus Titanomachy and a mech, go into active mode and look at the actions Ram or Grapple. The Titanomachy box appears twice on both actions.<br><br><strong>Expected Result:<br> </strong> The Titanomachy synargy box should only appear once.<br><br><strong>Additional Context:<br> </strong> https://imgur.com/wCldFDJ (illustration of the bug)<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Pretty sure this is a duplicate of #1968, albeit in a different place too.  Closing for now
