### ISSUE TITLE
[BUG] missing licenses?

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2004]
<strong>Submitted At: </strong> 5/11/2022 16:10:53<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> the Licenses of Orchis/Enkidu etc. are missing in the level up and compendium, the frame is still in the compendium<br><br><strong>Reproduction Steps:<br> </strong> no idea sorry.<br><br><strong>Expected Result:<br> </strong> that while leveling up, i can choose the Enkidu License <br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Enkidu is a variant of Tokugawa and Orchis is a variant of Black Witch. Variant frames are located under the original frames’ licenses and lack their own named licenses.
