### ISSUE TITLE
[BUG] Encounter

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2008]
<strong>Submitted At: </strong> 5/14/2022 20:19:17<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Tablet<br><br><strong>Issue Description: </strong><br> No encounter<br><br><strong>Reproduction Steps:<br> </strong> No encounter<br><br><strong>Expected Result:<br> </strong> Can't build<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Closing this as it’s unclear what the error is and has no steps to reproduce.
