### ISSUE TITLE
[BUG] No encounter option

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2009]
<strong>Submitted At: </strong> 5/15/2022 2:10:58<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Phone<br><br><strong>Issue Description: </strong><br> I can not build any thing or have encounters please help<br><br><strong>Reproduction Steps:<br> </strong> Log in<br><br><strong>Expected Result:<br> </strong> No option<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
The link to the encounter builder is hidden on phones due to not being designed to work well with mobile devices. Closing due to lack of means for follow-up.
