### ISSUE TITLE
[BUG] Used system equipment stays unuseable 

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2013]
<strong>Submitted At: </strong> 5/18/2022 13:08:23<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When you use a grenade (or potentially other deployable systems) quick action during active combat mode the grenade stays 'used' and greyed out for the remainder of the turn, and even into the next encounter.

The grenade cannot be used again as a result until a full repair.<br><br><strong>Reproduction Steps:<br> </strong> Create pilot and Everest with GMS smoke or GMS hex charges in systems.
Go into active combat mode
Activate quick action grenade.
End Turn
Start next round
The button remains greyed out<br><br><strong>Expected Result:<br> </strong> The button should return blue and be useable.<br><br><strong>Additional Context:<br> </strong> Some on the discord had the same issue, even with a tech attack.<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Collected in #2005
