### ISSUE TITLE
[BUG] Bond option not available

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2014]
<strong>Submitted At: </strong> 5/19/2022 20:15:43<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Phone<br><br><strong>Issue Description: </strong><br> I have the LCP for KTB, but the Bond system will not show up in my app. <br><br><strong>Reproduction Steps:<br> </strong> I've deleted and reinstalled the LCP. I've refreshed. I've synced. <br><br><strong>Expected Result:<br> </strong> Expected the option to activate. <br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
This could be due to being stuck on Compcon v2.2.35? Not sure and there’s no Discord contact. I’ll link #1993 just in case but otherwise closing unless more information is provided.
