### ISSUE TITLE
[BUG] Can't create Pilot code

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2015]
<strong>Submitted At: </strong> 5/19/2022 20:34:23<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> If I attempt to create an share code for my pilot, it tells me I do not own that character. Seeing as I made it, I'm pretty sure I do. I am also unable to use a share code from a friend. When I enter the code Comp/Con says "ERROR IMPORTING PILOT: Unexpected token < in JSON at position 0"<br><br><strong>Reproduction Steps:<br> </strong> All attempts have yielded the same result for both issues<br><br><strong>Expected Result:<br> </strong> For both of these features to work I guess<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Without additional info to follow up, the best I can say is:
1. Make sure you both are on CompCon v2.3+ (check the wiki’s FAQ for troubleshooting if not on 2.3+)
2. Create a duplicate (not a flash clone) of the pilot and reattempt creating a share code with that duplicate. 
3. Have the friend generate a new share code and try again.

**Comment by jarena3** [comment]
Going to guess that it's a version mismatch
