### ISSUE TITLE
[BUG] not updating and going back to old comp/con

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2017]
<strong>Submitted At: </strong> 5/24/2022 13:38:29<br><br><strong>Browser: </strong> Edge<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> I go to update, and it just reloads as old version <br><br><strong>Reproduction Steps:<br> </strong> update the app<br><br><strong>Expected Result:<br> </strong> new version to load<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Collecting in #1993
