### ISSUE TITLE
[BUG] Down time actions remain when the content pack is deactive

### ISSUE THREAD

**Issue by Datguy777** [massif-press/compcon#2025]
**Describe the bug**
when you look at downtime actions in the active mode the downtime actions of other content packs are still there it is for both homebrew and official content

**To Reproduce**
1. Have content installed that has downtime actions (like Long Rim or CASTOR & POLLUX)
2. In manage content packs disable the packs that carry the actions
3. Go to the active mode in a pilot`s profile and hit the downtime actions
4. the actions from the deactivated content is still there (in version 2.3.8)

**Expected behavior**
I expected the downtime actions to not be there

**Screenshots**
![pic 1](https://user-images.githubusercontent.com/106645104/171328675-f0be27d9-eef6-4634-aa69-a061dabbe4b2.png)
![pic 2](https://user-images.githubusercontent.com/106645104/171328734-a980d43f-5c90-4105-8469-90969c5177f5.png)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Version [2.3.8]

**Additional context**
I think that this might be a good feature but it doesn`t tell you where the downtime comes form like most other items and mechs so you don't know if it is homebrew or a content pack that the gm doesn't have so they don't know where it is from and why its and option

**Comment by msprijatelj** [comment]
Whomever works on this should check how we normally hide LCP data and then apply it to Downtime actions (and any other LCP items we may not yet hide).

Bonus points if the dev finds a way to indicate LCP source for the downtime action(s), following patterns for Backgrounds, Frames, Pilot Gear, and the like.

**Comment by msprijatelj** [comment]
Additional context from #2054 : this happens in the Compendium as well
