### ISSUE TITLE
[BUG] Auto rotate when not active

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2029]
<strong>Submitted At: </strong> 6/2/2022 16:39:59<br><br><strong>Browser: </strong> App downloaded to android phone<br><strong>Platform: </strong> Phone<br><br><strong>Issue Description: </strong><br> App will rotate if phone is tilted. Even if the setting is turned off for the phone.<br><br><strong>Reproduction Steps:<br> </strong> Open app, tilt phone<br><br><strong>Expected Result:<br> </strong> Dont reorient the app<br><br><strong>Additional Context:<br> </strong> Verizon 35thinq<br><br><br><strong>Stack Trace: </strong> No error appears<br>

**Comment by jarena3** [comment]
I'm unable to reproduce this on any Android device I could find. This might be device specific, but at any rate I'm going to mark this one wontfix: manually ignoring breakpoints based on eg. toggle would be too much work for too little payoff
