### ISSUE TITLE
[BUG] Missing Invade options from Hacker 2

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2037]
<strong>Submitted At: </strong> 6/18/2022 14:48:21<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Hacker talent Invade options are not shown when using Invade in Active mode (other options, from systems, are present)<br><br><strong>Reproduction Steps:<br> </strong> Get Hacker 3 for the character
Go to active mode
Launch a mission
Do a Quick Tech -> Invade -> Successful<br><br><strong>Expected Result:<br> </strong> Invade options should contain Jam Cockpit, Disable Life Support and Hack./Slash from the Hacker 2 talent and Last Argument of Kings from Hacker 3<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
To elaborate, Last Argument of Kings isn’t an invade (so we don’t expect it there), but it’s **still** not showing up under the compcon Full Tech menu. I’m guessing the update to cloud saves is preventing talent tech actions from being collected and displayed in active mode (and potentially other talent actions, as well).

**Comment by msprijatelj** [comment]
Closed by https://github.com/massif-press/compcon/commit/583e918b40ac8aeb482f7f6baa8251397bf93c13
