### ISSUE TITLE
[BUG] Unable to create standard mechs

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2039]
<strong>Submitted At: </strong> 6/25/2022 4:41:50<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Created a new Pilot. My first for i normally dm. Worked fine. Wanted to open the mech hanger and create new mech. i am not licensed for more then the everest and some "dlc" mechs.<br><br><strong>Reproduction Steps:<br> </strong> Install following lcps: 
core npcs: 1.0.4 (cant update for reasons)
No Room for a Wallflower: Act I 	1.0.8 
The Long Rim 	1.0.11
The Karrakin Trade Baronies 	1.1.0 (demo version)
Intercorp Licenses 	Interpoint Station	2.1.6 
-> pilot roster: 
> new pilot
> create randoms names
> following pilot skills: Assault, blow something up, survive, take someone out
> following talents: heavy gunner, siege specialist, technophile
> agility and engineering 1 point each
> open mech hanger: only see lcp mechs as licensed or non after activating and deactivating lcps<br><br><strong>Expected Result:<br> </strong> Show all mechs as licensed i have lcps for including the standard free variety<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
If I’m understanding this correctly, it sounds like you’re creating a fresh LL0 Pilot that lacks licenses. As a result, by default you will see none of the gear locked behind a license. You can toggle a switch with a “lock” icon to reveal all frames/equipment loaded into COMP/CON.

**Comment by msprijatelj** [comment]
Closing this as it seems the user misunderstood the License unlock process. Hopefully the advice above can help.
