### ISSUE TITLE
[BUG] my compcon character isn't registering as my but as someone else's and won't let me share my character

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2041]
<strong>Submitted At: </strong> 6/25/2022 22:42:07<br><br><strong>Browser: </strong> Edge<br><strong>Platform: </strong> desktop and phone<br><br><strong>Issue Description: </strong><br> none of the characters are saying they are mine, and they are saying they belong to someone else, can't change or send them to anyone either<br><br><strong>Reproduction Steps:<br> </strong> tried updating, won't update<br><br><strong>Expected Result:<br> </strong> fix the bugs<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Seems like a duplicate of #1993. Not enough data to reproduce otherwise, so closing as a duplicate.
