### ISSUE TITLE
[BUG] Actions from disabled LCP show up in compendium

### ISSUE THREAD

**Issue by eschatonic** [massif-press/compcon#2054]
**Describe the bug**
A downtime action (specifically in this case, Step Into The Ring from the Field Guide To Suldan) shows up in the Compendium list of downtime actions despite the fact that the LCP is disabled in the Content Pack Manager.

**To Reproduce**
1. Add the Field Guide To Suldan LCP, available here: https://kaitave.itch.io/field-guide-to-suldan
2. Disable the LCP in the Content Manager
3. Navigate to the Action Economy section of the Compendium
4. (Occasionally necessary, probably its own separate bug) Clear browser cache and/or force-reload the page to update it

**Expected behavior**
The downtime action Step Into The Ring should not display.

**Actual behavior**
The downtime action Step Into The Ring displays.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] -  Windows 10 Home
 - Browser [e.g. chrome, safari] - Chrome
 - Version [e.g. 22] - Version 102.0.5005.115 (Official Build) (64-bit)

**Additional context**
I have heard that there have been other issues with disabled LCPs in the past, so I thought it might be worth flagging this up as a possible bug with Comp/Con itself rather than an issue specifically with the LCP - but I have not tested this with a custom LCP to verify whether it occurs in other cases.

**Comment by msprijatelj** [comment]
Collected in #2025
