### ISSUE TITLE
[BUG] Skill Point Reserve adds two skill points, rather than one

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2057]
<strong>Submitted At: </strong> 7/1/2022 2:08:25<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When I make a pilot, or edit an existing pilot, and add the Skill Point Pilot Bonus, it grants me two skill points to spend rather than one<br><br><strong>Reproduction Steps:<br> </strong> Whether I am making a new pilot or editing an existing pilot, when I add the Skill Point Pilot Bonus on the Reserves and Bonus menu, it grants me two skill points instead of one. My LL0 pilots show 4/6 skills leveled, and my LL3 pilot shows 7/9<br><br><strong>Expected Result:<br> </strong> The Skill Point Pilot Bonus should only add one skill points, as per the Get Focused rules.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by TranslucentSabre** [comment]
I cannot reproduce this issue on either Chrome or Firefox, with either the latest 2.3.3b or the Dev tip.
OP, will you please provide more details and possibly attach a pilot which exhibits this issue?

**Comment by msprijatelj** [comment]
Yeah, can't see this on Firefox on the live site (v2.3.9a). "Skill Point" and "Get Focused" are both contributing 1 skill point each.  Without more info (e.g. which CompCon version the user is on), I don't know if this is reproducible.

Primary recommendation is to update CompCon to v2.3.0 or higher, following the troubleshooting wiki: https://github.com/massif-press/compcon/wiki/FAQ%3A-Troubleshooting
