### ISSUE TITLE
[BUG]  Integrated weapon added to custom frames not functional

### ISSUE THREAD

**Issue by AliceWntz** [massif-press/compcon#2060]
**Describe the bug**
The "Integrated" (Integrated, not single Aux, which is also named Integrated but functions differently) weapon mount is not functional when added to a frame in a custom LCP

**To Reproduce**
1. Install the attached LCP or, if you don't trust me, make your own empty frame with an integrated mount, or add an integrated mount to any frame with an LCP.
2. Go to the pilot roster and select any character (or make one, nothing about the character matters), the frame in the LCP file is available at LL0
3. Go to the mech hangar and click to add a new mech
4. Choose the test mech (or the one you made) and register it with any name
5. Scroll down to the weapon mounts and click the integrated weapon mount, it will give an error which will be attached bellow (f12 console included) and will not be functional
6. Additionally, going to the compendium and then the frames, selecting the test frame and scrolling down to the weapon mount, mousing over the weapon mount will give an error, also attached bellow

**Expected behavior**
The mount is not functional and will give out an error, attached bellow

**Screenshots**
Error upon selecting the mount
![unknown (5)](https://user-images.githubusercontent.com/108504501/177899549-d292426c-57f3-43a0-9ec5-2852cadaa3f8.png)
![unknown (4)](https://user-images.githubusercontent.com/108504501/177899613-c05f9dfa-2106-44c2-b988-19dae173d672.png)

Error in F12, Console Tab
![unknown (6)](https://user-images.githubusercontent.com/108504501/177899698-43545742-76a9-4270-a44f-06fd0c84ddd5.png)
![unknown (7)](https://user-images.githubusercontent.com/108504501/177899727-04f290e7-eafa-49ce-87ce-558c56a6c4b4.png)

Error in the compendium
![unknown (9)](https://user-images.githubusercontent.com/108504501/177899790-69f68b90-ac14-49db-aa50-c10198db3060.png)
![unknown (8)](https://user-images.githubusercontent.com/108504501/177899804-21d788ba-f780-4cba-bba4-360081e96307.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Chrome
 - Version: Chrome version 103.0.5060.114 (Official Version) 64 bits

**Comment by msprijatelj** [comment]
Is there any chance you could share the entry in this LCP so we could diagnose it? Alternatively, if you have access to the PilotNET discord, you could run your LCP past the \#comp-con homebrew channel for help.

**Comment by msprijatelj** [comment]
Is there any chance you could share the entry in this LCP so we could diagnose it? Alternatively, if you have access to the PilotNET discord, you could run your LCP past the \#comp-con-homebrew channel for help.

**Comment by msprijatelj** [comment]
Is there any chance you could share the entry in this LCP so we could diagnose it? Alternatively, if you have access to the PilotNET discord, you could run your LCP past the \#comp-con-homebrew channel for help.

**Comment by AliceWntz** [comment]
Ah sorry i intended to attach it, here it is in zip format so i can attach it

[IntegratedTest-1.0.zip](https://github.com/massif-press/compcon/files/9075886/IntegratedTest-1.0.zip)

Additionally, here's the code for the frame, the only thing in the LCP

<details>
<summary>Code</summary>

```
[

  {
    "id": "mf_empty",
    "license_level": 0,
    "source": "GMS",
    "name": "Test",
    "mechtype": [
      "Striker"
    ],
    "description": "---",
    "mounts": [
      "Integrated"
    ],
    "stats": {
      "size": 1,
      "structure": 4,
      "stress": 4,
      "armor": 0,
      "hp": 10,
      "evasion": 8,
      "edef": 8,
      "heatcap": 6,
      "repcap": 5,
      "sensor_range":10,
      "tech_attack": 0,
      "save": 10,
      "speed": 4,
      "sp": 6
    },
    "traits": [
   {
        "name": "---",
        "description": "---"
      }
    ],
    "core_system": {
      "name": "---",
      "description": "---",
      "active_name": "---",
      "active_effect": "---",
      "activation": "---",
      "tags": []
      },
    "y_pos": 69
  }
]
```

</details>

**Comment by msprijatelj** [comment]
Alright, the “Integrated” mount type listed in Lancer-Data is probably not intended to be used as an actual mount type (and probably instead used as a descriptor in Pilot JSON exports). Special mounts are pretty hard coded at this time; there’s a feature for making it more robust in the future. 

In the meantime: What are you attempting to accomplish in your homebrew here, and is it possible that you could add a trait that describes the desired functionality instead of using an Integrated mount?

**Comment by jarena3** [comment]
that's correct -- @AliceWntz, I'm going to close this ticket and refer you to the Discussions tab if you want to discuss workaround for your LCP until the homebrew mount system is expanded
