### ISSUE TITLE
[BUG] Mech skill point reserve not granting bonus 

### ISSUE THREAD

**Issue by Smitts16** [massif-press/compcon#2070]
Description
When adding the "MECH SKILL POINT" reserve it does not grant a bonus skill point to the pilot

To Reproduce
1. Go to add reserves and bonuses
2. Add MECH SKILL POINT

Expected behavior
+1 mech skill point.

 - Browser: chrome,

**Comment by msprijatelj** [comment]
Can confirm that this is happening on 2.3.9a
