### ISSUE TITLE
[BUG] Variant Frames show up in License even if LCP is disabled

### ISSUE THREAD

**Issue by thesjans** [massif-press/compcon#2076]
**Describe the bug**
After disabling a LCP that adds variant frames to a License, those Frames still show up on rank 2 of their License in the Compendium.

**To Reproduce**
(0. Install a LCP that adds variant frames, e.g. the Karrakin Baronies LCP)
1. In the content manager dialog, deactivate the LCP by switching the toggle on the left.
2. Go to Licenses in the Compendium.
3. Click on a License the variant frame belongs to (e.g. Minotaur).
4. The variant frame (Calendula) shows up on rank 2 of the license.

**Expected behavior**
The variant frames of the LCP are hidden after it is disabled.

**Screenshots**
Content Manager:
![image](https://user-images.githubusercontent.com/61207565/181304802-621dd7b3-d255-40fe-9316-d77b8768e608.png)
License in Compendium:
![image](https://user-images.githubusercontent.com/61207565/181304950-e0a6dd62-02ad-4a62-8201-7e8dab375b76.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox (version 102.0.1)
 - Version: 2.3.9a

**Additional context**
The same issue happens in the License selection screen for pilots when leveling up or changing Licenses, which seems to be using the same or very similar UI.

**Comment by super-salad** [comment]
I'll look into this as part of #2078 .
