### ISSUE TITLE
[BUG] Full Tech - Hurl into the Duat not selectable

### ISSUE THREAD

**Issue by dysphoniq** [massif-press/compcon#2088]
**Describe the bug**
When using a Full Tech action, Hurl into the Duat is not able to be added to the list of complete actions.  

Adding other unique tech actions (such as "CONSTRUCT OTHER: IDEAL IMAGE") to the Full Tech action work as expected.  Using Hurl into the Duat as a Quick Tech action also behaves as expected.

**To Reproduce**
1. Create a mech with the "Osiris-Class NHP" system equipped
2. Enter Active Mode
3. Click "Full Actions" >> "Full Tech" >> "Hurl into the Duat"
4. Click "Hurl into the Duat" button on the popup and observe that nothing happens

**Expected behavior**
Step 4 should result in a "success or failure" component revealing, which should then be added to the list of completed tech actions

**Screenshots**
The button in question
![image](https://user-images.githubusercontent.com/22550932/183790589-193d9d1d-965c-4a11-8c7d-cd1e0de2c255.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: C/C version: 2.3.9a

**Smartphone (please complete the following information):**
 - Device: iPad Air 4
 - OS: iPadOS 15.6
 - Browser: Safari
 - Version: C/C version: 2.3.9a

**Additional context**
Issue is reproducible on both devices listed above.

If this is a duplicate please feel free to close this! I couldn't find anything about HitD in particular, and have been unable to replicate the issue with other actions on my end, but haven't checked everything possible.

**Comment by super-salad** [comment]
I have a fix almost done for this. It's part of a wider problem that effects any tech attack option (besides Invade) that is launched from the Full Tech dialog .
