### ISSUE TITLE
[BUG] Delete or edit system buttons unresponsive or difficult to use from mech sheet on mobile

### ISSUE THREAD

**Issue by Bluecricket70** [massif-press/compcon#2095]
**Describe the bug**
While viewing the mech sheet on mobile, it is very difficult to press the delete or swap buttons on a system because the page now thinks I'm trying to re-order the system. 

**To Reproduce**
1. Go to mech sheet on mobile 
2. Add a system
3. Attempt to delete or swap it
4. Note the buttons do not always respond to double-tapping.

**Expected behavior**
I would like to be able to delete and swap systems easily without double-tapping the icons.

**Video**
Video of my screen available https://drive.google.com/file/d/1IBXMnyvxcHSNlIJypgPAbckLoxP6TOjU/view?usp=drivesdk

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 12
 - Browser: Chrome
 - Version: 104.0.5112.69

**Additional context**
The video added isn't the best example; the issue occurs with other systems that don't break the table too. Weapons are unaffected.

**Comment by msprijatelj** [comment]
@super-salad it sounds like we need a toggle switch like the Pilot Roster for mobile view, given this bug report

**Comment by super-salad** [comment]
I'll take a look as soon as I can!

**Comment by Bluecricket70** [comment]
Wanted to add that it may actually be impossible to edit systems instead of it just being hard, even zoomed in:

https://drive.google.com/file/d/1Imv82fTO5Ncpi7cm-XXo2vSglcuVKetM/view?usp=drivesdk

**Comment by super-salad** [comment]
I have so far been able to use both buttons on my phone, but it could be device specific. Regardless, I think it's a good idea to implement the lock toggle as @msprijatelj suggested since it's also difficult to scroll on mobile due to the draggable components being over-eager.

**Comment by Bluecricket70** [comment]
If there's anything else you'd like me to provide in order to diagnose the issue, let me know. A toggle is a great idea.
