### ISSUE TITLE
[BUG] wont update

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2101]
<strong>Submitted At: </strong> 8/18/2022 19:26:15<br><br><strong>Browser: </strong> Edge<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> wont update<br><br><strong>Reproduction Steps:<br> </strong> tires to update<br><br><strong>Expected Result:<br> </strong> i want it to update<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Duplicate of #1993
