### ISSUE TITLE
[BUG] Deleting cloud data deleted local data

### ISSUE THREAD

**Issue by IkomaTanomori** [massif-press/compcon#2104]
**Describe the bug**
See title. Was having problems with cloud data overwriting my local data. So I deleted cloud data. This also deleted local data, because on the next sync the app decided once again that the cloud version (now empty) was the correct version.

**To Reproduce**
1. Go to any page of COMP/CON
2. Click on Cloud Account
3. Scroll down to Delete All Cloud Data
4. See error by deleting cloud data

**Expected behavior**
Local data should not be affected and will update the cloud upon next sync. The dialog told me local data would not be affected. That logically means local data should have been present since it was all loaded into my app. However, no local data was preserved; it was deleted on the next refresh.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome (standalone comp/con app downloaded using chrome)
 - Version 104.0.5112.102 (Official Build) (64-bit)

**Additional context**
The cloud has been overwriting local changes a lot lately since the last few updates, though I don't know specific steps to reproduce a bug for it. I do know we've not been able to reliably have character encounter information stay saved or have turns update properly using active mode for several months, with several annoying glitch behaviors that I couldn't describe exact steps to reproduce because they don't seem to happen every time so I don't know what the difference is. I ran into this catastrophic bug trying to fix a cloud data problem where deleted characters kept showing back up even after hitting permanently delete - again, I couldn't describe exact steps to reproduce this, they would just sometimes show up on refresh or a new load.

**Comment by jarena3** [comment]
Should be resolved in 2.3.11, collected in ticket #2222
