### ISSUE TITLE
[BUG] Atlas has a Main mount instead of a Heavy mount

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2109]
<strong>Submitted At: </strong> 9/2/2022 22:44:22<br><br><strong>Source: </strong> The Long Rim<br><br><strong>Incorrect Text/Data: </strong><br> Atlas has a Main mount and a Flex mount<br><br><strong>Correct Text/Data: </strong><br> Atlas has a Heavy mount and a Flex mount (as per Long Rim page 41)<br>

**Comment by msprijatelj** [comment]
Atlas no longer has a Heavy Mount as of the latest PDF. Please download the latest version of The Long Rim from itch.io.
