### ISSUE TITLE
Deleting Problems since Forever [BUG] 

### ISSUE THREAD

**Issue by Maboi000** [massif-press/compcon#2113]
**Describe the bug**
Basically whenever one would delete an object, it would reappear upon logging, futhermore during the process of deleting the stuff it doesn't allow you to delete multiple things through the selection option. Making deleting npc and other aspect a quite tiring mean. Continuing on, the entire process takes at least 3 Clicks and more then 15 seconds to delete 1 object, ence being way too long for mass deletion. Finally the delete button creates a duplicate of the object due to comp/con believing it to be gone which it is yet to be and as such reconstructing it through the cloud, duplicating the object.

**To Reproduce**
1. Go to comp/con like usual
2. Click on connected
3. Scroll down to npc, pilot, or anything
4. Attempt to delete it
5. Refresh page
6. See error

Alternatively 
1. Go to comp/con
2. Click either pilot list or encounter manager
3. Delete a Pilot or NPC
4. Refresh
5. Pilot / NPC is now duplicated.

**Expected behavior**
Deleted Object is Deleted.

**Additional context**
This is a larger issue that has plagued much of Comp/con and has yet to be resolved. At least give the option to chain delete selected objects.

**Comment by jarena3** [comment]
Should be resolved in 2.3.11, collected in ticket #2222
