### ISSUE TITLE
[BUG] Cloud sync makes deleting troublesome

### ISSUE THREAD

**Issue by Chaemera** [massif-press/compcon#2116]
**Describe the bug**
After deleting items in CompCon (NPCs, pilots, missions, anything really) there's a very high chance it will just spontaneously reappear as the cloud-sync decides you didn't really mean it.

**To Reproduce**
1. Create any item within Comp/Con.
2. Delete that item.
3. See item reappear on cloud-sync, sometimes even after going through the Permanently Delete dialog in Options.

**Expected behavior**
If I delete something I want it to actually delete.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome desktop app
 - Version: 2.3.10

**Comment by jarena3** [comment]
Should be resolved in 2.3.11, collected in ticket #2222
