### ISSUE TITLE
[BUG] wont update - stuck in 2.2.31

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2117]
<strong>Submitted At: </strong> 9/9/2022 13:18:53<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> stuck in 2.2.31 - not sure how to uninstall service worker<br><br><strong>Reproduction Steps:<br> </strong> my computer - chrome - comp/con<br><br><strong>Expected Result:<br> </strong> update<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Duplicate of #1993 .  Please refer to that issue for links to the wiki/guidance.
