### ISSUE TITLE
[BUG] Slowdown/lockup and "Too much recursion" error when entering long (30+ character) email address at login screen

### ISSUE THREAD

**Issue by heckinahandbag** [massif-press/compcon#2119]
**Describe the bug**
Attempting to log in, I type my 36 character email address and about 2/3rds of the way through I get slowdown and an error message  "⚠️ ERROR: too much recursion"

**To Reproduce**
1. Open Compcon in a fresh session (e.g. private browsing window)
2. Click Log In on the bottom left
3. Begin typing a long string in the email field, at least 30 characters
4. Compcon will slow down and then lock up. After some time (perhaps a minute or so), compcon will become responsive again and an error message will appear.

**Expected behavior**
No slowdown or error.

**Desktop**
 - OS: Windows 10 Home
 - Browser: Firefox v104.0.2

**Additional context**
Pasting the email into the field seems to work fine. It's typing it one character at a time that seems to cause the problem.

**Comment by msprijatelj** [comment]
I can confirm that this occurs on Firefox while entering an email address.

**Comment by super-salad** [comment]
This is probably caused by the email validation regex that I added last release, and is causing this bug here:

https://stackoverflow.com/questions/69477123/regex-test-causes-too-much-recursion-error-in-javascript

I'll get patch going.
