### ISSUE TITLE
[BUG] Unable to receive verification email

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2122]
<strong>Submitted At: </strong> 9/14/2022 11:36:11<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Phone<br><br><strong>Issue Description: </strong><br> After registering I am prompted to receive a verification code, but no matter how many times I click resend code I do not receive a verification email.<br><br><strong>Reproduction Steps:<br> </strong> Register a new comp con account <br><br><strong>Expected Result:<br> </strong> The ability to receive a verification code<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
This is a known issue with signups and logins with a fix awaiting review; keeping open for tracking. 

Workaround: Attempt to sign up or log in again; the second attempt should work (for whatever reason).
