### ISSUE TITLE
[BUG] Compendium incorrectly displays Frames under Licenses as Rank II

### ISSUE THREAD

**Issue by pkarjala** [massif-press/compcon#2129]
**Describe the bug**
Under https://compcon.app/#/compendium/licenses for all of the listed licenses, the Frame itself appears under the Rank II license column, implying that you have to have License Level (LL) 2 in order to use the Frame.

**To Reproduce**
1. Go to https://compcon.app/#/compendium/licenses
2. Click on any of the listed Licenses under any Manufacturer to extend the fold out
3. The purple `NAME FRAME` button will appear under the  `RANK II` column heading.

**Expected behavior**
A simple fix for this would be to relocate the frame info button so that it appears above the the listed ranks.  It would probably need to be in its own separate row to avoid layout issues and keep a clean consistency across the layout.

Fortunately this should be a relatively simple fix within the layout, and will improve readability and consistency with the content.  I'm creating this bug first so that I can reference it later when I make a pull request (time permitting unless someone else gets to it first!).

**Screenshots**
See circled issue in layout here:

![licenses_issue](https://user-images.githubusercontent.com/5232936/190927872-eebad66b-244d-4a9c-be6e-421c7603288f.jpg)

Potential layout mockup fix here:

![licenses_fixed_suggestion](https://user-images.githubusercontent.com/5232936/190927957-810136f8-977a-467f-98df-0e330085b5f3.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10.x
 - Browser: Firefox
 - Version: 104.0.2

**Comment by msprijatelj** [comment]
> the Frame itself appears under the Rank II license column, implying that you have to have License Level (LL) 2 in order to use the Frame.
By the rules as written, you *do* need rank 2 in a license in order to unlock the frame after which the license is named. This is sounding like a wontfix?

**Comment by pkarjala** [comment]
That is entirely my misunderstanding, then!  Closed issue.
