### ISSUE TITLE
Bug Report: Duplication of pilot profile

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#213]
<strong>Submitted At: </strong>6/3/2019 10:27:01
<strong>Platform: </strong>Windows
<strong>Severity: </strong>High (problem that impairs software function, bad or missing game mechanic implementation)
<strong>Issue Description: </strong>Duplication of pilot profile
<strong>Reproduction Steps: </strong>Follow up of my last request with the step n°6 "confirm" of the pilot creation not functionning. When in the bugged n°6 step, if I cancel, it fills my "Pilot Roster" with copies of the pilot I was trying to make. The copies are all functionning which is weird I think
<strong>Contact Info: </strong>Melon_commado

**Comment by twillacy** [comment]
@jarena3 

Successfully reproduced with the following steps:

1. Download Melon_commado's pilots.old data, stored in [this gist](https://gist.github.com/twillacy/e580c1a02a6ff431748df5d31a6afdd7) for posterity
  * Note that this is the pilots.old file they sent in discord, renamed to pilots.json for convenience
2. Place it in compcon/data, making sure it replaces any existing pilot data
3. Launch compcon 1.3.1.35 or greater
4. Proceed through the steps of making a new pilot, click confirm a few times
5. Cancel pilot creation, observe duplicated pilots in roster

**Comment by twillacy** [comment]
Tested [Tricky's data](https://gist.github.com/twillacy/8ab497c251d044ddd4264aa5bc034253) for this issue:

Contains two pilots, "Wren" and "Crow". Both successfully migrate, but only Wren causes this error if left on the roster. No easy connection between pilots so far, but certainly doesn't occur in 100% of cases.
