### ISSUE TITLE
[BUG] Viceroy frame not recognizing Launchers aas CQB weapons.

### ISSUE THREAD

**Issue by floodedstrand1** [massif-press/compcon#2132]
Discovered when attempting to place Supermassive Mod onto Hammer U-RPL with the Viceroy frame equipped.

**Comment by msprijatelj** [comment]
Similar to #1760, but special since the Viceroy adds CQB to Launchers instead of having weapons pre-baked with multiple weapon types.

**Comment by msprijatelj** [comment]
Closing this in favor of https://github.com/massif-press/compcon/issues/2181.
