### ISSUE TITLE
[BUG] Cannot delete NPCs from NPC Roster

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2137]
<strong>Submitted At: </strong> 9/26/2022 10:59:07<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Due to some issues with Comp/Con syncing, I have some duplicate NPCs. I delete these NPCs in the NPC Roster, I go to the Sync menu, check all NPCs, and I click "Overwrite Cloud" to make them flagged as deleted. I get a "Error Overwriting" message. No big deal, I instead click "permanently delete" in the sync menu next to the flagged NPCs, and then I check all and click "Overwrite Cloud". Comp/Con reports a success, and in doing so, brings back all of the NPCs I deleted.<br><br><strong>Reproduction Steps:<br> </strong> Create NPC. Update to cloud. In the NPC Roster, delete it. Go to sync menu, delete permanently. Select all NPCs, and click "Overwrite Cloud". NPC is back.<br><br><strong>Expected Result:<br> </strong> I expected that deleting an NPC would tell the cloud version to delete it as well, but it seems to want to keep it around.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by jarena3** [comment]
Should be resolved in 2.3.11, collected in ticket #2222
