### ISSUE TITLE
Equipment Loadouts displaying incorrectly

### ISSUE THREAD

**Issue by Cubicdd** [massif-press/compcon#2138]
**Describe the bug**
When making an alternate loadout on a single mech only the primary loadouts systems is shown. The SP count is accurate to the loadout, systems can still be equipped to secondary loadouts and but not changed or removed as the ui for the equipment doesn't show up. The primary loadouts equipment cannot be changed or removed when viewing the secondary loadouts, despite the menu to switch working properly. Weapons work fine.

**To Reproduce**
1.Go to a mech sheet
2. Add systems to primary loadout
3. Create a second loadout
4. scroll down so systems are on screen
5. See error

**Expected behavior**
The equipped systems for the chosen loadout should be displayed.

**Screenshots**
Primary Loadout:
![image](https://user-images.githubusercontent.com/55968409/192932632-f2115f55-f46c-4c2a-993a-99bf7b3ad485.png)
Secondary Loadout with full SP spent:
![image](https://user-images.githubusercontent.com/55968409/192932689-d37b2464-fab3-4a52-a864-aeb1e2c93011.png)
Quaternary Loadout with no SP spent: (Third loadout was copy of primary)
![image](https://user-images.githubusercontent.com/55968409/192932716-4ab1818f-4296-4926-8b57-64c90cf0e455.png)

**Desktop:**
 - OS: Windows 10 Home 19044.2006
 - Browser: Firefox 104.0.2

**Comment by msprijatelj** [comment]
Can confirm this is occurring on CompCon v2.3.10.

**Comment by msprijatelj** [comment]
Refreshing the page seems to let the user view and modify the systems of the ActiveLoadout, but simply selecting a different loadout doesn't seem to update the Systems display to match the current active loadout (though systems are still equipped correctly). Checking if there's a way to update the systemblock of the loadout correctly.

**Comment by msprijatelj** [comment]
Okay, I think this is a result of the drag-and-drop changes to Mech Systems. There needs to be a way to update the SystemsBlock once the CCMechLoadout changes.

**Comment by msprijatelj** [comment]
Figured it out, followed the pattern in PilotRoster to `watch` for changes in the ActiveLoadout's Systems. PR to follow.
