### ISSUE TITLE
[BUG] Cloud sync stuff gets messed up by uBlock Origin ad blocker, which really doesn't like cognito-identity

### ISSUE THREAD

**Issue by BlckKnght** [massif-press/compcon#2145]
**Describe the bug**
Since one of the last few updates (maybe a month or two ago), I've been having a lot of issues with Comp/Con cloud sync not working correctly. Sometimes it would forget an edit I'd made to my pilot or mech, other times it would properly remember them. Things were very inconsistent and I never understood the logic. In earlier versions it would sometimes seem a bit glitchy, but the cloud sync features still worked.

Today I discovered that the sync window didn't show *anything* at all on its list of items to sync (it used to show all the pilots I have created, but show nearly all of them out of date in the cloud, and no attempts at manually syncing did anything). I decided to check if I was getting any Javascript errors, and found one that seemed to be causing the rest:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cognito-identity.us-east-1.amazonaws.com/. (Reason: CORS request did not succeed). Status code: (null).`

The "Tell me more" link from the console sent me to [this page](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed), which suggests that it's often ad blockers that cause the failure. Sure enough, when I disabled uBlock Origin on the page and reloaded, it worked!

**To Reproduce**
1. Visit the site with uBlock Origin enabled. I'm pretty sure I'm using the default filter lists.
2. Click on the 'Login' button on the bottom left of the front page to see the Sync screen.
3. Notice that none of the pilots or other sync-able objects show up in the lists.
4. Press F12 to see error in the JavaScript console. The error above seems to be the root cause, leading to a few other failures.

**Expected behavior**
Cloud Sync should work as normal. It used to work fine, but started having issues a few months ago (I think after a Comp/Con update, but maybe the worsening behavior was after a ad blocker or browser update instead).

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 105.0.1

**Additional context**
The uBlock icon on my browser menubar shows that it's blocked 12 requests to cognito-identity.us-east-1.amazonaws.com . Searching through the settings shows cognito-identity is on the Easy Privacy block list.

**Comment by msprijatelj** [comment]
Marking this as wontfix. CompCon has used AWS Cognito for account handling for over a year, and requires access to AWS to serve content from the Cloud. It is recommended to whitelist CompCon and its connections on extensions like PrivacyBadger and uBlock origin. Otherwise, managing these optional browser extensions are the responsibility of the user, not CompCon.

**Comment by BlckKnght** [comment]
That's fair. I mostly wanted to report it because the situation got worse in some way relatively recently, and maybe some details of what was going wrong can help you make the site a little more robust in the face of the potential for ad blockers going haywire. In any case, thanks for your work on Comp/Con in general!
