### ISSUE TITLE
[BUG] Deleted pilots returning to the roster after being 'permanently deleted'

### ISSUE THREAD

**Issue by Nasajin** [massif-press/compcon#2148]
**Describe the bug**
Occasionally, deleted pilots (at least when using the Delete Multiple option in the roster) will reappear in the roster. This is a bit inconsistent, but appears to be happening after about 24 hours after deletion. Additionally, pilots deleted using the Permanently Delete All button are repopulating in the local deleted items section of the options menu even after being 'permanently deleted'. It seems to specifically be the Permanently Delete option in the Options menu that is causing the issue.

**To Reproduce**
1. Go to the pilot roster and delete any number of pilots using the Delete Multiple option
2. In the options menu, scroll down to the bottom of the list of deleted pilots and press the red Permanently Delete All button.
3. Refresh Comp/Con and go to the pilot roster; the deleted pilots will reappear.

**Expected behavior**
Deleted pilots should not reappear once deleted.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: Firefox
 - Version 105.0.2 (64-bit)
 -
**Additional context**
Several of the pilots I'm trying to delete, when removed from the roster, have expiry dates that have already passed.
![image](https://user-images.githubusercontent.com/115373600/194726029-35ac86c9-78a5-409c-acd2-20621352e2b7.png)

**Comment by jarena3** [comment]
Should be resolved in 2.3.11, collected in ticket #2222
