### ISSUE TITLE
[BUG] Mission Runner Activation Pips Unresponsive

### ISSUE THREAD

**Issue by WombatCD** [massif-press/compcon#2156]
**Bug**
In the mission runner, there are plus and minus symbols next to the activations icon, but they are unresponsive when you click them.

**To Reproduce**
1. Go to Mission Runner
2. Start/Continue a mission
3. See "Activations" near moves and HP
4. Click the plus and minus symbols next to the corresponding icon

**Expected behavior**
Activations are modified when the plus or minus symbols are clicked

**Desktop:**
 - OS: Windows 10, OS build 19044.2130
 - Browser: Brave, Microsoft Edge 
 - Version: 21H2

**Comment by msprijatelj** [comment]
Can confirm that nothing happens when clicking the Activation plus/minus symbols in the Mission Runner.

**Comment by super-salad** [comment]
I will be taking a look at this.
