### ISSUE TITLE
[BUG] COMP/CON bringing back deleted lcp when not in incognito mode

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2159]
<strong>Submitted At: </strong> 11/22/2022 9:02:55<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When the lcp is deleted on the Cloud Management window, leaving it at Local Data: no data and Cloud Data with a version and pression sync all, the deleted Lcp comes back instead of staying deleted<br><br><strong>Reproduction Steps:<br> </strong> -Go to Cloud Management
-Go to LCP list
-Press Delete on one of the lcp
-Sync All<br><br><strong>Expected Result:<br> </strong> When pressing the delete button on the Cloud account management window, that the entire lcp is gone from both local data and cloud data, instead of just the local data, and that it works outside of incognito mode.<br><br><strong>Additional Context:<br> </strong> It works as expected in incognito but not outside of incognito mode, even without any extensions active.

-on Comp/Con, Sync on Login setting is enabled<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by jarena3** [comment]
Should be resolved in 2.3.11, collected in ticket #2222
