### ISSUE TITLE
[BUG] Deleted NPCs, Encounters, Pilots, and Missions do not stay deleted.

### ISSUE THREAD

**Issue by InkwellMusic** [massif-press/compcon#2160]
**Describe the bug**
Deleted NPCs, Encounters, Pilots, and Missions do not stay deleted, and reappear upon refreshing the page.

**To Reproduce**
1. Delete desired item/s
2. refresh page
4. item/s reappear.

**Expected behavior**
Items should stay deleted, and changes should sync to the cloud.

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser: Google Chrome
 - Browser Version: 107.0.5304.122
 - Comp/Con Version: 2.3.11

**Comment by skalchemist** [comment]
I'm having the exact same issue.

Windows 11, Google Chrome, Comp/Con vs 2.3.11
