### ISSUE TITLE
[BUG] Unable to toggle off auto-sync intermittently

### ISSUE THREAD

**Issue by Hawkzed** [massif-press/compcon#2165]
**Describe the bug**
Dynamodb error I get when toggling between auto-sync on and off.

The response is a 200 leading the UI to assume the request was a success and toggle the sync button but upon refresh and re-log the auto sync option remains 'On'.

**To Reproduce**
Can't nail down exactly what's causing the problem but it's happened at least twice for me and once for another user.

1. Go to User Profile
2. Click on 'On Login' switch to switch it off
3. Refresh page (Or Logout)
4. 'On Login' switch remains on

**Expected behavior**
'On Login' switch should be turned off upon re-log.

**Screenshots**
I've captured the requests below

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 108

**Additional context**

The response is a 200 leading the UI to assume the request was a success and toggle the sync button but upon refresh and re-log the auto sync option remains 'On'.

I imagine this could cause confusion among users when they assume auto-sync is turned off and still have the issues mentioned here.

Request:

Endpoint:

> https://hmhcmquzenfaxpearfzp3f3dlu.appsync-api.us-east-1.amazonaws.com/graphql

Payload:

```
{
  "query": "mutation UpdateUserData($input: UpdateUserDataInput!, $condition: ModelUserDataConditionInput) {\n  updateUserData(input: $input, condition: $condition) {\n    id\n    user_id\n    theme\n    achievements\n    lcp_data\n    pilots\n    npcs\n    encounters\n    missions\n    active_missions\n    welcome_hash\n    sync_frequency\n    sync_options\n    view_options\n    _version\n    _deleted\n    _lastChangedAt\n    createdAt\n    updatedAt\n  }\n}\n",
  "variables": {
    "input": {
      "id": "",
      "user_id": "A UUID I've censored",
      "theme": "gms",
      "welcome_hash": "none",
      "achievements": null,
      "view_options": "{\"selector\":\"split\",\"npc\":\"list\",\"roster\":\"list\",\"hangar\":\"cards\",\"talents\":\"full\",\"pilotSheet\":\"tabbed\",\"showExotics\":false,\"quickstart\":false,\"savePerformant\":false}",
      "sync_frequency": "{\"cloudSync_v2\":false,\"remotes\":false}",
      "sync_options": "{\"promptLocal\":true,\"promptCloud\":false}",
      "pilots": null,
      "lcp_data": "",
      "npcs": null,
      "encounters": null,
      "missions": null,
      "active_missions": null,
      "_version": 0
    }
  }
}
```

Response:
```
{
  "data": {
    "updateUserData": null
  },
  "errors": [
    {
      "path": [
        "updateUserData"
      ],
      "data": null,
      "errorType": "DynamoDB:DynamoDbException",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "One or more parameter values are not valid. The AttributeValue for a key attribute cannot contain an empty string value. Key: id (Service: DynamoDb, Status Code: 400, Request ID: IRK5TGK0UA05G1JSC00L61Q2FFVV4KQNSO5AEMVJF66Q9ASUAAJG)"
    }
  ]
}```

**Comment by jarena3** [comment]
Should be resolved in 2.3.11, collected in ticket #2222
