### ISSUE TITLE
[BUG] People cannot download my Pilot data 

### ISSUE THREAD

**Issue by Fyre4** [massif-press/compcon#2176]
**Describe the bug**
I cannot send out pilot codes to other people. It finds the data but then says 'an error occurred while downloading remote data'. So they cannot download my pilot data to their compcon

**To Reproduce**
Use the code VPNTHL in a compcon and it will not work. 

**Expected behavior**
Other people should be able to download my character from the cloud without problems. 

**Screenshots**

![Jacks_error](https://user-images.githubusercontent.com/123198776/213774466-8ee6d76b-8bb0-4eef-8bac-793f6bdcb592.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: Don't know

**Comment by msprijatelj** [comment]
Hello @Fyre4, I recommend regenerating the Share Code for this pilot and then sharing that code instead. Right now I'm seeing a 404 not found error when attempting to import VPNTHL, which leads me to believe that either the code failed to save on the backend, or it expired.

**Comment by Fyre4** [comment]
Here is the new code BNJDL4

**Comment by Fyre4** [comment]
> Hello @Fyre4, I recommend regenerating the Share Code for this pilot and then sharing that code instead. Right now I'm seeing a 404 not found error when attempting to import VPNTHL, which leads me to believe that either the code failed to save on the backend, or it expired.

Here is another one if that doesnt work DUH7SV

@msprijatelj

**Comment by msprijatelj** [comment]
@Fyre4 The new code (DUH7SV) works for me!
![image](https://user-images.githubusercontent.com/44978587/213780448-e502e882-f97d-4faf-8df4-5dc030e013c9.png)

**Comment by Fyre4** [comment]
Awesome, weird but thank you!
