### ISSUE TITLE
[BUG] Cloud Synch not saving edits to Pilots and Mechs

### ISSUE THREAD

**Issue by evantide2** [massif-press/compcon#2184]
**Describe the bug**
Any edits I do on a pilot or mech are instantly reverted when I close the tab and open it up again a while later. Last night I deleted a pilot completely and woke up to seeing them on my roster again. The only way I've avoided the bug is making a new pilot, which it saves on initial closing. But any new edits I do also don't take.

**To Reproduce**
1. Delete/Edit/Do anything with a Pilot that isn't Create New.
2. Close Comp/Con
3. Reopen Comp/Con
4. Click Pilot Roster
5. See all edits reverted since last time except New Pilot creation.

**Expected behavior**
My edits to save to cloud properly.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: Latest version as o this date, not sure the number though.

**Comment by jarena3** [comment]
Should be resolved in 2.3.11, collected in ticket #2222
