### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AFodes** [massif-press/compcon#2185]
When I try to log in, CompCon says that no account exists with my email, but when I try to create a new account with my email, it says that an account with that email already exists! I created the account in Sept, 2022. Is there any way I might trouble shoot this without having to create a new email address?

**Comment by jarena3** [comment]
sorry about the delay, but I can reset this manually and have you make a new account with the same e-mail. What would be your preferred way to send me your e-mail address?

**Comment by AFodes** [comment]
Hi Jarena,

No worries! I was ultimately able to sort it out. All has been going well otherwise so far, except for some reason whenever I change my Talents, it specifically doesn't save those choices? I'm specifically relying on the "Smart Sync All" button to save all my changes.

**Comment by msprijatelj** [comment]
@AFodes I recommend using the following workaround for now: https://github.com/massif-press/compcon/wiki/Troubleshooting-Issues#my-pilot-or-npc-changes-keep-reverting

**Comment by jarena3** [comment]
Should be resolved in 2.3.11, collected in ticket #2222
