### ISSUE TITLE
[BUG] Still cannot properly delete items

### ISSUE THREAD

**Issue by Chaemera** [massif-press/compcon#2188]
**Describe the bug**
After deleting basically anything (pilots, NPCs, encounters, missions) there's a pretty high chance CompCon will just "fix" the deletion upon syncing to the cloud. This even happens when using the Permanently Delete button.

**To Reproduce**
1. Delete basically anything.
2. Smart Sync.
3. Items are back where they started.

**Expected behavior**
Deleting something (especially using Permanently Delete) should mean it gets deleted.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Firefox
 - 
**Additional context**
This has been a problem for long enough, and consistently enough, that I basically regard CompCon as only a chargen tool and utterly useless from a GM perspective.

**Comment by jarena3** [comment]
Should be resolved in 2.3.11, collected in ticket #2222
