### ISSUE TITLE
[BUG] NPC Rollback w/SmartSync turned off?

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2189]
<strong>Submitted At: </strong> 2/16/2023 17:47:09<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> My NPC library keeps rolling back to a previous version despite me disabling all forms of SmartSync<br><br><strong>Reproduction Steps:<br> </strong> Create (1) new NPC
Close out of CompCon
Restart CompCon

OR

Create (1) new NPC
Sign out of CompCon
Sign back into CompCon<br><br><strong>Expected Result:<br> </strong> The NPC to either vanish or revert to the default "New (NPC Class)" version<br><br><strong>Additional Context:<br> </strong> I think SmartSync on Login is re-enabling itself whenever I log back into CompCon for the first time. Or the NPC library isn't saving changes even without SmartSync.<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by jarena3** [comment]
Should be resolved in 2.3.11, collected in ticket #2222
