### ISSUE TITLE
[BUG] ERROR:   e.mech is undefined

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2192]
<strong>Submitted At: </strong> 2/23/2023 19:42:04<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Whenever I try to save (upload to the cloud) a new mech, I get ERROR:   e.mech is undefined, and it will not save. <br><br><strong>Reproduction Steps:<br> </strong> I've made the mech 7 or 8 times. Curiously, it will not let me generate a stat block after I've built the mech, although it will let me print it out. <br><br><strong>Expected Result:<br> </strong> I expected the mech to save. I've saved other mechs. <br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> A search of the error log brought up no errors of this type.<br>

**Comment by jarena3** [comment]
Should be resolved in 2.3.11, collected in ticket #2222
