### ISSUE TITLE
[BUG] I can no longer see the "No Room For a Wallflower" NPCs when creating a new NPC. Windows, Chrome, Compcon 2.3.11

### ISSUE THREAD

**Issue by unique-usernames-are-annoy** [massif-press/compcon#2196]
**Describe the bug**
I can no longer see the "No Room For a Wallflower" NPCs when creating a new NPC. 

**To Reproduce**
Encounter Toolkit -> NPC Roster -> Add new NPC 

**Expected behavior**
should see wallflower npcs
not there

**Screenshots**

**Desktop (please complete the following information):**
Windows, Chrome, Compcon 2.3.11

**Additional context**

**Comment by msprijatelj** [comment]
Just to be clear, is the Wallflower NPCs LCP both installed and enabled on your account?

**Comment by unique-usernames-are-annoy** [comment]
Yep and I tried deleting and redownloading the lcp

**Comment by msprijatelj** [comment]
Can you take screenshots of your installed  LCPs and post them here? As well as the NPC list you see when selecting “Add New NPC”

**Comment by unique-usernames-are-annoy** [comment]
Content packs:
[image: image.png]

NPC list:
[image: image.png]
[image: image.png]
[image: image.png]

It used to have a wallflower category at the bottom

Cheers,
Amanda

**Comment by msprijatelj** [comment]
I can’t see the images, though it may be a Mobile thing. Usually NPCs in the “add NPC” menu are grouped by role instead of by content pack? Is the Spite present in the Defender list?

**Comment by unique-usernames-are-annoy** [comment]
No the Spite isn't present at all - that's the one I was trying to make
yesterday

trying the images as jpgs

**Comment by msprijatelj** [comment]
Yeah the images aren’t sending through the email. If you get the chance to submit the screenshots on GitHub itself it would be appreciated

**Comment by unique-usernames-are-annoy** [comment]
![NPC_list2](https://user-images.githubusercontent.com/126765747/222678879-7f943ddd-1ea6-4564-881e-adf69bb0655b.jpg)
![NPC_list1](https://user-images.githubusercontent.com/126765747/222678892-1c1d98dc-9885-4083-8c1a-0a4a8b2edf52.jpg)
![content_packs](https://user-images.githubusercontent.com/126765747/222678897-13cad940-6f90-447a-afcf-6299158b3ee2.jpg)
![NPC_list3](https://user-images.githubusercontent.com/126765747/222678900-e2dd781a-74d0-4246-9ef3-c4db770035dc.jpg)

**Comment by msprijatelj** [comment]
Okay, it looks like you only have the Wallflower data, which is the Player-facing LCP. The NPCs are part of a separate LCP, which comes with the paid PDF. If you’ve bought Wallflower, you should have access to the Wallflower NPCs LCP.

**Comment by unique-usernames-are-annoy** [comment]
Oh cool thank you - I did buy wallflower but didn't realise it came with an
extra lcp file, I'll go find it

**Comment by msprijatelj** [comment]
I’ll mark this as closed for now, bur feel free to reopen it if you continue to experience this issue.
