### ISSUE TITLE
[BUG] Everything is breaking

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2197]
<strong>Submitted At: </strong> 3/4/2023 9:20:04<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> Pilot sheets do not show up, attempts to open certain compendium categories turn up a "user.getview function does not exist" error, as well as attempting to open the options menu.<br><br><strong>Reproduction Steps:<br> </strong> Not sure, I've uninstalled lcps, reinstalled them, and yet nothing changes.<br><br><strong>Expected Result:<br> </strong> Pilot sheets, compendium categories, etc. show up as intended.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> ```
Vue error at [ee]
get@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:140:1948986
2b0e/</rr.prototype.get@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30788
2b0e/</rr.prototype.evaluate@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:31777
2b0e/</fr/<@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:33470
o@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:140:1943124
2b0e/</wn/e.prototype._render@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:23862
r@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27903
2b0e/</rr.prototype.get@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30788
rr@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30706
Dn@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27917
2b0e/</xr.prototype.$mount@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:66038
init@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:20676
p@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44578
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44207
b@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:45193
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44322
b@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:45193
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44322
2b0e/</Mi/<@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:48688
2b0e/</Pn/e.prototype._update@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27087
r@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27893
2b0e/</rr.prototype.get@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30788
rr@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30706
Dn@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27917
2b0e/</xr.prototype.$mount@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:66038
init@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:20676
p@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44578
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44207
2b0e/</Mi/<@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:48688
2b0e/</Pn/e.prototype._update@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27087
r@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27893
2b0e/</rr.prototype.get@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30788
rr@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30706
Dn@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27917
2b0e/</xr.prototype.$mount@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:66038
init@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:20676
p@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44578
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44207
b@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:45193
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44322
b@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:45193
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44322
2b0e/</Mi/<@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:48688
2b0e/</Pn/e.prototype._update@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27087
r@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27893
2b0e/</rr.prototype.get@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30788
rr@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30706
Dn@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27917
2b0e/</xr.prototype.$mount@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:66038
init@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:20676
p@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44578
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44207
b@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:45193
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44322
2b0e/</Mi/<@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:48688
2b0e/</Pn/e.prototype._update@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27087
r@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27893
2b0e/</rr.prototype.get@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30788
rr@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30706
Dn@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27917
2b0e/</xr.prototype.$mount@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:66038
init@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:20676
p@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44578
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44207
2b0e/</Mi/<@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:48688
2b0e/</Pn/e.prototype._update@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27087
r@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27893
2b0e/</rr.prototype.get@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30788
rr@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30706
Dn@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27917
2b0e/</xr.prototype.$mount@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:66038
init@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:20676
p@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44578
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44207
b@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:45193
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44322
b@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:45193
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44322
2b0e/</Mi/<@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:48688
2b0e/</Pn/e.prototype._update@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27087
r@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27893
2b0e/</rr.prototype.get@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30788
rr@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30706
Dn@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27917
2b0e/</xr.prototype.$mount@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:66038
init@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:20676
p@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44578
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44207
b@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:45193
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44322
2b0e/</Mi/<@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:48688
2b0e/</Pn/e.prototype._update@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27087
r@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27893
2b0e/</rr.prototype.get@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30788
rr@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30706
Dn@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27917
2b0e/</xr.prototype.$mount@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:66038
init@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:20676
p@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44578
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44207
b@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:45193
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44322
2b0e/</Mi/<@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:48688
2b0e/</Pn/e.prototype._update@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27087
r@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27893
2b0e/</rr.prototype.get@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30788
rr@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30706
Dn@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27917
2b0e/</xr.prototype.$mount@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:66038
init@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:20676
p@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44578
f@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:44207
E@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:46808
T@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:47595
2b0e/</Mi/<@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:48736
2b0e/</Pn/e.prototype._update@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27070
r@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:27893
2b0e/</rr.prototype.get@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:30788
2b0e/</rr.prototype.run@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:31521
Zn@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:29728
2b0e/</mt/<@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:12771
ut@https://d33wubrfki0l68.cloudfront.net/bundles/a10e2e3be48fc945831e05bc38c275cd62062b34.js:7:12166
```<br>

**Comment by r99712** [comment]
This is also occurring on Chrome.

**Comment by OasisWall** [comment]
I"m having the same issue. So far, it is specifically happening when attempting to use the features:
Frames
Mech Weapons
Mech Systems
Pilot Gear
NPC Features
Options
It also happens when using Comp/Con on mobile, but instead gives the message "this.user.GetView is not a function. (In 'this.user.GetView("showExotics")', this.user.GetView' is undefined)". This was previously a recurring issue (at least on mobile, but now seems to be unavoidable.

**Comment by msprijatelj** [comment]
Issue appears to be fixed. Closing.
