### ISSUE TITLE
[BUG] CORS error on share code generation & search

### ISSUE THREAD

**Issue by DirectXMan12** [massif-press/compcon#2199]
**Describe the bug**

Adding a pilot from a share code, or generating a new share code, seems to result in a CORS error when communicating with AWS.

**To Reproduce**

1. Create a new pilot
2. Attempt to generate a share code

*or*

1. Click Import Pilot
2. Click Import from Share Code
3. Paste in a valid share code
4. Click search

**Expected behavior**

A working share code is generated / a pilot is imported from share code

**Screenshots**
![image](https://user-images.githubusercontent.com/119737/224173640-65477833-e9bb-49ee-9225-b1aa3491b908.png)
![image](https://user-images.githubusercontent.com/119737/224173750-13dd98a0-8acc-43d9-8ba0-651d1199c10b.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 112.0.5615.20 (Official Build) beta (64-bit)

**Comment by msprijatelj** [comment]
Getting reports this is happening on Firefox as well as Chrome, so I don’t believe it’s browser-specific. I’m guessing AWS changed something about the CORS on the backend and needs to be configured to allow compcon.app

**Comment by msprijatelj** [comment]
This error appears to have been addressed, according to @jarena3 . Closing for now.
