### ISSUE TITLE
[BUG] Update not happening

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2201]
<strong>Submitted At: </strong> 3/10/2023 12:49:39<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> My version is 2.2.27 and I can't update.<br><br><strong>Reproduction Steps:<br> </strong> I click on the check for updates in the top right and nothing happens.<br><br><strong>Expected Result:<br> </strong> my comp/com would update to the most recent version<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Follow these steps for the workaround: https://github.com/massif-press/compcon/wiki/Troubleshooting-Issues#compcon-is-stuck-on-an-older-version-than-230-how-do-i-update-to-the-latest-version

Otherwise, duplicate of #1993
