### ISSUE TITLE
[BUG] Deleted things keep reappearing

### ISSUE THREAD

**Issue by plazma5000** [massif-press/compcon#2207]
**Describe the bug**
Anything I delete reappears when I log in again.

**To Reproduce**
1. Delete something you made (a pilot, an NPC, a mission, anything)
2. Close COMP/CON
3. Reopen COMP/CON and log in.
5. See error

**Expected behavior**
Those things should stay deleted after I delete them.

**Desktop (please complete the following information):**
 - OS: [chromeOS]
 - Browser [Chrome]
 - Version [2.3.11]

**Comment by jarena3** [comment]
Should be resolved in 2.3.11, collected in ticket #2222
