### ISSUE TITLE
[BUG] User not confirmed--no option to resend confirmation email

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2208]
<strong>Submitted At: </strong> 3/31/2023 1:06:34<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When I try to login in, I get an error: UserNotConfirmedException. However, I don't have the option to reconfirm the email.<br><br><strong>Reproduction Steps:<br> </strong> Login with an account that you made years ago and then lost the confirmation emal.<br><br><strong>Expected Result:<br> </strong> A button to resend the confirmation email to validate the account.<br><br><strong>Additional Context:<br> </strong> This is entirely on me, sorry. I made the account when I first bought the pdf a couple of years ago but forgot to validate the account. Now I have the time to run a campaign, I cannot connect to account I made.<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Not sure if you'll see this message, but I'm putting it here anyway: 

Follow these steps:
1. Click "Log In" from the main page
2. Enter your email address into the email field
3. Click "Have a Verification code?" that appears under the email field
4. In the new dialog box, click "Re-Send Verification Code"
5. Check your email/spam folder for the new code
6. Enter the new code and click "Confirm Verification Code"

Additionally, check that you're on CompCon v2.3.0 or higher (v2.3.11 is current at time of writing). If you see you're stuck on a version like 2.2.35 or the like, please follow the troubleshooting steps here to force an update to the latest version: https://github.com/massif-press/compcon/wiki/Troubleshooting-Issues#compcon-is-stuck-on-an-older-version-than-230-how-do-i-update-to-the-latest-version
