### ISSUE TITLE
[BUG]  Email not recieved

### ISSUE THREAD

**Issue by JJJSmit1** [massif-press/compcon#2209]
**Describe the bug**

When creating an account it asked me to use a confirmation code sent to my email to verify the email, but I never received an email, even after making sure I typed the email correctly and having it resend, I ended up dismissing the account creation page and just doing stuff on the website, a few hours later I tried again with making an account, this time it said that there already was an account with that email, so I tried logging in with the info I had put in previously, I received an error saying the user is not confirmed. I attempted the verification code thing from the link under the email, but I still had the same problem of not receiving the email.

**To Reproduce**
-the results might not be reproducible depending on if this is an anomaly-
1. Sign up
2. Do not receive the confirmation code
3. Dismiss the page
4. Attempt to access the account that was created

**Expected behavior**

I expected to receive an email with a code that I would used to verify my email account

**Screenshots**

![Capture](https://user-images.githubusercontent.com/129707160/229399691-716fbbb7-eb95-4a71-94fe-c18491107910.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [OperaGX]
 - Version [2.3.11] (I'm assuming this is asking for what version of the website)

**Smartphone (please complete the following information):**
 
Smartphone was not used

**Additional context**

Thank you for having an intuitive system for reporting bugs and suggesting features. Sorry if the description lacks conciseness I wanted to explain the full sequence of events incase that could be useful.

**Comment by msprijatelj** [comment]
I'll close this issue for now, then! Glad the codes were found :D
