### ISSUE TITLE
Reword the Fade Cloak

### ISSUE THREAD

**Issue by Maboi000** [massif-press/compcon#2213]
**Is your feature request related to a problem? Please describe.**
Fix the wording on the Fade Cloak of Mourning Cloak, it makes you intangible and when Calendula was created they updated Fade to give intangible but forgot to remove the line describing the effect, now RAW the system makes you unable to tag team someone with Calendula, and many players just outright ignore this entire line and continue to tag team as they should.

**Describe the solution you'd like**
Take Tom's job and change the line by giving a "While Intangible" or "with tangible characters or objects" at the end of the line "You cannot interact with any other object or character or be interacted with in any way (e.g., taking or dealing damage)."

**Describe alternatives you've considered**
"You cannot interact with any other object or character that are tangible or be interacted with in any way. (e.g., taking or dealing damage)." instead of the usual line.

**Additional context**
This post was created by the Hearth-7 community after a long discussion about the problems with Fade Cloak. With the high hopes that the Comp/Con team be able to do what Tom can't and give good updates to some of the Core rules or write clarifications.
Thank you for reading.

**Comment by msprijatelj** [comment]
The general policy of CompCon is to stick to the books as written, not to handle errata. This may be worth mentioning as a submission on the [Lancer FAQ Repo](https://github.com/aritsune/lancer-faq)  if this issue has caused as much confusion as mentioned.
