### ISSUE TITLE
[BUG] Third-party homebrew LCP disappear for some reason upon login in

### ISSUE THREAD

**Issue by Maboi000** [massif-press/compcon#2215]
**Describe the bug**
I'm the Hearth-7 homebrew updater for the Hearth-7 server, lately I've had a bug happen where when I load into compcon, some of my pilots disappear, and I get an error if they haven't been deleted already. I can fix the bug by reuploading the LCP into my content manager, this bug only happened to me as of now but i'm worried it may spread.

**To Reproduce**
1. Go to compcon.app
2. Click on nothing, and wait for you to auto-connect
3. See error

**Expected behavior**
Deleted pilot, or "Cannot read properties of undefined (reading 'length')" Error

**Screenshots**
![image](https://user-images.githubusercontent.com/107842478/231683642-d28dcb70-db32-41d7-8c1e-7fa6f45f2407.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Opera GX]
 - Version [Compcon 2.3.11]

**Comment by jarena3** [comment]
Should be resolved in 2.3.11, collected in ticket #2222
