### ISSUE TITLE
[BUG] NPC dropdown menus

### ISSUE THREAD

**Issue by DamicoS** [massif-press/compcon#2216]
**Describe the bug**
In the active mission screen as the GM, adding and removing individual statuses, conditions or resistances to NPCs (but not pilots) with the drop-down menu causes an error message to display with the error "this.$refs.menu is undefined". However, the selected condition/status/resistance does appear in the menu bar as intended, so it's mostly an annoyance having to dismiss the error message every time.

**To Reproduce**
1. Go to Mission Runner tab
2. Start or continue a mission
3. Click on an NPC
4. Select or deselect any option from any of the three drop-down menus labeled Conditions, Statuses or Resistances.
5. See error

**Expected behavior**
I expected the status/condition/resistance to apply without throwing an error, the way it does when applying them to pilots in the same window.

**Desktop (please complete the following information):**
 - OS: Windows 10 and macOS 12.6.3
 - Browser:  Firefox
 - Version: 112.0 (64 bit)

**Comment by msprijatelj** [comment]
Collecting in #2221
