### ISSUE TITLE
[BUG] BUG Cloud Sync

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2217]
<strong>Submitted At: </strong> 4/21/2023 2:21:02<br><br><strong>Browser: </strong> Opera<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When I update pilot/mech informations and data regarding stats, systems, etc... they do not get saved within the cloud sync and when I access Comp/con again they seem to have been brought back to the version before the changes.
For example, I gave a pilot a mech and when I came back to Comp/con later on I found that the mech wasn't there.<br><br><strong>Reproduction Steps:<br> </strong> Create a pilot (a mech too if you need), then close comp/con and re-open it either on a new instance of the browser of a new tab, then make some changes to the pilot/mech. Close and open comp/con again and check if the pilot/mech have the changes you made saved.<br><br><strong>Expected Result:<br> </strong> What I expected was for Comp/con to save the updates I made to my pilot/mech, not to revert them to a previous stage.<br><br><strong>Additional Context:<br> </strong> This can be especially frustrating when being a GM, because your players might update their pilot/mech and the changes revert, creating issues with organizing sessions and missions.<br><br><br><strong>Stack Trace: </strong> <br>

**Comment by jarena3** [comment]
Should be resolved in 2.3.11, collected in ticket #2222
