### ISSUE TITLE
[BUG] No scroll bar in chrome

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2219]
<strong>Submitted At: </strong> 4/25/2023 10:05:59<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When I view Comp/Con in Chrome, there is no scroll bar anywhere. I cannot view any content that requires scrolling down to see, either in the compendium or character sheet.<br><br><strong>Reproduction Steps:<br> </strong> I look at the website in Chrome.<br><br><strong>Expected Result:<br> </strong> I would expect there to be a normal scroll bar. <br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> None available.<br>

**Comment by jarena3** [comment]
unable to reproduce
