### ISSUE TITLE
[FEATURE] Option to Turn Off Extraneous Text

### ISSUE THREAD

**Issue by LonePaladin** [massif-press/compcon#2225]
**Is your feature request related to a problem? Please describe.**
One of the players in my group does not like "greebling", when a document or website includes a bunch of nonessential filler text. He considers it a distraction.

**Describe the solution you'd like**
To accommodate him, I'd like a toggle in the Options page to turn off the extra text.

**Describe alternatives you've considered**
The alternatives? I guess I could just use Notepad for his stats, but that's boring.

**Additional context**
He considers this stuff "greebles":
![image](https://user-images.githubusercontent.com/37523352/235277035-33de96e7-6c6a-4c5c-853d-dd4f40537be1.png)

And just about all of this:
![image](https://user-images.githubusercontent.com/37523352/235277133-e94815b8-ec71-446f-9c1d-b8d28e1178fa.png)

(Personally, I like it. But you can't please everyone.)

**Comment by jarena3** [comment]
nope, sorry
there's a lot of critical stuff I need to take care of and this would be a considerable amount of work, moreover though I think it would diminish from the aesthetic and artistic aspects of the app
