### ISSUE TITLE
[BUG] No Pilots in Roster

### ISSUE THREAD

**Issue by KeeperOfTheVoid** [massif-press/compcon#2226]
**Describe the bug**
I went to check on one of my pilot sheets, and on going to the website it asked me to log in. Under Rosters, I don't see any pilots.  

**To Reproduce**
I am not entirely sure what happened, but here is what I did

1. Arrive at compcon
1. Log in and see the notice on Cloud Saves
1. Goes to Pilot Roster
1. All my pilots were gone

**Expected behavior**
I expected to log in and have all of my pilots shown.

**Screenshots**
<details>
  <summary>Click me</summary>

![pilot roster](https://user-images.githubusercontent.com/7490332/235328582-0a797dcc-a0d6-431d-bbd2-1ffd626e1c16.png)
</details>

<details>
  <summary>Click me</summary>

![pilots](https://user-images.githubusercontent.com/7490332/235328658-422b75dd-237d-41f5-9723-c45e47e7e699.png)
</details>

**Desktop (please complete the following information):**

OS: Windows 10 10.0.19045 
Browser: Chrome (112.0.5615.138)
Compcon Version: 2.3.11

**Smartphone (please complete the following information):**
N/A

**Additional context**
I found this issue (#2154) that is basically what is happening to me, but I decided to submit a more recent issue.  Not sure if it's related to #2222.

**Comment by jarena3** [comment]
if you wouldn't mind, could you make a c/c backup and send it to me? I'm on Discord as beeftime#0558 but if you don't use discord let me know what you'd be comfortable with

secondly, once you've done that, could you try manually reinstalling any LCPs you had and see if that resolves the issue?
