### ISSUE TITLE
[BUG] Code showing on the sheet Armory

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2234]
<strong>Submitted At: </strong> 5/14/2023 12:25:20<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br>  I notice code line among the page and it's pretty strange, with the tag "Undefined" with all the Armor<br><br><strong>Reproduction Steps:<br> </strong> When I read the compendium on the Armor to decides for a character, on the compendium of Comp/con <br><br><strong>Expected Result:<br> </strong> I though that was strange, maybe a update to fix it?<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Verified on CompCon v2.3.14 on Firefox: 
![image](https://github.com/massif-press/compcon/assets/44978587/072a49e0-a192-4bdf-a523-585e95c065f0)

**Comment by msprijatelj** [comment]
I’ve got a report of this issue still occurring on Chrome for Mobile and Desktop on CompCon v2.3.15. I can confirm that it’s fixed on Firefox Mobile at least, though.
