### ISSUE TITLE
[BUG] Kidd

### ISSUE THREAD

**Issue by MyNameIsMoto** [massif-press/compcon#2236]
**Describe the bug**
Can't select any other systems from the kidd besides the frame. 

**To Reproduce**
Add license levels in the kidd. 
Try adding them to the kidd or any everest variant

**Expected behavior**
You should not be able to readily see them as available systems. 

**Screenshots**
I attached a screenshot of having them equipped to the Kidd after searching for them in the equipment catalogue. 

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox 112.0.1
 
**Additional context**
I did see that this was also a problem with the Emperor, but i didn't try very thoroughly to see if maybe it was just all the most recently updated LCPs. 
![BUG](https://github.com/massif-press/compcon/assets/133822060/b2bfc7c8-704c-4022-a11d-084eaf25b075)

**Comment by msprijatelj** [comment]
@jarena3 I'm worried this may have to do with decapitalizing the Frame names in the LCPs? Frame names are still and relied upon in some locations in CompCon, which is why I avoided touching them previously.
