### ISSUE TITLE
[BUG] Error when viewing some things

### ISSUE THREAD

**Issue by h80newvave** [massif-press/compcon#2241]
**Describe the bug**
it says  ERROR this.user.GetView is not a function when i go to a cearten COMPENDIUM page it becomes just a blank page with nothing on it other than the arrows and home at the top also i cannot acces my login when i click it all theat shows up is the log in pop up with nothing to type into.

**To Reproduce**
any time I go to the pilot gear, frames, mech weapons, mech systems or npcs fetures also I cant access the settings.

**Expected behavior**
to see the page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser google chrome
 - Version 2.3.15

**Smartphone (please complete the following information):**
 - N/A
**Additional context**

**Comment by MaxPelly** [comment]
#2237

**Comment by jarena3** [comment]
this should be resolved thanks to the backend changes. If not, I can reopen this ticket.
