### ISSUE TITLE
[BUG] Can't login to CompCon from Development Build

### ISSUE THREAD

**Issue by msprijatelj** [massif-press/compcon#2244]
**Describe the bug**
When running CompCon locally, I am unable to login to my cloud account due to restrictive CORS permissions on the AWS backend. This means I cannot test sync and cloud account-related changes in a consistent manner without some amount of workaround.

**To Reproduce**
1. Clone CompCon, and install/serve with `yarn` and `yarn serve`
2. Once the local dev version is available on localhost:8080, open the dev version in a browser.
3. Click "log in" and attempt to log in with a valid CompCon account.
4. Observe that the loading spinner continues ad infinitum, and that a 403 Forbidden error due to CORS occurs in the devtools console log.

**Expected behavior**
Either developers should be able to log into CompCon through a local development build, or documentation be provided on how to deploy a compcon build that meets the backend CORS requirements.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 2.3.15

**Additional context**
For whatever reason, I also can't build CompCon while having Node v18 installed, unless I first perform `export NODE_OPTIONS=--openssl-legacy-provider` to use the Node v16 OpenSSL provider. That's a little bit of a personal problem, to be fair, but I noticed it since I recently found I needed to upgrade Node to v18 to properly perform development on the LCP directories (which uses an `assert` keyword that only works on major Node versions higher than 16). I can work around it, it's just a little frustrating.

**Comment by jarena3** [comment]
This might be due to some of the new WAF rules I implemented after the usage spike, I'll take a look to see if it's blocking localhost or similar

**Comment by jarena3** [comment]
should be resolved, I'll close when I get your go-ahead @msprijatelj

**Comment by msprijatelj** [comment]
@jarena3 Unfortunately still hitting 403 errors on CORS:
![image](https://github.com/massif-press/compcon/assets/44978587/db60103c-9e00-4daa-b758-1ecf25865d0d)
![image](https://github.com/massif-press/compcon/assets/44978587/68a1acc0-28a3-4218-b182-65b9f56c0f53)
