### ISSUE TITLE
List view while equipping heavy weapons sorts incorrectly due to the Mimic Gun [BUG] 

### ISSUE THREAD

**Issue by ChangelingRain** [massif-press/compcon#2257]
**Describe the bug**
While equipping heavy weapons to a mech, the list view gives incorrect results when sorting by Range or Damage if you have access to the Mimic Gun

**To Reproduce**
1. Go to any mech with a heavy weapon mount and 2 LLs in Pegasus(or the 'show unlicensed equipment' toggle on)
2. Click the heavy mount to pick a weapon and toggle on list view
![](https://i.imgur.com/QMiQosW.png)
3. Click on either Range or Damage to sort by them
![](https://i.imgur.com/bxn3QRw.png)
4. Scroll down to see the Mimic Gun sorting incorrectly

**Expected behavior**
Sorting by Range or Damage would sort everything, including the Mimic Gun, properly

**Screenshots**
![](https://i.imgur.com/ryVyM2R.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 108.0.2
 - Version: COMP/CON 2.3.16
 
 **Additional information:**
 This *only* occurs if you have access to the mimic gun. If you don't, it will sort properly by range and damage.

**Comment by Hawkzed** [comment]
![image](https://github.com/massif-press/compcon/assets/15632927/6f4d2066-dcc8-4bed-89a9-6c1b7ce0d1e5)
Range and damage are funky values. I might be able to fix this.

**Comment by Hawkzed** [comment]
![image](https://github.com/massif-press/compcon/assets/15632927/7492d7f5-7025-4c8e-a87b-14ae0e01ac08)
Got Range working

![image](https://github.com/massif-press/compcon/assets/15632927/0297004d-9318-4009-8de4-affe03a830da)
And got damage working... for the most part
Retort Loop, Fusion Rifle and Mimic gun all have NaN MaxDamage.
![image](https://github.com/massif-press/compcon/assets/15632927/99cd64eb-0f13-43be-be1b-98c7a5d920f2)
