### ISSUE TITLE
[BUG] this.user.GetView is not a function

### ISSUE THREAD

**Issue by Osha2501** [massif-press/compcon#2266]
**Describe the bug**
Unable to log in, unable to use pilot roster, unable to do anything but Compendium

**To Reproduce**
1. Go to login
2. Click on login
3. Go to options/log

**Expected behavior**
Use of the Comp/Con website

**Screenshots**
N/A

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: 

**Additional context**

**Comment by msprijatelj** [comment]
This is a transient issue relating to outages in AWS US-East-1. Not much to do but wait for it to pass, and it looks like it’s resolved now.
