### ISSUE TITLE
[FEATURE] Manual sorting of Licenses within Manufacturer and sorting of Manufactures instead of download order

### ISSUE THREAD

**Issue by VeroTheWald** [massif-press/compcon#2271]
**Is your feature request related to a problem.**
I installed some homebrew lcps before some core lcps by accident and did not notice meaning I would need to delete all homebrew lcp files above them to reorder (get them below the core frames in the compendium/charcter license select) and then reinstall the homebrew.

**Describe the solution you'd like**
Manual sorting of individual Licenses within a Manufacturer. Within a license would also give you the opportunity structure it to your preference/ favourite licenses (similiar to shuffling the pilot order). Manually sorting an entire license manufacturer/homebrew manufacturer would allow you to do the same (order for preference/sort by favourite manufactures) and also would mean you would not have to scroll down to the very bottom when you install a cool new homebrew and can just drag it to the top.

**Describe alternatives you've considered**
Manually dragging/sorting the order within the Content Manager.

**Comment by jarena3** [comment]
I've backported a v3 feature for declaring LCP dependencies that should address any issues with loading order, but for strict UI arrangement I won't be adding this. v3 will have a lot of new options to quickly get to LCP specific content that can be seen in the Compendium at the dev build: https://cc-dev-preview.netlify.app/
