### ISSUE TITLE
[BUG] reserves not taking the reward away when marked as used

### ISSUE THREAD

**Issue by Melted-Gallium** [massif-press/compcon#2274]
**Describe the bug**
When marking some reserves as used, their mechanical bonus is not automatically removed.

**To Reproduce**
1. Go to any comp/con player character
2. give them any of the following reserves:
- talent point
- extra core bonus
- mech skill bonus
- license point
- extended harness (on my pull request fixing #1747 )
3. mark said reserve as used

**Expected behavior**
This may be how it is expected to work, but some of the reserves, when marked, remove their functionality automatically. One example would be the original Extended Harness.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 114.0.5735.134

**Additional context**
I'm 99% sure this bug is appearing due to the way that the Int function in the Bonus.ts class works, as those four (five with my update) rely on that function to figure out how much of those abilities are given to the player.

**Comment by msprijatelj** [comment]
To be fair, most of the cases you mentioned are meant to be more long-term (namely license points and other level-up-stuff). I get you on the extended harness part though. Not sure if we *want* to ignore “used” reserves, or what would even count as “used” (bringing a reserve on a mission vs finishing the a mission vs used a 1/mission reserve on the mission). I’d be willing to say that most of these are functioning as intended.

**Comment by Melted-Gallium** [comment]
alright then, thanks for the info!
