### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by gungurbuz** [massif-press/compcon#2284]
**Describe the bug**
HORUS chat still active after switching themes

**To Reproduce**
1)Change theme to horus on main page
2)switch to any other theme

**Expected behavior**
I expected the horus chat to go away after changing themes

**Screenshots**
![image](https://github.com/massif-press/compcon/assets/50180396/462c0107-1a4d-48ef-959e-101c3d9f6e8f)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version 115.0.2 (64-bit)

**Additional context**
The problem resolved itself after I changed to horus on the home screen then went into compendium and changed the theme back to GMS while in the compendium page.

**Comment by jarena3** [comment]
this is related to #2281, so I'll close this out to be collected there

**Comment by msprijatelj** [comment]
I actually think this one is unrelated to the options sync issue. I believe it’s a matter of the horus.ts chat continuing to run indefinitely, even after the theme changes, until the home page refreshes/relaunches.
