### ISSUE TITLE
Dustgrave Mech Licenses gone[BUG] 

### ISSUE THREAD

**Issue by SixthRule** [massif-press/compcon#2286]
Viceroy and Störtebeker Licenses missing

1. Go to Comp/Con
2. Click on Pilot Roster
3. in level up menu for Licenses 

Vicroy and Störtebeker missing from lists

**Screenshots**
![Screenshot 2023-07-29 214626](https://github.com/massif-press/compcon/assets/140931818/46a19ad0-08fc-48da-8ec4-ad3a01bef453)
![Screenshot 2023-07-29 214706](https://github.com/massif-press/compcon/assets/140931818/8befd4af-f8af-479c-9765-a34e89a6b336)

![Screenshot 2023-07-29 214724](https://github.com/massif-press/compcon/assets/140931818/e951331c-e2d7-4344-a47a-559697d4e06e)

**Desktop (please complete the following information):**
 - Browser [FireFox]
 - Version [2.3.17a]

**Comment by msprijatelj** [comment]
For context for others, the frames added by Dustgrave are alternate frames for existing licenses. They do not have licenses of their own.
