### ISSUE TITLE
[BUG] Cleared data

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2292]
<strong>Submitted At: </strong> 8/8/2023 5:54:16<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> I went to clear my Cloud data, and it wiped my local data on my computer as well even though it was supposed to leave the local data alone. I know there’s no getting the wiped data back, but could you check the buttons for wiping data to make sure it doesn’t happen to someone else?<br><br><strong>Reproduction Steps:<br> </strong> On my computer, I opened up the login screen using the button at the bottom left. I then scrolled all the way to the bottom, selected the option to delete the cloud data, and then confirmed it on the small pop up window that appeared.<br><br><strong>Expected Result:<br> </strong> I figured it would clear my Cloud data but leave the local data on my computer intact. <br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by jarena3** [comment]
This has been fixed as of the .19a hotfix
