### ISSUE TITLE
[BUG] Comp/con wont install .lcp files

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2297]
<strong>Submitted At: </strong> 8/22/2023 2:55:18<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Phone<br><br><strong>Issue Description: </strong><br> When I go to install .lcp files the app can't seem to find them<br><br><strong>Reproduction Steps:<br> </strong> Attempt to install .lcp files<br><br><strong>Expected Result:<br> </strong> I Expected to be able to install the files <br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
A common issue that’s turned up recently is users downloading the LCPs from the itch app, which automatically interprets the LCP as a zip file. I recommend downloading the LCP from a web browser instead.
