### ISSUE TITLE
[BUG] cannot install .lcp on mobile 

### ISSUE THREAD

**Issue by CometVoid** [massif-press/compcon#2306]
**Descdibe the bug**
.lcp files are greyed out and unselectable when trying to upload .lcp files on mobile as if they were the wrong filtype

**To Reproduce**
1. press the select a .LCP file button
2. see that .LCP files are greyed out

**Expected behavior**
.LCP files should be selectable 

**Screenshots**
![Screenshot_20230916_215850_Files](https://github.com/massif-press/compcon/assets/80859724/423cfa7c-75dc-47c5-bb0e-100dce5a3624)

**Smartphone (please complete the following information):**
 - Device: Galaxy A54
 - OS: Android 13, OneUI 5.1
 - Browser: Brave and Chrome

**Comment by jarena3** [comment]
try going to `chrome://flags` in the search bar and finding and enabling the "Use deprecated external picker"
