### ISSUE TITLE
[BUG] Somehow ended up with a LL13 Pilot ... And failed attept to recreate

### ISSUE THREAD

**Issue by MaiaMooCow** [massif-press/compcon#2311]
**Describe the bug**
As the title says, accidentally made a level 13 pilot, extra perks and all.

**To Reproduce**
I honestly do not know how it happened.
1. I went through the basic setup of a LL 0 pilot
2. I edited the pilot's level to 11 and pressed the level up button
3. I went through stat and attribute selection as normal.
4. Upon completion of the pilot, i had the option to level up again, and tried it. Same as step 3, i was able to add an addition point in all regards except core bonus
5. In trying to recreate this bug, i went through the process again, but am now unable to finish the process on the final 7th tab, getting an error, "Cannot read properties of undefined (reading 'ApplyLevel')
**Expected behavior**
Well, i dont know what to put here besides "not expecting to go above level 12"
And "expecting to finish character creation". 

**Screenshots**
 
![Screenshot_20230926-045242](https://github.com/massif-press/compcon/assets/146082078/97436eae-6ee1-4c91-a0f8-8db83211c6f2)
![Screenshot_20230926-052233](https://github.com/massif-press/compcon/assets/146082078/4dc9dc86-68f1-4a8f-8d48-3e7b923d47b0)

**Desktop (please complete the following information):**
 - OS: N/A

**Smartphone (please complete the following information):**
 - Device: Fire HD 8 Plus
 - OS: Fire OS 8.3.1.9
 - Browser: Silk Browser
 
![Screenshot_20230926-053126](https://github.com/massif-press/compcon/assets/146082078/3076578b-c7ac-48cf-a0cd-f5b747e16bca)

 

I was in the middle of this report for the LL 13 pilot bug when i tried to recreate it and ended up with another bug. I really hope i have been helpful, and have provided adequate information. I also brought this up in the official discord, so if you need additional information, you can contact me through there.

**Comment by jarena3** [comment]
I haven't been able to reproduce this either, so I'm willing to chalk it up to a one-off weirdness. If you can reliably reproduce this let me know and I'll reopen the ticket
