### ISSUE TITLE
Roster bug

### ISSUE THREAD

**Issue by BIOGEAR20** [massif-press/compcon#2313]
**Describe the bug**
When clicking on the pilot in roster the only thing that shows up is the background and call sign.

information is still there when selecting to print but is other wise invisible and unable to be interacted with.

Additional bug: sign in will not complete the process.

 It will say if something is wrong with ether the password or username and can change password.
**To Reproduce**
Unknown

**Expected behavior**
As intended.

**Screenshots*

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [iPhone XR 
 - OS: [17
 - Browser [safari
 - Version [for comp/con: 2.3.18

**Additional context**

**Comment by jarena3** [comment]
please try backing up your COMP/CON data, clearing user data, and deleting site/cache data and reloading
