### ISSUE TITLE
[BUG] Siren's Song; Missing Lighthouse Gear (Pg. 51)

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2321]
<strong>Submitted At: </strong> 10/16/2023 20:26:07<br><br><strong>Source: </strong> LANCER Core Book<br><br><strong>Incorrect Text/Data: </strong><br> Actually in Siren's Song; appears to just have been overlooked in the .lcp to include the "reserves" from page 51 of Siren's Song<br><br><strong>Correct Text/Data: </strong><br> see Incorrect text<br>

**Comment by msprijatelj** [comment]
Closed by https://github.com/massif-press/ssmr-data/commit/aff949b82002f32dc211c73fdd887f56beac367f
