### ISSUE TITLE
[BUG] SSMR - Tempest Size Issue

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2339]
<strong>Submitted At: </strong> 11/15/2023 15:33:23<br><br><strong>Source: </strong> LANCER Core Book<br><br><strong>Incorrect Text/Data: </strong><br> Size 4 for Tier 1<br><br><strong>Correct Text/Data: </strong><br> Size 3 for Tier 1<br>

**Comment by msprijatelj** [comment]
Fixed in v1.6.5 of the SSMR NPC data, currently live on itch.io.
