### ISSUE TITLE
[FEATURE] Add effect field to pilot armor

### ISSUE THREAD

**Issue by eschatonic** [massif-press/compcon#2347]
Currently pilot armour in comp/con only has a single "description" field, which is ordinarily used for compendium entries. The "effect" field, which is ordinarily used to contain game mechanics, does not display.

This causes several issues, chief amongst which is that this field ends up being used to pull double duty for both the flavour text and the mechanics of any given piece of armour. Since the regular hardsuits from the CRB have no flavour text, this is most noticeable in existing first party content when looking at the Carapace Hardsuit variants from Wallflower - where the mechanics of the armor are buried at the end of a paragraph that looks like it's purely flavour text, and the Madrigal Boarding Carapace from Dustgrave which needs to inject HTML tags through the LCP data in order to make its rules visible.

Shadow of the Wolf will add a new piece of pilot armour that will also run into this issue, as it has both flavour text and separate mechanics, and I would prefer not to have to use a hacky solution similar to Dustgrave's LCP.

The ideal solution for me would be to create a separate "effect" field which can contain the mechanical effect of a given armour piece. This would bring armour into line with pilot weapons and other systems. Notably this field appears to exist on pilot weapons, but also appears to be absent on regular pilot gear; it may be desirable to add an effect field to the gear at the same time, though that is a lower priority for me personally.

This would not necessarily require an update to existing LCPs, as the description field would still function as it currently does. That said, adding this field might present an opportunity to bring these older LCPs into line with the new structure.

**Comment by msprijatelj** [comment]
This sounds like a relatively straightforward feature, to me. Add an optional “effect” field like so much other Lancer gear, and have CompCon display it when present. Agreed that Dustgrave’s gear would highly benefit from this.

**Comment by ApprenticeofEnder** [comment]
Looks like Effect already exists on the Pilot Equipment, looks like a fix would just be snagging the data contained within it for displaying the Armour.

https://github.com/massif-press/compcon/blob/master/src/classes/pilot/components/Loadout/equipment/PilotEquipment.ts

**Comment by vialra** [comment]
So in the end smth like this:
![image](https://github.com/massif-press/compcon/assets/108127897/0ea498b1-7434-4a88-bbe7-03eae0ebe5cd)
would be the desired view?

**Comment by eschatonic** [comment]
> So in the end smth like this: [image] would be the desired view?

Yes, this would be perfect.

**Comment by msprijatelj** [comment]
@vialra this looks like what was requested! Please make a PR when you’re comfortable!

**Comment by vialra** [comment]
@msprijatelj done :)
