### ISSUE TITLE
[BUG] Cant access data because of my account

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2352]
<strong>Submitted At: </strong> 12/17/2023 12:19:40<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> wont open anything<br><br><strong>Reproduction Steps:<br> </strong> happens every time<br><br><strong>Expected Result:<br> </strong> I can access my pilots or mechs<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
Not a lot of context here and no way to reach out to the reporter. Not sure if it’s a temporary issue, an account login issue, or a browser issue. Closing due to lack of information
