### ISSUE TITLE
Bug Report: The frame view under Licenses on the character sheet does not show SP.

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#236]
<strong>Submitted At: </strong>6/9/2019 23:31:14
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Minor/Cosmetic (styling errors, misspellings, etc)
<strong>Issue Description: </strong>The frame view under Licenses on the character sheet does not show SP.
<strong>Reproduction Steps: </strong>Open a character, expand one of their licenses that are LL2 or greater, and click on the Frame link.  The compendium view that opens does not show the frame's SP.
<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
can't reproduce
