### ISSUE TITLE
[BUG] Small typo in many NHP systems

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2360]
<strong>Submitted At: </strong> 1/8/2024 18:02:13<br><br><strong>Source: </strong> LANCER Core Book<br><br><strong>Incorrect Text/Data: </strong><br> Most NHPs are missing the following rules text: "Your mech gains the AI tag"

I have checked NHPs from Core, KTB, Long Rim, and Wallflower. Of the NHPs included, only ATHENA seems to have this text; all others contain only the actions granted by the NHP. The list of NHPs checked:

SEKHMET
TLALOC
DIDYMOS
OSIRIS
SCYLLA
SISYPHUS
AGNI
ASURA
LUCIFER
NOAH

Although minor, the rules text is technically relevant as the AI tag on systems is not synonymous with granting the AI tag to the mech; UNCLE is a system with the AI tag that does not grant the AI tag to the mech. <br><br><strong>Correct Text/Data: </strong><br> <br>

**Comment by tomjel45** [comment]
Lcp issue most likely.
