### ISSUE TITLE
Bug Report: Dusk Wing has an extra flex mount

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#238]
<strong>Submitted At: </strong>6/10/2019 12:45:05
<strong>Platform: </strong>OSX
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>Dusk Wing has an extra flex mount
<strong>Reproduction Steps: </strong>extra flex mount is present on dusk wings on old pilots updated to the new system, unsure if it's present on new pilots' dusk wings
<strong>Contact Info: </strong>Radio Protector

**Comment by bargle0** [comment]
I've had this issue with the Hydra as well, also on OSX. I haven't been able to reproduce the issue by creating an otherwise identical pilot.
