### ISSUE TITLE
[BUG] Flex Mount from Improved Armament not valid for Superheavy Mounting Bracing 

### ISSUE THREAD

**Issue by theian212** [massif-press/compcon#2380]
**Describe the bug**
Hey I noticed if I have the superheavy mount and improved armament core bonuses I can't use the flex mount from improved armament to be a brace mount for the superheavy weapon from the superheavy mount,

**To Reproduce**
1. Go to Go mech in the mech hangar
2. Click on superheavy mount 
3. Scroll down to Mount

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by msprijatelj** [comment]
Duplicate of #2381
