### ISSUE TITLE
Bug Report: Terashima Blade not appearing

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#240]
<strong>Submitted At: </strong>6/10/2019 23:09:23
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Minor/Cosmetic (styling errors, misspellings, etc)
<strong>Issue Description: </strong>Terashima Blade not appearing
<strong>Reproduction Steps: </strong>Pilot has the following stats: had set under its atlas frame in mech hangar to have core "mount retrofitting" applied to its main mount; Terashima Blade doesn't appear in the options to outfit.

{"id":"h5fovqcg8ci","gistID":"","level":4,"callsign":"Lu Bu","name":"Temmie Illyas","text_appearance":"Just a badass girl piloting a mech suit","notes":"","history":"","portrait":"","cloud_portrait":"","quirk":"","current_hp":8,"active":true,"background":"priest","mechSkills":[1,3,2,0],"licenses":[{"id":"atlas","rank":3},{"id":"pegasus","rank":1}],"skills":[{"id":"readsituation","rank":2},{"id":"cool","rank":1},{"id":"gethold","rank":1},{"id":"threaten","rank":3},{"id":"assault","rank":1}],"talents":[{"id":"arms","rank":3},{"id":"duel","rank":2},{"id":"hunter","rank":1},{"id":"gunslinger","rank":1}],"core_bonuses":["retrofit"],"loadouts":[],"active_loadout":null,"mechs":[{"id":"qiw65z7md6k","name":"Lu Bu","notes":"","portrait":"","cloud_portrait":"","frame":"atlas","active":false,"current_structure":3,"current_hp":10,"current_stress":3,"current_heat":6,"current_repairs":3,"loadouts":[{"id":"jbu9dg7if5","name":"Primary Loadout","systems":[{"id":"hunterlock","notes":[]},{"id":"burst","notes":[]},{"id":"jagerkunst_1","notes":[]},{"id":"jagerkunst_2","notes":[]}],"mounts":[{"mount_type":"Flex","lock":false,"slots":[{"size":"Flex","weapon":null}],"extra":[{"size":"Auxiliary","weapon":null}],"bonus_effects":[]},{"mount_type":"Main/Aux","lock":false,"slots":[{"size":"Main","weapon":null},{"size":"Auxiliary","weapon":null}],"extra":[],"bonus_effects":[]},{"mount_type":"Flex","lock":false,"slots":[{"size":"Flex","weapon":null}],"extra":[{"size":"Auxiliary","weapon":null}],"bonus_effects":[]}],"improved_armament":{"mount_type":"Flex","lock":false,"slots":[{"size":"Flex","weapon":null}],"extra":[{"size":"Auxiliary","weapon":null}],"bonus_effects":[]},"integratedWeapon":{"mount_type":"Aux","lock":false,"slots":[{"size":"Auxiliary","weapon":null}],"extra":[],"bonus_effects":[]},"retrofitIndex":1,"retrofitOriginalType":"Main"}],"active_loadout":"jbu9dg7if5","cc_ver":"1.3.6"}],"active_mech":null,"cc_ver":"1.3.6"}
<strong>Contact Info: </strong>@crimson_qian

**Comment by aritsune** [comment]
terashima blade costs 1SP and this pilot's mech is using all its SP on systems
closing for now, although i might be missing something
