### ISSUE TITLE
Feature Request: A toggle-able dark mode function for the interface

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#246]
<strong>Submitted At: </strong>6/14/2019 22:59:41
<strong>Feature: </strong>Dark Mode
<strong>Details: </strong>A toggle-able dark mode function for the interface
<strong>Contact: </strong>Mico Mayhem#9616

**Comment by aritsune** [comment]
working on it #450

**Comment by aritsune** [comment]
as per beef on discord, we're waiting on this until we get input from Jay & get the colors down right, probably shortly after 2.0

**Comment by aritsune** [comment]
tracking this from #454 now
