### ISSUE TITLE
Minor Duplicate Bug[BUG] 

### ISSUE THREAD

**Issue by gavinragland** [massif-press/compcon#2462]
**Describe the bug**
When choosing to Duplicate a Pilot via the Pilot Roster page, the site adds an extra quotation mark at the end of the Callsign. Snip attached.

**To Reproduce**
1. Go to 'Pilot Roster' page
2. If you don't have an existing Pilot, create a new one.
3. Click the settings button
4. Choose Clone
5. Choose Duplicate

**Expected behavior**
Make a pure copy 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.3.1
 - Browser: Chrome
 - Version: 123.0.6312.87 

**Additional context**
Obviously a small issue, but I figured I'd toss it your way.

<img width="1103" alt="Screenshot 2024-05-09 at 11 32 19 AM" src="https://github.com/massif-press/compcon/assets/17618055/3abd4aea-5d63-45dc-8ef6-0abe7e206281">

**Comment by msprijatelj** [comment]
This isn’t a bug; it’s an intentional mark used to indicate a copy or clone. Are you requesting that a different mark be used instead?

**Comment by gavinragland** [comment]
Ah I see. I thought it was a bug as Duplicating also marks the Pilot's name with (COPY). If it isn't a bug, then no issues, sorry for the confusion.
