### ISSUE TITLE
[FEATURE] Add storage limit warning message

### ISSUE THREAD

**Issue by nimoooos** [massif-press/compcon#2486]
It's a pretty common issue when people make too many pilots or load too many LCPs, compcon throws an error and it's pretty difficult to resolve on their own. 

A simple warning message about browser in the lcp loading menu can help inform users about this issue without much development time added.

Some alternate solutions include:
* Adding this warning messages everywhere that involves browser storage (might be ignored if used too much)
* Displaying how close you are to storage limit (might be difficult for little benefit)
* Also including how to see how close you are to storage limit (could be fine)

**Comment by jarena3** [comment]
hotfixing this one in right now
