### ISSUE TITLE
[BUG] QR code no worky

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2501]
<strong>Submitted At: </strong> 8/20/2024 23:11:19<br><br><strong>Source: </strong> LANCER Core Book<br><br><strong>Incorrect Text/Data: </strong><br> You don't have access to this page
This download page has been disabled and is no longer available.<br><br><strong>Correct Text/Data: </strong><br> Here is you PDF and NPC options are now open<br>

**Comment by msprijatelj** [comment]
This is an issue that should be brought up to massifpress@gmail.com or itch.io, not with CompCon.
