### ISSUE TITLE
[BUG] App version not updating on Chrome

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#2508]
<strong>Submitted At: </strong> 8/22/2024 18:48:24<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When I load I'm stuck on V2.2.32 <br><br><strong>Reproduction Steps:<br> </strong> Checking for updates does nothing. Going to Options > Download updates and Reload doesn't update.<br><br><strong>Expected Result:<br> </strong> App to update to <br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

**Comment by msprijatelj** [comment]
This is a known issue, and the workaround can be found here: https://github.com/massif-press/compcon/wiki/Troubleshooting-Issues#compcon-is-stuck-on-an-older-version-than-230-how-do-i-update-to-the-latest-version

There's not currently a clear fix for this issue so it's recommended to follow this workaround. Seeing as there's no contact information for a follow-up, I will close this issue.
