### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by infinitenovav** [massif-press/compcon#2530]
**Describe the bug**
Asking for a verification code to reset account login information doesn't work. Clicking "forgot password" results in compcon sending me a verification code that doesn't work. Also, my login information (saved on my browser) isn't working anymore, even though I haven't changed my password.

**To Reproduce**
1. Go to ' login'
2. Click on "sign in'
3. See error "Incorrect username or password. NotAuthorizedException"
4. clicking forgot password leads to an email with a verification code being sent
5. clicking "click here to use verification code" does nothing.

**Expected behavior**
Log in

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox and Chrome

**Comment by msprijatelj** [comment]
Can you confirm that you've followed all the steps from [this FAQ entry](https://github.com/massif-press/compcon/wiki/Troubleshooting-Issues#how-do-i-verify-my-compcon-account) to the letter? Particularly Steps 3 and 5?

**Comment by infinitenovav** [comment]
I did confirm that the email is correct on both the initial box and after I
click on the verify email link. Resending the verification email does not
seem to work

**Comment by infinitenovav** [comment]
Actually I was able to finally change my password. Sorry for the confusion

**Comment by msprijatelj** [comment]
All good, glad this has been addressed. Closing for now.
