### ISSUE TITLE
[BUG] A simple but annoying problem -> Can't edit the name of mechs in the hangars after creation

### ISSUE THREAD

**Issue by Cytok1n3** [massif-press/compcon#2577]
**Describe the bug**
Generally, after a mech is made, there would be a button to immediately edit the name of the mech after opening it up, right next to mech's name. However, sometime this month, it disappeared after an update.

**Location of 'Problem'**
1. Go to 'Pilot Roster' and select any pilot
2. Go to 'Mech Hangar' and select any mech
3. Look next to the name of the mech, the edit button is unavailable

**Expectation**
The edit button is supposed to be there, simple, but annoying.

**Screenshots**
![Screenshot 2024-12-19 202939](https://github.com/user-attachments/assets/552d5ea1-0341-426e-9ab6-bfd360f0ef20)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Avast Secure Browser
 - Version: If it means the OS, Windows 11, otherwise, I have no idea

**Note**
I understand this is a minor problem - I can simply delete the mech and write the new name when I create it again - but it's a bit frustrating and tiring. If anyone can fix this, I will be grateful for your help and support. Also, the screenshot will show a error relating to the network but I'm pretty sure that was never the cause, as it was always like that before the edit button went missing whenever I used Netlimiter. Thanks & CHEERIO!

**Comment by msprijatelj** [comment]
See the bottom left corner of the same nameplate for the button you're searching for. (Also consider replacing this screenshot with one with less info like your tabs & bookmarks.)

**Comment by Cytok1n3** [comment]
> See the bottom left corner of the same nameplate for the button you're searching for. (Also consider replacing this screenshot with one with less info like your tabs & bookmarks.)

Thanks, didn't notice that. Problem solved!
