### ISSUE TITLE
Bug Report: Navigating left-to-right between Loadout tabs causes screen to 'jump' upward

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#264]
<strong>Submitted At: </strong>6/24/2019 1:23:30
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Minor/Cosmetic (styling errors, misspellings, etc)
<strong>Issue Description: </strong>Navigating left-to-right between Loadout tabs causes screen to 'jump' upward
<strong>Reproduction Steps: </strong>1. Select a Pilot or Mech
2. Create multiple Gear Loadouts (but not more than 3 for Pilot Gear - see bug ticket #263)
3. Scroll down as far as possible while still being able to access the Loadout selection tabs
4. Select the Leftmost Loadout
5. Select any Loadout to the right of the currently selected Loadout
6. Observe screen 'jumping' up. For Pilot Gear it seems to align the screen with the last 'Gear' field, but with Mech loadouts it moves up enough to obscure most of the Loadout

Note this does not occur when move right-to-left between loadout tabs

<strong>Contact Info: </strong>Discord: ashkaun#5579

**Comment by aritsune** [comment]
Fixed in v2 as we no longer use v-tabs for loadouts.
