### ISSUE TITLE
Feature Request: Close Pop-Up Dialogs with Esc

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#267]
<strong>Submitted At: </strong>6/24/2019 1:37:56
<strong>Feature: </strong>Close Pop-Up Dialogs with Esc
<strong>Details: </strong>Currently some dialog windows (Options, About, Help, Custom Image UI, Add New Mech, etc) allow the user to close them with the Esc key, but many others (Export/Duplicate/Delete Configuration, Add New Pilot, Rename/Delete Loadout, probably more) just bounce when the users tries to close them with the Esc key. Aligning functionality with those dialog windows that properly make use of the Esc key would be great.
<strong>Contact: </strong>Discord: ashkaun#5579

**Comment by Isoptera** [comment]
Wanna add to this to my original ticket now that GM toolkit is in beta - it would be awesome if the GM toolkit hamburger menu could also be closed with Esc~
