### ISSUE TITLE
Bug Report: The enemy type labels (striker, defender, etc) in the NPC designer are visible through the blue bar on top of the window.

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#289]
<strong>Submitted At: </strong>7/12/2019 15:03:22
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Minor/Cosmetic (styling errors, misspellings, etc)
<strong>Issue Description: </strong>The enemy type labels (striker, defender, etc) in the NPC designer are visible through the blue bar on top of the window.
<strong>Reproduction Steps: </strong>Self explanatory
<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
fixed in https://github.com/massif-press/compcon/commit/63365da7bc679aef2e8a40f2e67b28415cde5640
