### ISSUE TITLE
Feature Request: Sorting/organization system for NPCs

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#293]
<strong>Submitted At: </strong>7/12/2019 21:19:27
<strong>Feature: </strong>Sorting/organization system for NPCs
<strong>Details: </strong>A system in the COMP/CON's GM toolkit, that allows GMs to arrange created NPCs into folders with the ability for the GM to name and move the folders around. 
<strong>Contact: </strong>

**Comment by aritsune** [comment]
Added in v2
