### ISSUE TITLE
Bug Report: Encounters cannot be deleted

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#297]
<strong>Submitted At: </strong>7/13/2019 10:42:57
<strong>Platform: </strong>Windows
<strong>Severity: </strong>High (problem that impairs software function, bad or missing game mechanic implementation)
<strong>Issue Description: </strong>Encounters cannot be deleted
<strong>Reproduction Steps: </strong>Create an active encounter, then attempt to delete it.
<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
Duplicate of #292
