### ISSUE TITLE
Bug Report: "Recharge" weapons on NPCs do not function according to the game manual

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#298]
<strong>Submitted At: </strong>7/13/2019 10:46:07
<strong>Platform: </strong>Windows
<strong>Severity: </strong>High (problem that impairs software function, bad or missing game mechanic implementation)
<strong>Issue Description: </strong>"Recharge" weapons on NPCs do not function according to the game manual
<strong>Reproduction Steps: </strong>Create an NPC with multiple recharging weapons (e.g. Witch). During an active encounter, each recharging weapon must make its own roll to recharge. However, the PR2 book has each NPC making one roll for all modules.
<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
Too complex to fix in this pass since recharge isn't handled on the NPC back end, only in the UI. Will just remove recharge button functionality for now (keeping the checkbox though)

**Comment by aritsune** [comment]
collected in #550
