### ISSUE TITLE
Make design responsive for tablet/phone screens

### ISSUE THREAD

**Issue by aritsune** [massif-press/compcon#300]
Mobile versions are planned. Making this issue to refer to when closing requests for it since we get them a lot.
~Will probably be written in Nativescript.~

**Comment by Ignus3** [comment]
Thanks, I looked everywhere for this before posting about it, but I wanted to make sure to speak up and add my voice as a plus one for the mobile version request. I'll try to keep an eye on this post for any requests for volunteer help or commits or anything

**Comment by aritsune** [comment]
The plan for mobile versions has changed - we're now going to provide these via the https://compcon.app web version: it already loads on mobile OSes, we just need to make the UI responsive. It's a PWA with a manifest & service worker, so it works offline and can be "installed" with most browsers for a closer-to-native experience.

Since we're using Capacitor for cross-platform APIs, it would be possible to eventually make a bonafide Android app, and possibly even an iOS one if we end up paying the Apple Developer Tithe to get Catalina to work. However this might be too much work for not enough of a benefit, considering a PWA can already accomplish everything we'd want out of a mobile version.
