### ISSUE TITLE
Bug Report: Unable to delete an active encounter 

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#306]
<strong>Submitted At: </strong>7/14/2019 19:36:26
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>Unable to delete an active encounter 
<strong>Reproduction Steps: </strong>create an active encounter, then attempt to delete it. 
<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
Duplicate of #292 which is fixed
