### ISSUE TITLE
Feature Request: Make an export to PFD of characters and mechs

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#307]
<strong>Submitted At: </strong>7/14/2019 19:50:44
<strong>Feature: </strong>Make an export to PFD of characters and mechs
<strong>Details: </strong>There is no option avaliable of exporting character or mechs to PDF, and could be really usefull if you want to have it in your phone or other device
<strong>Contact: </strong>Discord: Supercapos#1236

**Comment by aritsune** [comment]
A lot of platforms offer a "print to PDF" pseudo-printer, but I'm not sure how common the feature actually is. Should look into that.

**Comment by aritsune** [comment]
after researching it seems like windows and mac offer this feature natively for all prints, and most full-featured linux distros have it too, so I don't think we need to add it as a feature of c/c (which would almost definitely add dependencies). I'm curious what platform the reporter is on that they didn't get this option.

up to you whether to keep this open @jarena3

**Comment by jarena3** [comment]
I think it's safe to close. We may eventually move to exclusively PDF output as printing gets more complicated, but for the request above I think it can safely rest on the user to get a psuedo-printer
