### ISSUE TITLE
Feature Request: Linux 32-bit version

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#310]
<strong>Submitted At: </strong>7/15/2019 12:32:36
<strong>Feature: </strong>Linux 32-bit version
<strong>Details: </strong>The current Linux AppImage seems to only work for 64-bit architecture, and a 32-bit version would be nice. Thank you!
<strong>Contact: </strong>

**Comment by CommanderTso** [comment]
Do you have any info on the person that requested this?  It'd be helpful for them to be able to test it works.
