### ISSUE TITLE
Bug Report: Long name NPCs can't be deleted from Encounter Builder

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#313]
<strong>Submitted At: </strong>7/15/2019 22:01:51
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>Long name NPCs can't be deleted from Encounter Builder
<strong>Reproduction Steps: </strong>Found in 1.5.1 Beta

1. Make an NPC with a super long name (50-60 uppercase characters)
2. Add NPC to an encounter in the Encounter Builder tab
3. Note delete icon is obscured because of long name

If you rename the NPC to something shorter the icon is accessible, so that's a simple workaround.
<strong>Contact Info: </strong>Buppi#6833

**Comment by CoreyT355** [comment]
Did this get closed by accident? I am still seeing the bug in latest dev branch. I have a potential fix for it I can PR if you'd like to reopen.
