### ISSUE TITLE
Feature Request: Monstrosities in NPC editor

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#323]
<strong>Submitted At: </strong>7/16/2019 14:39:47
<strong>Feature: </strong>Monstrosities in NPC editor
<strong>Details: </strong>Add in monstrosities in the NPC builder tool, and/or the option to make any of the given NPCs a biological entity capable of receiving the monstrosity bonus modules (like building a Pyro that also has claws and wings).
<strong>Contact: </strong>

**Comment by Eranziel** [comment]
Can probably be closed.
