### ISSUE TITLE
Feature Request: Charges counter for talents and certain weapons (barbarossa's, sherman's)

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#339]
<strong>Submitted At: </strong>7/30/2019 17:33:00
<strong>Feature: </strong>Charges counter for talents and certain weapons (barbarossa's, sherman's)
<strong>Details: </strong>the ability to track how many charges you have on certain cases such as talents (Brawler, Gunslinger, Duelist and so on) and weapons (E.G. Sherman's ZONE FOCUS MK IV SOLIDCORE)

P.S. sorry for the redundant ping on discord
<strong>Contact: </strong>Corvon#2560

**Comment by aritsune** [comment]
I'd like to propose a solution for this: a "counters" API which creates a way for compendium items (frames, weapons, talents...) to provide counters that can be tracked in Active Mode, including defining min/max values, etc. They would show up in a section at the bottom of Active Mode - we should probably allow for custom counters to be added by users as well.
This could also be a lazy way to implement the "rollable uses" for Enginner weapons.

**Comment by aritsune** [comment]
Since this would be a pretty simple API we could just embed it into the JSON data. However, we're autoparsing the compendium data now and this is a bit complex for a parser to infer. Maybe we could have a "mask" file that we apply to the parsed data to add the counter info?

**Comment by aritsune** [comment]
@Eranziel ^

**Comment by Eranziel** [comment]
I agree on putting it into the JSON, should be simple. Make it a sub-object with a few fields? (Name, id, min, max, starting?)

There is already a few things the auto parser can't handle (RA text, and we have a few hidden tags that need to be manually retained). A "mask" file could work well for those, too.

**Comment by aritsune** [comment]
Resolved in v2 by #448
