### ISSUE TITLE
Bug Report: When more of the same item is in a column and one of them is destroyed, all of that item is destroyed.

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#348]
<strong>Submitted At: </strong>8/3/2019 21:21:05
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>When more of the same item is in a column and one of them is destroyed, all of that item is destroyed.
<strong>Reproduction Steps: </strong>Using the hydra mecha, add three tempest nexus onto the sheet one after the other. When in active play mode and one of the items is labeled as destroyed, of the items with that name are also labeled as destroyed.
<strong>Contact Info: </strong>Kisato the XIII #9372

**Comment by Qwertronix** [comment]
Definitely seems fixed in 1.5.3 beta.
