### ISSUE TITLE
Feature Request: The ability to tick off HP, Heat and other variables

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#35]
<strong>Submitted At: </strong>3/28/2019 17:56:15
<strong>Feature: </strong>The ablity to tick off HP, Heat and other variables
<strong>Details: </strong>Right now, a feature that would make COMP/CON an 11/10 program would be the ability to allow the user to treat the player sheet as their actual digital player sheet without having to print it (naturally showing any negative effects from things like building heat or having system damage if there is any). It would make the program an objectively better option compared to Roll20's sheet or just printing the sheet (gotta save the trees, go digital)

**Comment by Fireyheart** [comment]
@jarena3 

For this, would the different indicators just be selectable? Is there any calculation that needs to be done when say, Heat reaches a certain thresh hold?

**Comment by jarena3** [comment]
Eventually, yes, there would be things that could happen as indicators change (eg the Tachyon Lance in the danger zone), and there would be mechanics we could guide or automate (structure/stress and rolling on their respective tables) but for the first pass it will probably only be selectable indicators, yeah

**Comment by Fireyheart** [comment]
I haven't done any Vue work but I've done a substantial amount of React and I can take a crack at this.

**Comment by jarena3** [comment]
For sure! The more the merrier!
Something to keep in mind though is that right now (like literally right this moment) @aritsune and I are working on porting the whole mess over to typescript & working on a refactor. if you're interested in jumping in you might want to hold off until we merge `typescript` into `dev`

**Comment by Fireyheart** [comment]
This implementation would most likely be part of the full enablement of the app for a live character sheet. 

I have some rough ideas of what that would look like but after the refactor I'll probably have a more educated opinion.
