### ISSUE TITLE
Bug Report: When HP drops to 0 and the structure is removed, the dice automatically rolls 0d6.

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#351]
<strong>Submitted At: </strong>8/6/2019 17:16:19
<strong>Platform: </strong>OSX
<strong>Severity: </strong>High (problem that impairs software function, bad or missing game mechanic implementation)
<strong>Issue Description: </strong>When HP drops to 0 and the structure is removed, the dice automatically rolls 0d6.
<strong>Reproduction Steps: </strong>Manually set mech hp to 0 and hit enter.

<strong>Contact Info: </strong>Kisato the XIII#9372

**Comment by tonny890h** [comment]
**Platform:** Windows
**Version:** 1.5.3

**Comment by jarena3** [comment]
I'm unable reproduce this issue -- when a point of structure damage is removed by HP loss, the system damage dialog seems to have the correct dice quantity set.
@kisatoto could you explain in more detail what you see and what you expect to see? I'm wondering if this is a rules interpretation issue

**Comment by jarena3** [comment]
Closing -- unable to reproduce
