### ISSUE TITLE
Bug Report: Blank pilot sheet

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#353]
<strong>Submitted At: </strong>8/9/2019 8:50:45
<strong>Platform: </strong>Windows
<strong>Severity: </strong>High (problem that impairs software function, bad or missing game mechanic implementation)
<strong>Issue Description: </strong>Blank pilot sheet
<strong>Reproduction Steps: </strong>After pilot creation, the pilot sheet page is completely blank. The active pilot sheet displays the correct information but with no way to level the pilot.
<strong>Contact Info: </strong>

**Comment by Qwertronix** [comment]
As of current /dev commit, it seems PilotSheet is trying to display numbers directly from the PilotLoadout's armor, with no fallback if there is no selected loadout (getting loadout returns 'undefined', can't access Armor of undefined).

**Comment by jarena3** [comment]
this has been corrected in the latest beta version
