### ISSUE TITLE
Feature Request: Adding Special Classes to the NPC Builder

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#364]
<strong>Submitted At: </strong>8/20/2019 13:54:22
<strong>Feature: </strong>Adding Special Classes to the NPC Builder
<strong>Details: </strong>The NPC Builder is wonderful, but it still lacks the option of creating Infantry Squads or Monstrosities.
<strong>Contact: </strong>Squirx#3388

**Comment by Eranziel** [comment]
This can probably be closed.
