### ISSUE TITLE
Bug Report: NPCs Loading with Wrong Systems

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#369]
<strong>Submitted At: </strong>8/31/2019 16:13:38
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>NPCs Loading with Wrong Systems
<strong>Reproduction Steps: </strong>Create a Cataphract NPC, add the Charge system, click Done. Close CompCon and reopen. Edit the previously saved Cataphract, it will now have the Berserker's Charge system. Should also occur with any other NPC classes that duplicate system names.
<strong>Contact Info: </strong>Andarel#9616

**Comment by Eranziel** [comment]
This happens because the system names are identical, and the serialized NPC only contains the name of added systems. When CompCon is closed and then reopened, the NPC is deserialized and the system is populated with the first match from the NPC systems library.

**Comment by aritsune** [comment]
This shouldn't happen anymore with the new NPC backend in v2.
