### ISSUE TITLE
Bug Report: Get Focused does not add a bonus point when adding triggers through level up

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#374]
<strong>Submitted At: </strong>9/9/2019 7:51:10
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>The get focused downtime activity does not add a bonus point to the trigger list. This means that if you use get focused on your next level up it assumes you've already bought your max amount of triggers and you have to delete get focused to get your level trigger and then recreate get focused.
<strong>Reproduction Steps: </strong>Use the get focused downtime activity in active tracker, then level up the pilot.
<strong>Contact Info: </strong>Zieche8902

**Comment by aritsune** [comment]
Fixed via reserves in v2.
