### ISSUE TITLE
Bug Report: Mech Loadout not appearing and deleting the wrong Loadout

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#378]
<strong>Submitted At: </strong>9/16/2019 19:16:25
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>Mech Loadout not appearing and deleting the wrong Loadout
<strong>Reproduction Steps: </strong>In the Mech Hangar on a character with more than one mech and each with only one loadout (Primary), switching between the mechs using the little drop-down with the character name on the top right corner, makes it so no loadout appears under Primary. The work around I found is to add a new Secondary loadout to one of the mechs (can be empty) and switch back to viewing the Primary. It seems that if at least one of the two mechs has a secondary, the problem doesn't pop up, so it might just be a problem with only when there's 2 mechs minimum, 1 loadout each. I have not named any of the loadouts.

Also while testing this I noticed that if I tried deleting the Secondary it just deletes the Primary instead... Happens only when I create a secondary (doesn't have to be empty), switch to a different mech through the same method, switch back to the one with 2 loadouts, and then try deleting the Secondary. Primary's completely gone and the Secondary just moves in from the right even though I was just looking at it.   Not sure if it's a separate issue, but I can tell you that's *much* more frustrating lol. 
<strong>Contact Info: </strong>CounterShift#6635

**Comment by aritsune** [comment]
Can't reproduce in v2.
