### ISSUE TITLE
Bug Report: Integrated weapon from Engineer cannot roll uses or display number of uses in any way

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#379]
<strong>Submitted At: </strong>9/16/2019 21:13:40
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Minor/Cosmetic (styling errors, misspellings, etc)
<strong>Issue Description: </strong>Integrated weapon from Engineer cannot roll uses or display number of uses in any way
<strong>Reproduction Steps: </strong>Take Engineer during character creation
<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
Duplicate of #288
