### ISSUE TITLE
Feature Request: A Timeline/Campaign Manager

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#380]
<strong>Submitted At: </strong>9/16/2019 23:36:16
<strong>Feature: </strong>A Timeline/Campaign Manager
<strong>Details: </strong>      It would be a set timeline designed with boxes and tabs (that connect to the timeline) to help better organize the campaign. It is divided into Mechanics and Narrative. 
      Mechanics are tabs that record the functional parts of the game, like downtime, preparation, scenes, narrative action, combats, encounters, and an outline of the mission, its goal, and its stakes.
      Narrative are the tabs where the GM can write down the main points of their story in relation to the timeline. There should also be a place where the GM can write down blurbs, notes, and deviations from the story. And also hopefully a place where the GM can keep track of the story arc(s), overarching story arc(s), subplot arc(s), and character arc(s) 
      Apologies for the large amount of new work, especially with how heavy these demands are; or at least I'm assuming so, I've barely an idea how programming works. There's also a chance that you've already been planning to add a campaign manager, and so it was pointless to write this down.
<strong>Contact: </strong>@WandererSimple

**Comment by Qwertronix** [comment]
Some stuff out of this, or extrapolated, or just other related ideas that I definitely think most GMs could find useful: 

- Campaigns
  - grouping of everything below, kept separate per-campaign, for running multiple
- Scenes
  - Linking Encounters to a Scene
  - Scene description, usage notes, planned vs played status
  - History of previous scenes
  - Displaying unused scenes "on deck" for jumping into those during session
- Missions
  - Mission brief
    - goals
    - stakes
    - actors
  - Opfor / factions involved
    - Force composition
    - Objectives
    - (optionally) link to a persistent, independent Faction entry?
- Actors / Factions (AKA NPC/faction roster)
  - profiles, links to Scenes/missions where they're involved, to other actors/factions?
  - would implement https://github.com/massif-press/compcon/projects/7#card-20488672
- Notes
  - link scenes/missions/actors to/from notes
- State tracker
  - state of the PC party and any other important details at a specific moment
  - include local GM notes never sync'd with the character
  - history/timeline feature?
    - memoization of all campaign state into a single history track
  - interop with https://github.com/massif-press/compcon/issues/221 to load and resume play

**Comment by claman** [comment]
It seems like this might be a big enough project to push it back to either v2.5 or even v3?
