### ISSUE TITLE
Feature Request: An account or something that is able to link devices.

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#382]
<strong>Submitted At: </strong>9/19/2019 18:36:14
<strong>Feature: </strong>An account or something that is able to link devices.
<strong>Details: </strong>Exactly what the title says. I just need something can link a single Compcon to separate devices.
<strong>Contact: </strong>@WandererSimple

**Comment by aritsune** [comment]
tracking this from #453 now
