### ISSUE TITLE
Bug Report: The tooltip for the Minotaur's metafold carver is still the prerelease version 1 tooltip 

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#388]
<strong>Submitted At: </strong>10/1/2019 12:29:40
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Minor/Cosmetic (styling errors, misspellings, etc)
<strong>Issue Description: </strong>The tooltip for the Minotaur's metafold carver is still the prerelease version 1 tooltip 
<strong>Reproduction Steps: </strong>Go into the mech hangar and equip the metafold Carver 
<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
Compendium data will be resourced from scratch from the release PDF in v2.
