### ISSUE TITLE
Feature Request: Localization/Translation

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#390]
<strong>Submitted At: </strong>10/3/2019 13:38:25
<strong>Feature: </strong>Localization/Translation
<strong>Details: </strong>Tools to translate Comp/Con's UI components labels and items descriptions.These modifications affect the printing output too.
<strong>Contact: </strong>

**Comment by aritsune** [comment]
@jarena3 are we planning on doing this? vuetify does have an i18n system built in, however i'm not sure if it's in scope for c/c to translate lancer unless the game itself gets officially translated. also, we would either have to either completely redo the way we store compendium data or accept having a translated UI along with english compendium data

**Comment by jarena3** [comment]
We may, but it'll depend on where Lancer goes. Tom and Miguel want translations, but as a Lancer Season 2 thing. I think it's safe to close this one for now and readdress it in the future
