### ISSUE TITLE
Bug Report: Incorrect SP calculation

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#393]
<strong>Submitted At: </strong>10/18/2019 6:45:18
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>Incorrect SP calculation
<strong>Reproduction Steps: </strong>Create a LL2 pilot.
Add no points to Systems
Add two levels to Monarch Mech License
Equip mech systems worth 3SP and Gandiva Missiles (1 SP).
You should have 2 SP left.
Add Stabilizer Mod (2 SP) to Gandiva Missiles
Notice you can't.

Adding the mod to a weapon that doesn't cost SP itself works fine.
Issue seems to be related to weapons with inherent SP costs.
<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
Can't reproduce in v2, assuming fixed.
