### ISSUE TITLE
Bug Report: For pilots at license level 1+ the "Edit Pilot Talents" page warns you if you have ranks in less than 3 talents despite it being possible to have ranks in only 2 talents through the retrofitting rules

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#394]
<strong>Submitted At: </strong>10/18/2019 17:59:35
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>For pilots at license level 1+ the "Edit Pilot Talents" page warns you if you have ranks in less than 3 talents despite it being possible to have ranks in only 2 talents through the retrofitting rules
<strong>Reproduction Steps: </strong>On a new pilot after going through the level up process once click the "Edit Pilot Talents" button, select a talent that has ranks in it and unlearn it. The warning "Must select a minimum of 3 talents" appears.
<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
It's a little unintuitive but after reading the rules (page 18) the reporter is right, you should be able to do this. Seems like the 3 talents rule should only apply during creation.

**Comment by aritsune** [comment]
Waiting for input from Tom on this

**Comment by aritsune** [comment]
Tom said it should indeed be allowed, working on it
