### ISSUE TITLE
Feature Request: Ability to export GM data

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#395]
<strong>Submitted At: </strong>10/18/2019 23:09:04
<strong>Feature: </strong>Ability to export encounters
<strong>Details: </strong>Ability to export encounters and the NPCs therein for use on other computers
<strong>Contact: </strong>

**Comment by claman** [comment]
are you envisioning this as a PDF with all of the information, or a ZIP file that could then be imported into other CompCon instances?

**Comment by aritsune** [comment]
@jarena3 do you plan on getting this out before v2 release or should I change the milestone to v2.1?

**Comment by jarena3** [comment]
This is mostly (individual NPCs and all C/C data) in v2 now. There's another level of encounter/mission exporting that I'm going to hold off on until campaign management.
