### ISSUE TITLE
Compendium Frame view does not show integrated weapon tags

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#396]
<strong>Submitted At: </strong>10/19/2019 15:57:06
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>In the compendium, frame integrated weapons (e.g. Sherman SOLIDCORE) display the tags of the frame's CORE power, instead of their own tags. In the case of the SOLIDCORE, it displays the Protocol tag instead of the Ordnance tag. This doesn't happen when the frame is used to build a mech - in the mech loadout and active play mode screens, the correct tags are applied to the weapon.
<strong>Reproduction Steps: </strong>View a frame with an integrated weapon that has tags in the Compendium, either in the License browser or the Frame browser. (Note that the Sherman's SOLIDCORE is missing the Ordnance tag in current releases, so it can't be used as a test case unless you add the tag.) 
<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
Actually a data error, tags should be displaying fine according to the code. None of the integrated weapons have their tags set in the current lancer-data, but that should be fixed with the data re-do.

Closing.
