### ISSUE TITLE
Bug Report: When filtering for a specific license in the compendium system and weapon browsers, frames which have a space in the name show zero results.

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#397]
<strong>Submitted At: </strong>10/19/2019 22:24:06
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>When filtering for a specific license in the compendium system and weapon browsers, frames which have a space in the name show zero results.
<strong>Reproduction Steps: </strong>Go to Compendium -> Systems or Weapons. Filter for a specific license with a space in the name, like Black Witch or Death's Head. No results are shown.
<strong>Contact Info: </strong>

**Comment by Eranziel** [comment]
Figured out what's going on here. The license filter is filtering with the license id (i.e. "bwitch"), but systems/weapons use the license's full name (i.e. "BLACK WITCH"). 

Would the "right" way to fix this be changing all of the systems/weapons to use the license id instead? It feels like that's a bigger change than just fixing the license filter. This might be something you've looked at in v2 already, too.

**Comment by aritsune** [comment]
Closing this as you can no longer filter by frame in v2.
