### ISSUE TITLE
Bug Report: av_buffer_create not found

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#398]
<strong>Submitted At: </strong>10/24/2019 11:45:10
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Catastrophic (causes software to crash and/or corruption of saved data)
<strong>Issue Description: </strong>av_buffer_create not found
<strong>Reproduction Steps: </strong>none
<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
Not enough detail given to know how to investigate this & no contact info provided, so I'm closing this.
