### ISSUE TITLE
Bug Report: When I run the program it only launches as a background process and won't actually open.

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#400]
<strong>Submitted At: </strong>10/26/2019 22:23:45
<strong>Platform: </strong>Windows
<strong>Severity: </strong>High (problem that impairs software function, bad or missing game mechanic implementation)
<strong>Issue Description: </strong>When I run the program it only launches as a background process and won't actually open.
<strong>Reproduction Steps: </strong>I downloaded it, ran it, Windows asked me if I trusted it, I said yes, it only opened in the background. Can't do anything.
<strong>Contact Info: </strong>@MIHistoryGuy on Twitter

**Comment by aritsune** [comment]
User seems to no longer have the issue.
