### ISSUE TITLE
Bug Report: Applying a tier to an NPC removes extra structure/stress applied by the veteran trait

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#401]
<strong>Submitted At: </strong>10/27/2019 14:33:29
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>Applying a tier to an NPC removes extra structure/stress applied by the veteran trait
<strong>Reproduction Steps: </strong>1. Create any new NPC
2. Set it to tier 2
3. add veteran: it loses its stress/structure values and will not gain any more when given veteran status again. I'm guessing this MIGHT be a negative number issue where stress/structure is subtracted to be 0 or something, where the application won't show your stress/structure @ <=1. 
4. This I think is the crux of the issue: make it so that stress/structure is always shown so that the editor can always change these stats, otherwise you can't adjust stress/structure 
<strong>Contact Info: </strong>Nice#0367

**Comment by aritsune** [comment]
Waiting until we have this functionality in v2 to verify and close this.

**Comment by jarena3** [comment]
fixed in v2
