### ISSUE TITLE
Bug Report: Balor is missing a trait

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#402]
<strong>Submitted At: </strong>10/27/2019 14:34:19
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>Balor is missing a trait
<strong>Reproduction Steps: </strong>The Balor is missing the Self-Replicating trait from the frame traits where it automatically repairs during a rest. 
<strong>Contact Info: </strong>Nice#0367

**Comment by aritsune** [comment]
Compendium will be redone from scratch in v2
