### ISSUE TITLE
Feature Request: Lock the Table Header Row

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#404]
<strong>Submitted At: </strong>11/1/2019 6:40:24
<strong>Feature: </strong>Lock the Table Header Row
<strong>Details: </strong>When I scroll down in a table with many rows, I want to always see the column headers. Basically, make only the table contents scroll and not the table headers.

Thanks!
<strong>Contact: </strong>

**Comment by aritsune** [comment]
Duplicate of #93
