### ISSUE TITLE
Bug Report: When using the Elite and Veteran templates the NPCs Structure/Stress will not be modified properly.

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#406]
<strong>Submitted At: </strong>11/7/2019 7:12:20
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Minor/Cosmetic (styling errors, misspellings, etc)
<strong>Issue Description: </strong>When using the Elite and Veteran templates the NPCs Structure/Stress will not be modified properly.
<strong>Reproduction Steps: </strong>If you add the 'Veteran' elite template 1st, and then add the 'Elite' template 2nd, a NPC will only have 2 Structure/Stress, instead of the proper 3. However, if you add Elite first then it will work and display 3 Structure/Stress.
<strong>Contact Info: </strong>

**Comment by Eranziel** [comment]
Pretty sure this is someone using an old version - that used to be the behaviour, since Elite used to set structure/stress to 2 instead of adding 1. 

I can't reproduce on 1.5.6, adding Elite/Veteran/Commander in any order results in +1 structure/stress for each of them.
