### ISSUE TITLE
Bug Report: Mech loadouts have been missing two times after closing out of comp/con

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#407]
<strong>Submitted At: </strong>11/10/2019 12:18:01
<strong>Platform: </strong>OSX
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>Mech loadouts have been missing two times after closing out of comp/con
<strong>Reproduction Steps: </strong>Created a mech loadout. Close out of Comp/Con. Reboot Comp/Con and go to Mech Hangar
<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
Not enough info to reproduce. Either way there's been enough refactoring done in v2 that this is likely no longer a problem.
