### ISSUE TITLE
Bug Report: Made a drone Ultra NPC unit with (what I think is the problem peice) the SSC silvershielding. Everytime I open up the gm toolkit and look at the NPC it loses 5hp. THis continues into the negative, at which point it cause the encounter runner to have a fit if I try to manualy adjust the Hp. 

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#413]
<strong>Submitted At: </strong>11/18/2019 15:47:48
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>Made a drone Ultra NPC unit with (what I think is the problem peice) the SSC silvershielding. Everytime I open up the gm toolkit and look at the NPC it loses 5hp. THis continues into the negative, at which point it cause the encounter runner to have a fit if I try to manualy adjust the Hp. 
<strong>Reproduction Steps: </strong>Install SSC Silvershield on a NPC, return to comp/com and then reopen the gm toolkit, the NPC will have 5 less health. In the encounter runner, once in the negatives, trying to manually adjust the HP locks Comp/Com. I am using the unstable build 1.5.6
<strong>Contact Info: </strong>TDawg#3394

**Comment by aritsune** [comment]
Closing as in v2 generic optional systems were removed & the backend was reworked - this is unlikely to still be a relevant issue
