### ISSUE TITLE
Feature Request: GM Tools - NPC Share Codes / Import Function

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#414]
<strong>Submitted At: </strong>11/23/2019 23:53:07
<strong>Feature: </strong>GM Tools - NPC Share Codes / Import Function
<strong>Details: </strong>When editing a NPC, have a button to generate a hashed code, text block, or .JSON for sharing the NPC with other GMs and a function to import from the code/.JSON; this can also lead to sharing encounters built from NPCs if a text block can be generated from the NPC list / module list
<strong>Contact: </strong>Cpt. Clem Cuddlecakes

**Comment by aritsune** [comment]
#395
