### ISSUE TITLE
Bug Report: I just updated my computer to MAC OS Catalina so that might be the reason why, but it hasn't even opened for me.

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#415]
<strong>Submitted At: </strong>11/24/2019 9:27:16
<strong>Platform: </strong>OSX
<strong>Severity: </strong>High (problem that impairs software function, bad or missing game mechanic implementation)
<strong>Issue Description: </strong>I just updated my computer to MAC OS Catalina so that might be the reason why, but it hasn't even opened for me.
<strong>Reproduction Steps: </strong>Download. Unzip Folder. Double Click Program. Doesn't Open.
<strong>Contact Info: </strong>twitter.com/speedysole

**Comment by Kalus** [comment]
I'm having the same issue on macOS 10.15.1

**Comment by jarena3** [comment]
Known issue — in the meantime try https://compcon.app

**Comment by aritsune** [comment]
^
When I'm off vacation, I might try doing a manual code sign and notarization for the current version, since I'll need to set up that pipeline for v2 anyways.

**Comment by aritsune** [comment]
#436
