### ISSUE TITLE
Feature Request: Could you put this program online somewhere? 

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#416]
<strong>Submitted At: </strong>11/24/2019 9:28:08
<strong>Feature: </strong>Could you put this program online somewhere? 
<strong>Details: </strong>If it's a free and open resource it might be better to run on a browser than computer for some folk
<strong>Contact: </strong>twitter.com/speedysole

**Comment by aritsune** [comment]
would contact this person re: the web app but they seem to have deactivated their twitter or something
