### ISSUE TITLE
Bug Report: The program says it cannot be opened. I downloaded the osx version but each time it says it cannot be opened. Can capcom be used with the new Catalina osx?

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#417]
<strong>Submitted At: </strong>11/29/2019 18:49:47
<strong>Platform: </strong>OSX
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>The program says it cannot be opened. I downloaded the osx version but each time it says it cannot be opened. Can capcom be used with the new Catalina osx?
<strong>Reproduction Steps: </strong>Download the file. Unzip the file then attempt to open on a machine running Catalina. I then receive an error message saying the program cannot be opened. 
<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
#436
