### ISSUE TITLE
Feature Request: Pilot Folders

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#419]
<strong>Submitted At: </strong>12/1/2019 17:50:19
<strong>Feature: </strong>Pilot Folders
<strong>Details: </strong>System for organizing pilots into folders inside the Pilot Roster view. Intended purpose is for organizing by campaign or purpose, I.E. "Test Builds", "Pregens", or "Characters at Future Levels" folders.

Definitely a luxury feature implementation but would be a nice quality of life improvement.

Low Priority of course.
<strong>Contact: </strong>Klondike#5396

**Comment by aritsune** [comment]
#328
