### ISSUE TITLE
Bug Report: compcon.app refuses to open after unziping file

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#420]
<strong>Submitted At: </strong>12/1/2019 19:17:37
<strong>Platform: </strong>OSX
<strong>Severity: </strong>Catastrophic (causes software to crash and/or corruption of saved data)
<strong>Issue Description: </strong>compcon.app refuses to open after unziping file
<strong>Reproduction Steps: </strong>1) Download compcon-osx from https://massif-press.itch.io/compcon 2) double click to unzip app 3) doubleclick app, it breaks
<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
#436
