### ISSUE TITLE
Get Focused triggers shouldn't count for triggers per level calc

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#422]
<strong>Submitted At: </strong>12/2/2019 14:09:31
<strong>Feature: </strong>A spot for the Get focused triggers
<strong>Details: </strong>the extra triggers you get via Get Focused have no place because you can only have a certain amount of triggers per level
<strong>Contact: </strong>80teeth#7971 @80teeth

**Comment by aritsune** [comment]
Fixed in v2
