### ISSUE TITLE
Feature Request: Auto Calculation for Armor and Resistance

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#424]
<strong>Submitted At: </strong>12/3/2019 10:48:45
<strong>Feature: </strong>Auto Calculation for Armor and Resistance
<strong>Details: </strong>Add in a box you can check when entering damage values that would automatically account for resistances and armor, maybe make them separate, and potentially include it in the GM side of things for NPCs.
<strong>Contact: </strong>Elderino #7590

**Comment by aritsune** [comment]
I wonder if this is actually a good idea to implement, considering how many different buttons and levers we'd have to add for all the edge cases.
