### ISSUE TITLE
Bug Report: Program immediately closes on startup. Running the program in Terminal produces the error message that the electron framework file is "too short". 

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#425]
<strong>Submitted At: </strong>12/3/2019 12:46:45
<strong>Platform: </strong>OSX
<strong>Severity: </strong>Catastrophic (causes software to crash and/or corruption of saved data)
<strong>Issue Description: </strong>Program immediately closes on startup. Running the program in Terminal produces the error message that the electron framework file is "too short". 
<strong>Reproduction Steps: </strong>Open the program in Terminal
<strong>Contact Info: </strong>@realfakewatches

**Comment by Kirbstomper** [comment]
Reproduced this.
Pulled down and built using Mac OS 10.15.1 (Catalina)
Weirdly enough it's only the packaged `compcon.zip` version that fails, running using `compcon.app` in the `/build/mac` folder works fine?
I would think its some kind of problem with electron-builder? Just commenting to add more information for others.

**Comment by Kirbstomper** [comment]
https://github.com/electron-userland/electron-builder/issues/4299#issuecomment-540262406
Yep its a builder issue in relation to new Catalina signing requirements -_-
Current workaround in that link is basically zipping and distributing the app yourself.

**Comment by aritsune** [comment]
#436
