### ISSUE TITLE
Bug Report: Walking Armory missing in talent selection

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#427]
<strong>Submitted At: </strong>12/3/2019 21:46:21
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>Walking Armory missing in talent selection
<strong>Reproduction Steps: </strong>N/A
<strong>Contact Info: </strong>

**Comment by walesgrey** [comment]
"Armsman" is the old name for the talent _Walking Armory_. This will likely be corrected with an upcoming compendium update.
