### ISSUE TITLE
Bug Report: Despite downloading the application I am completely unable to even open it.

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#428]
<strong>Submitted At: </strong>12/7/2019 15:15:12
<strong>Platform: </strong>OSX
<strong>Severity: </strong>Catastrophic (causes software to crash and/or corruption of saved data)
<strong>Issue Description: </strong>Despite downloading the application I am completely unable to even open it.
<strong>Reproduction Steps: </strong>Just trying to download it, giving it permission, and it still will not open. I get "The application “compcon” can’t be opened." as a popup again and again.
<strong>Contact Info: </strong>PB#3515

**Comment by aritsune** [comment]
#436
