### ISSUE TITLE
Bug Report: Every time Comp/Con is closed and re-launched, any created NPCs with the 'Reinforced' System are granted their +5HP again

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#430]
<strong>Submitted At: </strong>12/12/2019 7:44:40
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>Every time Comp/Con is closed and re-launched, any created NPCs with the 'Reinforced' System are granted their +5HP again
<strong>Reproduction Steps: </strong>Create an NPC with the Reinforced trait, close Comp/Con and relaunch it then open the profile of that NPC.
<strong>Contact Info: </strong>ZacmanTheDamned #4252

**Comment by aritsune** [comment]
Duplicate of #413
