### ISSUE TITLE
Catalina issues

### ISSUE THREAD

**Issue by aritsune** [massif-press/compcon#436]
**Catalina users should use https://compcon.app until we fix this (if we ever do - it might not be worth it?)**

Users on macOS 10.15 Catalina seem to have a lot of trouble getting the Electron app to run. It seems like the only real solution is to notarize the app which requires a $99/yr Apple Developer account. Opening this issue so I can clean up the many Catalina reports.

**Comment by sergiolmartins** [comment]
Regarding the signing of the app, it might be possible to work around it later – Apple is cutting off unsigned software, however it has been stated it should be possible to still used unsigned software, albeit not in a straightforward way.
The last time I had to bypass this kind of issue, OSX (High Sierra) was flagging every app not downloaded through the app store with a quarantine attribute, which was removed via the `xattr` command. This is, however, a user-side solution and I don't know if it's the same in Catalina.
