### ISSUE TITLE
[FEATURE] Theme support

### ISSUE THREAD

**Issue by aritsune** [massif-press/compcon#454]
Using vuetify's theming support, add a system where users can choose between different flavorful themes for the app. Starting out we'll have GMS (light, current theme) and MSMC (dark).

Also, eventually we might add a way for users to load up their own theme .json.

**Comment by jarena3** [comment]
Incoming change adds a dark theme off of vuetify's dark. In the future, I'll rework this to handle everything during the construction of the Vue object itself on load.

**Comment by Racoo-Bomba** [comment]
are there any potential updates for the theme features ?
