### ISSUE TITLE
[FEATURE] Switch to Conventional Commits/Commitizen

### ISSUE THREAD

**Issue by aritsune** [massif-press/compcon#459]
Once v2 is out we should switch to using Conventional Commits. Read more [here](https://www.conventionalcommits.org/en/v1.0.0/)
Should update the contributing guide to reflect this.
Should also consider [standard-version](https://github.com/conventional-changelog/standard-version) alongside them.

Tools for using Conventional Commits:
- [VSCode Commitizen Support](https://marketplace.visualstudio.com/items?itemName=KnisterPeter.vscode-commitizen)
- [Commitizen CLI](https://github.com/commitizen/cz-cli)

**Comment by jarena3** [comment]
Added in f2227aae332a624383b409bd135501d4a4cb13c4
