### ISSUE TITLE
Bug Report: In the Encounter Runner, the columns that the NPCs are in are too narrow and the text doesn't wrap. This means that almost every single ability, weapon, and tech is cut off. You can read it if you click on it, but then you can mouse over keywords to see what they are. Additionally, if the NPC name is longer than a certain length, the Kill button disappears so they can't be moved to the graveyard when killed.

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#462]
<strong>Submitted At: </strong>1/12/2020 14:10:13
<strong>Platform: </strong>OSX
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>In the Encounter Runner, the columns that the NPCs are in are too narrow and the text doesn't wrap. This means that almost every single ability, weapon, and tech is cut off. You can read it if you click on it, but then you can mouse over keywords to see what they are. Additionally, if the NPC name is longer than a certain length, the Kill button disappears so they can't be moved to the graveyard when killed.
<strong>Reproduction Steps: </strong>I have made half a dozen different encounters with various NPCs and it always turns out the same.
<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
encounter runner is being rebuilt from scratch in v2 with better consideration for this. dunno if we should close as i don't know if it's been built out yet

**Comment by jarena3** [comment]
fixed in v2
