### ISSUE TITLE
Bug Report: V2 - Everest License Requirements 

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#464]
<strong>Submitted At: </strong>1/12/2020 22:56:09
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Minor/Cosmetic (styling errors, misspellings, etc)
<strong>Issue Description: </strong>V2 - Everest License Requirements 
<strong>Reproduction Steps: </strong>When you create a new Everest in the mech hangar, the license requirements show Everest Level II instead of "GMS", unless and until you add another piece of GMS gear to the loadout.
<strong>Contact Info: </strong>

**Comment by Eranziel** [comment]
Small bug I noticed while testing. 
Culprit seems to be lines 127 in src/classes/mech/Mech.ts. (Snippet below uses updated text from my branch, but the only different is the string for the Everest name; works the same on version_2 branch.)
```typescript
if (this._frame.Name.toUpperCase() === 'STANDARD PATTERN I "EVEREST"') {
  const gmsIdx = requirements.findIndex(x => x.source === 'GMS')
  if (gmsIdx > -1) requirements[gmsIdx].items.push('STANDARD PATTERN I "EVEREST" Frame')
  else requirements.push(this.Frame.RequiredLicense)
}
```

**Comment by jarena3** [comment]
Looks like this is resolved in v2
