### ISSUE TITLE
Bug Report: Active Play Mode does not save loaded status if you navigate to the home page or close the program

### ISSUE THREAD

**Issue by Xul13** [massif-press/compcon#465]
Discovered this when we didn't finish combat in one session. 

This is with the downloadable executable for windows, version compcon-win 1.5.5c.

The status of the "Loaded/Not Loaded" toggle does not appear to be saved if the program is closed, or you navigate back to the home screen. 

To Reproduce:
1. Equip mech loadout with one or multiple GMS Loading weapons. 
2. Select that pilot's Active Play Mode. The weapons should be shown in the loadout section with a Loaded status that includes a toggle switch. 
3. Flip the "Loaded" toggle to "Not Loaded"
4. Press Home, or close the application then relaunch. 
5. Select Pilot Roster
6. Select your pilot
7. Select Active Play Mode

The Loaded toggle switch will be back in the default state of "Loaded". 

This only appears to occur through the above two methods. It might have something to do with attributes resetting when you access the home screen. Using links at the top to move to the compendium or pilot roster and then the pilot drop down, or back button, to return to the Active Play Mode page do not appear to cause the issue. 

As values like HP, Hull and limited use item count are saved between program runs it would be nice to do this with the loaded status as well.

**Comment by Xul13** [comment]
Apologies for not tagging this. It appears I cannot edit tags after a ticket has been created.

**Comment by jarena3** [comment]
This has been resolved in v2
