### ISSUE TITLE
[FEATURE] Sort weapon sizes more intuitively

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#477]
<strong>Submitted At: </strong>1/14/2020 17:08:08
<strong>Platform: </strong>Windows
<strong>Severity: </strong>Moderate (obvious problem but can be worked around)
<strong>Issue Description: </strong>When sorting by weapon size it goes Superheavy-->Main-->Heavy which is weird
<strong>Reproduction Steps: </strong>In the mech hanger go to add a heavy weapon to a heavy mount and sort by size.
<strong>Contact Info: </strong>Neverender

**Comment by Qwertronix** [comment]
There's a bit of a restriction with the v-data-table component that would make this trickier to implement than it seems. The best solution might be to use the external/server-side sorting options to handle item ordering in a custom method, and manually setting the external options to the right sorting state representing this.

**Comment by aritsune** [comment]
We could also solve this in the data end by changing weapon size to an enum.
Could make it so when weapons are instantiated it converts the string data to the size enum, that way we don't have to change the data/homebrew doesn't get too arcane.

**Comment by Qwertronix** [comment]
> We could also solve this in the data end by changing weapon size to an enum.
> Could make it so when weapons are instantiated it converts the string data to the size enum, that way we don't have to change the data/homebrew doesn't get too arcane.

That'd work. You'd need to override the `v-slot:item.size` in that case for a self-managed v-data-table, or build a bit of extra custom logic if `v-slot:item` is already overridden. Otherwise the default render for an enum is the .toString() of the values rather than the keys.
