### ISSUE TITLE
[FEATURE] Robust Error Logging

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#486]
**Is your feature request related to a problem? Please describe.**
Often, a user will report an issue that is difficult to reproduce, or we have otherwise no visibility on.

**Describe the solution you'd like**
Expand the current `ExtLog` utility code to catch errors and write them to a log a user can extract (from the user menu) and send to the developers.

**Additional context**
Due to space considerations, the log should only ever contain the most recent few hundred reports.

**Comment by aritsune** [comment]
Should also consider having some sort of snackbar or alert for errors - some bugs might not seem like bugs to the end user

**Comment by jarena3** [comment]
tracked in https://github.com/massif-press/compcon/issues/495

**Comment by aritsune** [comment]
Was thinking of using `window.onerror` for this, but it looks like it doesn't catch Vue errors. `Vue.config.errorHandler` /does/ work, but I'm pretty sure this wouldn't catch vuex errors, since it's not technically part of the render process. Will have to do more testing later
