### ISSUE TITLE
[FEATURE] Generalized Bonus Framework

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#489]
**Is your feature request related to a problem? Please describe.**
Currently, item bonuses and stat modifications (Pilot Engineering "Limited" tag bonuses, Weapon range mods, etc) are handled through clumsy ID lookups. This is inefficient, bug-prone, and will be restrictive for homebrew content. 

**Describe the solution you'd like**
We should design and develop an item bonus framework that will open more game mechanics to item-based modification. The code should be terse and reusable.

**Comment by aritsune** [comment]
i LOVE generalizing things i'll probably do this

**Comment by jarena3** [comment]
Added in 2.2
