### ISSUE TITLE
[FEATURE] Global Notifications

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#495]
**Is your feature request related to a problem? Please describe.**
We need a way to pass alerts (confirmations, errors, etc) to the user without having to rebuild a snackbar component in every view

**Describe the solution you'd like**
A universal snackbar/toast/banner system that can be called from any view. Pops in, waits for a set amount of time, and fades out. If multiple notifications arrive at the same time, each should stack vertically. Additionally, this system should allow the user to revisit faded notifications (via a link in the top nav menu, maybe).

**Additional context**
We will probably need several styled modes of notification: confirmation, error, and achievement, at least.

**Comment by aritsune** [comment]
Closed by #524
