### ISSUE TITLE
[FEATURE] Browser Sync Storage

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#500]
**Is your feature request related to a problem? Please describe.**
Currently, the only way to manage the same data on two machines is by tossing around lots of cloud IDs

**Describe the solution you'd like**
Prior to a full backend, we should let the user opt for synching their C/C data with their browser account

**Additional context**
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync

**Comment by aritsune** [comment]
Looking into this and I think we may have been misinformed - I'm pretty sure the storage API is intended for & only available to browser extensions, not sites. @jarena3

**Comment by jarena3** [comment]
Yeah, looks like you're right. Alas~
