### ISSUE TITLE
[FEATURE] Factions

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#510]
**Is your feature request related to a problem? Please describe.**
C/C does not acknowledge the game fiction's varios factions in any way

**Describe the solution you'd like**
A new compendium entry for Factions, set up like the Manufacturers page.

**Additional context**
This will be further developed in the Campaign Builder, but this should be sufficient for now.

**Comment by Bradshaw** [comment]
This works: https://github.com/Bradshaw/compcon/commit/7652b916f04458c9a3767edbef0b2e7c2c8da01d
But I'm not sure about factions necessarily having logos?

**Comment by Bradshaw** [comment]
FYI @jarena3, without merging https://github.com/massif-press/lancer-data/pull/126 and making compcon require the updated lancer-data, compcon won't work properly
