### ISSUE TITLE
[FEATURE] More Icons

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#529]
**High priority**
 - [ ] Compendium
 - [ ] Encounter Toolkit
 - [ ] Campaign Manager
 - [ ] Content Editor
 - [ ] System Point
 - [ ] NPC Custom Tier icon
 - [ ] Actor Destroyed
 - [ ] Actor Defeated
 - [ ] Actor Routed/Retreated
 - [ ] E-Defense
 - [ ] Evasion
 - [ ] Speed
 - [ ] Free Action
 - [ ] Reaction
 - [ ] Save
 - [ ] Sensor Range
 - [ ] Vehicle
 - [ ] Ship
 - [ ] Biological
 - [ ] Squad
 - [ ] License
 - [ ] Downtime Resource/Reserve

**Low Priority**
 - [ ] Statuses (?)
 - [ ] Mount Sizes (?)

**Comment by jarena3** [comment]
Tagged as `help wanted` if anyone has any icon suggestions @aritsune @Qwertronix @Eranziel

**Comment by Qwertronix** [comment]
Suggestions and ideas from the MDI pool. Some are probably terrible. Some might be starting points for inspiration. Some might overlap / conflict conceptually. 

* License: 
  * ![account-card-details (1)](https://user-images.githubusercontent.com/360217/73406189-ccc8f780-42c3-11ea-9279-892367d3c827.png) account-card-details 
  * ![card-bulleted](https://user-images.githubusercontent.com/360217/73406440-75775700-42c4-11ea-8e59-91b09e55c191.png) card-bulleted 
  * ![smart-card](https://user-images.githubusercontent.com/360217/73409390-1e29b480-42cd-11ea-81fa-965bb1779ec9.png) smart-card
  * ![certificate](https://user-images.githubusercontent.com/360217/73410507-6eeedc80-42d0-11ea-9cc3-1ecf4ac3c8e2.png) certificate


* Content Editor
  * ![developer-board](https://user-images.githubusercontent.com/360217/73406913-a60bc080-42c5-11ea-9743-50fa6697112e.png) developer-board

* Biological
  * ![fingerprint](https://user-images.githubusercontent.com/360217/73407030-f1be6a00-42c5-11ea-9e73-1bf1ecf70091.png) fingerprint
  * ![flower](https://user-images.githubusercontent.com/360217/73407082-0a2e8480-42c6-11ea-8e11-5c719da915aa.png) flower
  * ![foot-print](https://user-images.githubusercontent.com/360217/73407123-23cfcc00-42c6-11ea-93ae-d7f32ae36e45.png) foot-print
  * ![heart-pulse](https://user-images.githubusercontent.com/360217/73407289-a6588b80-42c6-11ea-804d-71a585004d8f.png) heart-pulse

* Squad
  * ![grain](https://user-images.githubusercontent.com/360217/73407202-61345980-42c6-11ea-8c4f-2714b17b1886.png) grain
  * ![graph](https://user-images.githubusercontent.com/360217/73407251-85903600-42c6-11ea-8078-4dd7434ebf0b.png) graph
  * ![run](https://user-images.githubusercontent.com/360217/73409251-be330e00-42cc-11ea-9409-bcf9e01a893f.png) run
  * ![walk](https://user-images.githubusercontent.com/360217/73409620-d5263000-42cd-11ea-833d-cc067619ffed.png) walk
  * ![shoe-print](https://user-images.githubusercontent.com/360217/73409950-c2602b00-42ce-11ea-92f7-fd36d89e20be.png) shoe-print



* Campaign Manager
  * ![library](https://user-images.githubusercontent.com/360217/73408924-b0c95400-42cb-11ea-9215-bc9dd13409d5.png) library

* Encounters
  * ![alien](https://user-images.githubusercontent.com/360217/73408989-f0903b80-42cb-11ea-897b-491b3059e221.png) alien
  * ![drama-masks](https://user-images.githubusercontent.com/360217/73409025-0867bf80-42cc-11ea-9f59-1acd7a906903.png) drama-masks

* System Points
  * ![engine](https://user-images.githubusercontent.com/360217/73409068-31885000-42cc-11ea-8d0a-16f8439d5887.png) engine
  * ![state-machine](https://user-images.githubusercontent.com/360217/73409569-af992680-42cd-11ea-960d-73ed7a50dc52.png) state-machine


* Actor Destroyed
  * ![nuke](https://user-images.githubusercontent.com/360217/73409166-701e0a80-42cc-11ea-86c5-071cd3ca8b39.png) nuke

* Actor Defeated
  * ![engine-off](https://user-images.githubusercontent.com/360217/73410326-dce6d400-42cf-11ea-819d-43479cb4765d.png) engine-off


* Actor Routed / Retreated
  * ![run-fast](https://user-images.githubusercontent.com/360217/73409478-6b0d8b00-42cd-11ea-9f56-9f4316ab1888.png) run-fast
  * ![wifi-strength-off-outline](https://user-images.githubusercontent.com/360217/73409823-58478600-42ce-11ea-8ffe-b381251ef3f4.png) wifi-strength-off-outline
  * ![strategy](https://user-images.githubusercontent.com/360217/73409887-8d53d880-42ce-11ea-91b1-11f1e853e263.png) strategy
  * ![exit-run](https://user-images.githubusercontent.com/360217/73410274-bfb20580-42cf-11ea-9a54-b5db329bcbc1.png) exit-run



* Actor Defeated? || Actor Destroyed?
  * ![skull-outline](https://user-images.githubusercontent.com/360217/73409407-313c8480-42cd-11ea-8bd9-b522aa6f3f9f.png) skull-outline
  *  ![skull-crossbones](https://user-images.githubusercontent.com/360217/73409419-37cafc00-42cd-11ea-98a3-784df7d179c7.png) skull-crossbones
  * ![skull](https://user-images.githubusercontent.com/360217/73409428-3d284680-42cd-11ea-8e38-d4f9654fb7fd.png) skull


* Speed
  * ![rabbit](https://user-images.githubusercontent.com/360217/73410151-66e26d00-42cf-11ea-84d2-1cc900817fd5.png) rabbit
  * ![clock-fast](https://user-images.githubusercontent.com/360217/73410417-26372380-42d0-11ea-8beb-dee63fcdad92.png) clock-fast
  * ![chevron-triple-right](https://user-images.githubusercontent.com/360217/73410418-26cfba00-42d0-11ea-8b3a-fca0b95f353a.png) chevron-triple-right
  * ![speedometer](https://user-images.githubusercontent.com/360217/73410649-e6247080-42d0-11ea-9d78-f0023c9b2d6b.png) speedometer


* Save
  * ![security](https://user-images.githubusercontent.com/360217/73409288-da36af80-42cc-11ea-8b14-88c8c74adf07.png) security
  * ![shield-alert](https://user-images.githubusercontent.com/360217/73409342-fa666e80-42cc-11ea-99f1-44d1e12a655d.png) shield-alert

* Reaction
  * ![sync-alert](https://user-images.githubusercontent.com/360217/73409533-955f4880-42cd-11ea-8bb2-72ac216e6c75.png) sync-alert
  * ![watch-vibrate](https://user-images.githubusercontent.com/360217/73409666-ed964a80-42cd-11ea-9fc3-c9fdaf57c537.png) watch-vibrate
  * ![watch-export](https://user-images.githubusercontent.com/360217/73409667-ef600e00-42cd-11ea-89cb-55bc1a2340ec.png) watch-export

* E-Defense
  * ![server-security](https://user-images.githubusercontent.com/360217/73409988-df94f980-42ce-11ea-99c5-21fd5ea8490e.png) server-security

* Evasion
  * ![strategy](https://user-images.githubusercontent.com/360217/73409887-8d53d880-42ce-11ea-91b1-11f1e853e263.png) strategy

* Ship
  * ![orbit](https://user-images.githubusercontent.com/360217/73410185-7cf02d80-42cf-11ea-8a28-8db43fae7f36.png) orbit


* NPC Tiers
  *  ![chevron-up](https://user-images.githubusercontent.com/360217/73410457-4c5cc380-42d0-11ea-87cc-112613de663f.png) ![chevron-double-up](https://user-images.githubusercontent.com/360217/73410458-4cf55a00-42d0-11ea-92cf-0b18959907f7.png) ![chevron-triple-up](https://user-images.githubusercontent.com/360217/73410459-4e268700-42d0-11ea-94e6-a68c4be50bad.png) chevron-up, chevron-double-up, chevron-triple-up

**Comment by jarena3** [comment]
There are some really good ones here. I'll take a closer look through these to implement some ASAP. As the app matures (and we get Patreon funding) I'd like to trend towards having a full set of cc-specific glyphs though.
