### ISSUE TITLE
[FEATURE] Reusable Confirm v-menu

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#530]
**Is your feature request related to a problem? Please describe.**
The flavorful confirmation menu (used in eg. Delete Pilot) is repeated often and should be moved into a global component per DRY

**Describe the solution you'd like**
A reusable CC- global component confirmation menu that has a default message slot and returns a confirmation button click

**Additional context**
An example can be found in `DeletePilotDialog.vue`

**Comment by aritsune** [comment]
We already have a global confirm component unless I'm misunderstanding, so all we'd need to do is match the look of that example.

**Comment by jarena3** [comment]
We can reflavor that global confirm dialog too, but I'd like a confirm v-menu as well for quick/minor confirmations

**Comment by aritsune** [comment]
ah I missed the v-menu part! Yeah this should be trivial, I'll self-assign
