### ISSUE TITLE
[FEATURE] "routes.ts" subnode for all features

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#547]
**Is your feature request related to a problem? Please describe.**
The root router.ts is becoming unwieldy.

**Describe the solution you'd like**
Like the Encounter tools, each features should have its own `routes.ts` file that manages routing for all feature views.

**Comment by Qwertronix** [comment]
Oh! Fair warning, with vue-class-components, lifecycle hooks inserted by plugins are not available by default, so those need to be registered first: https://github.com/vuejs/vue-class-component#adding-custom-hooks.
