### ISSUE TITLE
[BUG] Mission Build Campaign Name Mismatch

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#568]
<strong>Submitted At: </strong>2/2/2020 11:53:46
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Sorting encounters by campaign will show as 'NONE' if no campaign is set. After clicking on the campaign field and entering no string, the campaign is set to 'NULL' because empty string evaluates as Null instead of what the field is initialized to normally. 
<strong>To Reproduce: </strong>
Go into encounter menu, sort by campaign. Make a new encounter and do nothing to do. Make another new encounter, click the campaign field, hit enter.
<strong>Expected behavior: </strong>
Missions that aren't meant to be put into a campaign should all be under the same header of 'None'. Ever clicking into the campaign field causes a divide between these missions.
<strong>Additional context: </strong>
This seems to just be a discrepancy between the campaign being set to the mission in the localstorage vs how it is displayed. Both missions display as 'None', but are stored as https://i.imgur.com/tsKCmLh.png .
<strong>Contact Info: </strong>

**Comment by jarena3** [comment]
fixed in 4275c1785977cd8b1a5b6a3bde638c7164c044e7
