### ISSUE TITLE
[BUG] NPC Editor: Base Installs aren't linked to the base edit mode

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#569]
<strong>Submitted At: </strong>2/2/2020 11:55:11
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
It seems that the base traits/weapons on an NPC aren't listed as "installed", basically it becomes impossible to add a second base weapon or readd it without unlocking all NPCs
<strong>To Reproduce: </strong>
Create a sniper
Get the desire to add a second AMR for an elite mob that has two shots per round
realize that the AMR isn't available to install / reinstall if you remove it without using the unlock all feature
assume that this encompasses all base traits. 
<strong>Expected behavior: </strong>
clicking the installed filter should show base traits
when a base trait is uninstalled, it should show up in the list of uninstalled traits.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Nice#0367

**Comment by jarena3** [comment]
Fixed in 6190eab10fd62115d94ff636e4157fb88c51f603
