### ISSUE TITLE
[BUG] Duplicating mechs leads to two active mechs

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#570]
<strong>Submitted At: </strong>2/2/2020 11:58:20
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
If you duplicate your active mech, both the original and the copy are marked as active.
<strong>To Reproduce: </strong>
Set a mech to be active and the click the 'copy' button on it in the hangar.
<strong>Expected behavior: </strong>
Only the original should be active.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
megane

**Comment by jarena3** [comment]
fixed by 2dcfa9cbcfd65542a62a2fffabd927f873417d19
