### ISSUE TITLE
[BUG] Clicking and Unclicking Custom Tier disables size edit

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#572]
<strong>Submitted At: </strong>2/2/2020 12:05:19
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
Edit size button disappears if you set tier to NULL
<strong>To Reproduce: </strong>
I clicked on custom, made an edit of my NPC, turned it into what I wanted except for size. Clicked the custom tier button thus removing its tier and then clicked it again, the edit function for size disappears until you refresh
<strong>Expected behavior: </strong>
Edit size button should stay around
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Nice#0367

**Comment by jarena3** [comment]
fixed by c862e8e0b4e9a78ec3471579332c5ba70e6f4756
