### ISSUE TITLE
Feature Request: Alter color of quick actions and full actions

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#574]
<strong>Submitted At: </strong>2/2/2020 13:20:32
<strong>Is your feature request related to a problem? Please describe. </strong>
In comp/con 1.5.6, when the actions are described under the reference section, the quick actions are a different color from the full actions. This made it much easier to tell where the full actions started at a glance.

In 2.0, however, they are the same color. This makes it harder to tell where the full actions are at a glance.
<strong>Describe the solution you'd like: </strong>
Simply revert the colors of the quick and full actions to what they were in comp/con v1.5.6.
<strong>Additional context: </strong>

<strong>Contact: </strong>

**Comment by jarena3** [comment]
This will be addressed in https://github.com/massif-press/compcon/issues/519
