### ISSUE TITLE
[BUG] NPC Weapon Difficulty Listed as +- Accuracy

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#575]
<strong>Submitted At: </strong>2/2/2020 13:33:48
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
NPC weapons that have a Difficulty penalty instead of an accuracy bonus are listed as +- x Accuracy. See Demolisher or Breacher for examples.
<strong>To Reproduce: </strong>
Add a Demolisher or Breacher to the NPC Rooster.
<strong>Expected behavior: </strong>
It should be listed as + x Difficulty
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

**Comment by jarena3** [comment]
Fixed in https://github.com/massif-press/compcon/pull/583
