### ISSUE TITLE
[BUG] NPC Weapon display issues

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#576]
<strong>Submitted At: </strong>2/2/2020 13:41:35
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
NPC Weapons do not show the weapon size - (See demolisher hammer)
NPC weapons do not express difficulty correctly (See demolisher hammer for +-1 Accuracy)
<strong>To Reproduce: </strong>
Create a demolisher
Look at its hammer and see.
<strong>Expected behavior: </strong>
+1 Difficulty, 
Have it show it as a superheavy weapon somewhere
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Nice#0367

**Comment by jarena3** [comment]
fixed in https://github.com/massif-press/compcon/pull/583
