### ISSUE TITLE
[BUG] NPC recharge numbers not listed.

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#577]
<strong>Submitted At: </strong>2/2/2020 13:51:46
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
The recharge tag has the correct rules but does not list the number for the recharge.
<strong>To Reproduce: </strong>
Add an NPC with a recharge system. Such as a Hornet.
<strong>Expected behavior: </strong>
The Recharge tag on NPCs should list the number: Recharge (x)
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

**Comment by Eranziel** [comment]
Actually an issue in lancer-data. Will be fixed in next update.
