### ISSUE TITLE
[BUG] NPC template select

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#579]
<strong>Submitted At: </strong>2/2/2020 15:17:53
<strong>Platform: </strong>
Brave browser (chromium based)
<strong>Describe the bug: </strong>
Template selection shows optional traits heading when none are present
<strong>To Reproduce: </strong>
View NPC template selection
<strong>Expected behavior: </strong>
The heading is hidden, or says "No traits"
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
unwary#3649

**Comment by jarena3** [comment]
corrected in 3755616b002b91e28e114ffdd2ac58f02e941353
