### ISSUE TITLE
[BUG] Elite/Ultra activations

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#580]
<strong>Submitted At: </strong>2/2/2020 16:25:36
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Adding the Elite or Ultra templates don't add to the NPC's activations stat.
<strong>To Reproduce: </strong>
Add Elite/Ultra to an NPC
<strong>Expected behavior: </strong>
Adding Elite should increase activations by 1, Ultra by 3
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Eranziel

**Comment by Eranziel** [comment]
Data issue, will be fixed in next update.
