### ISSUE TITLE
[BUG] Pilot selection does not persist

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#581]
<strong>Submitted At: </strong>2/2/2020 16:32:22
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
In v1.5.6, when a pilot is selected from the pilot roster and then the compendium is selected from the header, the pilot remains in the header, such that the pilot's character sheet can be reached with only one click. In v2.0, this is no longer the case.
<strong>To Reproduce: </strong>
1) Click on Pilot roster.
2) Select pilot. Note how the pilot's callsign now appears on the header.
3) Click "compendium" in the header. The pilot's callsign disappears.
<strong>Expected behavior: </strong>
When selecting "compendium" (step 3), the pilot's callsign should remain in the header.
<strong>Additional context: </strong>
As this functionality existed in a prior version of comp/con, I'm assuming that it is a bug that the latest version does not have it.
<strong>Contact Info: </strong>

**Comment by jarena3** [comment]
collected in https://github.com/massif-press/compcon/issues/605
