### ISSUE TITLE
[BUG] Ineligible for Core Bonus

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#582]
<strong>Submitted At: </strong>2/2/2020 17:33:43
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When editing my pilot's level from 0 to 6 and then hitting level up, taking my pilot to 7 and entering the leveling up menu, I am stuck on the "Add Core Bonus" screen. I receive a message that (despite being level 7) my pilot is eligible to receive any Core Bonuses and I will recieve my next Core bonus in 2 levels. So I have no option to choose a Core Bonus, but I am also unable to continue as the button is greyed out. Unable to finish the level up process because of this.
<strong>To Reproduce: </strong>
1. On the pilot narrative profile screen, edit the license level from 0 to 6. 
2. Click on level up (taking you to level 7). 
3. I put all my skill points Apply Fists to Faces, Assault, Blow Something Up, and Survive. 
4. I put all my pilot talents in Ace, Bonded, Brawler, and Brutal. 
5. I put all my mech skill points into Hull and Agility.
6. I took 3 levels in Blackbeard, 3 in Nelson, and 1 in Vlad. 
7. When I hit continue and go to the Core Bonus screen I have a message telling me that my pilot is ineligible for any Core Bonuses and I will receive my next one in 2 levels. I having nothing to select, and I am also unable to hit on Continue because that button is greyed out. Hitting back and selecting different mechs does nothing to remedy this.

<strong>Expected behavior: </strong>
As I'm level 7 I should be able to pick 2 Core bonuses, either from GMS, or from another manufacturer if I have at least 3 licenses from them. Example: I have 3 levels in the IPS-N Vlad so I should be able to get 1 IPS-N Core Bonus.
<strong>Additional context: </strong>
I've posted about this in the comp/con channel in the Lancer discord. If you'd like any screenshots I'd be happy to produce them.
<strong>Contact Info: </strong>
Moltenfungus #7388

**Comment by jarena3** [comment]
fixed in 76493fcf2f9ffb6be588b3f03774cbd8efeb699b
