### ISSUE TITLE
Feature Request: Delete pilot from Roster

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#584]
<strong>Submitted At: </strong>2/2/2020 21:20:42
<strong>Is your feature request related to a problem? Please describe. </strong>
Must go into pilot view to delete them
<strong>Describe the solution you'd like: </strong>
Just put a delete button on the list-view
<strong>Additional context: </strong>

<strong>Contact: </strong>

**Comment by jarena3** [comment]
collected in https://github.com/massif-press/compcon/issues/533
