### ISSUE TITLE
[BUG] AIs counted incorrectly

### ISSUE THREAD

**Issue by Eranziel** [massif-press/compcon#585]
<strong>Describe the bug: </strong>
Technophile 1 and 2 bonus AI is not counted towards the AI limit, but should be. Only Technophile 3 bonus AI doesn't count towards the limit.
Uncle C/C is also missed because weapon mods are not checked when counting AIs.
<strong>To Reproduce: </strong>
Create a pilot with Techno 1/2 and add another AI. Or, add Uncle to a weapon first, then add another AI.
<strong>Expected behavior: </strong>
Having the Techno 1/2 AI should disallow other AIs from being added. Likewise with Uncle. (Unless the pilot has the Lesson of Shaping core bonus, of course.)

**Comment by jarena3** [comment]
fixed in https://github.com/massif-press/compcon/pull/586
