### ISSUE TITLE
[FEATURE] Switchable Modes for Weapons

### ISSUE THREAD

**Issue by Eranziel** [massif-press/compcon#587]
**Is your feature request related to a problem? Please describe.**
Some PC weapons have different profiles which can be toggled. Some examples include:
* Siege Cannon
* DD/288
* Flayer shotgun (Caliban integrated)

**Describe the solution you'd like**
Add a button or gear-menu option to weapon cards in active mode to toggle between the different profiles.

**Comment by jarena3** [comment]
Linking https://github.com/massif-press/compcon/issues/519

**Comment by jarena3** [comment]
Added in 2.2
