### ISSUE TITLE
[BUG] NPC Traits do not display tags

### ISSUE THREAD

**Issue by Eranziel** [massif-press/compcon#588]
<strong>Describe the bug: </strong>
NPC trait cards don't display their tags.
<strong>To Reproduce: </strong>
View an NPC in the encounter tools, no traits show any tags (despite tags being present in the data).
<strong>Expected behavior: </strong>
Traits should show tags, same as other features.

**Comment by jarena3** [comment]
fixed in https://github.com/massif-press/compcon/pull/583
