### ISSUE TITLE
[BUG] Custom Paint Job Destruction

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#589]
<strong>Submitted At: </strong>2/2/2020 22:55:04
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
Custom Paint Job says it isn't a valid choice for system destruction, but in C/C it is.
<strong>To Reproduce: </strong>
Put CPJ on a mech, and then either set it to Destroyed manually or take Structure damage and roll System Trauma.
<strong>Expected behavior: </strong>
CPJ shouldn't be destructible.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
megane

**Comment by jarena3** [comment]
This probably necessitates the addition of an `indestructible` hidden tag

**Comment by jarena3** [comment]
Tracking this in #649
