### ISSUE TITLE
[BUG] Custom counter too small

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#590]
<strong>Submitted At: </strong>2/2/2020 23:01:01
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
The custom counter box is too small to show the number. May be caused by my screen being high-DPI.
<strong>To Reproduce: </strong>
Create a custom counter.
<strong>Expected behavior: </strong>
It should be widened a bit.
<strong>Additional context: </strong>
Image: https://i.imgur.com/RteaQbF.png
<strong>Contact Info: </strong>
megane

**Comment by jarena3** [comment]
fixed by 50b079d39f19eaf5dffa4563648a38c6dcca4059
