### ISSUE TITLE
[BUG] Comp/Con webapp won’t load npc file

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#591]
<strong>Submitted At: </strong>2/3/2020 0:07:20
<strong>Platform: </strong>
PWA - iOS
<strong>Describe the bug: </strong>
I am unable to add the npc file from my iOS downloads folder to my webapp on my iPad
<strong>To Reproduce: </strong>
I visited the itch page and downloaded the npc file to my downloads folder in iOS.
I visited the comcon webpage through my safari browser and was then able to import the lcp file through the content manager. I then ported the page into a webapp on my home screen and noticed I had to reinstall the content pack. When I make the attempt through the content manager it won’t let me select it. When I attempt to import the data through options nothing happens. I can use the browser version just fine. 
<strong>Expected behavior: </strong>
To be able to install the lcp file in the webapp version the same way I did the browser version.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
LilDark01

**Comment by Eranziel** [comment]
Related to #300. Mobile is not supported currently.
