### ISSUE TITLE
[BUG] no pilot talents in character creation

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#592]
<strong>Submitted At: </strong>2/3/2020 1:07:37
<strong>Platform: </strong>
Browser - Safari
<strong>Describe the bug: </strong>
on the pilot character creation screen, there are no pilot talents to choose
<strong>To Reproduce: </strong>
go to comp con.app on safari, create a new pilot, get to select talents
<strong>Expected behavior: </strong>
I expected there to be pilot talents
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
this sounds like something went wrong loading data, but no contact info means we can't follow up and ask about their environment... 😔
