### ISSUE TITLE
[BUG] Weird spacing of downtime reserves

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#594]
<strong>Submitted At: </strong>2/3/2020 18:10:21
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Downtime reserve cards are not spaced correctly
<strong>To Reproduce: </strong>
Add more than 1 downtime reserve
<strong>Expected behavior: </strong>
Cards are spaced correctly
<strong>Additional context: </strong>
Wish I could submit a screenshot
<strong>Contact Info: </strong>
CombustibleLemons#6669

**Comment by jarena3** [comment]
fixed in 4325b5a5bc631890cc6a7936a35080370600306e
