### ISSUE TITLE
Feature Request: Assigning Pilot a Side

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#595]
<strong>Submitted At: </strong>2/3/2020 19:04:08
<strong>Is your feature request related to a problem? Please describe. </strong>
COMP/CON does not smoothly run inter-player conflict.
<strong>Describe the solution you'd like: </strong>
Be able to assign pilots a "side" (ally/neutral/enemy), either in mission runner or by inserting them ahead of time in the encounter builder.
<strong>Additional context: </strong>

<strong>Contact: </strong>
no#8963

**Comment by jarena3** [comment]
Inter-player conflict isn't really supported by LANCER RAW and COMP-CON won't either
