### ISSUE TITLE
Feature Request: An easy view for the pilot license shown at the end of a level up

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#596]
<strong>Submitted At: </strong>2/3/2020 19:13:52
<strong>Is your feature request related to a problem? Please describe. </strong>
View of license is currently difficult to access. Takes multiple clicks and deliberately leveling down. This is unfortunate as it is a concise summary of the character and is a useful tool for a GM to use at-a-glance.
<strong>Describe the solution you'd like: </strong>
A tab, button, or view that allows a player to view the summary at the end of a license level up.
<strong>Additional context: </strong>

<strong>Contact: </strong>
TriangularBlasphemy

**Comment by Qwertronix** [comment]
Could perhaps reuse the component for these as a view mode option in the Pilot Roster? I do agree that they look good and provide a solid easy-to-parse overview of the pilot.

**Comment by Eranziel** [comment]
Using them in Pilot Roster is a good idea. Another option would be a view for the Dossier tab, or add another tab to the left of Dossier named "ID Card" or similar.
