### ISSUE TITLE
[BUG] Repair cap shows twice

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#597]
<strong>Submitted At: </strong>2/3/2020 20:21:45
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Repair cap shows twice in mech frame profiles. Once as "Repair cap" and once as "Repair Capacity"
<strong>To Reproduce: </strong>
View a mech frame
<strong>Expected behavior: </strong>
Only shows repair cap once
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

**Comment by jarena3** [comment]
Fixed in ef00730476c62b7ab7990449e9e743d9675d80e1
