### ISSUE TITLE
[BUG] Add NPC List Limit in Encounter Builder

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#599]
<strong>Submitted At: </strong>2/3/2020 21:36:35
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When attempting to use the Add NPC feature in Encounter Builder, the list of available NPCs is limited to 10 on the short list on the left. The shown NPCs change based on how I choose to filter them but there is always exactly 10. The detailed list on the right includes all NPCs. Still able to search up NPCs by name using the search bar, though this is also limited to 10 (added 11 NPCs with the same name to test, did not test with a higher number like 30). Attempted to scroll, with wheel and by dragging, as well as clicking on an option and using all 4 arrow keys, no effect.
<strong>To Reproduce: </strong>
Bug occurs every time I attempt to add an NPC to an encounter, unable to clear issue so as to know what might be what is required to reproduce.
<strong>Expected behavior: </strong>
For the NPC list on the left to be longer, or to have a scroll function.
<strong>Additional context: </strong>
Chrome is Up to date at this time, Version 79.0.3945.130 (Official Build) (64-bit). Will include screenshots of issue if possible. Unsure where to upload as it is technically sharing of paid content for LANCER.
<strong>Contact Info: </strong>
no#8963

**Comment by jarena3** [comment]
fixed in 64c89435f2046afdb6d94a8b40fceba41125b65b
