### ISSUE TITLE
[BUG] NPC Builder Autofills Last Submitted Name

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#600]
<strong>Submitted At: </strong>2/3/2020 21:53:27
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When editing an NPC's name for the second time in the NPC Builder, it autofills whatever the last submitted name was. This occurs when hitting enter or clicking away to submit the previous NPC's name. Selecting to edit a name also clears the existing name from the box, though if you click away it brings back the previous name. This occurs the first time you select an NPC name onwards, and may be related, as if you do not include a submission and it reverts to the previous name, then select to edit another name, that is also blank, the autofill only occurs if you previously entered something. So long as it is blank when you submit the name, it reverts back, even if you select on first a unit with a different name than the second (if you attempt to edit "Paul" and enter nothing, it reverts to Paul, if you then select and attempt to edit "Bob" and enter nothing, it will still revert to Bob. However, if you type in Paul to name "Paul", when you select "Bob" it will autofill to Bob). This resets if you click on NPC Builder again, counting it as a fresh session.
<strong>To Reproduce: </strong>
Issue occurs every time upon entering the NPC Builder, but only on the second attempt to edit when a previous submission has already been done. Leaving page or clicking on NPC Builder refreshes autofill. Clicking the back button does not. Occurs even when all 3 autofill settings are turned off on Chrome.
<strong>Expected behavior: </strong>
Either for it to be blank every time you attempt to edit an NPCs name or to retain the NPC's name for you to then edit.
<strong>Additional context: </strong>
Google Chrome is up to date
Version 79.0.3945.130 (Official Build) (64-bit). Able to include screenshots but unsure about uploading them to a host site first, as they are technically of paid LANCER content.
<strong>Contact Info: </strong>
no#8963

**Comment by jarena3** [comment]
Unless I'm missing something this is working as intended, and if there's a drop-down autofill this on the OS, not on C/C
