### ISSUE TITLE
[BUG] Missing Rests in Mission Builder/Runner

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#601]
<strong>Submitted At: </strong>2/3/2020 22:09:50
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
I've added a rest to an encounter but it keeps disappearing when I switch from the mission builder page, and when I run the encounter any rests get skipped
<strong>To Reproduce: </strong>
Make a mission, add an encounter, then add a rest. Switch to the Mission Runner, and try to run that mission. Open the mission information, and it should only show any encounters in the mission, not any of the rests. Try ending the encounter, and it should end the mission instead of transitioning to the rest first. If a second encounter is added after the rest, it should start that encounter instead

Go back to the mission builder and select the mission. The rest in the mission should be missing. Then go back to the mission runner's initial screen, where you select missions. The encounter/ rest display next the mission under Available missions should still show that there's at least one rest

I've done variations on this, adding extra rests or encounters, and the results are the same; the only indication that the mission is supposed to have a rest is the number of rests listed next to it under the Available Missions list. If you try to add rests back in after leaving the mission builder once,  all that changes is the listed number of rests. I've been able to reproduce this after deleting all pilot data and building encounters and missions from scratch
<strong>Expected behavior: </strong>
That the rests would appear in the mission information popup, that ending an encounter before a rest would transition to a rest, that the mission builder would still show the rest listed on returning to edit the mission from another part of the app.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
AndySimons#7958

**Comment by jarena3** [comment]
Fixed in c921b16d2a841d110a65ecf92c12cbecd5aa63c7
