### ISSUE TITLE
[BUG] NPC Feature Selection "Locked" toggle breaks dialog

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#603]
<strong>Submitted At: </strong>2/4/2020 5:13:51
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
v2.0.1b:  
When editing an NPC, the toggle to display available vs all features breaks the dialog somehow and disables all mouse and keyboard events. 
<strong>To Reproduce: </strong>
* Encounter Toolkit  
* NPC Roster  
* Edit existing or new NPC (tested both)  
* Add Feature  
* Click the lock / all features toggle 
<strong>Expected behavior: </strong>
Should still be able to select a feature from the list, view the information details on a feature,  toggle things on and off, or exit the selection dialog.
<strong>Additional context: </strong>
vue.runtime.esm.js:1888 TypeError: Cannot read property 'key' of undefined
    at ei (vue.runtime.esm.js:5817)
    at vue.runtime.esm.js:6219
    at C (vue.runtime.esm.js:6319)
    at vue.runtime.esm.js:6193
    at C (vue.runtime.esm.js:6319)
    at vue.runtime.esm.js:6193
    at C (vue.runtime.esm.js:6319)
    at vue.runtime.esm.js:6193
    at C (vue.runtime.esm.js:6319)
    at r.__patch__ (vue.runtime.esm.js:6482)
Ut @ vue.runtime.esm.js:1888
Gt @ vue.runtime.esm.js:1879
Vt @ vue.runtime.esm.js:1839
(anonymous) @ vue.runtime.esm.js:1982
Jt @ vue.runtime.esm.js:1906
Promise.then (async)
qt @ vue.runtime.esm.js:1933
ee @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
(anonymous) @ vue.runtime.esm.js:4544
(anonymous) @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonymous) @ vue.runtime.esm.js:4631
validate @ index.js:226
onChange @ index.js:142
$t @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
(anonymous) @ vue.runtime.esm.js:6917
<strong>Contact Info: </strong>
Qwertronix#4443

**Comment by jarena3** [comment]
@Qwertronix are you sure you've updated to the latest npc data?

**Comment by Qwertronix** [comment]
It was indeed caused by the 1.0.1 NPC data, bug is gone after updating and creating new NPCs with the updated 1.0.2 data.
