### ISSUE TITLE
[FEATURE] Stateful Nav Bar

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#605]
**Is your feature request related to a problem? Please describe.**
The Nav Bar does not remember where you came from (compendium or pilot), and does not retain a pilot linke

**Describe the solution you'd like**
The nav bar should watch a vuex field to determine what "side" of the app the user is navigating from and show the appropriate links. This is mostly important for the compendium now, but should be written with the intention of expanding it for homebrew and the campaign builder

**Comment by Qwertronix** [comment]
Perhaps a simpler, cleaner alternative could be to simply establish the links it presents based on the route the nav bar is being rendered into, via the before-enter and before-update router hooks. This would require #547 to be implemented first though (although a fallback state could be kept around and left there during the transition).
