### ISSUE TITLE
[BUG] Doubled Repair capacity

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#607]
<strong>Submitted At: </strong>2/4/2020 13:58:34
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
All frames seem to have "repair cap" and "repair capacity"
<strong>To Reproduce: </strong>
Check any frame
<strong>Expected behavior: </strong>
No doubled repair capacity?
<strong>Additional context: </strong>
I love you all, thanks for such a great app!
<strong>Contact Info: </strong>
Sawfish#1810

**Comment by jarena3** [comment]
Fixed in ef00730476c62b7ab7990449e9e743d9675d80e1
