### ISSUE TITLE
[BUG] Omninet Uplink ID

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#610]
<strong>Submitted At: </strong>2/4/2020 20:47:27
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
The OmniNet Uplink ID can be changed to whatever the user types but then cannot be saved or synced to the cloud.
<strong>To Reproduce: </strong>
Click the edit button for the Omninet Uplink ID. Change ID to something else (like the pilot name). Enter to save. Click "save to cloud" icon next to ID. Receive Error 404 message. 
<strong>Expected behavior: </strong>
Should be able to save the new Omninet Uplink ID after changing it.
<strong>Additional context: </strong>
It would be a lot easier to share pilots and builds between players with something easy to type in. We use Discord a lot but some of us can't access Discord on our laptops so we have to type in that horribly long Uplink ID.
<strong>Contact Info: </strong>
StarCharter#8489 (Discord)

**Comment by jarena3** [comment]
Removed the erroneous edit option for this field. Shouldn't have been in and that was an oversight on my part.
