### ISSUE TITLE
[BUG] Integrated Engineer Weapon Select Invisible Window

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#613]
<strong>Submitted At: </strong>2/5/2020 13:18:36
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
When clicking on the Integrated button to select a weapon on an Engineer Integrated Mount, the app "opens" an empty Select Weapon window. The window doesn't cover the previous screen, but it does impede the user from interacting with anything in the screen. The only indication that something has happened is the title bar on top of the screen that says "Select Weapon" and has the X button to close the bugged window (The X button still works).
<strong>To Reproduce: </strong>
Create a Pilot with the Engineer talent. Select a mech and scroll to the weapons screen. Click on the [INTEGRATED] button on the Engineer Integrated Mount.
<strong>Expected behavior: </strong>
Either no window opens since you cannot change Engineer Weapons, or a window opens with only one option, hiding the previous screen. Alternatively, a special window could open that allows the user to customize their Engineer Weapon according to the options the talent gives.
<strong>Additional context: </strong>
The problem is the lack of feedback that happens when opening the phantom window. Since only the topmost part of the screen changes, the first time it happened I thought the app had crashed because I couldn't interact with anything.
<strong>Contact Info: </strong>
Zebigbos#3786

**Comment by Eranziel** [comment]
This is from 1.5.X. Not possible in 2.X.
