### ISSUE TITLE
[FEATURE] Indicate missing content when importing a pilot that uses a content pack

### ISSUE THREAD

**Issue by aritsune** [massif-press/compcon#616]
**Is your feature request related to a problem? Please describe.**
Right now, when you try to import a character that uses items from a content pack you don't have installed, the importer gives you a vague error (usually something about `toUpperCase`). This is confusing and doesn't tell the user how they can solve the problem - it even tripped me up once.

**Describe the solution you'd like**
Show a more helpful error message when the imported pilot or any of its mechs has missing content. Would be especially helpful if it showed the name/version of the required pack, but I think that might need to first be handled by #560.

**Comment by Eranziel** [comment]
Linked to #560
