### ISSUE TITLE
Feature Request: Cloud Sync from Active Play Mode/ Mission Runner

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#625]
<strong>Submitted At: </strong>2/7/2020 11:23:42
<strong>Is your feature request related to a problem? Please describe. </strong>
Currently to sync the cloud with a local copy as a player you need to exit active play mode for your pilot sheet. And to sync the local copy with the cloud as a gm, you have to leave the Mission Runner and open that pilot in the pilot roster
<strong>Describe the solution you'd like: </strong>
It would be convenient if the options for syncing appeared in Active Play Mode and when you have the pilot's mech selected in the Mission Runner
<strong>Additional context: </strong>

<strong>Contact: </strong>

**Comment by jarena3** [comment]
this won't be possible until we have a proper backend set up, at which point we won't need to lean on sync buttons. I'm going to close this one.
