### ISSUE TITLE
[FEATURE] Quick Switcher

### ISSUE THREAD

**Issue by aritsune** [massif-press/compcon#633]
**Is your feature request related to a problem? Please describe.**
Switching views and finding certain things in the app can feel slow and cumbersome. The Compendium search function is old and unmaintained, can't find anything that isn't equipment, and shows a different/less detailed view of the items with no way to go to the full description.

**Describe the solution you'd like**
A quick switcher akin to Discord's (Ctrl+K). It would find things like pilots, mechs, NPCs, encounters, missions, compendium items (including things like actions, tags...), options and the content manager.
Also, by having the default option be the last view like Discord does, it would provide a really fast way to switch between two parts of the app.
We could also use some of this functionality to bring the Compendium search bar up to speed.

**Additional context**
Probably would take the form of a global component inside App.vue, which can be invoked with a shortcut or an icon in the nav bar. Views and compendium items could be registered via some kind of API. Will likely have to implement some way to programatically expand an item in CompendiumTable.

**Comment by AshleyMcVeigh** [comment]
I think just a universal search like 5e.tools does would be a good solution, it means you can just universal search for the thing/rule you want at that particular time.

like this image but obviously with the current search result styling.

![Capture](https://user-images.githubusercontent.com/21981959/97528828-572cbc00-19fa-11eb-94a5-99d9408c7205.PNG)

In which case from what I can see will require an update to `\compendium\Views\SearchResults.vue` to include more stuff from compendium store. and then maybe more intelligent weighted filtering of the results.
