### ISSUE TITLE
[FEATURE] Overshield bars

### ISSUE THREAD

**Issue by Eranziel** [massif-press/compcon#635]
**Is your feature request related to a problem? Please describe.**
Currently the only way to track overshield in active mode is with a custom counter, which is at the very bottom of the view.

**Describe the solution you'd like**
I suggest adding an overshield tracker near the HP tracker.

**Describe alternatives you've considered**
A tick bar like HP would be ideal aesthetically, but then needs a way to set the maximum. A simple counter like burn would also work.

**Comment by Qwertronix** [comment]
Could use a rating comp where current = max, so it just decreases the maximum when lowering it, and would need a separate way to add more past the "current"/max value (e.g. via the keyboard quick-edit, if the total exceeds max, just set max to the new total)
