### ISSUE TITLE
[BUG] Sort By Type/Name Key Error

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#636]
<strong>Submitted At: </strong>2/9/2020 11:16:59
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
NPC Add Feature menu soft locks when enabling Viewing All Features and Viewing Installed Feature then sorting by Type.
<strong>To Reproduce: </strong>
1. Go to an NPC in the NPC Roster
2. Add Feature
3. Unlock 'Already Installed' and 'All Features'
4. Sort by Type or Name
<strong>Expected behavior: </strong>
Expected menu to continue as normal, displaying information and allowing the addition of parts and features.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
PudgyElderGod #2076

**Comment by Qwertronix** [comment]
@Eranziel already reached out to PudgyElderGod to confirm and this occurs with the version 1.0.2 of the Core NPCs pack.

**Comment by jarena3** [comment]
with 1.0.2 under the latest build I'm unable to reproduce this issue. This might be a system-dependent thing because while it's pretty slow, I haven't been able to get it to lock. This is certainly an optimization target, but I don't think this is currently a bug.
