### ISSUE TITLE
Feature Request: search/filter option for talents?

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#638]
<strong>Submitted At: </strong>2/10/2020 1:13:56
<strong>Is your feature request related to a problem? Please describe. </strong>
there is no way to filter/collapse talents, and i know this is a pretty personal problem, but its a lot of stuff to sort through and read, and theres a lot on-screen and it's hard to keep up and a lot to look through to search out one specific sort of talent
<strong>Describe the solution you'd like: </strong>
a way to group talents, even into broad groups, would ease a lot of touble. there are 29(?) talents, but even having them in groups of say, 10, if theyre in really broad groupings, would be a lot easier than having to go through all 30ish of them. this probably is easier in theory than practice, but thats the only sort of example thing i can offer at the moment, im sorry!
<strong>Additional context: </strong>

<strong>Contact: </strong>
twitter @tokohaanjou

**Comment by jarena3** [comment]
A search field would certainly be possible. Groupings (tags?) would be a potential longer-term feature
