### ISSUE TITLE
[BUG] Can't import pilot through either option (JSON object or cloud ID)

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#642]
<strong>Submitted At: </strong>2/12/2020 12:18:42
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When trying to upload a pilot JSON file or import a pilot cloud ID, both generated from Comp/Con desktop app v.1.5.6, the new browser app consistently gives this this error message: "ERROR ERROR=[[CANNOT/READ/PROPERTY/'TOUPPERCASE'/OF/UNDEFINED]] 
// IDENT INVALID // PLEASE CHECK PROVIDED DATA.", "ERROR IMPORTING PILOT: Cannot read property 'toUpperCase' of undefined".
<strong>To Reproduce: </strong>
1) Go to compcon.app, 
2) select Pilot Roster, 
3) select 'Add a new pilot', 
4) select either 'file import' or 'cloud import', 
4) select local JSON file in provided field (if file import) or paste and enter provided cloud ID in provided field (if cloud import)
<strong>Expected behavior: </strong>
As advertised, either option should successfully import an existing pilot to the new Compcon app.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Discord: rows#6896

**Comment by jarena3** [comment]
can't import from v1.x
