### ISSUE TITLE
[BUG] NPC classes not showing up after loading Lancer CORE NPCs pack

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#643]
<strong>Submitted At: </strong>2/13/2020 2:37:55
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
After loading the Lancer CORE NPCs 1.0.2 LCP I downloaded on the 12th of February, I still cannot create NPCs.
<strong>To Reproduce: </strong>
- Open Content Manager
- Select the Install Content tab
- Browse the Lancer CORE NPCs 1.0.2 LCP
- Press Install
- Confirm on the Content Packs tab that it is indeed active
- Open Encounter Toolkit
- Open NPC Roster
- Press "Add New NPC"
- The app prompts me to "Select NPC Class", but the list is empty, just as if the content pack was not installed.
<strong>Expected behavior: </strong>
I expected the list of loaded NPC classes to appear after pressing "Add New NPC" 
<strong>Additional context: </strong>
Chrome Version 67.0.3396.62 (Official Build) (64-bit), on Ubuntu Linux 16.04
<strong>Contact Info: </strong>
msanyi#2579

**Comment by jarena3** [comment]
unable to reproduce this
