### ISSUE TITLE
[BUG] Black Thumb Text

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#653]
<strong>Submitted At: </strong>2/19/2020 13:25:59
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
In the text for Black Thumb tier 2, Rig Vents does not have its own bullet (and is part of Field Repair's description)
<strong>To Reproduce: </strong>
any time Black Thumb is viewed in the talents pane
<strong>Expected behavior: </strong>
each of the three effects for Black Thumb tier 2 should have their own bullet point for visual clarity
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Xen_Nanashi#5703

**Comment by jarena3** [comment]
moving to relevant repo
