### ISSUE TITLE
Feature Request: Something akin to the Chargen or Mecha construction elements, but for NPC design

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#66]
<strong>Submitted At: </strong>4/16/2019 11:46:14
<strong>Feature: </strong>NPC Kit
<strong>Details: </strong>Something akin to the Chargen or Mecha construction elements, but for NPC design

**Comment by aritsune** [comment]
The NPC toolkit has been integrated into COMP/CON as of 1.5.0.
