### ISSUE TITLE
[BUG] Problem Importing Pilot

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#673]
<strong>Submitted At: </strong>2/26/2020 15:41:19
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
Any attempts to import a pilot via cloud or file import is met with "Cannot read property 'toUpperCase' of undefined"
<strong>To Reproduce: </strong>
Pretty much any time I attempt to import I get that error
<strong>Expected behavior: </strong>
To have my pilot imported
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Sangria#6907

**Comment by aritsune** [comment]
Reached out to the reporter; they were trying to import a 1.5.6 pilot. This does make me want to bring back the validator so we can give a more helpful error message though.
