### ISSUE TITLE
Feature Request: Equipped mod limited use tracker

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#674]
<strong>Submitted At: </strong>2/26/2020 21:05:31
<strong>Is your feature request related to a problem? Please describe. </strong>
Thermal Charge weapon mod doesn't have a charge tracker, so it's not easy to tell how many charges it has total when Engineering points or "Integrated Ammo Feeds" core bonus are applied (or if they are at all), nor an easy way to track how many charges remain at any given time.
<strong>Describe the solution you'd like: </strong>
Add a charge tracker to the mod.
<strong>Additional context: </strong>
https://imgur.com/ChtOsuT.png
<strong>Contact: </strong>
Tropical Bob#6781

**Comment by jarena3** [comment]
Forgot to close this in a previous update
