### ISSUE TITLE
Feature Request: Truly Modular NPC creation

### ISSUE THREAD

**Issue by jarena3** [massif-press/compcon#68]
<strong>Submitted At: </strong>4/18/2019 1:57:39
<strong>Feature: </strong>Truly Modular NPC creation
<strong>Details: </strong>For the encounter builder it would be extremely helpful to let selected Templates choose from all available systems, even those not of their template. This way the options for fun NPC creation within the system is greatly enhanced

**Comment by aritsune** [comment]
This is implemented.
