### ISSUE TITLE
Feature Request: Unmounted pilots in encounter runner

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#680]
<strong>Submitted At: </strong>2/29/2020 16:50:07
<strong>Is your feature request related to a problem? Please describe. </strong>
Currently, there is no way to track unmounted pilots when they inevitably dismount their mechs in the encounter runner. This requires you going to their sheet to check stats which defeats a bit point of the encounter runner.
<strong>Describe the solution you'd like: </strong>
Having Pilots stats be tracked in the encounter runner either as their own character sheet or part of the mech's sheet. Possibly automatically if the pilot's mech is destroyed?
<strong>Additional context: </strong>

<strong>Contact: </strong>
Ragu#0009

**Comment by jarena3** [comment]
collected in #492
