### ISSUE TITLE
[BUG] Não meche

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#687]
<strong>Submitted At: </strong>3/7/2020 20:59:15
<strong>Platform: </strong>
Electron - Linux
<strong>Describe the bug: </strong>
ao abrir o dispositivo não muda sua posição cortando assim uma parte da tela
<strong>To Reproduce: </strong>
...
<strong>Expected behavior: </strong>
...
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

**Comment by aritsune** [comment]
glad we're attracting an international crowd. duplicate of #300
