### ISSUE TITLE
[BUG] Editing Pilot Weapon Options

### ISSUE THREAD

**Issue by Prem-Sinha** [massif-press/compcon#689]
**Describe the bug**
Customization options on pilot gear seem to have a delayed effect,

**To Reproduce**
1. Go to Narrative Profile of a Pilot
2. Click on the gear icon on a piece of equipment to see the options like "Set Custom Name", or for weapons "Select Damage Type"
3. Type in a name or make a selection
4. Nothing seems to change in the description of the equipment.
5. Going elsewhere, like the mech page, and returning shows the changes implemented.

**Expected behavior**
Changes to the gear should be visible as soon as they are made.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10
 - Browser: Mozilla Firefox
 - Version 9016843

**Comment by jarena3** [comment]
This seems to be related to Vue watchers missing the update. Loadout stuff might be a good refactor candidate for this reason

**Comment by jarena3** [comment]
Should be resolved per the removal of multiple pilot loadouts
