### ISSUE TITLE
[BUG] Compendium License Tab Bug

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#690]
<strong>Submitted At: </strong>3/8/2020 13:38:27
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
The License tab of the compendium needs a page reload to show and doesn't show licenses coming from data packs 
<strong>To Reproduce: </strong>
install a datapack (long rim, wallflower or homebrew) open up compcon and try to go on the license tab in the compendium
<strong>Expected behavior: </strong>
I expected the licenses added by data packs to be visible. 
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Elderino #7590

**Comment by aritsune** [comment]
I think I noticed this. The component most likely just needs to get refactored to grab from the compendium with a computed prop instead of only once on creation

**Comment by aritsune** [comment]
Nevermind, just checked and I already did that. might be a tougher one than expected
