### ISSUE TITLE
Feature Request: Discord emojis in generated statblocks

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#694]
<strong>Submitted At: </strong>3/9/2020 10:56:02
<strong>Is your feature request related to a problem? Please describe. </strong>

<strong>Describe the solution you'd like: </strong>
Optionally use Pilot NET emoji codes in generated statblocks (weapon traits and other stuff) for better readability.
<strong>Additional context: </strong>

<strong>Contact: </strong>

**Comment by gnu-lorien** [comment]
Do I have a specific example of what you're looking for? I'm thinking what you mean is to update the following output to something like:

Current
```
[ WEAPONS ]
  Main Mount: NEXUS (HUNTER-KILLER)
  Flex Mount: NEXUS (LIGHT) / NEXUS (LIGHT)
  Heavy Mount: HOWITZER
```

Desired
```
[ WEAPONS ]
  Main Mount: NEXUS (HUNTER-KILLER) :cc_range: 10 :cc_damage_kinetic: 1d6
  Flex Mount: NEXUS (LIGHT) / NEXUS (LIGHT) :cc_range: 10 :cc_damage_kinetic: 16
  Heavy Mount: HOWITZER :cc_range: 20 :cc_aoe_blast: 2 :cc_damage_explosive: 2d6
```
