### ISSUE TITLE
[BUG] Tag values listed as X when printing sheets

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#697]
<strong>Submitted At: </strong>3/10/2020 12:02:05
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When trying to print a character sheet, any tags with a variable value included (limited 3, thrown 5, etc) display the value as "X" instead of a number
<strong>To Reproduce: </strong>
Create a character whose mech is equipped with a system that has a numbered tag, like the Tactical Knife or Pattern-B Hex charges, then use the print option to preview a printout of the character. Even if printed as a pdf, the tags will still have the "X" value
<strong>Expected behavior: </strong>
The tags should show the same numerical value that they do in the book and in regular use of comp/con
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

**Comment by jarena3** [comment]
closed in e55ab2b9c5db7597b6c65b7f0568316540caad11
