### ISSUE TITLE
[BUG] Sisyphus Cut in Half

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#698]
<strong>Submitted At: </strong>3/10/2020 14:44:06
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
The Pegasus' Sisyphus only lists the Probabilistic Cannibalism reaction and not the full action, Bend Probability.
<strong>To Reproduce: </strong>
Click Pegasus, click Sisyphus-Class NHP.
<strong>Expected behavior: </strong>
It should display the full action, rather than just the reaction the NHP lets you take.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

**Comment by Eranziel** [comment]
Can't duplicate in 2.0.15. Looks like it was fixed in e55ab2b9c5db7597b6c65b7f0568316540caad11.
