### ISSUE TITLE
[BUG] Hard Reload causes "Not Found" error

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#701]
<strong>Submitted At: </strong>3/12/2020 15:44:12
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Hard refreshing (through any method) brings up only a simple "Not Found" error. Refreshing normally restores COMP/CON, but the version is still 2.0.20.
<strong>To Reproduce: </strong>
Using latest version of Google Chrome (Version 80.0.3987.132 (Official Build) (64-bit)) hard refresh through any method (dev tools + right clicking refresh for the hard reload option), Ctrl + Shift + R, Ctrl +F5 using COMP/CON 2.0.20.
<strong>Expected behavior: </strong>
Expected hard refresh to update COMP/CON to latest version.
<strong>Additional context: </strong>
Appears to be having a similar issue loading pages, requiring a refresh before they load, though this may be resolved by updating COMP/CON and no ticket has yet been submitted.
<strong>Contact Info: </strong>
no#8963

**Comment by jarena3** [comment]
Unable to reproduce this issue. This seems like a connection problem specific to this user.
