### ISSUE TITLE
Feature Request: Ability to remove pilot portrait

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#716]
<strong>Submitted At: </strong>3/19/2020 10:09:17
<strong>Is your feature request related to a problem? Please describe. </strong>
Setting pilot images seems to block the "license level up" button on mobile. Being able to remove the portrait would be simpler than rebuilding and rewriting the characters. 
<strong>Describe the solution you'd like: </strong>
Under "set pilot portrait" an option to remove a previously set image without replacing it. 
<strong>Additional context: </strong>

<strong>Contact: </strong>
"Lancer of the Endless" in discord.

**Comment by jarena3** [comment]
collected in #300
