### ISSUE TITLE
[BUG] Counter Dice - Stuck

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#717]
<strong>Submitted At: </strong>3/19/2020 12:08:48
<strong>Platform: </strong>
BOTH Firefox and Chrome
<strong>Describe the bug: </strong>
Player reports:

"I went to my active sheet, and there's a counter on the bottom for Leadership dice by default, because I have that ability. I wanted to see if I could set up a counter that counts down, instead of up, so I added a custom counter.

Can't make it count down, though, so I tried to remove it. Hit the trash can. It will not go away.
I'm stuck with a counter called "Leadershipl" at the bottom of my sheet and I don't like it."
<strong>To Reproduce: </strong>
>Create New Counter on Active Pilot Sheet
>Un-able to Remove after addition or subtraction of numbers
<strong>Expected behavior: </strong>
>Removal on clicking of trash-can
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Baconside (She/Her)#1452

**Comment by jarena3** [comment]
Closed #727 via fa7110f.
