### ISSUE TITLE
[BUG] Pilot Talents not displaying

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#718]
<strong>Submitted At: </strong>3/19/2020 17:07:30
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
Attempting to create a pilot in my rooster and everything apart from pilot talents displays correctly and allows me to select things. Pilot talents is the only menu which displays nothing and wont let me select anything.
<strong>To Reproduce: </strong>
Simply open pilot rooster and select add new pilot and select pilot talents.
<strong>Expected behavior: </strong>
Nothing displays once pilot talents has been selected apart from the fluff text and the select 3 pilot talents text box.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

**Comment by jarena3** [comment]
This seems like a custom content issue, but without any contact info I can't diagnose this.
