### ISSUE TITLE
[BUG] Keeps erasing my data

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#719]
<strong>Submitted At: </strong>3/20/2020 7:02:02
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
Compcon will randomly delete my pilots and NPCs that I've built between start-ups. Sometimes it won't, but other times it'll do it multiple times a day. 
<strong>To Reproduce: </strong>
I literally just open it and try to load my pilot. 
<strong>Expected behavior: </strong>
It will be like I've never opened it before. 
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Ertsatz#0362

**Comment by jarena3** [comment]
User is clearing their cache
