### ISSUE TITLE
[BUG] First Custom Counter cannot be removed

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#720]
<strong>Submitted At: </strong>3/20/2020 14:15:35
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
The first custom counter you make in the active combat screen (very bottom of the screen after all mech systems) cannot be removed. Additional counters can be removed freely.
<strong>To Reproduce: </strong>
Create a custom counter in active combat screen with no other counters present. Attempt to remove the counter via the appropriate GUI button.
<strong>Expected behavior: </strong>
Removal of the counter when clicking on the appropriate GUI button.
<strong>Additional context: </strong>
Optional: Ability to rename counters, due to having to delete and recreate a counter if you incorrectly named the counter.
<strong>Contact Info: </strong>
KryliaViru#9347
<strong>Stack Trace: </strong>
First Custom Counter cannot be removed

**Comment by jarena3** [comment]
Closed #727 via fa7110f.
