### ISSUE TITLE
[BUG] Error when reopening an NPC class

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#721]
<strong>Submitted At: </strong>3/20/2020 14:51:31
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When reopening an NPC class dialogue, it fails, and an error appears: ERROR: t.$refs[("modal_" + i.ID)].show is not a function
<strong>To Reproduce: </strong>
Open an NPC class entry in the compendium, close it, and then try opening the same one again.  Each class will open successfully once, but fail the second time.
<strong>Expected behavior: </strong>
It should open both times.
<strong>Additional context: </strong>
Backing out of the NPC classes list to the menu or main compendium screen allows each class to be opened (once) again.
<strong>Contact Info: </strong>
megane
<strong>Stack Trace: </strong>
Error when reopening an NPC class

**Comment by jarena3** [comment]
Closed #727 via fa7110f.
