### ISSUE TITLE
[BUG] ERROR:   t.ccLog is not a function

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#723]
<strong>Submitted At: </strong>3/21/2020 12:24:36
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Error code whenever loading into comp/con. Nothing seems broken 
<strong>To Reproduce: </strong>
open comp con on your chrome browser
<strong>Expected behavior: </strong>
not get an error
<strong>Additional context: </strong>
error code
<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>
ERROR:   t.ccLog is not a function

**Comment by jarena3** [comment]
Closed #727 via fa7110f.
