### ISSUE TITLE
[BUG] Error message when naming NPC.

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#726]
<strong>Submitted At: </strong>3/22/2020 16:04:12
<strong>Platform: </strong>
Browser: Opera
<strong>Describe the bug: </strong>
When I try to change an NPC's name, an error message pops up. The name is still able to be changed with no apparent issue.
<strong>To Reproduce: </strong>
Attempt to edit an NPC's name.
<strong>Expected behavior: </strong>
For the NPC name to change without an error message.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
mFictionist (Victoria)#6006
<strong>Stack Trace: </strong>
Error message when naming NPC.

**Comment by jarena3** [comment]
Closed #727 via fa7110f.
