### ISSUE TITLE
[BUG] ERROR:   t.tag.GetName is not a function

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#728]
<strong>Submitted At: </strong>3/24/2020 11:25:17
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Upon selection of a NPC, three minor pop-ups in the bottom right appear with the error "ERROR:
 
t.tag.GetName is not a function"

Seems to have no noticeable effect.
<strong>To Reproduce: </strong>
Unsure. Seems random but, mainly appears when selecting npc's with the custom name "Grunt"
<strong>Expected behavior: </strong>
For that error to not appear?
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Baconside (She/Her)#1452
<strong>Stack Trace: </strong>
ERROR:   t.tag.GetName is not a function

**Comment by jarena3** [comment]
Looks to be resolved as of the 1.0.3 NPC Data update
