### ISSUE TITLE
Feature Request: Source Filtering

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#729]
<strong>Submitted At: </strong>3/25/2020 11:00:52
<strong>Is your feature request related to a problem? Please describe. </strong>
Not a present problem but one that could happen in the future if a very large number of source books are eventually released
<strong>Describe the solution you'd like: </strong>
Ability to filter items based on the source, ie, Core book, Long Rim, Wallflower, etc
<strong>Additional context: </strong>

<strong>Contact: </strong>
MeckaMecha#6969

**Comment by jarena3** [comment]
collected in #965
