### ISSUE TITLE
[BUG] Unknown error

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#730]
<strong>Submitted At: </strong>3/25/2020 15:37:20
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
I get a error message but not sure what it is for
<strong>To Reproduce: </strong>
Happens at random while on the main screen.
<strong>Expected behavior: </strong>
No random error logs?
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
The-Smiling-Fool#1331
<strong>Stack Trace: </strong>
Unknown error

**Comment by thesmilingfool** [comment]
My issue is the same as #731[BUG} but they have better explained the issue.

**Comment by jarena3** [comment]
Closed #727 via fa7110f.
