### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by baslisks** [massif-press/compcon#731]
**Describe the bug**
orange windo that says ERROR: tccLog is not a function in bottom right hand side of the screen.

**To Reproduce**
1. Go to Compcon
2. Hover over view changelog
3. look at bottom right and see that it says ERROR: tccLog is not a function

**Expected behavior**
nothing shows up

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 74

**Comment by jarena3** [comment]
Closed #727 via fa7110f.
