### ISSUE TITLE
[BUG] Bug when selecting npcs

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#732]
<strong>Submitted At: </strong>3/26/2020 7:53:40
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
When i am in the npc roaster I get a error whenever i click on a npc that i can customized the name of. produces 3-8 of the same error logs. Tried changing the name to see if that was the problem but them it gives me a new error (posted below after the first error log)
<strong>To Reproduce: </strong>
Name npc, made ultra elite and anytime i leave the npc and click on them again
<strong>Expected behavior: </strong>
shouldn't be getting an error?
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
The-Smiling-Fool#1331
<strong>Stack Trace: </strong>
Bug when selecting npcs

**Comment by jarena3** [comment]
Closed #727 via fa7110f.
