### ISSUE TITLE
[BUG] ERROR:   t.ccLog?

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#733]
<strong>Submitted At: </strong>3/26/2020 10:00:43
<strong>Platform: </strong>
Browser - Safari
<strong>Describe the bug: </strong>
Red error Box appearing on home screen.
<strong>To Reproduce: </strong>
hover mouse over View Change Log
<strong>Expected behavior: </strong>
ERROR:
 
t.ccLog is not a function. (In 't.ccLog("update")', 't.ccLog' is undefined) appears. 
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Flintwyrm
<strong>Stack Trace: </strong>
ERROR:   t.ccLog?

**Comment by jarena3** [comment]
Closed #727 via fa7110f.
