### ISSUE TITLE
[BUG] Encounter Runner displays incorrect Structure/HP

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#737]
<strong>Submitted At: </strong>3/28/2020 11:11:07
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When using the encounter runner with NPCs that have Ultra or RPV templates (or presumably any others that increase max HP), or any NPC that has more than 1 structure/stress, only the base amount is shown by default - for example a 15 base HP Veteran Ultra should start a battle with 20/20 HP and 4/4 Structure/Stress, but instead starts with 15/20HP and 1/4 Structure/Stress.
<strong>To Reproduce: </strong>
Make an NPC with any template that increases HP/Structure/Stress (eg Ultra). Add this NPC to an encounter and then add the encounter to a mission. In the mission runner, this encounter will display their HP and Structure/Stress at their base values, rather than with the increase from their templates.
<strong>Expected behavior: </strong>
The NPCs should start battle with full HP, Structure, and Stress.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
This should be fixed as of the NPC stat changes
