### ISSUE TITLE
Feature Request: NPC Roster Organization

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#741]
<strong>Submitted At: </strong>3/29/2020 8:41:28
<strong>Is your feature request related to a problem? Please describe. </strong>
When you've made a lot of NPCs the list can get overwhelming.
<strong>Describe the solution you'd like: </strong>
Making it possible to collapse the tree headers created by the Sort function, and having the Sort maintained during a session. Like, sorting by Campaign and then collapsing all campaigns except the one you're working in.
<strong>Additional context: </strong>

<strong>Contact: </strong>

**Comment by jarena3** [comment]
Collected in #865
