### ISSUE TITLE
Feature Request: Hide NPC modules.

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#744]
<strong>Submitted At: </strong>3/29/2020 14:32:30
<strong>Is your feature request related to a problem? Please describe. </strong>
Some NPCs have layouts which are clogged by "trivial" modules like the Ultra's +5 HP trait which can making sifting for the relevant information more difficult.
<strong>Describe the solution you'd like: </strong>
The option to hide modules added to the module modification box where you can change module tier or name would be excellent. With something to indicate that X modules have been hidden and that they can be revealed
<strong>Additional context: </strong>

<strong>Contact: </strong>
Neverender

**Comment by jarena3** [comment]
Collected in #749
