### ISSUE TITLE
[BUG] Error Messages

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#753]
<strong>Submitted At: </strong>3/31/2020 10:20:20
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When searching in the compendium, too many error messages pop up
<strong>To Reproduce: </strong>
After searching for anything in the compendium, any alterations to the search query causes an error.
<strong>Expected behavior: </strong>
Error messages should not be appearing after editing search query
<strong>Additional context: </strong>
The popupis "Error: Expected a funciton"
<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by aritsune** [comment]
Fixed in 2.0.20, reporter probably didn't update. Wish they'd dropped a contact
