### ISSUE TITLE
[BUG] NPC structure, stress not updating properly

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#754]
<strong>Submitted At: </strong>4/1/2020 14:08:54
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
NPC structure and stress does not update properly with multiple templates, and extra structure and stress does not show up in the encounter runner.
<strong>To Reproduce: </strong>
adding the elite and veteran templates to an NPC in the NPC creator only applies the extra structurea and stress from the first template applied. 

in the encounter runner, structure, stress, and HP changes from the baseline are not shown, such as an elite veteran having no extra structure and grunts remaining at the regular HP value.
<strong>Expected behavior: </strong>
accurate stress and structure amounts on the NPC roster page and in the encounter runner.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
SalsaDeGranada
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
This looks to be fixed in the latest version. It may require the user remake old NPCs. I'll contact them directly
