### ISSUE TITLE
[BUG] Biography text field issue

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#756]
<strong>Submitted At: </strong>4/1/2020 23:57:59
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
So, for some reason or another, editing the pilot biography field results in the behavior of as if you have pressed the insert key once and then began typing. As you can imagine, this is rather frustrating if you decide to go back and change something. Additionally, it would appear actually attempting to press the insert key on the keyboard does nothing to stop this.
<strong>To Reproduce: </strong>
Type something into the pilot biography field, then either by clicking or usage of the arrow keys, go to an earlier part of what you typed, and change it.
<strong>Expected behavior: </strong>
Being able to change the text without every newly typed character 'typing over' a currently existing one without having any characters selected. Now, if I had a character selected, I would expect to replace it by typing something, but I don't have any selected.
<strong>Additional context: </strong>
It potentially may be that it is forcibly selecting a character to replace, rather than no selection.
<strong>Contact Info: </strong>
KryliaViru#9347
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Chrome version-specific issue. Closing.
