### ISSUE TITLE
Feature Request: Long RIM Alternate Mana system implementation

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#758]
<strong>Submitted At: </strong>4/3/2020 18:40:09
<strong>Is your feature request related to a problem? Please describe. </strong>
No
<strong>Describe the solution you'd like: </strong>
Can you implement the Long Rim atlernate manna system in comp/con, please? I find this system and its granularity very appealing and more organic. Sadly there is no way to use it with the comp/con that I know of. I tried to look in the requested features, but didn't see any request. 
<strong>Additional context: </strong>
My character is the sole survivor of a ghost ship, man by an NHP called NOBILIS. Being sick, he didn't join his family in suspension pod and was awake when a critical incident happened. The skeleton crew died instantly or trying to save the ship. The rest of the crew died because of cascading failures in the power grid or ended up locked in stasis. The NHP and my character did what they could to keep the ship in one piece. As the NHP was past the point of non return and had precise directives to avoid contact with non corporate agents, the ship stayed on its course in the Long Rim for the years that followed. In the end the NHP ended up cascading and tricked my character into entering an escape pod before launching him in the vicinity of a space station (he waited a couple of days before being rescued). To that day my character still wonder if he has been betrayed or saved by the unshackle NHP, who ran away with the forever frozen bodies of his friends and families in the ship. He then developped an obsession for NHPs and their innerworking. That's why he has the technophile talent, the Hack or Fix and researcher triggers. With the alternate manna system I can push those to max, before carring for chassis and licenses while the Everest is a solid mech for my character and its concept for a while I do long cover support with the heavy rifle among other weapons. 

<strong>Contact: </strong>

**Comment by jarena3** [comment]
That certainly is additional context!

Collected in #630
