### ISSUE TITLE
[BUG] Deleting Pilot Data

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#759]
<strong>Submitted At: </strong>4/3/2020 18:45:58
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
Not sure if it's my computer or the website, but if I close comp/con deletes all pilot data and the Long Rim data disappears, and I have to import it again (I am having to save my pilot ID to be prepared for it because it's happening so often)
<strong>To Reproduce: </strong>
Restarting my computer guaranteed reproduces the issue, and every comp/con update has reproduced the issue
<strong>Expected behavior: </strong>
Save imported data
<strong>Additional context: </strong>
Importing Cloud ID does successfully import the pilot data again, but only if I remember to add the Long Rim data again first every time.
<strong>Contact Info: </strong>
Sláinte#8894
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
This is almost certainly a browser settings issue. Contacting this user directly.
