### ISSUE TITLE
[BUG] Post Character Creation Pilot Card Talent bug.

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#765]
<strong>Submitted At: </strong>4/7/2020 12:43:17
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
The pilot card after character creation is done only list talents as being rank 1
<strong>To Reproduce: </strong>
generate a card on someone with talents that aren't at rank 1
<strong>Expected behavior: </strong>
I expected the card to show the rank of the talent.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Elderino#7590
<strong>Stack Trace: </strong>

**Comment by aritsune** [comment]
Fixed in https://github.com/massif-press/compcon/commit/0a09f15ee13930e49cd755a5dccf13654722f73a
