### ISSUE TITLE
[BUG] Integrated mount can be removed, changed, and destroyed via cog menu

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#766]
<strong>Submitted At: </strong>4/7/2020 20:25:11
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
You can remove integrated weapons from mechs in compcon. If you do, you can't put it back
<strong>To Reproduce: </strong>
Click the gear on an integrated weapon and click remove.
<strong>Expected behavior: </strong>
I dunno what I expected, but it's broke as hell.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
LesbianWitchAcademia#8652
<strong>Stack Trace: </strong>

**Comment by aritsune** [comment]
Provided screenshot: 
![image](https://user-images.githubusercontent.com/4382547/78734666-3813f300-791f-11ea-8da9-a47ca1431263.png)

As an addendum, integrated weapons also cannot be marked as destroyed
