### ISSUE TITLE
[BUG] Misalligned icons on Mech Systems

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#768]
<strong>Submitted At: </strong>4/8/2020 0:34:21
<strong>Platform: </strong>
Electron - Linux
<strong>Describe the bug: </strong>
Mech systems and weapons have the trash can icon and other clipped offin come cases. Seems to effect systems and weapons fruther down the page.
<strong>To Reproduce: </strong>
Create a mech with a full loadout
<strong>Expected behavior: </strong>
Icons fully visible
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Unwary@3649
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Seems to be resolved
