### ISSUE TITLE
[BUG] Reset in multiLL pilot adjustments clears everything

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#770]
<strong>Submitted At: </strong>4/8/2020 0:39:12
<strong>Platform: </strong>
Electron - Linux
<strong>Describe the bug: </strong>
Jumping a pilot several license levels and then going to edit talets, trigger, etc and hitting reset clears everything, not just the talent or triggers selected to "level up"
<strong>To Reproduce: </strong>
Create a pilot, then set it's license level to 3 or so, go to edit talents or triggers, add one or two, and hit reset.
<strong>Expected behavior: </strong>
Only chnages made in this interaction should be reset. Users can walk back talents and triggers manuall if wanted
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Unwary@3649
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
This isn't a bug, it's a feature change, and one I don't think needs to be made.
