### ISSUE TITLE
[BUG] Speed Scrolling and regular scrolling don't mix

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#772]
<strong>Submitted At: </strong>4/8/2020 0:42:50
<strong>Platform: </strong>
Electron - Linux
<strong>Describe the bug: </strong>
Scrolling up while being speed scrolled to the bottom after making a selection stops the speedscroll early,
<strong>To Reproduce: </strong>
Create a pilot, and select talents near the top of the screen. When you select your third talent, scroll up a little ways before the animation finishes
<strong>Expected behavior: </strong>
Scroll up cancels the animation, or the animation completely scrolls down
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Unwary#3649
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Not going to bother with breaking apart the vuetify scroll directive to deal with something like this
