### ISSUE TITLE
[BUG] Encounter builder text boxes overwriting each other

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#776]
<strong>Submitted At: </strong>4/10/2020 0:06:35
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
most of my encounters are sharing the contents of the pc victory, enemy victory, objective, etc text boxes. deleting the text in one encounter deletes it in all of them, making a new encounter copies the text from all the other missions that are doing this, etc
<strong>To Reproduce: </strong>
entering or deleting text in the various text boxes in the encounter builder, for objective or PC victory etc, overwrites the same text in multiple other encounters but for some reason not all.

affected encounters were all created as standard encounter in the sitrep dropdown, unaffected ones had been switched to holdout or escort

all newly created encounters after this started have the same issue 

additionally, the sitrep dropdown switches to whichever entry it was last set to in all encounters
<strong>Expected behavior: </strong>
each encounter's text boxes should not overwrite the same boxes in other encounters
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
ersatz#1820
<strong>Stack Trace: </strong>
n/a

**Comment by jarena3** [comment]
caught this in #749
