### ISSUE TITLE
[BUG] Mission Runner: Current HP and Heat bar problems

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#779]
<strong>Submitted At: </strong>4/10/2020 14:06:00
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Whenever you change an NPC's current HP or Heat in the mission runner, the length of the bar changes so that it's only as long as the current value for the given, and the numerical display changes to X/X instead of X/Max. Also, if Heat is set to zero, then set to any value above zero, the npc immediately becomes exposed, even if the new heat value is below the heat capacity. It seems to be impossible to have zero HP, so structure checks aren't being triggered. Inputting a negative value for HP also seems to set the current HP to the absolute value of the input, instead of subtracting the input from the current value.
<strong>To Reproduce: </strong>
Create a new npc, preferably with a template that adds extra structure, then add it to an encounter assigned to a mission. Start that mission, then try to edit the NPC's current health and heat values
<strong>Expected behavior: </strong>
HP and Heat capacity bars are normally based on maximum HP and heat, not the current value. HP going below 1 should trigger a structure check, heat values below the heat capacity shouldn't cause npcs to become exposed
<strong>Additional context: </strong>
Version 2.0.27

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by Cancermantis** [comment]
I'd missed something when I made this report: the same issue seems to happen with the movement meter. I'd just assume it's all the pip-based trackers
