### ISSUE TITLE
[BUG] The Caliban SUPERMASSIVE MOD, dont appear on system list

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#783]
<strong>Submitted At: </strong>4/12/2020 19:51:35
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
The Caliban SUPERMASSIVE MOD, dont appear on system list
<strong>To Reproduce: </strong>
chose rank I caliban, then create a mech and search The Caliban SUPERMASSIVE MOD
<strong>Expected behavior: </strong>
Appear The Caliban SUPERMASSIVE MOD
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
they're looking for the mod in the systems list, they should be checking the mod list
