### ISSUE TITLE
[BUG] Permanent Superheavy Weapon Bracing

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#785]
<strong>Submitted At: </strong>4/16/2020 1:36:17
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Superheavy Weapon Bracing can't be uninstalled.
<strong>To Reproduce: </strong>
On a frame (Everest), when changing from a Superheavy Weapon (Cyclone Pulse Rifle) to a Main (Assault Rifle) or Auxiliary Weapon (Pistol) in the Heavy Mount, the Main slot remains as Superheavy Weapon Bracing. The Superheavy Weapon Bracing persists through going back to the mech hangar.
<strong>Expected behavior: </strong>
When uninstalling the Superheavy Weapon, the Superheavy Weapon Bracing should also be uninstalled.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Nico#5913
<strong>Stack Trace: </strong>

**Comment by aritsune** [comment]
Reproduced
