### ISSUE TITLE
[BUG] Deleted Pilots, Forced Restart

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#792]
<strong>Submitted At: </strong>4/18/2020 19:27:38
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
I was making a new pilot and was in the middle of making the mech for the pilot when I accidentally closed out of the creator. When I reopened the creator, not only had I lost the data for that pilot, but I lost all my previous pilots and the creator reset itself to its original conditions.
<strong>To Reproduce: </strong>
Make a new pilot in full, make another pilot, and exit the creator mid-creation.
<strong>Expected behavior: </strong>
I expected to only lose the data for the new pilot, not have the entire creator reset.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
The Unknown#7590
<strong>Stack Trace: </strong>

**Comment by byronhulcher** [comment]
I've definitely noticed issues refreshing the page inside of a view and not getting my locally saved data to appear.  For instance, refreshing inside the NPC Roster reloads the NPC Roster with all your already-created NPC's missing.  I've noticed this across a few routes (but specifically remember running into this w/ NPC Roster).  I suspect if this person navigated to the root of the application they'd find their data again.

**Comment by jarena3** [comment]
yeah that's what it looks like. I'll take a routing pass later to clean things up but for now I'm going to close this one
