### ISSUE TITLE
[BUG] Saladin Shield Reaction Errors

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#793]
<strong>Submitted At: </strong>4/19/2020 1:48:53
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Both the Flash Anchor and the Support Shield have errors in their Reactions: Flash Anchor has the wrong Reaction entirely, and there is no indication of the Heat Cost on either the Support Shield's Blinkfield Intervention Reaction or the Flash Anchor's Flash Lock.
<strong>To Reproduce: </strong>
This appears to be the case wherever the systems are viewed, in pilot or in compendium.
<strong>Expected behavior: </strong>
The rules text on these reactions should be amended.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by aritsune** [comment]
The text error is PR'd over [here](https://github.com/massif-press/lancer-data/pull/122). It seems like effects (for reactions, at least) don't render their tags, so I'll make that a separate issue

**Comment by aritsune** [comment]
Text is fixed, tag issue is tracked in #796
