### ISSUE TITLE
Feature Request: Relocatable Custom Counters (gunsliger, ect)

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#794]
<strong>Submitted At: </strong>4/19/2020 19:03:21
<strong>Is your feature request related to a problem? Please describe. </strong>
Just a bit of a hassle for our players who have brawler,gunslinger to have to keep scrolling all the way down to the bottom of active play mode to use the custom counters for tracking charges
<strong>Describe the solution you'd like: </strong>
If custom counters could be under HP/Heat section, but above weapon mounts, that'd be awesome and more streamlined for use
<strong>Additional context: </strong>

<strong>Contact: </strong>
Xen_Nanashi #5703

**Comment by jarena3** [comment]
resolved in #546
