### ISSUE TITLE
[BUG] Reaction effects do not render tags

### ISSUE THREAD

**Issue by aritsune** [massif-press/compcon#796]
**Describe the bug**
Despite having tags (such as Heat X (Self)) described in the data, Reaction effects never render this. Flash Anchor's Flash Lock is an example.

**To Reproduce**
1. Open compendium's Systems section
2. Search for Flash Anchor, view the Flash Lock description
3. The Heat Self tag is nowhere to be seen, despite being there [in the data](https://github.com/massif-press/lancer-data/blob/6b27fe6892bd0a6f9564eee3296fdccb4ee0e111/lib/systems.json#L3034)

**Comment by jarena3** [comment]
Corrected in #842
