### ISSUE TITLE
[BUG] Caliban Superheavy Mod Not Appearing

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#799]
<strong>Submitted At: </strong>4/20/2020 20:52:43
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
The Supermassive Mod from Caliban License Level 1 cannot seem to be applied to any weapons. 
<strong>To Reproduce: </strong>
As far as I can tell the issue is that the Supermassive Mod does not show up in listings for weapons that should be applicable. Even if Caliban License Level 1 is selected, even when using melee/CQB/cannon weapons, it does not show. Whether license availability or SP capacity are turned on or off, the mod does not show.
<strong>Expected behavior: </strong>
In having Caliban LL1, I expected to have the mod available so that I could equip it to one of my mech weapons. As described above, the Superheavy Mod is not listed as an available mod regardless of specifications.
<strong>Additional context: </strong>
When I look at weapon mods, I see a [MODIFICATION DATA INVALID OR MISSING] indicator in the top right. This does not show for weapons nor systems.
<strong>Contact Info: </strong>
Kagimizu#8136
<strong>Stack Trace: </strong>

**Comment by aritsune** [comment]
Followed up and user had old version of Long Rim LCP
