### ISSUE TITLE
[BUG] HP rollover error when taking structuring damage

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#803]
<strong>Submitted At: </strong>4/23/2020 11:02:31
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
While running an encounter, if I type "-x" into the HP field where x is larger than their remaining HP (y), after structuring their current HP will be listed as larger than their max: Max+x-y.
<strong>To Reproduce: </strong>
See above
<strong>Expected behavior: </strong>
After structuring, their current HP should be Max-x+y
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by aritsune** [comment]
Error is here, should be + val rather than - val: https://github.com/massif-press/compcon/blob/cf3b7853bb466c9cce82d4bfb4da02ab3692d779/src/classes/npc/Npc.ts#L379-L381
