### ISSUE TITLE
[FEATURE] Effects stringifier 

### ISSUE THREAD

**Issue by aritsune** [massif-press/compcon#804]
**Is your feature request related to a problem? Please describe.**
The new effects format is very nice but it makes lancer-data a lot harder for other software to consume, since it takes so much extra work to make human-readable.

**Describe the solution you'd like**
A string property for the effects or a stringify method for ItemEffects.

**Comment by Edicatax** [comment]
I coincidentally added a stringify method to many (not all) effects in #805
