### ISSUE TITLE
Feature Request: Rename Option for Frames

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#806]
<strong>Submitted At: </strong>4/24/2020 22:53:48
<strong>Is your feature request related to a problem? Please describe. </strong>
I'm in a game that uses a homebrew setting but wants to keep the mechanics of the game without having everything be flavored as it is by default. The ability to rename frames in the mech hangar would help a lot to keep the homebrew lore flavor our GM is going for.
<strong>Describe the solution you'd like: </strong>
Just the ability to rename the specific frame used, the way equipment can be given custom names that show up on text statblocks -- like, where it says "GENERAL MASSIVE SYSTEMS STANDARD PATTERN I EVEREST", being able to set a custom manufacturer and frame name would be perfect. Custom colors would be neat too but probably not really necessary.
<strong>Additional context: </strong>

<strong>Contact: </strong>
Nasajin#1006

**Comment by jarena3** [comment]
Unfortunately this sort of total conversion stuff is outside the scope of COMP/CON
