### ISSUE TITLE
[BUG] Incorrect Evasion stat

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#814]
<strong>Submitted At: </strong>4/28/2020 3:48:05
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
Evasion of my mech should be 6 according to the mech hangar, but in active play mode it displays as 5
<strong>To Reproduce: </strong>
Pilot at LL5, 3 Ghengis 2 Sherman, 3Hull 4Engineering. Mech equipped with Krakatoa, Mortar, Laser Rifle. Went directly form mech hangar loadout to active play mode.
<strong>Expected behavior: </strong>
My evasion stat should remain consistent between different menus and not be 5 in active play mode.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
@jaketheknight#9089
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Unable to reproduce. Maybe "Stunned" was toggled as a status in active mode?

**Comment by GlennPatrickCullen** [comment]
A player in my party reproduced this bug by rolling the "Stunned" outcome of taking structure damage. This capped the mech's evasion to 5 but did not apply a stunned condition. The only way to fix this was to undergo a full repair.
