### ISSUE TITLE
[BUG] Encounter Builder NPC Selection Scroll Errors

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#816]
<strong>Submitted At: </strong>4/28/2020 12:12:25
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When adding NPCs to an encounter in the Encounter builder, clicking the name of an npc class doesn't properly scroll to the selected NPC in certain situations, instead scrolling to the top of the list. This occurs when you either click "add NPC" under Forces or Reinforcements, and causes the "add NPC" option under the other grouping to malfunction.
<strong>To Reproduce: </strong>
1. Create a new encounter under the Encounter Builder after making some test npcs
2. Click on add NPC under Forces.
3. Exit out of the NPC selector, and click on add NPC under Reinforcements. 
4. Attempt to navigate the NPC list by clicking the NPC names. Also try scrolling down a little and then clicking on an NPC name: It should scroll back to the top.
Similar behavior also occurs in reverse if you select add NPC under Reinforcements first and Forces second. Which one is "first" and thus which one is broken is reset every time you leave and reenter the Encounter builder.
<strong>Expected behavior: </strong>
Clicking on the name of an npc should cause scrolling to the selected NPC no matter what.
<strong>Additional context: </strong>
I am aware that this error was supposedly fixed in this update, 2.0.29, but the error still seems to appear. https://github.com/massif-press/compcon/pull/808
<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by byronhulcher** [comment]
@aritsune if you assign me I will look into this error, I'm sure it's the result of my changes in #808

**Comment by aritsune** [comment]
@byronhulcher go right ahead!

**Comment by jarena3** [comment]
resolved in #818
