### ISSUE TITLE
[BUG] Mac OS Chrome Webapp doesn't cloud share properly

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#817]
<strong>Submitted At: </strong>4/28/2020 15:25:33
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When sharing pilot Cloud IDs on Mac OS, doesn't create and share a valid Pilot ID. Works properly on the same computer when booting into windows mode vs mac OS
<strong>To Reproduce: </strong>
Save pilot to vault, then share cloud ID on a Mac OS chrome browser.
<strong>Expected behavior: </strong>
Pilot ID import error.
<strong>Additional context: </strong>
Same Machine dual booting Mac OS and windows. Windows chrome web app works fine, mac os chrome app doesn't.

Reporting for the player who is having issues.
<strong>Contact Info: </strong>
Keleth#5927
<strong>Stack Trace: </strong>

**Comment by byronhulcher** [comment]
I think this issue can be closed.  I discussed this with the reporting user in the `#comp-con` channel on Discord:

```
hypirlink (he/him)Today at 4:43 PM
@Keleth (She/Her) Carolina was the PC name?
LL1, Everest Holliday?
I was able to cloud import 4dc5877a0f980447ca3db88745dbd372 the id you included in #gm-corner on https://compcon.app/

Keleth (She/Her)Today at 4:44 PM
Yeah

hypirlink (he/him)Today at 4:45 PM
Also 7033a22bd91b71397410bb0ec36f4ca5

Keleth (She/Her)Today at 4:45 PM
Wait they both worked?

hypirlink (he/him)Today at 4:45 PM
Yup

Keleth (She/Her)Today at 4:45 PM
...Let me try reloading everything
Cuz a few others in CM corner didn't have it work but I'm wondering...if the web app didn't update and reload properly on my end
Yeah that one is working now
```

The issue resolved itself after a refresh of the client.  While there might have been a legitimate issue in their client when attempting to import the data from the cloud, I can confirm that the client IS generating and displaying correct IDs for cloud synced pilots, and we are able to import them on 2.0.29 on `https://compcon.app`

**Comment by aritsune** [comment]
thank you, closing!
