### ISSUE TITLE
[BUG] Version "Unknown"

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#820]
<strong>Submitted At: </strong>4/28/2020 19:22:22
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
The desktop app displays UNKNOWN for the version number and has the Download Update button active, despite being the newest release.
<strong>To Reproduce: </strong>
Downloaded and ran the Comp/Con v2 desktop app.
<strong>Expected behavior: </strong>
Finding and understanding its correct version.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
chaemera
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
This is known and will be resolved as part of the build process
