### ISSUE TITLE
Feature Request: GMS Core Bonus Selection

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#834]
<strong>Submitted At: </strong>5/5/2020 0:27:34
<strong>Is your feature request related to a problem? Please describe. </strong>
The GMS core bonuses should be available starting at license level 0 according to the manual
<strong>Describe the solution you'd like: </strong>
Adding the bonuses in a list like the licensed ones should work!
<strong>Additional context: </strong>
Thank you for your time
<strong>Contact: </strong>

**Comment by aritsune** [comment]
user misunderstood the book
