### ISSUE TITLE
[BUG] Spaceborn talent rank I does not auto equip EVA MODULE on build mech's.

### ISSUE THREAD

**Issue by Qlay** [massif-press/compcon#835]
**Describe the bug**
For Desktop standalone v2 version.
Spaceborn talent rank I does not auto equip the free EVA MODULE on new or existing mech's.
EVA module's are still available as a cost 1 option.

The web app does not have the Spaceborn talent.

**To Reproduce**
1. Select the Spaceborn talent rank 1 on character creation or on level up.
2. Create a new mech or modify an existing one in the mech hangar.
3. Modify a mech's systems.
4. See that the EVA module is available as a cost 1 option.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome.
 - Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by aritsune** [comment]
Spaceborn 1 as it is worded does not actually create a system like Technophile does, although it's not necessarily a bad idea to have C/C do so for clarity. 

It certainly isn't the GMS EVA module though - that's a separate thing (it doesn't have the "shunt" quick action) & nothing stops you from equipping both, as redundant as it may be, so it still showing up is fully intended.

Also, the web app certainly has Spaceborn, you just need to install the Long Rim content pack. This is the case for the standalone too so I'm curious how you reached this conclusion.

**Comment by Qlay** [comment]
I see. Thanks!

100% my mistake and confusion due to the wording and similarity in wording then.
Also did not realize Spaceborn belonged to Long-Rim...
