### ISSUE TITLE
Feature Request: Homebrew Support

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#836]
<strong>Submitted At: </strong>5/6/2020 17:27:29
<strong>Is your feature request related to a problem? Please describe. </strong>
Not problem related
<strong>Describe the solution you'd like: </strong>
A builder for custom content that could be used through the COMP/CON app. Examples include equipment that can be created through this builder would be able to be equipped in the mech builder/gear/etc. 
<strong>Additional context: </strong>
Example of use: The GM wants to make a custom piece of frame mod/equipment. Using the builder, the GM could construct a title, descriptions, use #, etc. and when finished, this item could be equipped through the Frame menu like any other equipment/weapon.
<strong>Contact: </strong>

**Comment by aritsune** [comment]
A homebrew editor is planned, although I guess we didn't have an issue for it

I wonder if the reporter knows about JSON homebrew though?

**Comment by jarena3** [comment]
I think I'm just going to close this one -- I'll make a better tracking issue when we get there
