### ISSUE TITLE
Feature Request: RM-4 export

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#848]
<strong>Submitted At: </strong>5/17/2020 11:46:59
<strong>Is your feature request related to a problem? Please describe. </strong>

<strong>Describe the solution you'd like: </strong>
The RM-4 Pilot Identification screen is a really nice visual, would it be possible to export it as part of the character sheet?
<strong>Additional context: </strong>

<strong>Contact: </strong>

**Comment by jarena3** [comment]
The little icon next to the IDENT ID
