### ISSUE TITLE
[BUG] Can't see what i'm typing on the overshield keyboard for GM active mode

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#855]
<strong>Submitted At: </strong>5/21/2020 21:19:34
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
on a smaller resolution, the GM active encounter tracker for PCs makes the overshield keyboard prompt disappear after clicking it, right under the mech picture
<strong>To Reproduce: </strong>
click on the overshield keyboard in the GM section while having a medium laptop resolution
<strong>Expected behavior: </strong>
I expected to be able to see what I typed
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Elderino #7590
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Closing this, it'll be addressed in the mobile view feature covered in #300
