### ISSUE TITLE
[BUG] (Minor bug) Default Mech Hangar mech image shrunk

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#858]
<strong>Submitted At: </strong>5/23/2020 4:18:26
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Since the latest set of updates (within the past week, as of May 23), the default image for my mech on its personal screen (not the Mech Hangar, but the specific mech's details) is just suddenly very small compared to its previous size. The mech I use is the SSC Death's Head, and I have no custom image, only the blue one by Tom Parkinson-Morgan, so it is not an issue with an uploaded file. I also use the browser-based app on Windows 10 Google Chrome. It doesn't seem to actually affect the performance of the app, but it's noticeable. If it is a new feature, it's a bit strange, as the mech image is much smaller than the pilot image, and does not fill the space obviously designed for a larger image.
<strong>To Reproduce: </strong>
Since the latest updates, it is like that when I open the Mech Hangar screen. Restarting the browser, re-opening the site, and moving around the app don't seem to affect it, so I assume that it might be due to coding. As the cloud sync is a work in progress, I am unable to check if mobile app has the same issue, although it seems to be present on mechs that are not just the Death's Head. (Tested on the HORUS Pegasus as well)
<strong>Expected behavior: </strong>
I rather expected the image to be bigger, and was surprised when it was not.
<strong>Additional context: </strong>
That's about it. It's mostly a design issue. Doesn't affect use or performance of the app, only cosmetics.
<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Not a bug, just a layout change to that page
