### ISSUE TITLE
Feature Request: A folder for pilots

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#863]
<strong>Submitted At: </strong>5/24/2020 22:03:18
<strong>Is your feature request related to a problem? Please describe. </strong>

<strong>Describe the solution you'd like: </strong>
The ability to create folders for pilots on the pilot roster
<strong>Additional context: </strong>
I don't need seventeen meme Genghis builds cluttering my pilot roster list, as amusing as it is.
<strong>Contact: </strong>
Old Man Genghis

**Comment by jarena3** [comment]
collected in #865
