### ISSUE TITLE
Feature Request: Adding Encounters to active missions should modify said current mission to have that encounter show up.

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#867]
<strong>Submitted At: </strong>5/26/2020 14:08:40
<strong>Is your feature request related to a problem? Please describe. </strong>
I don't like having to reactivate a whole mission from scratch when I add an encounter to an active mission.
<strong>Describe the solution you'd like: </strong>
The encounter should be automatically added to the active mission you add it to, which would make it possible to prepare a mission in chunks rather than needing to prepare all of it from scratch.
<strong>Additional context: </strong>

<strong>Contact: </strong>
Elderino#7590

**Comment by jarena3** [comment]
collected in #517
