### ISSUE TITLE
[BUG] tactics not showing up for berserker

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#874]
<strong>Submitted At: </strong>5/30/2020 10:10:56
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
in the tactics section for berserker in the npc roster their is nothing showing up
<strong>To Reproduce: </strong>
1. go to berserker in the npc roster
2. view tactics
<strong>Expected behavior: </strong>
i expected to see tactics
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in 2.2.2
