### ISSUE TITLE
Feature Request: Hovertext should be below mouse

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#875]
<strong>Submitted At: </strong>5/30/2020 15:22:46
<strong>Is your feature request related to a problem? Please describe. </strong>
Jammed hovertext goes offscreen at the top.
<strong>Describe the solution you'd like: </strong>
Hovertext should go down rather than up
<strong>Additional context: </strong>

<strong>Contact: </strong>

**Comment by jarena3** [comment]
I'd like to add left/right/top/bottom props to the cc-tooltip component and update where appropriate
