### ISSUE TITLE
[BUG] Oracle LMG-1 equippable despite licences

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#882]
<strong>Submitted At: </strong>6/2/2020 15:34:49
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
Oracle LMG-1 auxiliary rifle not usable on ssc swallowtale despite owning two licenses in Swallowtale. With 3 licenses you can equip one LMG, but not two, despite it not having the unique tag.
<strong>To Reproduce: </strong>
Create a character with 2 licenses in Swallowtale, use the aux/aux mount and try to equip the weapon. It is not shown even when you set unlicensed inventory to be shown.
<strong>Expected behavior: </strong>
The LMG should have been accessible.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>
None is available.

**Comment by jarena3** [comment]
Unable to reproduce. I think the reporter didn't realize the Oracle had an SP cost
