### ISSUE TITLE
[BUG] Error when syncing pilot data from cloud

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#885]
<strong>Submitted At: </strong>6/3/2020 22:54:32
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When updating a local pilot imported from the cloud, via the cloud, an error appears and the update doesn't occur.
<strong>To Reproduce: </strong>
Add New Pilot -> Import from cloud via cloud ID -> owner updates their pilot/mech and overwrites the cloud record -> non-owner syncs with the cloud
<strong>Expected behavior: </strong>
The local copy should become overwritten with the one from the cloud.
<strong>Additional context: </strong>
Installed content: Core NPCs 1.0.4; Lancer Long Rim Data 0.10.0; Lancer Wallflower Data 0.9.6
<strong>Contact Info: </strong>
VertigoCharades (he/him)#1590
<strong>Stack Trace: </strong>
Nothing appeared under "Recent Errors"

**Comment by jarena3** [comment]
unable to reproduce -- as long as the content packs are the same everything should be good. This might be on the gist end, and a retry usually corrects any issues here
