### ISSUE TITLE
[BUG] Sorting NPCs by labels doesn't work

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#889]
<strong>Submitted At: </strong>6/7/2020 14:28:24
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When I click "sort by Labels" in the NPC roster, two error messages that say "e.group.toUpperCase is not a function" appear. Clicking on any NPC causes the error to appear again.
<strong>To Reproduce: </strong>
Attempt to sort the NPC roster by labels.
<strong>Expected behavior: </strong>
I expected the sort by label function to work as it had before.
<strong>Additional context: </strong>
I tried removing all my extant labels and putting in all new ones, but it did not address the issue.
<strong>Contact Info: </strong>
FighterChimp
<strong>Stack Trace: </strong>
```
Vue error at [v-data]
fn@https://compcon.app/app.bundle.js:90:30466
i@https://compcon.app/app.bundle.js:22:15524
genDefaultGroupedRow@https://compcon.app/app.bundle.js:90:974904
genGroupedRows/<@https://compcon.app/app.bundle.js:90:974509
genGroupedRows@https://compcon.app/app.bundle.js:90:974296
genItems@https://compcon.app/app.bundle.js:90:974215
genBody@https://compcon.app/app.bundle.js:90:977916
genDefaultScopedSlot@https://compcon.app/app.bundle.js:90:978642
i@https://compcon.app/app.bundle.js:22:15524
render@https://compcon.app/app.bundle.js:90:954223
t.prototype._render@https://compcon.app/app.bundle.js:22:35296
i@https://compcon.app/app.bundle.js:22:64441
un.prototype.get@https://compcon.app/app.bundle.js:22:26610
un.prototype.run@https://compcon.app/app.bundle.js:22:27494
pn@https://compcon.app/app.bundle.js:22:25602
ee/<@https://compcon.app/app.bundle.js:22:12293
Jt@https://compcon.app/app.bundle.js:22:11737
```

**Comment by jarena3** [comment]
fixed in 2.1.4
