### ISSUE TITLE
[BUG] Add New Mech button missing without user agent

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#894]
<strong>Submitted At: </strong>6/11/2020 14:58:55
<strong>Platform: </strong>
Browser - Pale Moon
<strong>Describe the bug: </strong>
If no user agent is sent, then in the mech hangar there is no "add new mech" button.
<strong>To Reproduce: </strong>
Hide your user agent, or change it to something non-standard. Then go to the Mech Hangar.
<strong>Expected behavior: </strong>
I'm expecting that button to be there, yo.
<strong>Additional context: </strong>
https://wildwestscifi.net/Misc/LancerMechHangar.png  <- an image of the issue
<strong>Contact Info: </strong>
Discord -> Domochevsky#7107
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
localstorage is dependent on user agent (as far as I'm aware -- at least for keys), so this can't be addressed until we get a real backend in
