### ISSUE TITLE
[BUG] Defender icon missing, problems ensue.

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#901]
<strong>Submitted At: </strong>6/13/2020 21:58:51
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Defenders in the mission runner and npc roster no longer have the Defender icon. In the mission runner, this means that the options that clicking on the role icon offers are not available to defenders.
<strong>To Reproduce: </strong>
Make an encounter with a defender, then attempt to click where the icon would be for any NPC role. No options will arrive.
<strong>Expected behavior: </strong>
I expect a menu of options to be available when I click on the Defender icon in the mission runner. I also expect the icon to be present in the runner and roster.
<strong>Additional context: </strong>
It's not the end of the world, but I personally find it inconvenient.
<strong>Contact Info: </strong>
Izaak#7354
<strong>Stack Trace: </strong>
N/A

**Comment by jarena3** [comment]
resolved in #900
