### ISSUE TITLE
[FEATURE] Add Heat Stat to Drones & Deployables

### ISSUE THREAD

**Issue by Eranziel** [massif-press/compcon#902]
The upcoming IPS-N Kidd's WARCHILD-2 drones have a heat capacity stat, which currently isn't supported by the Drone effect type. The Kidd's SMOKESTACK deployable also has a heat capacity, likewise unsupported by the Deployable effect type.

**Suggested Solution**
Add heat as an optional property on drone effects, and show the icon and stat for drone effects which have the property.

Consider the same solution for deployables like the SMOKESTACK.

**Comment by jarena3** [comment]
Added in the 2.2.0 update
