### ISSUE TITLE
[BUG] Custom skill trigger descriptions don't display correctly

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#903]
<strong>Submitted At: </strong>6/14/2020 2:47:35
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
Custom skill triggers don't behave like built-in triggers.
They only have the "description" field, which is used for terse descriptions in the built-in triggers, and have no detail field, which is normally where the more in-depth explanation appears.

On the character sheet "narrative profile" tab, this leads to an unbalanced look, with custom triggers often taking several lines and an empty foldout.
More importantly, in "active mode", the "description" field doesn't appear at all (only the "detail" field, that custom triggers don't have), so users need to refer back to the character sheet if they want to read the full description.
<strong>To Reproduce: </strong>
Create a character with at least one built-in skill trigger and one custom skill trigger.
Go to the narrative profile tab. Notice that the built-in trigger has a terse description, and a fold-out to learn more, where as the custom trigger only has the terse description and an empty fold-out.
Enter "active mode" and dismount from mech if the character is currently mounted. Notice that the built-in trigger can be expanded to display its description, but only the name and level is available for custom triggers.
<strong>Expected behavior: </strong>
Custom triggers should have the same properties as built-in triggers and behave in the same way.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Twitter: @_gaeel_ / Discord: Gaeel#8548
<strong>Stack Trace: </strong>

**Comment by Bradshaw** [comment]
Some screenshots to help with context

This is the "Narrative profile" tab:
![narrative](https://files.spaceshipsin.space/skills-narrative.png)
Notice how the custom triggers ("Skillful Pilot" and "Genuine Smile") have much longer descriptions and empty detail foldouts.

And the "Active Mode" view:
![active](https://files.spaceshipsin.space/skills-active.png)
Here the custom triggers have no extra information when opened.
