### ISSUE TITLE
[BUG] Speed stat presented inconsistently between PC and NPC sheets

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#907]
<strong>Submitted At: </strong>6/15/2020 22:15:18
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
On Player Character sheets, speed is presented as a speed stat. However, on NPC sheets, it is presented as a "movement" counter up to the NPC's speed stat. This inconsistent presentation is needlessly confusing and should be standardized. Furthermore, this is presented as "movement" on both PC and NPC toggle buttons along the bottom of the Mission Runner Screen.
<strong>To Reproduce: </strong>
Load a mission in the mission runner, and compare the data presented on a PC sheet as compared to an NPC sheet.
<strong>Expected behavior: </strong>
Speed/Movement should be presented in a consistent fashion across both PC and NPC sheets, both in full view and in the condensed symbolic view in the Mission Runner.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
@Starling#4433
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
SPEED is the stat that gets converted into the trackable value MOVEMENT. Movement can come from different sources (base move/turn, boost, certain systems, etc) but it's not synonymous with speed.
