### ISSUE TITLE
[BUG] Missing Equipment Tag

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#912]
<strong>Submitted At: </strong>6/17/2020 3:16:42
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Black Witch's Perimeter Command Plate doesn't have a "Deployable" equipment tag
<strong>To Reproduce: </strong>
Looking at the "Tags" section for Black Witch's Perimeter Command Plate
<strong>Expected behavior: </strong>
Black Witch's Perimeter Command Plate should have a "Deployable" equipment tag
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Ælali (Discord)
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
C/C recognizes Deployables as a type, not a tag
