### ISSUE TITLE
[BUG] Archer NPC's Suppress

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#913]
<strong>Submitted At: </strong>6/18/2020 20:11:23
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
The archer's "Suppress" ability is listed as a reaction when it is actually a quick action. It has the quick action tag, but shows up as a reaction instead of a trait.
<strong>To Reproduce: </strong>
Change the ability to trait instead of a reaction
<strong>Expected behavior: </strong>
I expected it to be listed as a trait
<strong>Additional context: </strong>
Seems like a simple issue of mislabeling
<strong>Contact Info: </strong>
ℬertruvious#6200
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
collected by #873
