### ISSUE TITLE
[BUG] Printable sheet numbers

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#918]
<strong>Submitted At: </strong>6/21/2020 15:39:50
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When printing character sheets, the numbers for armor, E-def, evasion, speed, and mech skills are all offset weirdly and for some unreadable because of this. 
<strong>To Reproduce: </strong>
Pilot options -> print 
<strong>Expected behavior: </strong>
It looks like the numbers are supposed to be centered in the hexagons instead of offset
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
rory#5415 on discord
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
