### ISSUE TITLE
[FEATURE] Please make the Wiki publicly editable

### ISSUE THREAD

**Issue by danharel** [massif-press/compcon#919]
I want to start contributing by updating the documentation for NPC features as I've done here: https://github.com/danharel/compcon/commit/841c180dac8d9287ef9592ec2dd022a08c0d9ccd but as it stands, there's no way to perform a pull request on the wiki.

https://help.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis

**Comment by jarena3** [comment]
I appreciate the sentiment behind this and have allowed editing as requested, but please keep in mind that all of the homebrew structure currently, including how the lcp json is laid out and what it must contain, will likely change in the next few weeks and months

**Comment by danharel** [comment]
Understood. Thanks for the heads up,
