### ISSUE TITLE
[BUG] Tech Options not appearing

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#925]
<strong>Submitted At: </strong>6/24/2020 21:18:03
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
In looking at the various tech options for most mechs with those tech options, the actual effects of the tech options do not show up, namely these..
Emperor: Static Pulse, Lightning Lash, Bless, Purging Shield
Goblin: Metahook, Osiris-class NHP
Gorgon: Scylla-Class NHP has Osiris-NHP feature
Pegasus: Sisyphus Bend Probability action is missing
Lich: all tech systems except Unhinge Chronoflow
Sunzi: Accelerate, Distort, Unravel
...All appear blank after it says "Gain the following options"
<strong>To Reproduce: </strong>
It is a persistent issue, the options do not appear at all and continue not to during my time on Comp/Con.
<strong>Expected behavior: </strong>
What I expect is to be able to see the text of the "gain the following options" data as listed in the core rulebook where one finds the options in the baseline mechs, and see the tech options for the additional mechs.
<strong>Additional context: </strong>
All other systems and weapons seem to have the proper effects listed, only the specified tech options have a problem.
<strong>Contact Info: </strong>
Discord: Sparrowhawk#1651
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Contacted user; they hadn't updated to the latest version
