### ISSUE TITLE
[BUG] Not showing the Nanit whipe for Balor LL3

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#926]
<strong>Submitted At: </strong>6/25/2020 20:43:19
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
When putting LL3 into Balor I see the nexus hive equippable but not the Nanite whip equipable into the heavy slot
<strong>To Reproduce: </strong>
Putting the first 3 LL into Balor
<strong>Expected behavior: </strong>
I expected to get all the Weapons in the Balor License and i did not
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
abababababa#9506
<strong>Stack Trace: </strong>

**Comment by aritsune** [comment]
Guessing this is from not having the SP available, which could maybe be signalled better
