### ISSUE TITLE
[BUG] Spoofing another user (maybe)

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#927]
<strong>Submitted At: </strong>6/26/2020 18:44:16
<strong>Platform: </strong>
Electron - Windows
<strong>Describe the bug: </strong>
If someone else has shared their "Pilot Share ID" for importing, the 'cloudOwnerID' is added to "data\pilots_v2.json" and the local user id can be modified to that string. This could allow a user to modify someone else's vault (although I haven't tested that).
<strong>To Reproduce: </strong>
After importing another player's pilot, the data is added to "C:\Users\<USERNAME>\AppData\Roaming\compcon\data\pilots_v2.json". There the pilot's 'cloudOwnerID' can be found and the "User ID" under "Options & User Profile" can be modified. Then under the "Omninet Vault Settings" for the other player's pilot, it will read "PILOT STATUS:  <PILOT>'s data is stored in your Vault" instead of "someone else's Vault".
<strong>Expected behavior: </strong>
I don't really know whether this is intentional, but this is a behavior I've noticed.
<strong>Additional context: </strong>
Might be similar for the other Electron releases, but unable to check at the moment.
<strong>Contact Info: </strong>
Discord: Noli#9577
<strong>Stack Trace: </strong>
Not necessary

**Comment by aritsune** [comment]
There's plenty of ways to mess with the current system, it's a stopgap working 100% on the honor system and there's a replacement with proper user auth on the way. The concern is appreciated though.
