### ISSUE TITLE
Feature Request: integrated mount destruction

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#931]
<strong>Submitted At: </strong>6/27/2020 10:21:11
<strong>Is your feature request related to a problem? Please describe. </strong>
When taking structure damage you cant choose to destroy your integrated mount.
<strong>Describe the solution you'd like: </strong>
to be able to choose to damage the integrated mount
<strong>Additional context: </strong>

<strong>Contact: </strong>

**Comment by aritsune** [comment]
Integrated mounts cannot be destroyed.
