### ISSUE TITLE
[BUG] NPC Data Unreadable

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#933]
<strong>Submitted At: </strong>6/28/2020 14:07:03
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
The NPC Data from the CRB download keeps saying "Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html" and refuses to allow install.
<strong>To Reproduce: </strong>
1. COMP/CON Manage Content Packs
2. Install Content
3. Select "lcp_manifest.json"
<strong>Expected behavior: </strong>
For the file to be read proper and allow instal of NPC Data
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Dom#7700
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
This looks to be an issue in how the itch app installer handles .lcp files, I'm taking it up with them
