### ISSUE TITLE
[BUG] Compendium Pilot Equipment Gear not showing uses

### ISSUE THREAD

**Issue by linky00** [massif-press/compcon#938]
**Describe the bug**
In the list mode, the pilot equipment that have uses (such as frag grenades) don't show a number under 'uses'.

**To Reproduce**
1. Go to 'compendium/pilot_gear'
2. Click on 'GEAR'

**Expected behavior**
Number for 'uses' shown on items that have limited uses

**Screenshots**
![image](https://user-images.githubusercontent.com/17803813/86465578-d4d10b80-bd29-11ea-8a9c-117c00fa2e88.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83

**Comment by Mischala** [comment]
PR created for this issue #949
