### ISSUE TITLE
[BUG] Quick Sync resets group affiliation

### ISSUE THREAD

**Issue by HelmicNewciv** [massif-press/compcon#958]
**Describe the bug**
When quick syncing a pilot, it loses its group affiliation and returns to the ungrouped section.  This is annoying when trying to update PC sheets when managing multiple campaigns.

**To Reproduce**
1. Import a character from the cloud
2. Drag and drop them into a group
3. Quick sync the character (overwriting the local copy)
4. Navigate away from the pilot selection screen
5. Return to the pilot selection screen
6. Updated pilot is now ungrouped.

**Expected behavior**
The pilot should remain in the group you've dragged them into.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Firefox
 - Version: 78.0.1 (64-bit)

**Comment by jarena3** [comment]
Corrected in 2.2.6
