### ISSUE TITLE
[FEATURE] Sync all pilots in a group

### ISSUE THREAD

**Issue by HelmicNewciv** [massif-press/compcon#959]
**Describe the solution you'd like**
A simple "Sync All" button or option for all pilots in a group, such that a GM can click to update all the PC's before starting a game session.  Having the option in different parts of the UI (such as when prepping to run a mission) would be handy as well to avoid needing to navigate away from the task at hand.

**Comment by jarena3** [comment]
This is handled by automatic cloud syncing with connected C/C accounts, and when that moves into its freely-available state should satisfy this request.
