### ISSUE TITLE
[BUG] NPC roster sorting by class/role doesn't work

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#962]
<strong>Submitted At: </strong>7/9/2020 17:22:39
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
The headings to sort NPCs on the NPC roster by class and role don't seem to sort the list contents properly. It looks like it sorts them by order created instead.
<strong>To Reproduce: </strong>
1. Create multiple NPCs of different classes and roles. In my case, I have 4 infantry squads, a berserker, 3 demolishers, a sniper, and an assault, which I created in that order.

2. Name them things not in alphabetical order as you create them.

3. Attempt to sort the roster by class or role by clicking on the appropriate headers.
<strong>Expected behavior: </strong>
I expected the NPC list to sort by grouping the different classes or roles together alphabetically (e.g., all berserkers, then all demolishers, etc.; or all artillery, then all defenders, etc.), then ordering those groups alphabetically by their NPC name ("New Demolisher", "Other New Demolisher", etc.). Instead, both headers sort my NPCs in the order listed above (squad, squad, squad, squad, berserker, demolisher, demolisher, demolisher, sniper, assault), which is the order I created them in rather than any kind of logical order.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Mister Maf#6979
<strong>Stack Trace: </strong>
None available

**Comment by jarena3** [comment]
collected in #840
