### ISSUE TITLE
Cancel button in "Set Custom Name" dialog does nothing

### ISSUE THREAD

**Issue by cmcaine** [massif-press/compcon#974]
https://github.com/massif-press/compcon/blob/60aeffb490899847bc4eea611b9fa90c8fdb6c48/src/ui/components/CCStringEditDialog.vue#L18

I'm pretty sure this is the location of the bug. cn_dialog was removed from everywhere else in 7ebdcd6d5baa4f9854640eab421bd28d83135c59.

I think a natural UI would be to remove the reset button and to automatically reset the name if the user selects "Save" with the empty string.

**Comment by jarena3** [comment]
Fixed in 2.2
