### ISSUE TITLE
[BUG] Custom names and damage doesn't update immediately

### ISSUE THREAD

**Issue by cmcaine** [massif-press/compcon#975]
**Describe the bug**
Custom names and damage types on weapons do not update immediately.

**To Reproduce**
1. Go to a pilot profile
2. Remove a pilot weapon (important, pre-existing weapons sometimes work)
3. Add a light signature weapon
4. Click on the cog by and select "Set custom name"
3. Type something in and click "save"
4. See that the name hasn't changed
5. Refresh the page to see the name update (and now it will update immediately if changed again)

This works for mech weapons, too.

**Expected behavior**
The name and damage type should visibly update when you click save.

**Desktop (please complete the following information):**
 - OS: Various Linux
 - Browser Firefox
 - Version 76

**Comment by jarena3** [comment]
This should be resolves as of 2.2.2
