### ISSUE TITLE
[BUG] Nuclear Cavalier 1has outdated text

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#978]
<strong>Submitted At: </strong>7/15/2020 11:24:33
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
The text "If you enter the Danger Zone during your turn, this talent takes effect on your next attack." is no longer in the core rules, but it's still there in COMP/CON
<strong>To Reproduce: </strong>
Look at Nuclear Cavalier 1 in the Compendium, or add it onto any pilot
<strong>Expected behavior: </strong>
That talent rank should only read "The first attack roll you make on your turn while in the Danger Zone deals +2 Heat on a hit." without the second sentence
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
VertigoCharades (he/him)#1590
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in 2.2.2
