### ISSUE TITLE
[BUG] Printing Character Sheets

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#979]
<strong>Submitted At: </strong>7/16/2020 1:57:56
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When using comp/con to print character sheets, some systems' descriptions are not visible against the background. 
<strong>To Reproduce: </strong>
Using comp/con on a fully created and outfitted character, trying to print the character sheet, the preview shows some systems (for example, the Comp/Con-Class Assistant Unit) as blank. The text is present, and can be seen if highlighted, but does not otherwise show up. If the sheet is printed and saved as a PDF, the space is also blank, but highlighting the text no longer makes it visible.
<strong>Expected behavior: </strong>
Expected behavior is for all systems to show their details, not just some systems.
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
Ellie#0027
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in 2.2
