### ISSUE TITLE
Feature Request: NPC Folders

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#982]
<strong>Submitted At: </strong>7/16/2020 13:21:06
<strong>Is your feature request related to a problem? Please describe. </strong>
My NPC roster is very full, which sometimes makes it hard to find the NPC I'm looking for.
<strong>Describe the solution you'd like: </strong>
Collapsible NPC folders like the ones recently added to the Pilot roster.
<strong>Additional context: </strong>
Being able to assign the same NPC to multiple campaigns would also be nice.
<strong>Contact: </strong>

**Comment by jarena3** [comment]
collected in #982
