### ISSUE TITLE
Feature Request:  Unshackle mech license ranks from LLs

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#986]
<strong>Submitted At: </strong>7/18/2020 12:40:42
<strong>Is your feature request related to a problem? Please describe. </strong>
The Long Rim supplement added the ability to rent mech levels in exchange for manna, but compcon currently does not have the ability to add individual mech license ranks without full level ups.
<strong>Describe the solution you'd like: </strong>
Allow us to add individual mech license ranks without needing a full level up.
<strong>Additional context: </strong>

<strong>Contact: </strong>
@ScFirestorm

**Comment by Harlekin13** [comment]
it's possible to add license points under reserves&bonuses, which do exactly what is requested here, it may be a relatively new feature though.

**Comment by jarena3** [comment]
Actual Manna support will include this feature
