### ISSUE TITLE
[BUG] Barbarossa roller charge mine has smart tag

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#987]
<strong>Submitted At: </strong>7/19/2020 11:33:48
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Barbarossa roller charge mine has smart tag
<strong>To Reproduce: </strong>
look at the mine on that system
<strong>Expected behavior: </strong>
its just not supposed to be there
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
ThatOddDeer#4137
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Corrected in 2.2
