### ISSUE TITLE
[BUG] Invisible Tier symbol

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#989]
<strong>Submitted At: </strong>7/19/2020 13:05:05
<strong>Platform: </strong>
Browser - Firefox
<strong>Describe the bug: </strong>
The T3 symbol in the NPC list is hidden when using the Horus Terminal Theme. The symbol is there but is the same colour as the background
<strong>To Reproduce: </strong>
Set Compcon to the Horus Terminal theme. Open NPC roster. Create a new NPC or select an exiting one. Set the NPC to Tier 3. In the list on the left the tier symbol is absent
<strong>Expected behavior: </strong>
Tier 3 symbol should be recoloured so it can be seen against the black background
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
SalisofKnight #6445
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in 2.2.2
