### ISSUE TITLE
Feature Request: Calculations for values should be shown when hovering over calculated values (not only the labels)

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#992]
<strong>Submitted At: </strong>7/19/2020 18:13:29
<strong>Is your feature request related to a problem? Please describe. </strong>
I was initially going to request that C/C add a way to see how values on the sheet (e.g. mech HP) were being calculated; I found a feature request marked as "done" for exactly this, but was confused. I then realized that C/C seems to show exactly what I'm looking for when I hover over the label - but not when I hover over the value itself. That seems counterintuitive.

<strong>Describe the solution you'd like: </strong>
I'd expect that hovering over a value on the sheet would show how that value was derived/calculated; I wouldn't expect to have to hover over the label for this calculation to be shown. (Showing the popover when *either* the label or value is hovered over would make sense to me too, but not *only* the label.)
<strong>Additional context: </strong>
For example, my Death's Head has an HP of 11. Hovering over the smaller label text "HP" shows how that number is derived: the frame's base HP + my pilot's Grit + my pilot's Hull bonus (though it's +0) + 2 (from the Personalizations GMS system). However, hovering over the "11" below the label text doesn't show the same info (i.e. there's no such popover at all). I assumed C/C already had a way of finding this information, but didn't realize it for the longest time because I'd only ever tried hovering over the value rather than the label.
<strong>Contact: </strong>
V2Blast#8533

**Comment by V2Blast** [comment]
For reference, #91 is the feature request by @jarena3 that I mentioned above.

**Comment by jarena3** [comment]
This is available on the mech sheet by hovering over the label
