### ISSUE TITLE
[BUG] Add New Mech Screen - Splash Art Issue

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#993]
<strong>Submitted At: </strong>7/19/2020 21:40:18
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
The splash art for the Swallowtail, Metalmark, and Death's Head covers the text listing the name of the mech/roles on the "Add New Mech" page.
<strong>To Reproduce: </strong>
Create a new mech > Select Frame Screen > Scroll Down to Swallowtail/Metalmark/Death's Head 
<strong>Expected behavior: </strong>
It not to cover the text? I guess?
<strong>Additional context: </strong>
I can supply a snipped image on discord if needed.
<strong>Contact Info: </strong>
Hubumbly#0049
<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
somehow the transparency hover effects got lost somewhere, which should be fixed

**Comment by jarena3** [comment]
Fixed in 2.2
