### ISSUE TITLE
Feature Request: Integrated Systems

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#994]
<strong>Submitted At: </strong>7/19/2020 22:59:23
<strong>Is your feature request related to a problem? Please describe. </strong>
You cannot currently create a System that is integrated into a mech. For example an integrated Grenade system.
<strong>Describe the solution you'd like: </strong>
Integrated system functionality, the ability to read tagged systems from the systems.json basically and copy system formatting when reading them from there.
<strong>Additional context: </strong>

<strong>Contact: </strong>
Fwuffy (Luna)#1371

**Comment by jarena3** [comment]
Added in 2.2
