### ISSUE TITLE
Feature Request: Search weapons by tag

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#995]
<strong>Submitted At: </strong>7/20/2020 1:28:36
<strong>Is your feature request related to a problem? Please describe. </strong>
Trying to find what weapons are 'loaded' and need to check each
<strong>Describe the solution you'd like: </strong>
searching for tags in the weapon menu (or buttons to filter for them) to make searching easier
<strong>Additional context: </strong>

<strong>Contact: </strong>
Auraknight#5417

**Comment by jarena3** [comment]
This already exists:
