### ISSUE TITLE
Feature Request: Weapon Choice on Skirmish/Barrage

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#997]
<strong>Submitted At: </strong>7/20/2020 5:03:37
<strong>Is your feature request related to a problem? Please describe. </strong>

<strong>Describe the solution you'd like: </strong>
It'd be neat if there were an additional prompt when selecting Barrage or Skirmish to choose which weapon you're firing with, and for comp/con to automate things like heat addition/subtraction. This could be similar to the system trauma screen when taking structure.
<strong>Additional context: </strong>

<strong>Contact: </strong>
Hubumbly#0049

**Comment by jarena3** [comment]
Added in 2.2
