### ISSUE TITLE
[BUG] Black Thumb Formatting Error

### ISSUE THREAD

**Issue by compcon** [massif-press/compcon#998]
<strong>Submitted At: </strong>7/21/2020 2:07:51
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
Formatting error: Black Thumb 2, Rodeo action: Rig Vents is on the same line as Field Repair. 
<strong>To Reproduce: </strong>
View the Black Thumb from the talents page. https://compcon.app/#/compendium/talents
<strong>Expected behavior: </strong>
Rig Vents to have a bullet point. 
<strong>Additional context: </strong>

<strong>Contact Info: </strong>

<strong>Stack Trace: </strong>

**Comment by jarena3** [comment]
Fixed in the 2.2.0 update
